## Read ATB data
- source: internal RKI

In [2]:
import os 
import pandas as pd 
from utils.data_sampling import negatives_sampling
from pandarallel import pandarallel

# Initialization
pandarallel.initialize(progress_bar=True, nb_workers=4)

import warnings 
warnings.filterwarnings("ignore")

INFO: Pandarallel will run on 4 workers.
INFO: Pandarallel will use standard multiprocessing data transfer (pipe) to transfer data between the main process and workers.

In [6]:
FOLDER_TO_ATB = "dataset/prev_studies/ATB"
FOLDER_TEST = "dataset/test_folder"

### Read ATB positives description file

In [7]:
atb_desc_file = pd.read_csv(f"{FOLDER_TO_ATB}/ATB_positiv.tsv", sep="\t")

In [8]:
atb_desc_file['batch_folder'] = atb_desc_file['path'].apply(lambda x: x.split('/')[-2])

In [9]:
import gzip
import csv
import subprocess

tsv_gz_file = f"{FOLDER_TO_ATB}/file_list.all.latest.tsv.gz"

tar_xz_files = {}

with gzip.open(tsv_gz_file, "rt") as file:
    reader = csv.DictReader(file, delimiter = "\t")
    for row in reader:
        tar_xz = row["tar_xz"]
        tar_xz_url = row["tar_xz_url"]
        if tar_xz not in tar_xz_files:
            tar_xz_files[tar_xz] = tar_xz_url

In [10]:
selected_files = atb_desc_file.batch_folder.unique()
selected_files_dict = {k:tar_xz_files[k] for k in tar_xz_files.keys() if k.split(".tar.xz")[0] in selected_files}

In [11]:
len(selected_files_dict)

436

In [12]:
# Downloading the .fa files

from tqdm import tqdm 

for tar_xz, url in tqdm(selected_files_dict.items()):
    
    dest_folder = f"{FOLDER_TO_ATB}/atb_batch"
    os.makedirs(dest_folder, exist_ok=True)

    dest_file = f"{dest_folder}/{tar_xz}"
    if os.path.exists(dest_file) == False:
        print(f"Downloading {tar_xz} from {url}")
        subprocess.run(["wget", "-O", dest_file, url])

  0%|          | 0/436 [00:00<?, ?it/s]

Downloading atb.assembly.r0.2.batch.1.tar.xz from https://osf.io/download/667142936b6c8e33f404cce7/

--2026-09-06 18:51:13--  https://osf.io/download/667142936b6c8e33f404cce7/
Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667142936b6c8e33f404cce7 [following]
--2026-09-06 18:51:13--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667142936b6c8e33f404cce7
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/363bdb8e841f39e82624923d4d0677849867f38e085cfc8d007506cb0648f47d?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.1.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.1.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713534&Signature=VHioF2SshBNo914kVAyeLJVe28jIy8drpdyMVAnxxCeX165UmjrYnBwvKDRhh5ykl%2FVK0RnVhZrxZtXkah09xQMo%2F5P5DGp%2B9bwegWHfSII1A3d%2BHY6t4uohLfxmXopqdIHF8vEbIyvoJz1Q4UkCHVUp7OGzuefNrI1oXByivsDl2%2BS9dZG%2BQHx0meHggYuovUetvOJN1xGWT1%2B%2FbdbGoijFEh3T1kbF09OFWFr1roD9%2FIIUODHepmGQqno7zdXNgKVvT9iUuPQv8NEqXBwCRilfIHUPFh9Ko8V0CmmIBgK8l5SquC7KhQOeGRDD%2FlDX18Ff%2F78GocjwzmqYstd1lQ%3D%3D [following]
--2026-09-06 18:51:14--  https://storage.googleapis.com/cos-osf-prod-files-de-1/363bdb8e841f39e82624923d4d0677849867f38e085cfc8d007506cb0648f47d?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.1.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.1.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713534&Signature=VHioF2SshBNo914kVAyeLJVe28jIy8drpdyMVAnxxCeX165UmjrYnBwvKDRhh5ykl%2FVK0RnVhZrxZtXkah09xQMo%2F5P5DGp%2B9bwegWHfSII1A3d%2BHY6t4uohLfxmXopqdIHF8vEbIyvoJz1Q4UkCHVUp7OGzuefNrI1oXByivsDl2%2BS9dZG%2BQHx0meHggYuovUetvOJN1xGWT1%2B%2FbdbGoijFEh3T1kbF09OFWFr1roD9%2FIIUODHepmGQqno7zdXNgKVvT9iUuPQv8NEqXBwCRilfIHUPFh9Ko8V0CmmIBgK8l5SquC7KhQOeGRDD%2FlDX18Ff%2F78GocjwzmqYstd1lQ%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 192.178.183.207, 142.251.13.207, 142.251.14.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|192.178.183.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 34261612 (33M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.1.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.34M 24s
    50K .......... .......... .......... .......... ..........  0% 2.57M 19s
   100K .......... .......... .......... .......... ..........  0% 4.79M 15s
   150K .......... .......... .......... .......... ..........  0% 5.21M 12s
   200K .......... .......... .......... .......... ..........  0% 4.82M 11s
   250K .......... .......... .......... .......... ..........  0% 10.3M 10s
   300K .......... .......... .......... .......... ..........  1% 9.15M 9s
   350K .......... .......... .......... .......... ..........  1% 14.8M 8s
   400K .......... .......... .......... .......... ..........  1% 13.6M 7s
   450K .......... .......... .......... .......... ..........  1% 12.9M 7s
   500K .......... .......... .......... .......... ..........  1% 10.5M 7s
   550K .......... .......... .......... .......... ..........  1% 10.4M 6s
   600K .......... .......... .......... .......... ..........  1% 14.6M 6s
   650K .......... .......... .......... .......... ..........  2% 27.0M 6s
   700K .......... .......... .......... .......... ..........  2% 10.7M 5s
   750K .......... .......... .......... .......... ..........  2% 11.8M 5s
   800K .......... .......... .......... .......... ..........  2% 15.4M 5s
   850K .......... .......... .......... .......... ..........  2% 9.03M 5s
   900K .......... .......... .......... .......... ..........  2% 12.3M 5s
   950K .......... .......... .......... .......... ..........  2% 12.6M 5s
  1000K .......... .......... .......... .......... ..........  3% 14.9M 5s
  1050K .......... .......... .......... .......... ..........  3% 13.6M 4s
  1100K .......... .......... .......... .......... ..........  3% 14.5M 4s
  1150K .......... .......... .......... .......... ..........  3% 10.8M 4s
  1200K .......... .......... .......... .......... ..........  3% 10.9M 4s
  1250K .......... .......... .......... .......... ..........  3% 15.0M 4s
  1300K .......... .......... .......... .......... ..........  4% 15.9M 4s
  1350K .......... .......... .......... .......... ..........  4% 11.1M 4s
  1400K .......... .......... .......... .......... ..........  4% 15.9M 4s
  1450K .......... .......... .......... .......... ..........  4% 9.05M 4s
  1500K .......... .......... .......... .......... ..........  4% 29.4M 4s
  1550K .......... .......... .......... .......... ..........  4% 9.49M 4s
  1600K .......... .......... .......... .......... ..........  4% 12.5M 4s
  1650K .......... .......... .......... .......... ..........  5% 11.7M 4s
  1700K .......... .......... .......... .......... ..........  5% 12.3M 4s
  1750K .......... .......... .......... .......... ..........  5% 15.8M 4s
  1800K .......... .......... .......... .......... ..........  5% 14.7M 4s
  1850K .......... .......... .......... .......... ..........  5% 17.6M 4s
  1900K .......... .......... .......... .......... ..........  5% 7.94M 4s
  1950K .......... .......... .......... .......... ..........  5% 17.9M 3s
  2000K .......... .......... .......... .......... ..........  6% 13.3M 3s
  2050K .......... .......... .......... .......... ..........  6% 11.5M 3s
  2100K .......... .......... .......... .......... ..........  6% 15.3M 3s
  2150K .......... .......... .......... .......... ..........  6% 11.0M 3s
  2200K .......... .......... .......... .......... ..........  6% 17.0M 3s
  2250K .......... .......... .......... .......... ..........  6% 10.8M 3s
  2300K .......... .......... .......... .......... ..........  7% 13.9M 3s
  2350K .......... .......... .......... .......... ..........  7% 9.48M 3s
  2400K .......... .......... .......... .......... ..........  7% 15.1M 3s
  2450K .......... .......... .......... .......... ..........  7% 14.3M 3s
  2500K .......... .......... .......... .......... ..........  7% 13.4M 3s
  2550K .......... .......... .......... .......... ..........  7% 12.7M 3s
  2600K .......... .......... .......... .......... ..........  7% 14.6M 3s
  2650K .......... .......... .......... .......... ..........  8% 9.16M 3s
  2700K .......... .......... .......... .......... ..........  8% 14.7M 3s
  2750K .......... .......... .......... .......... ..........  8% 14.0M 3s
  2800K .......... .......... .......... .......... ..........  8% 10.8M 3s
  2850K .......... .......... .......... .......... ..........  8% 13.2M 3s
  2900K .......... .......... .......... .......... ..........  8% 12.1M 3s
  2950K .......... .......... .......... .......... ..........  8% 16.0M 3s
  3000K .......... .......... .......... .......... ..........  9% 12.9M 3s
  3050K .......... .......... .......... .......... ..........  9% 16.1M 3s
  3100K .......... .......... .......... .......... ..........  9% 10.1M 3s
  3150K .......... .......... .......... .......... ..........  9% 9.95M 3s
  3200K .......... .......... .......... .......... ..........  9% 13.1M 3s
  3250K .......... .......... .......... .......... ..........  9% 17.0M 3s
  3300K .......... .......... .......... .......... .......... 10% 9.56M 3s
  3350K .......... .......... .......... .......... .......... 10% 36.4M 3s
  3400K .......... .......... .......... .......... .......... 10% 10.4M 3s
  3450K .......... .......... .......... .......... .......... 10% 11.7M 3s
  3500K .......... .......... .......... .......... .......... 10% 22.9M 3s
  3550K .......... .......... .......... .......... .......... 10% 8.73M 3s
  3600K .......... .......... .......... .......... .......... 10% 10.9M 3s
  3650K .......... .......... .......... .......... .......... 11% 13.3M 3s
  3700K .......... .......... .......... .......... .......... 11% 19.5M 3s
  3750K .......... .......... .......... .......... .......... 11% 9.63M 3s
  3800K .......... .......... .......... .......... .......... 11% 21.7M 3s
  3850K .......... .......... .......... .......... .......... 11% 11.8M 3s
  3900K .......... .......... .......... .......... .......... 11% 12.9M 3s
  3950K .......... .......... .......... .......... .......... 11% 12.2M 3s
  4000K .......... .......... .......... .......... .......... 12% 11.7M 3s
  4050K .......... .......... .......... .......... .......... 12% 11.3M 3s
  4100K .......... .......... .......... .......... .......... 12% 5.66M 3s
  4150K .......... .......... .......... .......... .......... 12%  119M 3s
  4200K .......... .......... .......... .......... .......... 12% 39.6M 3s
  4250K .......... .......... .......... .......... .......... 12% 13.1M 3s
  4300K .......... .......... .......... .......... .......... 13% 12.5M 3s
  4350K .......... .......... .......... .......... .......... 13% 13.3M 3s
  4400K .......... .......... .......... .......... .......... 13% 8.13M 3s
  4450K .......... .......... .......... .......... .......... 13% 14.3M 3s
  4500K .......... .......... .......... .......... .......... 13% 11.0M 3s
  4550K .......... .......... .......... .......... .......... 13% 20.7M 3s
  4600K .......... .......... .......... .......... .......... 13% 12.2M 3s
  4650K .......... .......... .......... .......... .......... 14% 13.9M 3s
  4700K .......... .......... .......... .......... .......... 14% 17.1M 3s
  4750K .......... .......... .......... .......... .......... 14% 8.51M 3s
  4800K .......... .......... .......... .......... .......... 14% 10.3M 3s
  4850K .......... .......... .......... .......... .......... 14% 27.9M 3s
  4900K .......... .......... .......... .......... .......... 14% 11.9M 3s
  4950K .......... .......... .......... .......... .......... 14% 9.55M 3s
  5000K .......... .......... .......... .......... .......... 15% 20.0M 3s
  5050K .......... .......... .......... .......... .......... 15% 15.3M 3s
  5100K .......... .......... .......... .......... .......... 15% 11.9M 3s
  5150K .......... .......... .......... .......... .......... 15% 12.5M 3s
  5200K .......... .......... .......... .......... .......... 15% 9.05M 3s
  5250K .......... .......... .......... .......... .......... 15% 12.7M 3s
  5300K .......... .......... .......... .......... .......... 15% 14.4M 3s
  5350K .......... .......... .......... .......... .......... 16% 13.8M 3s
  5400K .......... .......... .......... .......... .......... 16% 16.5M 2s
  5450K .......... .......... .......... .......... .......... 16% 7.76M 2s
  5500K .......... .......... .......... .......... .......... 16% 23.8M 2s
  5550K .......... .......... .......... .......... .......... 16% 13.2M 2s
  5600K .......... .......... .......... .......... .......... 16% 12.9M 2s
  5650K .......... .......... .......... .......... .......... 17% 9.93M 2s
  5700K .......... .......... .......... .......... .......... 17% 12.0M 2s
  5750K .......... .......... .......... .......... .......... 17% 27.6M 2s
  5800K .......... .......... .......... .......... .......... 17% 8.96M 2s
  5850K .......... .......... .......... .......... .......... 17% 13.3M 2s
  5900K .......... .......... .......... .......... .......... 17% 13.1M 2s
  5950K .......... .......... .......... .......... .......... 17% 11.5M 2s
  6000K .......... .......... .......... .......... .......... 18% 12.7M 2s
  6050K .......... .......... .......... .......... .......... 18% 12.5M 2s
  6100K .......... .......... .......... .......... .......... 18% 24.9M 2s
  6150K .......... .......... .......... .......... .......... 18% 9.28M 2s
  6200K .......... .......... .......... .......... .......... 18% 12.5M 2s
  6250K .......... .......... .......... .......... .......... 18% 23.6M 2s
  6300K .......... .......... .......... .......... .......... 18% 9.74M 2s
  6350K .......... .......... .......... .......... .......... 19% 14.2M 2s
  6400K .......... .......... .......... .......... .......... 19% 9.71M 2s
  6450K .......... .......... .......... .......... .......... 19% 15.9M 2s
  6500K .......... .......... .......... .......... .......... 19% 14.8M 2s
  6550K .......... .......... .......... .......... .......... 19% 14.5M 2s
  6600K .......... .......... .......... .......... .......... 19% 9.86M 2s
  6650K .......... .......... .......... .......... .......... 20% 16.7M 2s
  6700K .......... .......... .......... .......... .......... 20% 15.7M 2s
  6750K .......... .......... .......... .......... .......... 20% 8.11M 2s
  6800K .......... .......... .......... .......... .......... 20% 13.8M 2s
  6850K .......... .......... .......... .......... .......... 20% 12.9M 2s
  6900K .......... .......... .......... .......... .......... 20% 11.7M 2s
  6950K .......... .......... .......... .......... .......... 20% 12.4M 2s
  7000K .......... .......... .......... .......... .......... 21% 16.2M 2s
  7050K .......... .......... .......... .......... .......... 21% 13.2M 2s
  7100K .......... .......... .......... .......... .......... 21% 13.0M 2s
  7150K .......... .......... .......... .......... .......... 21% 9.04M 2s
  7200K .......... .......... .......... .......... .......... 21% 15.6M 2s
  7250K .......... .......... .......... .......... .......... 21% 13.3M 2s
  7300K .......... .......... .......... .......... .......... 21% 16.9M 2s
  7350K .......... .......... .......... .......... .......... 22% 12.8M 2s
  7400K .......... .......... .......... .......... .......... 22% 15.8M 2s
  7450K .......... .......... .......... .......... .......... 22% 9.56M 2s
  7500K .......... .......... .......... .......... .......... 22% 14.5M 2s
  7550K .......... .......... .......... .......... .......... 22% 9.51M 2s
  7600K .......... .......... .......... .......... .......... 22% 16.2M 2s
  7650K .......... .......... .......... .......... .......... 23% 15.8M 2s
  7700K .......... .......... .......... .......... .......... 23% 12.8M 2s
  7750K .......... .......... .......... .......... .......... 23% 13.4M 2s
  7800K .......... .......... .......... .......... .......... 23% 14.5M 2s
  7850K .......... .......... .......... .......... .......... 23% 14.4M 2s
  7900K .......... .......... .......... .......... .......... 23% 9.06M 2s
  7950K .......... .......... .......... .......... .......... 23% 14.5M 2s
  8000K .......... .......... .......... .......... .......... 24% 11.4M 2s
  8050K .......... .......... .......... .......... .......... 24% 16.0M 2s
  8100K .......... .......... .......... .......... .......... 24% 14.3M 2s
  8150K .......... .......... .......... .......... .......... 24% 11.1M 2s
  8200K .......... .......... .......... .......... .......... 24% 12.7M 2s
  8250K .......... .......... .......... .......... .......... 24% 10.6M 2s
  8300K .......... .......... .......... .......... .......... 24% 22.1M 2s
  8350K .......... .......... .......... .......... .......... 25% 12.0M 2s
  8400K .......... .......... .......... .......... .......... 25% 8.42M 2s
  8450K .......... .......... .......... .......... .......... 25% 14.8M 2s
  8500K .......... .......... .......... .......... .......... 25% 10.8M 2s
  8550K .......... .......... .......... .......... .......... 25% 26.3M 2s
  8600K .......... .......... .......... .......... .......... 25% 11.5M 2s
  8650K .......... .......... .......... .......... .......... 26% 12.4M 2s
  8700K .......... .......... .......... .......... .......... 26% 19.6M 2s
  8750K .......... .......... .......... .......... .......... 26% 9.70M 2s
  8800K .......... .......... .......... .......... .......... 26% 13.4M 2s
  8850K .......... .......... .......... .......... .......... 26% 10.9M 2s
  8900K .......... .......... .......... .......... .......... 26% 12.4M 2s
  8950K .......... .......... .......... .......... .......... 26% 14.5M 2s
  9000K .......... .......... .......... .......... .......... 27% 14.5M 2s
  9050K .......... .......... .......... .......... .......... 27% 11.1M 2s
  9100K .......... .......... .......... .......... .......... 27% 13.1M 2s
  9150K .......... .......... .......... .......... .......... 27% 10.9M 2s
  9200K .......... .......... .......... .......... .......... 27% 13.5M 2s
  9250K .......... .......... .......... .......... .......... 27% 13.0M 2s
  9300K .......... .......... .......... .......... .......... 27% 12.7M 2s
  9350K .......... .......... .......... .......... .......... 28% 12.2M 2s
  9400K .......... .......... .......... .......... .......... 28% 14.6M 2s
  9450K .......... .......... .......... .......... .......... 28% 12.3M 2s
  9500K .......... .......... .......... .......... .......... 28% 11.1M 2s
  9550K .......... .......... .......... .......... .......... 28% 15.7M 2s
  9600K .......... .......... .......... .......... .......... 28% 11.8M 2s
  9650K .......... .......... .......... .......... .......... 28% 12.6M 2s
  9700K .......... .......... .......... .......... .......... 29% 10.8M 2s
  9750K .......... .......... .......... .......... .......... 29% 26.2M 2s
  9800K .......... .......... .......... .......... .......... 29% 15.1M 2s
  9850K .......... .......... .......... .......... .......... 29% 8.83M 2s
  9900K .......... .......... .......... .......... .......... 29% 13.5M 2s
  9950K .......... .......... .......... .......... .......... 29% 11.5M 2s
 10000K .......... .......... .......... .......... .......... 30% 11.1M 2s
 10050K .......... .......... .......... .......... .......... 30% 14.8M 2s
 10100K .......... .......... .......... .......... .......... 30% 12.7M 2s
 10150K .......... .......... .......... .......... .......... 30% 18.5M 2s
 10200K .......... .......... .......... .......... .......... 30% 11.3M 2s
 10250K .......... .......... .......... .......... .......... 30% 10.9M 2s
 10300K .......... .......... .......... .......... .......... 30% 18.6M 2s
 10350K .......... .......... .......... .......... .......... 31% 10.6M 2s
 10400K .......... .......... .......... .......... .......... 31% 10.8M 2s
 10450K .......... .......... .......... .......... .......... 31% 13.4M 2s
 10500K .......... .......... .......... .......... .......... 31% 10.4M 2s
 10550K .......... .......... .......... .......... .......... 31% 14.7M 2s
 10600K .......... .......... .......... .......... .......... 31% 27.7M 2s
 10650K .......... .......... .......... .......... .......... 31% 14.2M 2s
 10700K .......... .......... .......... .......... .......... 32% 8.13M 2s
 10750K .......... .......... .......... .......... .......... 32% 11.3M 2s
 10800K .......... .......... .......... .......... .......... 32% 10.8M 2s
 10850K .......... .......... .......... .......... .......... 32% 12.3M 2s
 10900K .......... .......... .......... .......... .......... 32% 36.4M 2s
 10950K .......... .......... .......... .......... .......... 32% 11.4M 2s
 11000K .......... .......... .......... .......... .......... 33% 10.1M 2s
 11050K .......... .......... .......... .......... .......... 33% 22.8M 2s
 11100K .......... .......... .......... .......... .......... 33% 9.68M 2s
 11150K .......... .......... .......... .......... .......... 33% 13.4M 2s
 11200K .......... .......... .......... .......... .......... 33% 13.3M 2s
 11250K .......... .......... .......... .......... .......... 33% 9.47M 2s
 11300K .......... .......... .......... .......... .......... 33% 16.2M 2s
 11350K .......... .......... .......... .......... .......... 34% 13.4M 2s
 11400K .......... .......... .......... .......... .......... 34% 13.5M 2s

Downloading atb.assembly.r0.2.batch.5.tar.xz from https://osf.io/download/667142aad835c4399c4cdf8e/

--2026-09-06 18:51:17--  https://osf.io/download/667142aad835c4399c4cdf8e/
Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667142aad835c4399c4cdf8e [following]
--2026-09-06 18:51:18--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667142aad835c4399c4cdf8e
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/3b41f1107b5b759baafedbc8365159ebc76d079787e7c9663d7a0d5bf4e1ed16?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.5.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.5.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713538&Signature=D6iASkRVTArhKxy0gWxXX10Jnf5G06mUtKYxO7oGQcg7eu3SoPimlzNorG6EC8k4hC%2BIEkOwL2yz%2FNDfWTwEM6PLlNrD7wSwxKFabUXfOxSuQuyM4KeZdQuom1ojsDesfFKh24318nGrb2lkJ%2B0lPdMxEPRh5bn9pa%2BSbbz%2FFiW4dY6cBb4EcRKTWhRA6L8TAwdz6GfhGVqtotsXXTbKPwE4XL38G3nY%2FgfFmsPPoSGPvzBMLG8IJahemY6ewLvUtwxpMG%2B6n%2FqzF8v1tJSuji4wTtOPlC3h6YeI8mOnlsXF2JQoI%2BMVg2IzAzIhigsVMWcldIVVJ7M8WtS8VbRVrg%3D%3D [following]
--2026-09-06 18:51:18--  https://storage.googleapis.com/cos-osf-prod-files-de-1/3b41f1107b5b759baafedbc8365159ebc76d079787e7c9663d7a0d5bf4e1ed16?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.5.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.5.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713538&Signature=D6iASkRVTArhKxy0gWxXX10Jnf5G06mUtKYxO7oGQcg7eu3SoPimlzNorG6EC8k4hC%2BIEkOwL2yz%2FNDfWTwEM6PLlNrD7wSwxKFabUXfOxSuQuyM4KeZdQuom1ojsDesfFKh24318nGrb2lkJ%2B0lPdMxEPRh5bn9pa%2BSbbz%2FFiW4dY6cBb4EcRKTWhRA6L8TAwdz6GfhGVqtotsXXTbKPwE4XL38G3nY%2FgfFmsPPoSGPvzBMLG8IJahemY6ewLvUtwxpMG%2B6n%2FqzF8v1tJSuji4wTtOPlC3h6YeI8mOnlsXF2JQoI%2BMVg2IzAzIhigsVMWcldIVVJ7M8WtS8VbRVrg%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.13.207, 142.251.14.207, 142.250.154.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.13.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60103584 (57M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.5.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.25M 46s
    50K .......... .......... .......... .......... ..........  0% 2.23M 36s
   100K .......... .......... .......... .......... ..........  0% 4.69M 28s
   150K .......... .......... .......... .......... ..........  0% 3.79M 25s
   200K .......... .......... .......... .......... ..........  0% 8.14M 21s
   250K .......... .......... .......... .......... ..........  0% 6.45M 19s
   300K .......... .......... .......... .......... ..........  0% 11.9M 17s
   350K .......... .......... .......... .......... ..........  0% 8.88M 16s
   400K .......... .......... .......... .......... ..........  0% 14.2M 14s
   450K .......... .......... .......... .......... ..........  0% 15.0M 13s
   500K .......... .......... .......... .......... ..........  0% 11.9M 12s
   550K .......... .......... .......... .......... ..........  1% 18.9M 12s
   600K .......... .......... .......... .......... ..........  1% 8.70M 11s
   650K .......... .......... .......... .......... ..........  1% 16.3M 11s
   700K .......... .......... .......... .......... ..........  1% 14.9M 10s
   750K .......... .......... .......... .......... ..........  1% 9.53M 10s
   800K .......... .......... .......... .......... ..........  1% 13.4M 10s
   850K .......... .......... .......... .......... ..........  1% 14.8M 9s
   900K .......... .......... .......... .......... ..........  1% 11.0M 9s
   950K .......... .......... .......... .......... ..........  1% 11.2M 9s
  1000K .......... .......... .......... .......... ..........  1% 21.2M 9s
  1050K .......... .......... .......... .......... ..........  1% 9.80M 8s
  1100K .......... .......... .......... .......... ..........  1% 11.5M 8s
  1150K .......... .......... .......... .......... ..........  2% 2.97M 9s
  1200K .......... .......... .......... .......... ..........  2%  367M 8s
  1250K .......... .......... .......... .......... ..........  2%  182M 8s
  1300K .......... .......... .......... .......... ..........  2%  432M 8s
  1350K .......... .......... .......... .......... ..........  2%  105M 7s
  1400K .......... .......... .......... .......... ..........  2% 11.9M 7s
  1450K .......... .......... .......... .......... ..........  2% 13.7M 7s
  1500K .......... .......... .......... .......... ..........  2% 7.85M 7s
  1550K .......... .......... .......... .......... ..........  2% 15.3M 7s
  1600K .......... .......... .......... .......... ..........  2% 20.0M 7s
  1650K .......... .......... .......... .......... ..........  2% 12.1M 7s
  1700K .......... .......... .......... .......... ..........  2% 10.7M 7s
  1750K .......... .......... .......... .......... ..........  3% 11.6M 7s
  1800K .......... .......... .......... .......... ..........  3% 15.1M 7s
  1850K .......... .......... .......... .......... ..........  3% 12.0M 7s
  1900K .......... .......... .......... .......... ..........  3% 18.9M 7s
  1950K .......... .......... .......... .......... ..........  3% 17.2M 6s
  2000K .......... .......... .......... .......... ..........  3% 7.88M 6s
  2050K .......... .......... .......... .......... ..........  3% 15.1M 6s
  2100K .......... .......... .......... .......... ..........  3% 17.8M 6s
  2150K .......... .......... .......... .......... ..........  3% 9.76M 6s
  2200K .......... .......... .......... .......... ..........  3% 12.5M 6s
  2250K .......... .......... .......... .......... ..........  3% 16.1M 6s
  2300K .......... .......... .......... .......... ..........  4% 14.0M 6s
  2350K .......... .......... .......... .......... ..........  4% 13.9M 6s
  2400K .......... .......... .......... .......... ..........  4% 7.95M 6s
  2450K .......... .......... .......... .......... ..........  4% 17.2M 6s
  2500K .......... .......... .......... .......... ..........  4% 10.9M 6s
  2550K .......... .......... .......... .......... ..........  4% 26.2M 6s
  2600K .......... .......... .......... .......... ..........  4% 13.5M 6s
  2650K .......... .......... .......... .......... ..........  4% 10.8M 6s
  2700K .......... .......... .......... .......... ..........  4% 11.3M 6s
  2750K .......... .......... .......... .......... ..........  4% 15.3M 6s
  2800K .......... .......... .......... .......... ..........  4% 8.45M 6s
  2850K .......... .......... .......... .......... ..........  4% 14.3M 6s
  2900K .......... .......... .......... .......... ..........  5% 13.8M 6s
  2950K .......... .......... .......... .......... ..........  5% 14.2M 6s
  3000K .......... .......... .......... .......... ..........  5% 10.7M 6s
  3050K .......... .......... .......... .......... ..........  5% 21.7M 6s
  3100K .......... .......... .......... .......... ..........  5% 13.8M 6s
  3150K .......... .......... .......... .......... ..........  5% 11.5M 6s
  3200K .......... .......... .......... .......... ..........  5% 10.0M 6s
  3250K .......... .......... .......... .......... ..........  5% 16.5M 6s
  3300K .......... .......... .......... .......... ..........  5% 11.0M 5s
  3350K .......... .......... .......... .......... ..........  5% 11.2M 5s
  3400K .......... .......... .......... .......... ..........  5% 12.9M 5s
  3450K .......... .......... .......... .......... ..........  5% 9.33M 5s
  3500K .......... .......... .......... .......... ..........  6% 22.9M 5s
  3550K .......... .......... .......... .......... ..........  6% 13.7M 5s
  3600K .......... .......... .......... .......... ..........  6% 11.3M 5s
  3650K .......... .......... .......... .......... ..........  6% 11.0M 5s
  3700K .......... .......... .......... .......... ..........  6% 23.2M 5s
  3750K .......... .......... .......... .......... ..........  6% 9.37M 5s
  3800K .......... .......... .......... .......... ..........  6% 19.6M 5s
  3850K .......... .......... .......... .......... ..........  6% 11.3M 5s
  3900K .......... .......... .......... .......... ..........  6% 13.9M 5s
  3950K .......... .......... .......... .......... ..........  6% 9.88M 5s
  4000K .......... .......... .......... .......... ..........  6% 10.7M 5s
  4050K .......... .......... .......... .......... ..........  6% 8.43M 5s
  4100K .......... .......... .......... .......... ..........  7% 81.8M 5s
  4150K .......... .......... .......... .......... ..........  7% 12.8M 5s
  4200K .......... .......... .......... .......... ..........  7% 13.2M 5s
  4250K .......... .......... .......... .......... ..........  7% 12.5M 5s
  4300K .......... .......... .......... .......... ..........  7% 10.8M 5s
  4350K .......... .......... .......... .......... ..........  7% 17.7M 5s
  4400K .......... .......... .......... .......... ..........  7% 9.20M 5s
  4450K .......... .......... .......... .......... ..........  7% 16.3M 5s
  4500K .......... .......... .......... .......... ..........  7% 15.6M 5s
  4550K .......... .......... .......... .......... ..........  7% 12.8M 5s
  4600K .......... .......... .......... .......... ..........  7% 14.3M 5s
  4650K .......... .......... .......... .......... ..........  8% 9.94M 5s
  4700K .......... .......... .......... .......... ..........  8% 15.6M 5s
  4750K .......... .......... .......... .......... ..........  8% 12.7M 5s
  4800K .......... .......... .......... .......... ..........  8% 11.2M 5s
  4850K .......... .......... .......... .......... ..........  8% 17.0M 5s
  4900K .......... .......... .......... .......... ..........  8% 14.4M 5s
  4950K .......... .......... .......... .......... ..........  8% 11.6M 5s
  5000K .......... .......... .......... .......... ..........  8% 9.57M 5s
  5050K .......... .......... .......... .......... ..........  8% 22.6M 5s
  5100K .......... .......... .......... .......... ..........  8% 12.6M 5s
  5150K .......... .......... .......... .......... ..........  8% 11.4M 5s
  5200K .......... .......... .......... .......... ..........  8% 10.6M 5s
  5250K .......... .......... .......... .......... ..........  9% 13.6M 5s
  5300K .......... .......... .......... .......... ..........  9% 17.0M 5s
  5350K .......... .......... .......... .......... ..........  9% 10.4M 5s
  5400K .......... .......... .......... .......... ..........  9% 14.0M 5s
  5450K .......... .......... .......... .......... ..........  9% 21.1M 5s
  5500K .......... .......... .......... .......... ..........  9% 9.10M 5s
  5550K .......... .......... .......... .......... ..........  9% 8.35M 5s
  5600K .......... .......... .......... .......... ..........  9% 30.4M 5s
  5650K .......... .......... .......... .......... ..........  9% 10.0M 5s
  5700K .......... .......... .......... .......... ..........  9% 12.1M 5s
  5750K .......... .......... .......... .......... ..........  9% 15.3M 5s
  5800K .......... .......... .......... .......... ..........  9% 13.3M 5s
  5850K .......... .......... .......... .......... .......... 10% 18.5M 5s
  5900K .......... .......... .......... .......... .......... 10% 11.4M 5s
  5950K .......... .......... .......... .......... .......... 10% 7.24M 5s
  6000K .......... .......... .......... .......... .......... 10% 28.8M 5s
  6050K .......... .......... .......... .......... .......... 10% 11.8M 5s
  6100K .......... .......... .......... .......... .......... 10% 14.5M 5s
  6150K .......... .......... .......... .......... .......... 10% 10.3M 5s
  6200K .......... .......... .......... .......... .......... 10% 27.3M 5s
  6250K .......... .......... .......... .......... .......... 10% 14.2M 5s
  6300K .......... .......... .......... .......... .......... 10% 11.2M 5s
  6350K .......... .......... .......... .......... .......... 10% 12.8M 5s
  6400K .......... .......... .......... .......... .......... 10% 8.23M 5s
  6450K .......... .......... .......... .......... .......... 11% 20.7M 5s
  6500K .......... .......... .......... .......... .......... 11% 12.7M 5s
  6550K .......... .......... .......... .......... .......... 11% 9.72M 5s
  6600K .......... .......... .......... .......... .......... 11% 22.1M 5s
  6650K .......... .......... .......... .......... .......... 11% 11.4M 5s
  6700K .......... .......... .......... .......... .......... 11% 10.2M 5s
  6750K .......... .......... .......... .......... .......... 11% 12.3M 5s
  6800K .......... .......... .......... .......... .......... 11% 22.0M 5s
  6850K .......... .......... .......... .......... .......... 11% 11.5M 5s
  6900K .......... .......... .......... .......... .......... 11% 16.0M 5s
  6950K .......... .......... .......... .......... .......... 11% 10.6M 5s
  7000K .......... .......... .......... .......... .......... 12% 11.7M 5s
  7050K .......... .......... .......... .......... .......... 12% 16.8M 4s
  7100K .......... .......... .......... .......... .......... 12% 8.08M 5s
  7150K .......... .......... .......... .......... .......... 12% 32.5M 4s
  7200K .......... .......... .......... .......... .......... 12% 8.19M 4s
  7250K .......... .......... .......... .......... .......... 12% 18.1M 4s
  7300K .......... .......... .......... .......... .......... 12% 19.0M 4s
  7350K .......... .......... .......... .......... .......... 12% 7.74M 4s
  7400K .......... .......... .......... .......... .......... 12% 12.4M 4s
  7450K .......... .......... .......... .......... .......... 12% 29.4M 4s
  7500K .......... .......... .......... .......... .......... 12% 15.2M 4s
  7550K .......... .......... .......... .......... .......... 12% 9.79M 4s
  7600K .......... .......... .......... .......... .......... 13% 11.1M 4s
  7650K .......... .......... .......... .......... .......... 13% 11.2M 4s
  7700K .......... .......... .......... .......... .......... 13% 34.7M 4s
  7750K .......... .......... .......... .......... .......... 13% 8.48M 4s
  7800K .......... .......... .......... .......... .......... 13% 12.6M 4s
  7850K .......... .......... .......... .......... .......... 13% 14.5M 4s
  7900K .......... .......... .......... .......... .......... 13% 11.6M 4s
  7950K .......... .......... .......... .......... .......... 13% 10.5M 4s
  8000K .......... .......... .......... .......... .......... 13% 18.4M 4s
  8050K .......... .......... .......... .......... .......... 13% 12.1M 4s
  8100K .......... .......... .......... .......... .......... 13% 11.4M 4s
  8150K .......... .......... .......... .......... .......... 13% 20.1M 4s
  8200K .......... .......... .......... .......... .......... 14% 12.4M 4s
  8250K .......... .......... .......... .......... .......... 14% 7.94M 4s
  8300K .......... .......... .......... .......... .......... 14% 13.5M 4s
  8350K .......... .......... .......... .......... .......... 14% 13.0M 4s
  8400K .......... .......... .......... .......... .......... 14% 17.3M 4s
  8450K .......... .......... .......... .......... .......... 14% 13.5M 4s
  8500K .......... .......... .......... .......... .......... 14% 13.4M 4s
  8550K .......... .......... .......... .......... .......... 14% 9.33M 4s
  8600K .......... .......... .......... .......... .......... 14% 22.3M 4s
  8650K .......... .......... .......... .......... .......... 14% 10.1M 4s
  8700K .......... .......... .......... .......... .......... 14% 18.6M 4s
  8750K .......... .......... .......... .......... .......... 14% 13.0M 4s
  8800K .......... .......... .......... .......... .......... 15% 14.5M 4s
  8850K .......... .......... .......... .......... .......... 15% 12.5M 4s
  8900K .......... .......... .......... .......... .......... 15% 10.6M 4s
  8950K .......... .......... .......... .......... .......... 15% 11.4M 4s
  9000K .......... .......... .......... .......... .......... 15% 14.4M 4s
  9050K .......... .......... .......... .......... .......... 15% 12.0M 4s
  9100K .......... .......... .......... .......... .......... 15% 12.3M 4s
  9150K .......... .......... .......... .......... .......... 15% 14.3M 4s
  9200K .......... .......... .......... .......... .......... 15% 9.99M 4s
  9250K .......... .......... .......... .......... .......... 15% 24.0M 4s
  9300K .......... .......... .......... .......... .......... 15% 6.92M 4s
  9350K .......... .......... .......... .......... .......... 16% 49.1M 4s
  9400K .......... .......... .......... .......... .......... 16% 8.05M 4s
  9450K .......... .......... .......... .......... .......... 16% 21.8M 4s
  9500K .......... .......... .......... .......... .......... 16% 13.0M 4s
  9550K .......... .......... .......... .......... .......... 16% 13.0M 4s
  9600K .......... .......... .......... .......... .......... 16% 13.5M 4s
  9650K .......... .......... .......... .......... .......... 16% 11.1M 4s
  9700K .......... .......... .......... .......... .......... 16% 12.5M 4s
  9750K .......... .......... .......... .......... .......... 16% 14.6M 4s
  9800K .......... .......... .......... .......... .......... 16% 17.2M 4s
  9850K .......... .......... .......... .......... .......... 16% 9.04M 4s
  9900K .......... .......... .......... .......... .......... 16% 16.2M 4s
  9950K .......... .......... .......... .......... .......... 17% 11.9M 4s
 10000K .......... .......... .......... .......... .......... 17% 11.6M 4s
 10050K .......... .......... .......... .......... .......... 17% 14.4M 4s
 10100K .......... .......... .......... .......... .......... 17% 12.6M 4s
 10150K .......... .......... .......... .......... .......... 17% 10.7M 4s
 10200K .......... .......... .......... .......... .......... 17% 13.3M 4s
 10250K .......... .......... .......... .......... .......... 17% 12.9M 4s
 10300K .......... .......... .......... .......... .......... 17% 14.8M 4s
 10350K .......... .......... .......... .......... .......... 17% 15.8M 4s
 10400K .......... .......... .......... .......... .......... 17% 14.9M 4s
 10450K .......... .......... .......... .......... .......... 17% 15.6M 4s
 10500K .......... .......... .......... .......... .......... 17% 9.71M 4s
 10550K .......... .......... .......... .......... .......... 18% 9.54M 4s
 10600K .......... .......... .......... .......... .......... 18% 21.4M 4s
 10650K .......... .......... .......... .......... .......... 18% 9.24M 4s
 10700K .......... .......... .......... .......... .......... 18% 12.1M 4s
 10750K .......... .......... .......... .......... .......... 18% 11.1M 4s
 10800K .......... .......... .......... .......... .......... 18% 20.0M 4s
 10850K .......... .......... .......... .......... .......... 18% 15.2M 4s
 10900K .......... .......... .......... .......... .......... 18% 12.6M 4s
 10950K .......... .......... .......... .......... .......... 18% 7.31M 4s
 11000K .......... .......... .......... .......... .......... 18% 47.0M 4s
 11050K .......... .......... .......... .......... .......... 18% 11.7M 4s
 11100K .......... .......... .......... .......... .......... 18% 10.1M 4s
 11150K .......... .......... .......... .......... .......... 19% 12.0M 4s
 11200K .......... .......... .......... .......... .......... 19% 29.2M 4s
 11250K .......... .......... .......... .......... .......... 19% 13.4M 4s
 11300K .......... .......... .......... .......... .......... 19% 3.19M 4s
 11350K .......... .......... .......... .......... .......... 19%  425M 4s
 11400K .......... .......... .......... .......... .......... 19%  452M 4s

Downloading atb.assembly.r0.2.batch.6.tar.xz from https://osf.io/download/667142a4d835c4399d4ce0c5/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667142a4d835c4399d4ce0c5 [following]
--2026-09-06 18:51:23--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667142a4d835c4399d4ce0c5
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/44303a10eb05e579ffab44bae3634eaa2a2478ef7f8c2a4bb82f444353c80fc2?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.6.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.6.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713544&Signature=oSUhoYf%2FN6lHl%2FRwSfmksEp2am2TwFXQ7CvTQR8BTzoIdPkAI9v40p9UOCJuF8H6iWQOmkc7cUBDI0j4FPsDO7sspacXJr5QDo0Qo7r9%2FijdXL4HecUoDN%2FXgdAwbwcs221mhdUB1Cqa7IXMoWBjzHVyoiskdkMbLme09yDq3OBjZPOVy2ZIUadFLgcI89MKQq5cv1qQvoMNNNOl9p5igq0ioJ8ek8476oKiTs0mSpwZnTGtnuHHDPrZhmitcy6QZuaXnMokR8Mopd4Vwmi%2FXfbVvFV%2BUopgTWIk5hzhdAj%2BfidmDeiTszw5vMyoAD18%2F%2BbkDGbhG7aOtX72HDeGaw%3D%3D [following]
--2026-09-06 18:51:24--  https://storage.googleapis.com/cos-osf-prod-files-de-1/44303a10eb05e579ffab44bae3634eaa2a2478ef7f8c2a4bb82f444353c80fc2?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.6.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.6.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713544&Signature=oSUhoYf%2FN6lHl%2FRwSfmksEp2am2TwFXQ7CvTQR8BTzoIdPkAI9v40p9UOCJuF8H6iWQOmkc7cUBDI0j4FPsDO7sspacXJr5QDo0Qo7r9%2FijdXL4HecUoDN%2FXgdAwbwcs221mhdUB1Cqa7IXMoWBjzHVyoiskdkMbLme09yDq3OBjZPOVy2ZIUadFLgcI89MKQq5cv1qQvoMNNNOl9p5igq0ioJ8ek8476oKiTs0mSpwZnTGtnuHHDPrZhmitcy6QZuaXnMokR8Mopd4Vwmi%2FXfbVvFV%2BUopgTWIk5hzhdAj%2BfidmDeiTszw5vMyoAD18%2F%2BbkDGbhG7aOtX72HDeGaw%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.14.207, 142.250.154.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.14.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18057140 (17M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.6.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.48M 12s
    50K .......... .......... .......... .......... ..........  0% 2.79M 9s
   100K .......... .......... .......... .......... ..........  0% 4.59M 7s
   150K .......... .......... .......... .......... ..........  1% 5.42M 6s
   200K .......... .......... .......... .......... ..........  1% 8.68M 5s
   250K .......... .......... .......... .......... ..........  1% 8.32M 5s
   300K .......... .......... .......... .......... ..........  1% 23.1M 4s
   350K .......... .......... .......... .......... ..........  2% 8.62M 4s
   400K .......... .......... .......... .......... ..........  2% 17.7M 4s
   450K .......... .......... .......... .......... ..........  2% 9.31M 3s
   500K .......... .......... .......... .......... ..........  3% 15.4M 3s
   550K .......... .......... .......... .......... ..........  3% 10.5M 3s
   600K .......... .......... .......... .......... ..........  3% 13.0M 3s
   650K .......... .......... .......... .......... ..........  3% 20.8M 3s
   700K .......... .......... .......... .......... ..........  4% 12.2M 3s
   750K .......... .......... .......... .......... ..........  4% 10.6M 3s
   800K .......... .......... .......... .......... ..........  4% 11.6M 2s
   850K .......... .......... .......... .......... ..........  5% 13.5M 2s
   900K .......... .......... .......... .......... ..........  5% 12.3M 2s
   950K .......... .......... .......... .......... ..........  5% 14.6M 2s
  1000K .......... .......... .......... .......... ..........  5% 13.2M 2s
  1050K .......... .......... .......... .......... ..........  6% 14.3M 2s
  1100K .......... .......... .......... .......... ..........  6% 12.5M 2s
  1150K .......... .......... .......... .......... ..........  6% 9.26M 2s
  1200K .......... .......... .......... .......... ..........  7% 11.1M 2s
  1250K .......... .......... .......... .......... ..........  7% 13.4M 2s
  1300K .......... .......... .......... .......... ..........  7% 16.4M 2s
  1350K .......... .......... .......... .......... ..........  7% 18.1M 2s
  1400K .......... .......... .......... .......... ..........  8% 14.6M 2s
  1450K .......... .......... .......... .......... ..........  8% 11.1M 2s
  1500K .......... .......... .......... .......... ..........  8% 12.5M 2s
  1550K .......... .......... .......... .......... ..........  9% 8.28M 2s
  1600K .......... .......... .......... .......... ..........  9% 32.3M 2s
  1650K .......... .......... .......... .......... ..........  9% 11.0M 2s
  1700K .......... .......... .......... .......... ..........  9% 11.1M 2s
  1750K .......... .......... .......... .......... .......... 10% 12.5M 2s
  1800K .......... .......... .......... .......... .......... 10% 29.5M 2s
  1850K .......... .......... .......... .......... .......... 10% 9.51M 2s
  1900K .......... .......... .......... .......... .......... 11% 10.9M 2s
  1950K .......... .......... .......... .......... .......... 11% 12.5M 2s
  2000K .......... .......... .......... .......... .......... 11% 13.1M 2s
  2050K .......... .......... .......... .......... .......... 11% 13.2M 2s
  2100K .......... .......... .......... .......... .......... 12% 13.8M 2s
  2150K .......... .......... .......... .......... .......... 12% 14.5M 2s
  2200K .......... .......... .......... .......... .......... 12% 15.3M 2s
  2250K .......... .......... .......... .......... .......... 13% 16.3M 2s
  2300K .......... .......... .......... .......... .......... 13% 10.5M 2s
  2350K .......... .......... .......... .......... .......... 13% 10.8M 2s
  2400K .......... .......... .......... .......... .......... 13% 10.9M 2s
  2450K .......... .......... .......... .......... .......... 14% 14.3M 2s
  2500K .......... .......... .......... .......... .......... 14% 13.6M 1s
  2550K .......... .......... .......... .......... .......... 14% 11.2M 1s
  2600K .......... .......... .......... .......... .......... 15% 25.2M 1s
  2650K .......... .......... .......... .......... .......... 15% 13.2M 1s
  2700K .......... .......... .......... .......... .......... 15% 12.6M 1s
  2750K .......... .......... .......... .......... .......... 15% 7.52M 1s
  2800K .......... .......... .......... .......... .......... 16% 20.0M 1s
  2850K .......... .......... .......... .......... .......... 16% 10.1M 1s
  2900K .......... .......... .......... .......... .......... 16% 18.7M 1s
  2950K .......... .......... .......... .......... .......... 17% 9.06M 1s
  3000K .......... .......... .......... .......... .......... 17% 25.6M 1s
  3050K .......... .......... .......... .......... .......... 17% 8.71M 1s
  3100K .......... .......... .......... .......... .......... 17% 11.4M 1s
  3150K .......... .......... .......... .......... .......... 18% 19.1M 1s
  3200K .......... .......... .......... .......... .......... 18% 15.0M 1s
  3250K .......... .......... .......... .......... .......... 18% 14.6M 1s
  3300K .......... .......... .......... .......... .......... 18% 8.70M 1s
  3350K .......... .......... .......... .......... .......... 19% 12.3M 1s
  3400K .......... .......... .......... .......... .......... 19% 24.6M 1s
  3450K .......... .......... .......... .......... .......... 19% 12.0M 1s
  3500K .......... .......... .......... .......... .......... 20% 11.0M 1s
  3550K .......... .......... .......... .......... .......... 20% 11.6M 1s
  3600K .......... .......... .......... .......... .......... 20% 11.5M 1s
  3650K .......... .......... .......... .......... .......... 20% 23.0M 1s
  3700K .......... .......... .......... .......... .......... 21% 10.2M 1s
  3750K .......... .......... .......... .......... .......... 21% 16.0M 1s
  3800K .......... .......... .......... .......... .......... 21% 14.5M 1s
  3850K .......... .......... .......... .......... .......... 22% 9.43M 1s
  3900K .......... .......... .......... .......... .......... 22% 22.1M 1s
  3950K .......... .......... .......... .......... .......... 22% 10.1M 1s
  4000K .......... .......... .......... .......... .......... 22% 9.12M 1s
  4050K .......... .......... .......... .......... .......... 23% 22.5M 1s
  4100K .......... .......... .......... .......... .......... 23% 8.22M 1s
  4150K .......... .......... .......... .......... .......... 23% 22.2M 1s
  4200K .......... .......... .......... .......... .......... 24% 12.7M 1s
  4250K .......... .......... .......... .......... .......... 24% 18.9M 1s
  4300K .......... .......... .......... .......... .......... 24% 13.0M 1s
  4350K .......... .......... .......... .......... .......... 24% 9.11M 1s
  4400K .......... .......... .......... .......... .......... 25% 11.5M 1s
  4450K .......... .......... .......... .......... .......... 25% 13.6M 1s
  4500K .......... .......... .......... .......... .......... 25% 10.9M 1s
  4550K .......... .......... .......... .......... .......... 26% 13.7M 1s
  4600K .......... .......... .......... .......... .......... 26% 19.9M 1s
  4650K .......... .......... .......... .......... .......... 26% 11.6M 1s
  4700K .......... .......... .......... .......... .......... 26% 12.5M 1s
  4750K .......... .......... .......... .......... .......... 27% 12.3M 1s
  4800K .......... .......... .......... .......... .......... 27% 9.65M 1s
  4850K .......... .......... .......... .......... .......... 27% 25.6M 1s
  4900K .......... .......... .......... .......... .......... 28% 11.2M 1s
  4950K .......... .......... .......... .......... .......... 28% 10.5M 1s
  5000K .......... .......... .......... .......... .......... 28% 16.1M 1s
  5050K .......... .......... .......... .......... .......... 28% 11.0M 1s
  5100K .......... .......... .......... .......... .......... 29% 17.6M 1s
  5150K .......... .......... .......... .......... .......... 29% 9.49M 1s
  5200K .......... .......... .......... .......... .......... 29% 17.8M 1s
  5250K .......... .......... .......... .......... .......... 30% 10.9M 1s
  5300K .......... .......... .......... .......... .......... 30% 11.2M 1s
  5350K .......... .......... .......... .......... .......... 30% 16.2M 1s
  5400K .......... .......... .......... .......... .......... 30% 11.4M 1s
  5450K .......... .......... .......... .......... .......... 31% 11.5M 1s
  5500K .......... .......... .......... .......... .......... 31% 12.6M 1s
  5550K .......... .......... .......... .......... .......... 31% 14.9M 1s
  5600K .......... .......... .......... .......... .......... 32% 12.6M 1s
  5650K .......... .......... .......... .......... .......... 32% 12.9M 1s
  5700K .......... .......... .......... .......... .......... 32% 11.7M 1s
  5750K .......... .......... .......... .......... .......... 32% 20.4M 1s
  5800K .......... .......... .......... .......... .......... 33% 9.31M 1s
  5850K .......... .......... .......... .......... .......... 33% 14.1M 1s
  5900K .......... .......... .......... .......... .......... 33% 25.5M 1s
  5950K .......... .......... .......... .......... .......... 34% 7.50M 1s
  6000K .......... .......... .......... .......... .......... 34% 23.2M 1s
  6050K .......... .......... .......... .......... .......... 34% 14.3M 1s
  6100K .......... .......... .......... .......... .......... 34% 9.64M 1s
  6150K .......... .......... .......... .......... .......... 35% 11.9M 1s
  6200K .......... .......... .......... .......... .......... 35% 22.3M 1s
  6250K .......... .......... .......... .......... .......... 35% 12.2M 1s
  6300K .......... .......... .......... .......... .......... 36% 10.5M 1s
  6350K .......... .......... .......... .......... .......... 36% 2.87M 1s
  6400K .......... .......... .......... .......... .......... 36%  474M 1s
  6450K .......... .......... .......... .......... .......... 36%  531M 1s
  6500K .......... .......... .......... .......... .......... 37%  568M 1s
  6550K .......... .......... .......... .......... .......... 37% 38.3M 1s
  6600K .......... .......... .......... .......... .......... 37% 15.5M 1s
  6650K .......... .......... .......... .......... .......... 37% 9.79M 1s
  6700K .......... .......... .......... .......... .......... 38% 14.6M 1s
  6750K .......... .......... .......... .......... .......... 38% 9.52M 1s
  6800K .......... .......... .......... .......... .......... 38% 18.3M 1s
  6850K .......... .......... .......... .......... .......... 39% 10.7M 1s
  6900K .......... .......... .......... .......... .......... 39% 13.5M 1s
  6950K .......... .......... .......... .......... .......... 39% 16.0M 1s
  7000K .......... .......... .......... .......... .......... 39% 10.7M 1s
  7050K .......... .......... .......... .......... .......... 40% 13.4M 1s
  7100K .......... .......... .......... .......... .......... 40% 13.1M 1s
  7150K .......... .......... .......... .......... .......... 40% 9.36M 1s
  7200K .......... .......... .......... .......... .......... 41% 13.1M 1s
  7250K .......... .......... .......... .......... .......... 41% 14.7M 1s
  7300K .......... .......... .......... .......... .......... 41% 17.6M 1s
  7350K .......... .......... .......... .......... .......... 41% 11.0M 1s
  7400K .......... .......... .......... .......... .......... 42% 12.1M 1s
  7450K .......... .......... .......... .......... .......... 42% 15.4M 1s
  7500K .......... .......... .......... .......... .......... 42% 16.7M 1s
  7550K .......... .......... .......... .......... .......... 43% 8.05M 1s
  7600K .......... .......... .......... .......... .......... 43% 16.9M 1s
  7650K .......... .......... .......... .......... .......... 43% 13.6M 1s
  7700K .......... .......... .......... .......... .......... 43% 17.9M 1s
  7750K .......... .......... .......... .......... .......... 44% 9.11M 1s
  7800K .......... .......... .......... .......... .......... 44% 21.2M 1s
  7850K .......... .......... .......... .......... .......... 44% 13.8M 1s
  7900K .......... .......... .......... .......... .......... 45% 12.6M 1s
  7950K .......... .......... .......... .......... .......... 45% 7.94M 1s
  8000K .......... .......... .......... .......... .......... 45% 10.5M 1s
  8050K .......... .......... .......... .......... .......... 45% 28.9M 1s
  8100K .......... .......... .......... .......... .......... 46% 12.6M 1s
  8150K .......... .......... .......... .......... .......... 46% 8.44M 1s
  8200K .......... .......... .......... .......... .......... 46% 21.3M 1s
  8250K .......... .......... .......... .......... .......... 47% 20.6M 1s
  8300K .......... .......... .......... .......... .......... 47% 9.90M 1s
  8350K .......... .......... .......... .......... .......... 47% 23.0M 1s
  8400K .......... .......... .......... .......... .......... 47% 8.84M 1s
  8450K .......... .......... .......... .......... .......... 48% 14.0M 1s
  8500K .......... .......... .......... .......... .......... 48% 9.50M 1s
  8550K .......... .......... .......... .......... .......... 48% 14.6M 1s
  8600K .......... .......... .......... .......... .......... 49% 11.1M 1s
  8650K .......... .......... .......... .......... .......... 49% 25.0M 1s
  8700K .......... .......... .......... .......... .......... 49% 10.9M 1s
  8750K .......... .......... .......... .......... .......... 49% 10.3M 1s
  8800K .......... .......... .......... .......... .......... 50% 13.3M 1s
  8850K .......... .......... .......... .......... .......... 50% 14.2M 1s
  8900K .......... .......... .......... .......... .......... 50% 13.1M 1s
  8950K .......... .......... .......... .......... .......... 51% 11.7M 1s
  9000K .......... .......... .......... .......... .......... 51% 12.9M 1s
  9050K .......... .......... .......... .......... .......... 51% 19.0M 1s
  9100K .......... .......... .......... .......... .......... 51% 11.0M 1s
  9150K .......... .......... .......... .......... .......... 52% 8.68M 1s
  9200K .......... .......... .......... .......... .......... 52% 19.0M 1s
  9250K .......... .......... .......... .......... .......... 52% 13.9M 1s
  9300K .......... .......... .......... .......... .......... 53% 10.7M 1s
  9350K .......... .......... .......... .......... .......... 53% 16.2M 1s
  9400K .......... .......... .......... .......... .......... 53% 10.5M 1s
  9450K .......... .......... .......... .......... .......... 53% 13.0M 1s
  9500K .......... .......... .......... .......... .......... 54% 20.9M 1s
  9550K .......... .......... .......... .......... .......... 54% 9.41M 1s
  9600K .......... .......... .......... .......... .......... 54% 14.6M 1s
  9650K .......... .......... .......... .......... .......... 55% 9.95M 1s
  9700K .......... .......... .......... .......... .......... 55% 20.2M 1s
  9750K .......... .......... .......... .......... .......... 55% 11.2M 1s
  9800K .......... .......... .......... .......... .......... 55% 12.0M 1s
  9850K .......... .......... .......... .......... .......... 56% 11.3M 1s
  9900K .......... .......... .......... .......... .......... 56% 31.6M 1s
  9950K .......... .......... .......... .......... .......... 56% 7.12M 1s
 10000K .......... .......... .......... .......... .......... 56% 25.7M 1s
 10050K .......... .......... .......... .......... .......... 57% 9.83M 1s
 10100K .......... .......... .......... .......... .......... 57% 12.2M 1s
 10150K .......... .......... .......... .......... .......... 57% 12.4M 1s
 10200K .......... .......... .......... .......... .......... 58% 16.4M 1s
 10250K .......... .......... .......... .......... .......... 58% 14.7M 1s
 10300K .......... .......... .......... .......... .......... 58% 13.9M 1s
 10350K .......... .......... .......... .......... .......... 58% 8.06M 1s
 10400K .......... .......... .......... .......... .......... 59% 17.3M 1s
 10450K .......... .......... .......... .......... .......... 59% 12.5M 1s
 10500K .......... .......... .......... .......... .......... 59% 16.3M 1s
 10550K .......... .......... .......... .......... .......... 60% 10.6M 1s
 10600K .......... .......... .......... .......... .......... 60% 23.0M 1s
 10650K .......... .......... .......... .......... .......... 60% 11.1M 1s
 10700K .......... .......... .......... .......... .......... 60% 14.9M 1s
 10750K .......... .......... .......... .......... .......... 61% 8.61M 1s
 10800K .......... .......... .......... .......... .......... 61% 11.4M 1s
 10850K .......... .......... .......... .......... .......... 61% 12.2M 1s
 10900K .......... .......... .......... .......... .......... 62% 14.1M 1s
 10950K .......... .......... .......... .......... .......... 62% 20.2M 1s
 11000K .......... .......... .......... .......... .......... 62% 10.5M 1s
 11050K .......... .......... .......... .......... .......... 62% 12.2M 1s
 11100K .......... .......... .......... .......... .......... 63% 24.7M 1s
 11150K .......... .......... .......... .......... .......... 63% 9.35M 1s
 11200K .......... .......... .......... .......... .......... 63% 16.9M 1s
 11250K .......... .......... .......... .......... .......... 64% 9.35M 1s
 11300K .......... .......... .......... .......... .......... 64% 9.83M 1s
 11350K .......... .......... .......... .......... .......... 64% 50.6M 1s
 11400K .......... .......... .......... .......... .......... 64% 12.0M 1s
 11450K .......... .......... .......... .......... .......... 65% 14.0M 0s
 11500K .......... .......... .......... .......... .......... 65% 10.2M 0s
 11550K .......... .......... .......... .......... .......... 65% 14.1M 0s

Downloading atb.assembly.r0.2.batch.7.tar.xz from https://osf.io/download/667142c365e1de5e73893c37/

--2026-09-06 18:51:26--  https://osf.io/download/667142c365e1de5e73893c37/
Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667142c365e1de5e73893c37 [following]
--2026-09-06 18:51:26--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667142c365e1de5e73893c37
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/8fda0867d5c33342706616425fbdaa075743a803f23c66d854f619be8c0a66a3?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.7.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.7.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713547&Signature=twn8kzjfgwJcrCkFC4Wz644RThRVmS9hjwqQNrNhXFN1bQqDwJpeI1ZMFoGmJQi64dG03KAEfLbcXTKpOZWMG2as%2FWDZwKTy4K964WmboqfMbJh%2Be6niKIl9WneOCbI3hgwiDRt5sMg09W0zWz0o3dSHvO27bmYFdMdByySx0HornSWplqbjUBthGYf5Drm9mNkohm6NzXL3zMCmU6BA9Vws6ldxMAJJHf1qe31MdeGZCzToqZkOMehHbIT2EAtKz8wEDdk531r6%2BUJPGm4CLDaFutFAWEiwlIWKWSlep2KQzTxvJUNw5MUGywVmc%2B8F%2FvLU45C0cHo69XOiE9StuA%3D%3D [following]
--2026-09-06 18:51:27--  https://storage.googleapis.com/cos-osf-prod-files-de-1/8fda0867d5c33342706616425fbdaa075743a803f23c66d854f619be8c0a66a3?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.7.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.7.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713547&Signature=twn8kzjfgwJcrCkFC4Wz644RThRVmS9hjwqQNrNhXFN1bQqDwJpeI1ZMFoGmJQi64dG03KAEfLbcXTKpOZWMG2as%2FWDZwKTy4K964WmboqfMbJh%2Be6niKIl9WneOCbI3hgwiDRt5sMg09W0zWz0o3dSHvO27bmYFdMdByySx0HornSWplqbjUBthGYf5Drm9mNkohm6NzXL3zMCmU6BA9Vws6ldxMAJJHf1qe31MdeGZCzToqZkOMehHbIT2EAtKz8wEDdk531r6%2BUJPGm4CLDaFutFAWEiwlIWKWSlep2KQzTxvJUNw5MUGywVmc%2B8F%2FvLU45C0cHo69XOiE9StuA%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 142.251.20.207, 142.251.127.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 37261548 (36M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.7.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.58M 22s
    50K .......... .......... .......... .......... ..........  0% 2.60M 18s
   100K .......... .......... .......... .......... ..........  0% 4.64M 15s
   150K .......... .......... .......... .......... ..........  0% 5.44M 13s
   200K .......... .......... .......... .......... ..........  0% 6.47M 11s
   250K .......... .......... .......... .......... ..........  0% 6.47M 10s
   300K .......... .......... .......... .......... ..........  0% 9.17M 9s
   350K .......... .......... .......... .......... ..........  1% 12.7M 8s
   400K .......... .......... .......... .......... ..........  1% 12.0M 8s
   450K .......... .......... .......... .......... ..........  1% 13.6M 7s
   500K .......... .......... .......... .......... ..........  1% 12.9M 7s
   550K .......... .......... .......... .......... ..........  1% 9.81M 7s
   600K .......... .......... .......... .......... ..........  1% 11.5M 6s
   650K .......... .......... .......... .......... ..........  1% 13.8M 6s
   700K .......... .......... .......... .......... ..........  2% 20.3M 6s
   750K .......... .......... .......... .......... ..........  2% 10.0M 6s
   800K .......... .......... .......... .......... ..........  2% 12.7M 5s
   850K .......... .......... .......... .......... ..........  2% 12.4M 5s
   900K .......... .......... .......... .......... ..........  2% 11.1M 5s
   950K .......... .......... .......... .......... ..........  2% 12.5M 5s
  1000K .......... .......... .......... .......... ..........  2% 12.9M 5s
  1050K .......... .......... .......... .......... ..........  3% 20.6M 5s
  1100K .......... .......... .......... .......... ..........  3% 13.4M 5s
  1150K .......... .......... .......... .......... ..........  3% 9.25M 5s
  1200K .......... .......... .......... .......... ..........  3% 11.4M 5s
  1250K .......... .......... .......... .......... ..........  3% 13.6M 4s
  1300K .......... .......... .......... .......... ..........  3% 22.0M 4s
  1350K .......... .......... .......... .......... ..........  3% 10.6M 4s
  1400K .......... .......... .......... .......... ..........  3% 15.2M 4s
  1450K .......... .......... .......... .......... ..........  4% 14.0M 4s
  1500K .......... .......... .......... .......... ..........  4% 8.99M 4s
  1550K .......... .......... .......... .......... ..........  4% 13.0M 4s
  1600K .......... .......... .......... .......... ..........  4% 13.3M 4s
  1650K .......... .......... .......... .......... ..........  4% 9.71M 4s
  1700K .......... .......... .......... .......... ..........  4% 43.3M 4s
  1750K .......... .......... .......... .......... ..........  4% 9.69M 4s
  1800K .......... .......... .......... .......... ..........  5% 12.9M 4s
  1850K .......... .......... .......... .......... ..........  5% 11.3M 4s
  1900K .......... .......... .......... .......... ..........  5% 18.4M 4s
  1950K .......... .......... .......... .......... ..........  5% 8.63M 4s
  2000K .......... .......... .......... .......... ..........  5% 12.6M 4s
  2050K .......... .......... .......... .......... ..........  5% 13.7M 4s
  2100K .......... .......... .......... .......... ..........  5% 17.5M 4s
  2150K .......... .......... .......... .......... ..........  6% 12.4M 4s
  2200K .......... .......... .......... .......... ..........  6% 13.9M 4s
  2250K .......... .......... .......... .......... ..........  6% 14.8M 4s
  2300K .......... .......... .......... .......... ..........  6% 12.4M 4s
  2350K .......... .......... .......... .......... ..........  6% 10.4M 4s
  2400K .......... .......... .......... .......... ..........  6% 16.0M 3s
  2450K .......... .......... .......... .......... ..........  6% 11.6M 3s
  2500K .......... .......... .......... .......... ..........  7% 9.48M 3s
  2550K .......... .......... .......... .......... ..........  7% 16.8M 3s
  2600K .......... .......... .......... .......... ..........  7% 13.1M 3s
  2650K .......... .......... .......... .......... ..........  7% 12.4M 3s
  2700K .......... .......... .......... .......... ..........  7% 14.4M 3s
  2750K .......... .......... .......... .......... ..........  7% 10.1M 3s
  2800K .......... .......... .......... .......... ..........  7% 9.62M 3s
  2850K .......... .......... .......... .......... ..........  7% 19.6M 3s
  2900K .......... .......... .......... .......... ..........  8% 11.3M 3s
  2950K .......... .......... .......... .......... ..........  8% 21.4M 3s
  3000K .......... .......... .......... .......... ..........  8% 9.45M 3s
  3050K .......... .......... .......... .......... ..........  8% 18.4M 3s
  3100K .......... .......... .......... .......... ..........  8% 11.8M 3s
  3150K .......... .......... .......... .......... ..........  8% 14.7M 3s
  3200K .......... .......... .......... .......... ..........  8% 10.6M 3s
  3250K .......... .......... .......... .......... ..........  9% 13.7M 3s
  3300K .......... .......... .......... .......... ..........  9% 11.5M 3s
  3350K .......... .......... .......... .......... ..........  9% 25.8M 3s
  3400K .......... .......... .......... .......... ..........  9% 8.59M 3s
  3450K .......... .......... .......... .......... ..........  9% 13.6M 3s
  3500K .......... .......... .......... .......... ..........  9% 17.0M 3s
  3550K .......... .......... .......... .......... ..........  9% 9.26M 3s
  3600K .......... .......... .......... .......... .......... 10% 14.0M 3s
  3650K .......... .......... .......... .......... .......... 10% 17.3M 3s
  3700K .......... .......... .......... .......... .......... 10% 12.7M 3s
  3750K .......... .......... .......... .......... .......... 10% 11.1M 3s
  3800K .......... .......... .......... .......... .......... 10% 14.2M 3s
  3850K .......... .......... .......... .......... .......... 10% 18.7M 3s
  3900K .......... .......... .......... .......... .......... 10% 8.77M 3s
  3950K .......... .......... .......... .......... .......... 10% 11.6M 3s
  4000K .......... .......... .......... .......... .......... 11% 12.5M 3s
  4050K .......... .......... .......... .......... .......... 11% 18.7M 3s
  4100K .......... .......... .......... .......... .......... 11% 10.8M 3s
  4150K .......... .......... .......... .......... .......... 11% 12.3M 3s
  4200K .......... .......... .......... .......... .......... 11% 20.3M 3s
  4250K .......... .......... .......... .......... .......... 11% 9.65M 3s
  4300K .......... .......... .......... .......... .......... 11% 12.1M 3s
  4350K .......... .......... .......... .......... .......... 12% 8.72M 3s
  4400K .......... .......... .......... .......... .......... 12% 9.26M 3s
  4450K .......... .......... .......... .......... .......... 12%  351M 3s
  4500K .......... .......... .......... .......... .......... 12% 8.90M 3s
  4550K .......... .......... .......... .......... .......... 12% 29.5M 3s
  4600K .......... .......... .......... .......... .......... 12% 11.9M 3s
  4650K .......... .......... .......... .......... .......... 12% 15.2M 3s
  4700K .......... .......... .......... .......... .......... 13% 11.7M 3s
  4750K .......... .......... .......... .......... .......... 13% 11.0M 3s
  4800K .......... .......... .......... .......... .......... 13% 16.3M 3s
  4850K .......... .......... .......... .......... .......... 13% 9.79M 3s
  4900K .......... .......... .......... .......... .......... 13% 19.8M 3s
  4950K .......... .......... .......... .......... .......... 13% 11.6M 3s
  5000K .......... .......... .......... .......... .......... 13% 10.7M 3s
  5050K .......... .......... .......... .......... .......... 14% 17.2M 3s
  5100K .......... .......... .......... .......... .......... 14% 11.5M 3s
  5150K .......... .......... .......... .......... .......... 14% 10.9M 3s
  5200K .......... .......... .......... .......... .......... 14% 10.9M 3s
  5250K .......... .......... .......... .......... .......... 14% 14.5M 3s
  5300K .......... .......... .......... .......... .......... 14% 18.6M 3s
  5350K .......... .......... .......... .......... .......... 14% 9.24M 3s
  5400K .......... .......... .......... .......... .......... 14% 14.5M 3s
  5450K .......... .......... .......... .......... .......... 15% 14.8M 3s
  5500K .......... .......... .......... .......... .......... 15% 12.2M 3s
  5550K .......... .......... .......... .......... .......... 15% 10.6M 3s
  5600K .......... .......... .......... .......... .......... 15% 10.1M 3s
  5650K .......... .......... .......... .......... .......... 15% 24.2M 3s
  5700K .......... .......... .......... .......... .......... 15% 13.7M 3s
  5750K .......... .......... .......... .......... .......... 15% 13.8M 3s
  5800K .......... .......... .......... .......... .......... 16% 15.0M 3s
  5850K .......... .......... .......... .......... .......... 16% 9.10M 3s
  5900K .......... .......... .......... .......... .......... 16% 16.9M 3s
  5950K .......... .......... .......... .......... .......... 16% 10.7M 3s
  6000K .......... .......... .......... .......... .......... 16% 11.8M 3s
  6050K .......... .......... .......... .......... .......... 16% 12.2M 3s
  6100K .......... .......... .......... .......... .......... 16% 14.8M 3s
  6150K .......... .......... .......... .......... .......... 17% 12.5M 3s
  6200K .......... .......... .......... .......... .......... 17% 12.3M 3s
  6250K .......... .......... .......... .......... .......... 17% 17.1M 3s
  6300K .......... .......... .......... .......... .......... 17% 10.0M 3s
  6350K .......... .......... .......... .......... .......... 17% 26.4M 3s
  6400K .......... .......... .......... .......... .......... 17% 10.2M 3s
  6450K .......... .......... .......... .......... .......... 17% 10.8M 3s
  6500K .......... .......... .......... .......... .......... 18% 12.2M 3s
  6550K .......... .......... .......... .......... .......... 18% 18.0M 3s
  6600K .......... .......... .......... .......... .......... 18% 7.56M 3s
  6650K .......... .......... .......... .......... .......... 18% 22.4M 3s
  6700K .......... .......... .......... .......... .......... 18% 12.5M 3s
  6750K .......... .......... .......... .......... .......... 18% 15.3M 3s
  6800K .......... .......... .......... .......... .......... 18% 10.3M 3s
  6850K .......... .......... .......... .......... .......... 18% 10.9M 3s
  6900K .......... .......... .......... .......... .......... 19% 12.9M 3s
  6950K .......... .......... .......... .......... .......... 19% 11.1M 3s
  7000K .......... .......... .......... .......... .......... 19% 11.8M 3s
  7050K .......... .......... .......... .......... .......... 19% 28.0M 3s
  7100K .......... .......... .......... .......... .......... 19% 10.5M 3s
  7150K .......... .......... .......... .......... .......... 19% 12.4M 2s
  7200K .......... .......... .......... .......... .......... 19% 11.3M 2s
  7250K .......... .......... .......... .......... .......... 20% 13.6M 2s
  7300K .......... .......... .......... .......... .......... 20% 12.8M 2s
  7350K .......... .......... .......... .......... .......... 20% 14.2M 2s
  7400K .......... .......... .......... .......... .......... 20% 14.5M 2s
  7450K .......... .......... .......... .......... .......... 20% 20.2M 2s
  7500K .......... .......... .......... .......... .......... 20% 12.4M 2s
  7550K .......... .......... .......... .......... .......... 20% 8.18M 2s
  7600K .......... .......... .......... .......... .......... 21% 14.3M 2s
  7650K .......... .......... .......... .......... .......... 21% 12.0M 2s
  7700K .......... .......... .......... .......... .......... 21% 14.1M 2s
  7750K .......... .......... .......... .......... .......... 21% 16.6M 2s
  7800K .......... .......... .......... .......... .......... 21% 11.8M 2s
  7850K .......... .......... .......... .......... .......... 21% 14.9M 2s
  7900K .......... .......... .......... .......... .......... 21% 13.5M 2s
  7950K .......... .......... .......... .......... .......... 21% 8.48M 2s
  8000K .......... .......... .......... .......... .......... 22% 13.8M 2s
  8050K .......... .......... .......... .......... .......... 22% 12.3M 2s
  8100K .......... .......... .......... .......... .......... 22% 13.3M 2s
  8150K .......... .......... .......... .......... .......... 22% 13.4M 2s
  8200K .......... .......... .......... .......... .......... 22% 23.4M 2s
  8250K .......... .......... .......... .......... .......... 22% 11.2M 2s
  8300K .......... .......... .......... .......... .......... 22% 8.74M 2s
  8350K .......... .......... .......... .......... .......... 23% 12.7M 2s
  8400K .......... .......... .......... .......... .......... 23% 16.3M 2s
  8450K .......... .......... .......... .......... .......... 23% 11.9M 2s
  8500K .......... .......... .......... .......... .......... 23% 14.6M 2s
  8550K .......... .......... .......... .......... .......... 23% 14.6M 2s
  8600K .......... .......... .......... .......... .......... 23% 10.7M 2s
  8650K .......... .......... .......... .......... .......... 23% 9.92M 2s
  8700K .......... .......... .......... .......... .......... 24% 36.2M 2s
  8750K .......... .......... .......... .......... .......... 24% 7.83M 2s
  8800K .......... .......... .......... .......... .......... 24% 16.7M 2s
  8850K .......... .......... .......... .......... .......... 24% 13.2M 2s
  8900K .......... .......... .......... .......... .......... 24% 15.8M 2s
  8950K .......... .......... .......... .......... .......... 24% 16.1M 2s
  9000K .......... .......... .......... .......... .......... 24% 8.76M 2s
  9050K .......... .......... .......... .......... .......... 25% 15.1M 2s
  9100K .......... .......... .......... .......... .......... 25% 12.6M 2s
  9150K .......... .......... .......... .......... .......... 25% 9.48M 2s
  9200K .......... .......... .......... .......... .......... 25% 15.1M 2s
  9250K .......... .......... .......... .......... .......... 25% 19.2M 2s
  9300K .......... .......... .......... .......... .......... 25% 11.7M 2s
  9350K .......... .......... .......... .......... .......... 25% 16.1M 2s
  9400K .......... .......... .......... .......... .......... 25% 9.84M 2s
  9450K .......... .......... .......... .......... .......... 26% 13.0M 2s
  9500K .......... .......... .......... .......... .......... 26% 20.5M 2s
  9550K .......... .......... .......... .......... .......... 26% 10.6M 2s
  9600K .......... .......... .......... .......... .......... 26% 12.4M 2s
  9650K .......... .......... .......... .......... .......... 26% 7.93M 2s
  9700K .......... .......... .......... .......... .......... 26% 46.2M 2s
  9750K .......... .......... .......... .......... .......... 26% 12.0M 2s
  9800K .......... .......... .......... .......... .......... 27% 17.1M 2s
  9850K .......... .......... .......... .......... .......... 27% 10.0M 2s
  9900K .......... .......... .......... .......... .......... 27% 11.3M 2s
  9950K .......... .......... .......... .......... .......... 27% 16.3M 2s
 10000K .......... .......... .......... .......... .......... 27% 9.20M 2s
 10050K .......... .......... .......... .......... .......... 27% 13.1M 2s
 10100K .......... .......... .......... .......... .......... 27% 13.2M 2s
 10150K .......... .......... .......... .......... .......... 28% 18.3M 2s
 10200K .......... .......... .......... .......... .......... 28% 11.4M 2s
 10250K .......... .......... .......... .......... .......... 28% 11.0M 2s
 10300K .......... .......... .......... .......... .......... 28% 17.2M 2s
 10350K .......... .......... .......... .......... .......... 28% 11.2M 2s
 10400K .......... .......... .......... .......... .......... 28% 11.1M 2s
 10450K .......... .......... .......... .......... .......... 28% 15.3M 2s
 10500K .......... .......... .......... .......... .......... 28% 10.1M 2s
 10550K .......... .......... .......... .......... .......... 29% 14.9M 2s
 10600K .......... .......... .......... .......... .......... 29% 23.8M 2s
 10650K .......... .......... .......... .......... .......... 29% 8.31M 2s
 10700K .......... .......... .......... .......... .......... 29% 36.3M 2s
 10750K .......... .......... .......... .......... .......... 29% 7.93M 2s
 10800K .......... .......... .......... .......... .......... 29% 14.5M 2s
 10850K .......... .......... .......... .......... .......... 29% 10.4M 2s
 10900K .......... .......... .......... .......... .......... 30% 12.4M 2s
 10950K .......... .......... .......... .......... .......... 30% 15.4M 2s
 11000K .......... .......... .......... .......... .......... 30% 21.8M 2s
 11050K .......... .......... .......... .......... .......... 30% 9.66M 2s
 11100K .......... .......... .......... .......... .......... 30% 11.1M 2s
 11150K .......... .......... .......... .......... .......... 30% 12.1M 2s
 11200K .......... .......... .......... .......... .......... 30% 7.58M 2s
 11250K .......... .......... .......... .......... .......... 31%  503M 2s
 11300K .......... .......... .......... .......... .......... 31% 10.5M 2s
 11350K .......... .......... .......... .......... .......... 31% 13.9M 2s
 11400K .......... .......... .......... .......... .......... 31% 14.4M 2s

Downloading atb.assembly.r0.2.batch.13.tar.xz from https://osf.io/download/6671439077ff4c5f1de045cc/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671439077ff4c5f1de045cc [following]
--2026-09-06 18:51:31--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671439077ff4c5f1de045cc
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/4b728b4df329de1d5bb5147f98c6781b052372bbd5159a91adf87e169ea378a4?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.13.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.13.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713551&Signature=sIx2c58gRwhRs1Yxe8UTELWIv5gVLAJTBFQK9x5RJ%2B3hO380Frcwh07BuUVHRReFtfNn4twftIwkvthFPmSJ3OLl%2BFHf%2FIo2DgXWtHcuYDZeXEJUhv488jaNk%2FPb8feBDhhQRYM1DPjEWETQjos5j%2BZTg658C289%2FYuY%2BSewGbux25I3eATEAOeMaQQC1b6xq2pynhJwt6aanDVzz3wOCtGW%2F41QBn0E5c2sh6QznhsG9ZStyEjL89vbEPdONZAlTjdFZCBE9ZfOdhWzQuPpP9eEXu%2Bf4a8OuPJNm9pH48dtLtbqm6GKqCTdXK7BZz0vD5dL2gqw080fyXZ4wm2fuQ%3D%3D [following]
--2026-09-06 18:51:32--  https://storage.googleapis.com/cos-osf-prod-files-de-1/4b728b4df329de1d5bb5147f98c6781b052372bbd5159a91adf87e169ea378a4?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.13.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.13.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713551&Signature=sIx2c58gRwhRs1Yxe8UTELWIv5gVLAJTBFQK9x5RJ%2B3hO380Frcwh07BuUVHRReFtfNn4twftIwkvthFPmSJ3OLl%2BFHf%2FIo2DgXWtHcuYDZeXEJUhv488jaNk%2FPb8feBDhhQRYM1DPjEWETQjos5j%2BZTg658C289%2FYuY%2BSewGbux25I3eATEAOeMaQQC1b6xq2pynhJwt6aanDVzz3wOCtGW%2F41QBn0E5c2sh6QznhsG9ZStyEjL89vbEPdONZAlTjdFZCBE9ZfOdhWzQuPpP9eEXu%2Bf4a8OuPJNm9pH48dtLtbqm6GKqCTdXK7BZz0vD5dL2gqw080fyXZ4wm2fuQ%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.20.207, 142.251.127.207, 142.251.110.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.20.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 33831008 (32M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.13.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.13M 29s
    50K .......... .......... .......... .......... ..........  0% 2.89M 20s
   100K .......... .......... .......... .......... ..........  0% 5.58M 15s
   150K .......... .......... .......... .......... ..........  0% 3.67M 13s
   200K .......... .......... .......... .......... ..........  0% 7.88M 12s
   250K .......... .......... .......... .......... ..........  0% 8.07M 10s
   300K .......... .......... .......... .......... ..........  1% 9.42M 9s
   350K .......... .......... .......... .......... ..........  1% 12.4M 8s
   400K .......... .......... .......... .......... ..........  1% 6.88M 8s
   450K .......... .......... .......... .......... ..........  1% 8.98M 8s
   500K .......... .......... .......... .......... ..........  1% 9.11M 7s
   550K .......... .......... .......... .......... ..........  1% 15.2M 7s
   600K .......... .......... .......... .......... ..........  1% 9.78M 6s
   650K .......... .......... .......... .......... ..........  2% 15.3M 6s
   700K .......... .......... .......... .......... ..........  2% 11.3M 6s
   750K .......... .......... .......... .......... ..........  2% 13.9M 6s
   800K .......... .......... .......... .......... ..........  2% 18.5M 5s
   850K .......... .......... .......... .......... ..........  2% 9.71M 5s
   900K .......... .......... .......... .......... ..........  2% 10.5M 5s
   950K .......... .......... .......... .......... ..........  3% 13.2M 5s
  1000K .......... .......... .......... .......... ..........  3% 11.9M 5s
  1050K .......... .......... .......... .......... ..........  3% 23.6M 5s
  1100K .......... .......... .......... .......... ..........  3% 9.12M 5s
  1150K .......... .......... .......... .......... ..........  3% 15.4M 5s
  1200K .......... .......... .......... .......... ..........  3% 12.9M 4s
  1250K .......... .......... .......... .......... ..........  3% 10.5M 4s
  1300K .......... .......... .......... .......... ..........  4% 16.9M 4s
  1350K .......... .......... .......... .......... ..........  4% 12.0M 4s
  1400K .......... .......... .......... .......... ..........  4% 13.2M 4s
  1450K .......... .......... .......... .......... ..........  4% 16.0M 4s
  1500K .......... .......... .......... .......... ..........  4% 12.5M 4s
  1550K .......... .......... .......... .......... ..........  4% 11.1M 4s
  1600K .......... .......... .......... .......... ..........  4% 12.4M 4s
  1650K .......... .......... .......... .......... ..........  5% 16.0M 4s
  1700K .......... .......... .......... .......... ..........  5% 11.6M 4s
  1750K .......... .......... .......... .......... ..........  5% 14.1M 4s
  1800K .......... .......... .......... .......... ..........  5% 12.6M 4s
  1850K .......... .......... .......... .......... ..........  5% 13.5M 4s
  1900K .......... .......... .......... .......... ..........  5% 13.1M 4s
  1950K .......... .......... .......... .......... ..........  6% 10.8M 4s
  2000K .......... .......... .......... .......... ..........  6% 9.88M 4s
  2050K .......... .......... .......... .......... ..........  6% 18.8M 4s
  2100K .......... .......... .......... .......... ..........  6% 16.1M 3s
  2150K .......... .......... .......... .......... ..........  6% 8.37M 3s
  2200K .......... .......... .......... .......... ..........  6% 29.0M 3s
  2250K .......... .......... .......... .......... ..........  6% 13.5M 3s
  2300K .......... .......... .......... .......... ..........  7% 9.28M 3s
  2350K .......... .......... .......... .......... ..........  7% 11.0M 3s
  2400K .......... .......... .......... .......... ..........  7% 10.9M 3s
  2450K .......... .......... .......... .......... ..........  7% 28.1M 3s
  2500K .......... .......... .......... .......... ..........  7% 12.6M 3s
  2550K .......... .......... .......... .......... ..........  7% 14.9M 3s
  2600K .......... .......... .......... .......... ..........  8% 9.47M 3s
  2650K .......... .......... .......... .......... ..........  8% 11.1M 3s
  2700K .......... .......... .......... .......... ..........  8% 19.9M 3s
  2750K .......... .......... .......... .......... ..........  8% 9.25M 3s
  2800K .......... .......... .......... .......... ..........  8% 12.4M 3s
  2850K .......... .......... .......... .......... ..........  8% 12.9M 3s
  2900K .......... .......... .......... .......... ..........  8% 17.5M 3s
  2950K .......... .......... .......... .......... ..........  9% 7.62M 3s
  3000K .......... .......... .......... .......... ..........  9% 78.4M 3s
  3050K .......... .......... .......... .......... ..........  9% 12.3M 3s
  3100K .......... .......... .......... .......... ..........  9% 9.87M 3s
  3150K .......... .......... .......... .......... ..........  9% 12.7M 3s
  3200K .......... .......... .......... .......... ..........  9% 13.4M 3s
  3250K .......... .......... .......... .......... ..........  9% 9.65M 3s
  3300K .......... .......... .......... .......... .......... 10% 34.8M 3s
  3350K .......... .......... .......... .......... .......... 10% 7.84M 3s
  3400K .......... .......... .......... .......... .......... 10% 25.8M 3s
  3450K .......... .......... .......... .......... .......... 10% 10.2M 3s
  3500K .......... .......... .......... .......... .......... 10% 10.6M 3s
  3550K .......... .......... .......... .......... .......... 10% 12.3M 3s
  3600K .......... .......... .......... .......... .......... 11% 10.7M 3s
  3650K .......... .......... .......... .......... .......... 11% 13.6M 3s
  3700K .......... .......... .......... .......... .......... 11% 28.6M 3s
  3750K .......... .......... .......... .......... .......... 11% 9.35M 3s
  3800K .......... .......... .......... .......... .......... 11% 10.5M 3s
  3850K .......... .......... .......... .......... .......... 11% 31.9M 3s
  3900K .......... .......... .......... .......... .......... 11% 11.6M 3s
  3950K .......... .......... .......... .......... .......... 12% 9.58M 3s
  4000K .......... .......... .......... .......... .......... 12% 19.6M 3s
  4050K .......... .......... .......... .......... .......... 12% 13.3M 3s
  4100K .......... .......... .......... .......... .......... 12% 8.17M 3s
  4150K .......... .......... .......... .......... .......... 12% 29.0M 3s
  4200K .......... .......... .......... .......... .......... 12% 7.76M 3s
  4250K .......... .......... .......... .......... .......... 13% 29.9M 3s
  4300K .......... .......... .......... .......... .......... 13% 10.6M 3s
  4350K .......... .......... .......... .......... .......... 13% 12.3M 3s
  4400K .......... .......... .......... .......... .......... 13% 14.6M 3s
  4450K .......... .......... .......... .......... .......... 13% 9.90M 3s
  4500K .......... .......... .......... .......... .......... 13% 13.9M 3s
  4550K .......... .......... .......... .......... .......... 13% 10.1M 3s
  4600K .......... .......... .......... .......... .......... 14% 24.2M 3s
  4650K .......... .......... .......... .......... .......... 14% 18.2M 3s
  4700K .......... .......... .......... .......... .......... 14% 11.0M 3s
  4750K .......... .......... .......... .......... .......... 14% 12.5M 3s
  4800K .......... .......... .......... .......... .......... 14% 11.7M 3s
  4850K .......... .......... .......... .......... .......... 14% 21.6M 3s
  4900K .......... .......... .......... .......... .......... 14% 10.6M 3s
  4950K .......... .......... .......... .......... .......... 15% 9.99M 3s
  5000K .......... .......... .......... .......... .......... 15% 17.2M 3s
  5050K .......... .......... .......... .......... .......... 15% 11.7M 3s
  5100K .......... .......... .......... .......... .......... 15% 13.5M 3s
  5150K .......... .......... .......... .......... .......... 15% 10.9M 3s
  5200K .......... .......... .......... .......... .......... 15% 19.6M 3s
  5250K .......... .......... .......... .......... .......... 16% 10.6M 3s
  5300K .......... .......... .......... .......... .......... 16% 11.3M 3s
  5350K .......... .......... .......... .......... .......... 16% 11.1M 3s
  5400K .......... .......... .......... .......... .......... 16% 15.9M 3s
  5450K .......... .......... .......... .......... .......... 16% 14.7M 3s
  5500K .......... .......... .......... .......... .......... 16% 13.4M 2s
  5550K .......... .......... .......... .......... .......... 16% 13.5M 2s
  5600K .......... .......... .......... .......... .......... 17% 11.7M 2s
  5650K .......... .......... .......... .......... .......... 17% 14.4M 2s
  5700K .......... .......... .......... .......... .......... 17% 8.52M 2s
  5750K .......... .......... .......... .......... .......... 17% 37.2M 2s
  5800K .......... .......... .......... .......... .......... 17% 8.01M 2s
  5850K .......... .......... .......... .......... .......... 17% 37.1M 2s
  5900K .......... .......... .......... .......... .......... 18% 8.70M 2s
  5950K .......... .......... .......... .......... .......... 18% 18.4M 2s
  6000K .......... .......... .......... .......... .......... 18% 10.2M 2s
  6050K .......... .......... .......... .......... .......... 18% 12.7M 2s
  6100K .......... .......... .......... .......... .......... 18% 13.7M 2s
  6150K .......... .......... .......... .......... .......... 18% 8.64M 2s
  6200K .......... .......... .......... .......... .......... 18% 36.3M 2s
  6250K .......... .......... .......... .......... .......... 19% 9.96M 2s
  6300K .......... .......... .......... .......... .......... 19% 16.0M 2s
  6350K .......... .......... .......... .......... .......... 19% 10.3M 2s
  6400K .......... .......... .......... .......... .......... 19% 11.3M 2s
  6450K .......... .......... .......... .......... .......... 19% 18.1M 2s
  6500K .......... .......... .......... .......... .......... 19% 14.9M 2s
  6550K .......... .......... .......... .......... .......... 19% 12.0M 2s
  6600K .......... .......... .......... .......... .......... 20% 11.6M 2s
  6650K .......... .......... .......... .......... .......... 20% 15.3M 2s
  6700K .......... .......... .......... .......... .......... 20% 15.3M 2s
  6750K .......... .......... .......... .......... .......... 20% 8.81M 2s
  6800K .......... .......... .......... .......... .......... 20% 14.8M 2s
  6850K .......... .......... .......... .......... .......... 20% 10.5M 2s
  6900K .......... .......... .......... .......... .......... 21% 17.2M 2s
  6950K .......... .......... .......... .......... .......... 21% 17.4M 2s
  7000K .......... .......... .......... .......... .......... 21% 11.1M 2s
  7050K .......... .......... .......... .......... .......... 21% 12.8M 2s
  7100K .......... .......... .......... .......... .......... 21% 12.4M 2s
  7150K .......... .......... .......... .......... .......... 21% 10.8M 2s
  7200K .......... .......... .......... .......... .......... 21% 9.98M 2s
  7250K .......... .......... .......... .......... .......... 22% 26.3M 2s
  7300K .......... .......... .......... .......... .......... 22% 9.36M 2s
  7350K .......... .......... .......... .......... .......... 22% 23.1M 2s
  7400K .......... .......... .......... .......... .......... 22% 6.64M 2s
  7450K .......... .......... .......... .......... .......... 22%  384M 2s
  7500K .......... .......... .......... .......... .......... 22% 11.6M 2s
  7550K .......... .......... .......... .......... .......... 23% 10.6M 2s
  7600K .......... .......... .......... .......... .......... 23% 10.1M 2s
  7650K .......... .......... .......... .......... .......... 23% 13.2M 2s
  7700K .......... .......... .......... .......... .......... 23% 22.1M 2s
  7750K .......... .......... .......... .......... .......... 23% 11.9M 2s
  7800K .......... .......... .......... .......... .......... 23% 8.01M 2s
  7850K .......... .......... .......... .......... .......... 23% 20.2M 2s
  7900K .......... .......... .......... .......... .......... 24% 12.3M 2s
  7950K .......... .......... .......... .......... .......... 24% 15.5M 2s
  8000K .......... .......... .......... .......... .......... 24% 12.4M 2s
  8050K .......... .......... .......... .......... .......... 24% 11.9M 2s
  8100K .......... .......... .......... .......... .......... 24% 12.9M 2s
  8150K .......... .......... .......... .......... .......... 24% 17.7M 2s
  8200K .......... .......... .......... .......... .......... 24% 10.2M 2s
  8250K .......... .......... .......... .......... .......... 25% 12.9M 2s
  8300K .......... .......... .......... .......... .......... 25% 15.4M 2s
  8350K .......... .......... .......... .......... .......... 25% 7.72M 2s
  8400K .......... .......... .......... .......... .......... 25% 17.8M 2s
  8450K .......... .......... .......... .......... .......... 25% 12.3M 2s
  8500K .......... .......... .......... .......... .......... 25% 9.92M 2s
  8550K .......... .......... .......... .......... .......... 26% 22.1M 2s
  8600K .......... .......... .......... .......... .......... 26% 22.6M 2s
  8650K .......... .......... .......... .......... .......... 26% 8.63M 2s
  8700K .......... .......... .......... .......... .......... 26% 21.9M 2s
  8750K .......... .......... .......... .......... .......... 26% 7.45M 2s
  8800K .......... .......... .......... .......... .......... 26% 15.7M 2s
  8850K .......... .......... .......... .......... .......... 26% 20.8M 2s
  8900K .......... .......... .......... .......... .......... 27% 11.3M 2s
  8950K .......... .......... .......... .......... .......... 27% 12.7M 2s
  9000K .......... .......... .......... .......... .......... 27% 8.32M 2s
  9050K .......... .......... .......... .......... .......... 27% 29.0M 2s
  9100K .......... .......... .......... .......... .......... 27% 9.30M 2s
  9150K .......... .......... .......... .......... .......... 27% 10.5M 2s
  9200K .......... .......... .......... .......... .......... 27% 28.0M 2s
  9250K .......... .......... .......... .......... .......... 28% 9.43M 2s
  9300K .......... .......... .......... .......... .......... 28% 22.6M 2s
  9350K .......... .......... .......... .......... .......... 28% 11.1M 2s
  9400K .......... .......... .......... .......... .......... 28% 10.1M 2s
  9450K .......... .......... .......... .......... .......... 28% 13.2M 2s
  9500K .......... .......... .......... .......... .......... 28% 30.2M 2s
  9550K .......... .......... .......... .......... .......... 29% 8.98M 2s
  9600K .......... .......... .......... .......... .......... 29% 9.56M 2s
  9650K .......... .......... .......... .......... .......... 29% 22.4M 2s
  9700K .......... .......... .......... .......... .......... 29% 12.1M 2s
  9750K .......... .......... .......... .......... .......... 29% 13.7M 2s
  9800K .......... .......... .......... .......... .......... 29% 9.21M 2s
  9850K .......... .......... .......... .......... .......... 29% 14.5M 2s
  9900K .......... .......... .......... .......... .......... 30% 16.1M 2s
  9950K .......... .......... .......... .......... .......... 30% 11.5M 2s
 10000K .......... .......... .......... .......... .......... 30% 12.6M 2s
 10050K .......... .......... .......... .......... .......... 30% 12.3M 2s
 10100K .......... .......... .......... .......... .......... 30% 12.4M 2s
 10150K .......... .......... .......... .......... .......... 30% 23.3M 2s
 10200K .......... .......... .......... .......... .......... 31% 9.27M 2s
 10250K .......... .......... .......... .......... .......... 31% 10.1M 2s
 10300K .......... .......... .......... .......... .......... 31% 40.3M 2s
 10350K .......... .......... .......... .......... .......... 31% 8.29M 2s
 10400K .......... .......... .......... .......... .......... 31% 14.4M 2s
 10450K .......... .......... .......... .......... .......... 31% 13.7M 2s
 10500K .......... .......... .......... .......... .......... 31% 10.8M 2s
 10550K .......... .......... .......... .......... .......... 32% 11.8M 2s
 10600K .......... .......... .......... .......... .......... 32% 21.1M 2s
 10650K .......... .......... .......... .......... .......... 32% 14.8M 2s
 10700K .......... .......... .......... .......... .......... 32% 8.65M 2s
 10750K .......... .......... .......... .......... .......... 32% 12.5M 2s
 10800K .......... .......... .......... .......... .......... 32% 9.51M 2s
 10850K .......... .......... .......... .......... .......... 32%  121M 2s
 10900K .......... .......... .......... .......... .......... 33% 8.67M 2s
 10950K .......... .......... .......... .......... .......... 33% 19.8M 2s
 11000K .......... .......... .......... .......... .......... 33% 13.9M 2s
 11050K .......... .......... .......... .......... .......... 33% 11.6M 2s
 11100K .......... .......... .......... .......... .......... 33% 13.1M 2s
 11150K .......... .......... .......... .......... .......... 33% 8.85M 2s
 11200K .......... .......... .......... .......... .......... 34% 16.1M 2s
 11250K .......... .......... .......... .......... .......... 34% 16.8M 2s
 11300K .......... .......... .......... .......... .......... 34% 10.7M 2s
 11350K .......... .......... .......... .......... .......... 34% 19.3M 2s
 11400K .......... .......... .......... .......... .......... 34% 9.52M 2s
 11450K .......... .......... .......... .......... .......... 34% 12.7M 2s
 11500K .......... .......... .......... .......... .......... 34% 9.95M 2s
 11550K .......... .......... .......... .......... .......... 35% 12.3M 2s

Downloading atb.assembly.r0.2.batch.14.tar.xz from https://osf.io/download/6671438c77ff4c5f1ee046d7/

--2026-09-06 18:51:34--  https://osf.io/download/6671438c77ff4c5f1ee046d7/
Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671438c77ff4c5f1ee046d7 [following]
--2026-09-06 18:51:35--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671438c77ff4c5f1ee046d7
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/de157638381418a6ee9e6ed1f7fc84a1070de4633db8bc56825299a580550ebb?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.14.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.14.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713556&Signature=k5%2Bw0ihkKr7tzIJLe5X1xKm7b%2Fe%2FFESKrWmLY5p9qJ%2B%2BwGYI2woC2f%2FreCxcW%2FhgXwWBYN0xzRMW%2FLD7vbiwXt85%2F5zqLws0WbbRnSRAe94dapeU1oHTm9X2fv4nOYvGGtn214m3nxUzMtdrZnhpWy6H%2B4DoWvK%2Bx2F4zBSHZukVeT%2FAtW3O1SzvWsfttYxWFgVHKzdH2Js96QqXDuKR%2FRkd0AbSz3PdlN62S76qU2klKvXG3tJNQOiIuS4VI0%2BTjKQ1tRmmrN7s9cHnbjib%2FLz3UGO6yw8%2FxihWGIXyUsGbr6EhcFGL%2F5J7d4q6%2BNnrNNayM%2FMuSAAPX%2BkyuYtFRg%3D%3D [following]
--2026-09-06 18:51:36--  https://storage.googleapis.com/cos-osf-prod-files-de-1/de157638381418a6ee9e6ed1f7fc84a1070de4633db8bc56825299a580550ebb?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.14.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.14.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713556&Signature=k5%2Bw0ihkKr7tzIJLe5X1xKm7b%2Fe%2FFESKrWmLY5p9qJ%2B%2BwGYI2woC2f%2FreCxcW%2FhgXwWBYN0xzRMW%2FLD7vbiwXt85%2F5zqLws0WbbRnSRAe94dapeU1oHTm9X2fv4nOYvGGtn214m3nxUzMtdrZnhpWy6H%2B4DoWvK%2Bx2F4zBSHZukVeT%2FAtW3O1SzvWsfttYxWFgVHKzdH2Js96QqXDuKR%2FRkd0AbSz3PdlN62S76qU2klKvXG3tJNQOiIuS4VI0%2BTjKQ1tRmmrN7s9cHnbjib%2FLz3UGO6yw8%2FxihWGIXyUsGbr6EhcFGL%2F5J7d4q6%2BNnrNNayM%2FMuSAAPX%2BkyuYtFRg%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.127.207, 142.251.110.207, 142.250.154.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.127.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27016920 (26M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.14.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.41M 18s
    50K .......... .......... .......... .......... ..........  0% 2.46M 14s
   100K .......... .......... .......... .......... ..........  0% 4.30M 12s
   150K .......... .......... .......... .......... ..........  0% 5.42M 10s
   200K .......... .......... .......... .......... ..........  0% 5.58M 9s
   250K .......... .......... .......... .......... ..........  1% 13.7M 8s
   300K .......... .......... .......... .......... ..........  1% 5.56M 7s
   350K .......... .......... .......... .......... ..........  1% 12.3M 6s
   400K .......... .......... .......... .......... ..........  1% 11.3M 6s
   450K .......... .......... .......... .......... ..........  1% 9.91M 6s
   500K .......... .......... .......... .......... ..........  2% 27.6M 5s
   550K .......... .......... .......... .......... ..........  2% 9.34M 5s
   600K .......... .......... .......... .......... ..........  2% 9.89M 5s
   650K .......... .......... .......... .......... ..........  2% 16.7M 5s
   700K .......... .......... .......... .......... ..........  2% 11.8M 4s
   750K .......... .......... .......... .......... ..........  3% 15.6M 4s
   800K .......... .......... .......... .......... ..........  3% 10.7M 4s
   850K .......... .......... .......... .......... ..........  3% 21.2M 4s
   900K .......... .......... .......... .......... ..........  3% 11.4M 4s
   950K .......... .......... .......... .......... ..........  3% 13.3M 4s
  1000K .......... .......... .......... .......... ..........  3% 10.9M 4s
  1050K .......... .......... .......... .......... ..........  4% 10.9M 4s
  1100K .......... .......... .......... .......... ..........  4% 14.6M 3s
  1150K .......... .......... .......... .......... ..........  4% 15.0M 3s
  1200K .......... .......... .......... .......... ..........  4% 10.5M 3s
  1250K .......... .......... .......... .......... ..........  4% 14.1M 3s
  1300K .......... .......... .......... .......... ..........  5% 10.5M 3s
  1350K .......... .......... .......... .......... ..........  5% 29.3M 3s
  1400K .......... .......... .......... .......... ..........  5% 9.63M 3s
  1450K .......... .......... .......... .......... ..........  5% 19.0M 3s
  1500K .......... .......... .......... .......... ..........  5% 9.22M 3s
  1550K .......... .......... .......... .......... ..........  6% 15.8M 3s
  1600K .......... .......... .......... .......... ..........  6% 11.0M 3s
  1650K .......... .......... .......... .......... ..........  6% 10.6M 3s
  1700K .......... .......... .......... .......... ..........  6% 15.0M 3s
  1750K .......... .......... .......... .......... ..........  6% 11.2M 3s
  1800K .......... .......... .......... .......... ..........  7% 29.3M 3s
  1850K .......... .......... .......... .......... ..........  7% 12.2M 3s
  1900K .......... .......... .......... .......... ..........  7% 10.3M 3s
  1950K .......... .......... .......... .......... ..........  7% 10.3M 3s
  2000K .......... .......... .......... .......... ..........  7% 21.8M 3s
  2050K .......... .......... .......... .......... ..........  7% 11.0M 3s
  2100K .......... .......... .......... .......... ..........  8% 12.8M 3s
  2150K .......... .......... .......... .......... ..........  8% 12.1M 3s
  2200K .......... .......... .......... .......... ..........  8% 20.3M 3s
  2250K .......... .......... .......... .......... ..........  8% 12.0M 3s
  2300K .......... .......... .......... .......... ..........  8% 14.1M 3s
  2350K .......... .......... .......... .......... ..........  9% 13.6M 3s
  2400K .......... .......... .......... .......... ..........  9% 10.8M 3s
  2450K .......... .......... .......... .......... ..........  9% 11.1M 2s
  2500K .......... .......... .......... .......... ..........  9% 15.1M 2s
  2550K .......... .......... .......... .......... ..........  9% 14.3M 2s
  2600K .......... .......... .......... .......... .......... 10% 15.3M 2s
  2650K .......... .......... .......... .......... .......... 10% 10.5M 2s
  2700K .......... .......... .......... .......... .......... 10% 13.5M 2s
  2750K .......... .......... .......... .......... .......... 10% 11.5M 2s
  2800K .......... .......... .......... .......... .......... 10% 11.1M 2s
  2850K .......... .......... .......... .......... .......... 10% 8.22M 2s
  2900K .......... .......... .......... .......... .......... 11% 13.0M 2s
  2950K .......... .......... .......... .......... .......... 11% 10.8M 2s
  3000K .......... .......... .......... .......... .......... 11% 13.5M 2s
  3050K .......... .......... .......... .......... .......... 11% 13.4M 2s
  3100K .......... .......... .......... .......... .......... 11% 21.9M 2s
  3150K .......... .......... .......... .......... .......... 12% 8.91M 2s
  3200K .......... .......... .......... .......... .......... 12% 11.8M 2s
  3250K .......... .......... .......... .......... .......... 12% 12.3M 2s
  3300K .......... .......... .......... .......... .......... 12% 23.8M 2s
  3350K .......... .......... .......... .......... .......... 12% 9.18M 2s
  3400K .......... .......... .......... .......... .......... 13% 32.6M 2s
  3450K .......... .......... .......... .......... .......... 13% 9.08M 2s
  3500K .......... .......... .......... .......... .......... 13% 12.7M 2s
  3550K .......... .......... .......... .......... .......... 13% 15.6M 2s
  3600K .......... .......... .......... .......... .......... 13% 10.1M 2s
  3650K .......... .......... .......... .......... .......... 14% 14.5M 2s
  3700K .......... .......... .......... .......... .......... 14% 18.1M 2s
  3750K .......... .......... .......... .......... .......... 14% 9.24M 2s
  3800K .......... .......... .......... .......... .......... 14% 12.3M 2s
  3850K .......... .......... .......... .......... .......... 14% 31.9M 2s
  3900K .......... .......... .......... .......... .......... 14% 13.0M 2s
  3950K .......... .......... .......... .......... .......... 15% 12.5M 2s
  4000K .......... .......... .......... .......... .......... 15% 8.07M 2s
  4050K .......... .......... .......... .......... .......... 15% 14.5M 2s
  4100K .......... .......... .......... .......... .......... 15% 13.7M 2s
  4150K .......... .......... .......... .......... .......... 15% 13.3M 2s
  4200K .......... .......... .......... .......... .......... 16% 15.0M 2s
  4250K .......... .......... .......... .......... .......... 16% 11.9M 2s
  4300K .......... .......... .......... .......... .......... 16% 13.0M 2s
  4350K .......... .......... .......... .......... .......... 16% 17.9M 2s
  4400K .......... .......... .......... .......... .......... 16% 8.34M 2s
  4450K .......... .......... .......... .......... .......... 17% 13.4M 2s
  4500K .......... .......... .......... .......... .......... 17% 13.3M 2s
  4550K .......... .......... .......... .......... .......... 17% 16.8M 2s
  4600K .......... .......... .......... .......... .......... 17% 13.8M 2s
  4650K .......... .......... .......... .......... .......... 17% 13.4M 2s
  4700K .......... .......... .......... .......... .......... 18% 10.7M 2s
  4750K .......... .......... .......... .......... .......... 18% 16.3M 2s
  4800K .......... .......... .......... .......... .......... 18% 12.7M 2s
  4850K .......... .......... .......... .......... .......... 18% 10.7M 2s
  4900K .......... .......... .......... .......... .......... 18% 16.8M 2s
  4950K .......... .......... .......... .......... .......... 18% 9.31M 2s
  5000K .......... .......... .......... .......... .......... 19% 20.0M 2s
  5050K .......... .......... .......... .......... .......... 19% 11.4M 2s
  5100K .......... .......... .......... .......... .......... 19% 10.8M 2s
  5150K .......... .......... .......... .......... .......... 19% 13.7M 2s
  5200K .......... .......... .......... .......... .......... 19% 9.01M 2s
  5250K .......... .......... .......... .......... .......... 20% 28.0M 2s
  5300K .......... .......... .......... .......... .......... 20% 10.9M 2s
  5350K .......... .......... .......... .......... .......... 20% 11.9M 2s
  5400K .......... .......... .......... .......... .......... 20% 13.4M 2s
  5450K .......... .......... .......... .......... .......... 20% 14.5M 2s
  5500K .......... .......... .......... .......... .......... 21% 16.1M 2s
  5550K .......... .......... .......... .......... .......... 21% 14.7M 2s
  5600K .......... .......... .......... .......... .......... 21% 10.6M 2s
  5650K .......... .......... .......... .......... .......... 21% 8.46M 2s
  5700K .......... .......... .......... .......... .......... 21% 15.1M 2s
  5750K .......... .......... .......... .......... .......... 21% 19.6M 2s
  5800K .......... .......... .......... .......... .......... 22% 12.0M 2s
  5850K .......... .......... .......... .......... .......... 22% 10.5M 2s
  5900K .......... .......... .......... .......... .......... 22% 14.6M 2s
  5950K .......... .......... .......... .......... .......... 22% 16.1M 2s
  6000K .......... .......... .......... .......... .......... 22% 12.8M 2s
  6050K .......... .......... .......... .......... .......... 23% 13.4M 2s
  6100K .......... .......... .......... .......... .......... 23% 9.88M 2s
  6150K .......... .......... .......... .......... .......... 23% 13.3M 2s
  6200K .......... .......... .......... .......... .......... 23% 14.7M 2s
  6250K .......... .......... .......... .......... .......... 23% 12.4M 2s
  6300K .......... .......... .......... .......... .......... 24% 12.0M 2s
  6350K .......... .......... .......... .......... .......... 24% 14.3M 2s
  6400K .......... .......... .......... .......... .......... 24% 12.8M 2s
  6450K .......... .......... .......... .......... .......... 24% 13.1M 2s
  6500K .......... .......... .......... .......... .......... 24% 11.9M 2s
  6550K .......... .......... .......... .......... .......... 25% 11.1M 2s
  6600K .......... .......... .......... .......... .......... 25% 8.92M 2s
  6650K .......... .......... .......... .......... .......... 25% 31.1M 2s
  6700K .......... .......... .......... .......... .......... 25% 16.6M 2s
  6750K .......... .......... .......... .......... .......... 25% 10.2M 2s
  6800K .......... .......... .......... .......... .......... 25% 11.5M 2s
  6850K .......... .......... .......... .......... .......... 26% 12.5M 2s
  6900K .......... .......... .......... .......... .......... 26% 13.0M 2s
  6950K .......... .......... .......... .......... .......... 26% 11.1M 2s
  7000K .......... .......... .......... .......... .......... 26% 15.0M 2s
  7050K .......... .......... .......... .......... .......... 26% 11.3M 2s
  7100K .......... .......... .......... .......... .......... 27% 13.1M 2s
  7150K .......... .......... .......... .......... .......... 27% 19.7M 2s
  7200K .......... .......... .......... .......... .......... 27% 8.92M 2s
  7250K .......... .......... .......... .......... .......... 27% 13.8M 2s
  7300K .......... .......... .......... .......... .......... 27% 15.8M 2s
  7350K .......... .......... .......... .......... .......... 28% 11.3M 2s
  7400K .......... .......... .......... .......... .......... 28% 12.9M 2s
  7450K .......... .......... .......... .......... .......... 28% 12.3M 2s
  7500K .......... .......... .......... .......... .......... 28% 7.41M 2s
  7550K .......... .......... .......... .......... .......... 28% 14.7M 2s
  7600K .......... .......... .......... .......... .......... 28% 63.4M 2s
  7650K .......... .......... .......... .......... .......... 29% 11.2M 2s
  7700K .......... .......... .......... .......... .......... 29% 13.5M 2s
  7750K .......... .......... .......... .......... .......... 29% 9.42M 2s
  7800K .......... .......... .......... .......... .......... 29% 14.9M 2s
  7850K .......... .......... .......... .......... .......... 29% 13.7M 2s
  7900K .......... .......... .......... .......... .......... 30% 13.1M 2s
  7950K .......... .......... .......... .......... .......... 30% 13.6M 2s
  8000K .......... .......... .......... .......... .......... 30% 13.8M 2s
  8050K .......... .......... .......... .......... .......... 30% 17.7M 2s
  8100K .......... .......... .......... .......... .......... 30% 9.59M 2s
  8150K .......... .......... .......... .......... .......... 31% 11.0M 2s
  8200K .......... .......... .......... .......... .......... 31% 15.7M 2s
  8250K .......... .......... .......... .......... .......... 31% 9.76M 2s
  8300K .......... .......... .......... .......... .......... 31% 21.6M 2s
  8350K .......... .......... .......... .......... .......... 31% 9.94M 2s
  8400K .......... .......... .......... .......... .......... 32% 11.8M 2s
  8450K .......... .......... .......... .......... .......... 32% 28.8M 2s
  8500K .......... .......... .......... .......... .......... 32% 11.2M 2s
  8550K .......... .......... .......... .......... .......... 32% 8.39M 2s
  8600K .......... .......... .......... .......... .......... 32% 20.3M 2s
  8650K .......... .......... .......... .......... .......... 32% 11.5M 1s
  8700K .......... .......... .......... .......... .......... 33% 10.9M 1s
  8750K .......... .......... .......... .......... .......... 33% 16.4M 1s
  8800K .......... .......... .......... .......... .......... 33% 12.2M 1s
  8850K .......... .......... .......... .......... .......... 33% 13.2M 1s
  8900K .......... .......... .......... .......... .......... 33% 14.2M 1s
  8950K .......... .......... .......... .......... .......... 34% 9.09M 1s
  9000K .......... .......... .......... .......... .......... 34% 19.8M 1s
  9050K .......... .......... .......... .......... .......... 34% 12.3M 1s
  9100K .......... .......... .......... .......... .......... 34% 14.0M 1s
  9150K .......... .......... .......... .......... .......... 34% 14.6M 1s
  9200K .......... .......... .......... .......... .......... 35% 8.86M 1s
  9250K .......... .......... .......... .......... .......... 35% 15.7M 1s
  9300K .......... .......... .......... .......... .......... 35% 21.8M 1s
  9350K .......... .......... .......... .......... .......... 35% 8.59M 1s
  9400K .......... .......... .......... .......... .......... 35% 14.6M 1s
  9450K .......... .......... .......... .......... .......... 36% 11.2M 1s
  9500K .......... .......... .......... .......... .......... 36% 23.4M 1s
  9550K .......... .......... .......... .......... .......... 36% 9.11M 1s
  9600K .......... .......... .......... .......... .......... 36% 14.5M 1s
  9650K .......... .......... .......... .......... .......... 36% 14.5M 1s
  9700K .......... .......... .......... .......... .......... 36% 11.1M 1s
  9750K .......... .......... .......... .......... .......... 37% 8.73M 1s
  9800K .......... .......... .......... .......... .......... 37% 24.4M 1s
  9850K .......... .......... .......... .......... .......... 37% 10.9M 1s
  9900K .......... .......... .......... .......... .......... 37% 11.2M 1s
  9950K .......... .......... .......... .......... .......... 37% 25.2M 1s
 10000K .......... .......... .......... .......... .......... 38% 14.3M 1s
 10050K .......... .......... .......... .......... .......... 38% 12.3M 1s
 10100K .......... .......... .......... .......... .......... 38% 11.8M 1s
 10150K .......... .......... .......... .......... .......... 38% 10.3M 1s
 10200K .......... .......... .......... .......... .......... 38% 18.1M 1s
 10250K .......... .......... .......... .......... .......... 39% 9.85M 1s
 10300K .......... .......... .......... .......... .......... 39% 12.6M 1s
 10350K .......... .......... .......... .......... .......... 39% 15.0M 1s
 10400K .......... .......... .......... .......... .......... 39% 12.7M 1s
 10450K .......... .......... .......... .......... .......... 39% 11.7M 1s
 10500K .......... .......... .......... .......... .......... 39% 13.9M 1s
 10550K .......... .......... .......... .......... .......... 40% 13.4M 1s
 10600K .......... .......... .......... .......... .......... 40% 10.3M 1s
 10650K .......... .......... .......... .......... .......... 40% 21.3M 1s
 10700K .......... .......... .......... .......... .......... 40% 15.8M 1s
 10750K .......... .......... .......... .......... .......... 40% 11.3M 1s
 10800K .......... .......... .......... .......... .......... 41% 7.71M 1s
 10850K .......... .......... .......... .......... .......... 41% 19.2M 1s
 10900K .......... .......... .......... .......... .......... 41% 10.0M 1s
 10950K .......... .......... .......... .......... .......... 41% 22.1M 1s
 11000K .......... .......... .......... .......... .......... 41% 10.9M 1s
 11050K .......... .......... .......... .......... .......... 42% 17.7M 1s
 11100K .......... .......... .......... .......... .......... 42% 14.9M 1s
 11150K .......... .......... .......... .......... .......... 42% 9.97M 1s
 11200K .......... .......... .......... .......... .......... 42% 10.9M 1s
 11250K .......... .......... .......... .......... .......... 42% 14.9M 1s
 11300K .......... .......... .......... .......... .......... 43% 11.6M 1s
 11350K .......... .......... .......... .......... .......... 43% 13.3M 1s

Downloading atb.assembly.r0.2.batch.15.tar.xz from https://osf.io/download/6671439065e1de5e73893cee/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671439065e1de5e73893cee [following]
--2026-09-06 18:51:38--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671439065e1de5e73893cee
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/fae4fab9fd712e200bae594f220ef3b2130e94db8e4dcef3b8d7377c07810871?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.15.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.15.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713559&Signature=eXEaeD7GcGnBswwa9c%2FqF8nQ32AeOIcSV4RUyPc42GpHliTQDSz2VZ2jqvvD7KqGrOHTYeIc3agPoJnVlhJLvNtdJC3HoOW1UHkmuF0%2BM%2F6YXH9Su8Iz%2BVm%2BNHi0nZWCTar1Uj%2FJnqJ7elbixNuhl8QmxJc49Ph5GigWiSEitVSnk5%2BAPZaoZcWmQd8ExSxwSg71ZaVcE64b3PChtNREchJIvl3ka%2BmcGnOdibv2vhnpqDXYFg6l%2BnaXWzy7safbn%2B3fbYQ1SevDkM0cYBBuTFTpMjtcDUDP0F3894DRyMcxPSfZNJin4fbbQ%2BMadofOwExKhOyTpfM9IPjCXxTNmA%3D%3D [following]
--2026-09-06 18:51:39--  https://storage.googleapis.com/cos-osf-prod-files-de-1/fae4fab9fd712e200bae594f220ef3b2130e94db8e4dcef3b8d7377c07810871?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.15.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.15.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713559&Signature=eXEaeD7GcGnBswwa9c%2FqF8nQ32AeOIcSV4RUyPc42GpHliTQDSz2VZ2jqvvD7KqGrOHTYeIc3agPoJnVlhJLvNtdJC3HoOW1UHkmuF0%2BM%2F6YXH9Su8Iz%2BVm%2BNHi0nZWCTar1Uj%2FJnqJ7elbixNuhl8QmxJc49Ph5GigWiSEitVSnk5%2BAPZaoZcWmQd8ExSxwSg71ZaVcE64b3PChtNREchJIvl3ka%2BmcGnOdibv2vhnpqDXYFg6l%2BnaXWzy7safbn%2B3fbYQ1SevDkM0cYBBuTFTpMjtcDUDP0F3894DRyMcxPSfZNJin4fbbQ%2BMadofOwExKhOyTpfM9IPjCXxTNmA%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.110.207, 142.250.154.207, 192.178.183.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.110.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 32391512 (31M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.15.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.37M 23s
    50K .......... .......... .......... .......... ..........  0% 2.63M 17s
   100K .......... .......... .......... .......... ..........  0% 5.01M 13s
   150K .......... .......... .......... .......... ..........  0% 4.99M 12s
   200K .......... .......... .......... .......... ..........  0% 8.05M 10s
   250K .......... .......... .......... .......... ..........  0% 9.98M 9s
   300K .......... .......... .......... .......... ..........  1% 12.4M 8s
   350K .......... .......... .......... .......... ..........  1% 8.15M 7s
   400K .......... .......... .......... .......... ..........  1% 11.7M 7s
   450K .......... .......... .......... .......... ..........  1% 15.7M 6s
   500K .......... .......... .......... .......... ..........  1% 8.30M 6s
   550K .......... .......... .......... .......... ..........  1% 18.7M 6s
   600K .......... .......... .......... .......... ..........  2% 12.6M 5s
   650K .......... .......... .......... .......... ..........  2% 13.1M 5s
   700K .......... .......... .......... .......... ..........  2% 13.0M 5s
   750K .......... .......... .......... .......... ..........  2% 15.4M 5s
   800K .......... .......... .......... .......... ..........  2% 10.1M 5s
   850K .......... .......... .......... .......... ..........  2% 16.0M 5s
   900K .......... .......... .......... .......... ..........  3% 12.9M 4s
   950K .......... .......... .......... .......... ..........  3% 9.75M 4s
  1000K .......... .......... .......... .......... ..........  3% 32.2M 4s
  1050K .......... .......... .......... .......... ..........  3% 12.7M 4s
  1100K .......... .......... .......... .......... ..........  3% 9.10M 4s
  1150K .......... .......... .......... .......... ..........  3% 12.7M 4s
  1200K .......... .......... .......... .......... ..........  3% 10.3M 4s
  1250K .......... .......... .......... .......... ..........  4% 19.7M 4s
  1300K .......... .......... .......... .......... ..........  4% 11.5M 4s
  1350K .......... .......... .......... .......... ..........  4% 13.5M 4s
  1400K .......... .......... .......... .......... ..........  4% 23.1M 4s
  1450K .......... .......... .......... .......... ..........  4% 9.08M 4s
  1500K .......... .......... .......... .......... ..........  4% 13.0M 4s
  1550K .......... .......... .......... .......... ..........  5% 15.8M 3s
  1600K .......... .......... .......... .......... ..........  5% 13.1M 3s
  1650K .......... .......... .......... .......... ..........  5% 9.33M 3s
  1700K .......... .......... .......... .......... ..........  5% 13.3M 3s
  1750K .......... .......... .......... .......... ..........  5% 10.7M 3s
  1800K .......... .......... .......... .......... ..........  5% 36.0M 3s
  1850K .......... .......... .......... .......... ..........  6% 8.35M 3s
  1900K .......... .......... .......... .......... ..........  6% 15.0M 3s
  1950K .......... .......... .......... .......... ..........  6% 15.5M 3s
  2000K .......... .......... .......... .......... ..........  6% 13.0M 3s
  2050K .......... .......... .......... .......... ..........  6% 14.3M 3s
  2100K .......... .......... .......... .......... ..........  6% 8.75M 3s
  2150K .......... .......... .......... .......... ..........  6% 27.1M 3s
  2200K .......... .......... .......... .......... ..........  7% 9.78M 3s
  2250K .......... .......... .......... .......... ..........  7% 15.8M 3s
  2300K .......... .......... .......... .......... ..........  7% 11.0M 3s
  2350K .......... .......... .......... .......... ..........  7% 22.5M 3s
  2400K .......... .......... .......... .......... ..........  7% 9.32M 3s
  2450K .......... .......... .......... .......... ..........  7% 12.3M 3s
  2500K .......... .......... .......... .......... ..........  8% 12.4M 3s
  2550K .......... .......... .......... .......... ..........  8% 9.95M 3s
  2600K .......... .......... .......... .......... ..........  8% 16.2M 3s
  2650K .......... .......... .......... .......... ..........  8% 13.6M 3s
  2700K .......... .......... .......... .......... ..........  8% 11.3M 3s
  2750K .......... .......... .......... .......... ..........  8% 15.6M 3s
  2800K .......... .......... .......... .......... ..........  9% 10.1M 3s
  2850K .......... .......... .......... .......... ..........  9% 14.0M 3s
  2900K .......... .......... .......... .......... ..........  9% 11.2M 3s
  2950K .......... .......... .......... .......... ..........  9% 29.1M 3s
  3000K .......... .......... .......... .......... ..........  9% 9.73M 3s
  3050K .......... .......... .......... .......... ..........  9% 19.2M 3s
  3100K .......... .......... .......... .......... ..........  9% 14.0M 3s
  3150K .......... .......... .......... .......... .......... 10% 11.1M 3s
  3200K .......... .......... .......... .......... .......... 10% 7.03M 3s
  3250K .......... .......... .......... .......... .......... 10% 22.9M 3s
  3300K .......... .......... .......... .......... .......... 10% 22.1M 3s
  3350K .......... .......... .......... .......... .......... 10% 8.34M 3s
  3400K .......... .......... .......... .......... .......... 10% 25.7M 3s
  3450K .......... .......... .......... .......... .......... 11% 10.5M 3s
  3500K .......... .......... .......... .......... .......... 11% 14.2M 3s
  3550K .......... .......... .......... .......... .......... 11% 12.4M 3s
  3600K .......... .......... .......... .......... .......... 11% 9.62M 3s
  3650K .......... .......... .......... .......... .......... 11% 16.7M 3s
  3700K .......... .......... .......... .......... .......... 11% 11.6M 3s
  3750K .......... .......... .......... .......... .......... 12% 11.3M 3s
  3800K .......... .......... .......... .......... .......... 12% 26.0M 3s
  3850K .......... .......... .......... .......... .......... 12% 9.32M 3s
  3900K .......... .......... .......... .......... .......... 12% 20.8M 3s
  3950K .......... .......... .......... .......... .......... 12% 6.81M 3s
  4000K .......... .......... .......... .......... .......... 12% 40.7M 3s
  4050K .......... .......... .......... .......... .......... 12% 12.2M 3s
  4100K .......... .......... .......... .......... .......... 13% 12.9M 3s
  4150K .......... .......... .......... .......... .......... 13% 10.5M 3s
  4200K .......... .......... .......... .......... .......... 13% 14.6M 3s
  4250K .......... .......... .......... .......... .......... 13% 12.2M 2s
  4300K .......... .......... .......... .......... .......... 13% 16.4M 2s
  4350K .......... .......... .......... .......... .......... 13% 12.9M 2s
  4400K .......... .......... .......... .......... .......... 14% 8.19M 2s
  4450K .......... .......... .......... .......... .......... 14% 27.7M 2s
  4500K .......... .......... .......... .......... .......... 14% 10.1M 2s
  4550K .......... .......... .......... .......... .......... 14% 19.0M 2s
  4600K .......... .......... .......... .......... .......... 14% 10.2M 2s
  4650K .......... .......... .......... .......... .......... 14% 26.2M 2s
  4700K .......... .......... .......... .......... .......... 15% 8.77M 2s
  4750K .......... .......... .......... .......... .......... 15% 14.7M 2s
  4800K .......... .......... .......... .......... .......... 15% 12.5M 2s
  4850K .......... .......... .......... .......... .......... 15% 12.7M 2s
  4900K .......... .......... .......... .......... .......... 15% 13.9M 2s
  4950K .......... .......... .......... .......... .......... 15% 10.8M 2s
  5000K .......... .......... .......... .......... .......... 15% 16.4M 2s
  5050K .......... .......... .......... .......... .......... 16% 9.80M 2s
  5100K .......... .......... .......... .......... .......... 16% 15.2M 2s
  5150K .......... .......... .......... .......... .......... 16% 19.6M 2s
  5200K .......... .......... .......... .......... .......... 16% 9.41M 2s
  5250K .......... .......... .......... .......... .......... 16% 9.74M 2s
  5300K .......... .......... .......... .......... .......... 16% 13.1M 2s
  5350K .......... .......... .......... .......... .......... 17% 16.8M 2s
  5400K .......... .......... .......... .......... .......... 17% 9.36M 2s
  5450K .......... .......... .......... .......... .......... 17% 25.4M 2s
  5500K .......... .......... .......... .......... .......... 17% 11.5M 2s
  5550K .......... .......... .......... .......... .......... 17% 12.8M 2s
  5600K .......... .......... .......... .......... .......... 17% 11.9M 2s
  5650K .......... .......... .......... .......... .......... 18% 16.0M 2s
  5700K .......... .......... .......... .......... .......... 18% 9.50M 2s
  5750K .......... .......... .......... .......... .......... 18% 19.9M 2s
  5800K .......... .......... .......... .......... .......... 18% 10.1M 2s
  5850K .......... .......... .......... .......... .......... 18% 12.1M 2s
  5900K .......... .......... .......... .......... .......... 18% 15.9M 2s
  5950K .......... .......... .......... .......... .......... 18% 13.0M 2s
  6000K .......... .......... .......... .......... .......... 19% 9.47M 2s
  6050K .......... .......... .......... .......... .......... 19% 20.7M 2s
  6100K .......... .......... .......... .......... .......... 19% 10.6M 2s
  6150K .......... .......... .......... .......... .......... 19% 14.4M 2s
  6200K .......... .......... .......... .......... .......... 19% 8.42M 2s
  6250K .......... .......... .......... .......... .......... 19% 33.8M 2s
  6300K .......... .......... .......... .......... .......... 20% 16.1M 2s
  6350K .......... .......... .......... .......... .......... 20% 11.3M 2s
  6400K .......... .......... .......... .......... .......... 20% 12.2M 2s
  6450K .......... .......... .......... .......... .......... 20% 9.57M 2s
  6500K .......... .......... .......... .......... .......... 20% 13.3M 2s
  6550K .......... .......... .......... .......... .......... 20% 15.2M 2s
  6600K .......... .......... .......... .......... .......... 21% 12.4M 2s
  6650K .......... .......... .......... .......... .......... 21% 12.4M 2s
  6700K .......... .......... .......... .......... .......... 21% 19.0M 2s
  6750K .......... .......... .......... .......... .......... 21% 13.4M 2s
  6800K .......... .......... .......... .......... .......... 21% 8.17M 2s
  6850K .......... .......... .......... .......... .......... 21% 15.7M 2s
  6900K .......... .......... .......... .......... .......... 21% 13.2M 2s
  6950K .......... .......... .......... .......... .......... 22% 10.8M 2s
  7000K .......... .......... .......... .......... .......... 22% 11.1M 2s
  7050K .......... .......... .......... .......... .......... 22% 39.3M 2s
  7100K .......... .......... .......... .......... .......... 22% 8.24M 2s
  7150K .......... .......... .......... .......... .......... 22% 30.2M 2s
  7200K .......... .......... .......... .......... .......... 22% 7.85M 2s
  7250K .......... .......... .......... .......... .......... 23% 12.9M 2s
  7300K .......... .......... .......... .......... .......... 23% 13.5M 2s
  7350K .......... .......... .......... .......... .......... 23% 14.0M 2s
  7400K .......... .......... .......... .......... .......... 23% 13.6M 2s
  7450K .......... .......... .......... .......... .......... 23% 16.3M 2s
  7500K .......... .......... .......... .......... .......... 23% 16.9M 2s
  7550K .......... .......... .......... .......... .......... 24% 13.4M 2s
  7600K .......... .......... .......... .......... .......... 24% 8.46M 2s
  7650K .......... .......... .......... .......... .......... 24% 13.7M 2s
  7700K .......... .......... .......... .......... .......... 24% 14.8M 2s
  7750K .......... .......... .......... .......... .......... 24% 12.5M 2s
  7800K .......... .......... .......... .......... .......... 24% 13.4M 2s
  7850K .......... .......... .......... .......... .......... 24% 14.4M 2s
  7900K .......... .......... .......... .......... .......... 25% 11.9M 2s
  7950K .......... .......... .......... .......... .......... 25% 12.8M 2s
  8000K .......... .......... .......... .......... .......... 25% 11.8M 2s
  8050K .......... .......... .......... .......... .......... 25% 9.18M 2s
  8100K .......... .......... .......... .......... .......... 25% 14.1M 2s
  8150K .......... .......... .......... .......... .......... 25% 12.7M 2s
  8200K .......... .......... .......... .......... .......... 26% 24.9M 2s
  8250K .......... .......... .......... .......... .......... 26% 9.40M 2s
  8300K .......... .......... .......... .......... .......... 26% 10.1M 2s
  8350K .......... .......... .......... .......... .......... 26% 19.3M 2s
  8400K .......... .......... .......... .......... .......... 26% 10.4M 2s
  8450K .......... .......... .......... .......... .......... 26% 12.0M 2s
  8500K .......... .......... .......... .......... .......... 27% 14.0M 2s
  8550K .......... .......... .......... .......... .......... 27% 15.2M 2s
  8600K .......... .......... .......... .......... .......... 27% 9.29M 2s
  8650K .......... .......... .......... .......... .......... 27% 21.7M 2s
  8700K .......... .......... .......... .......... .......... 27% 14.5M 2s
  8750K .......... .......... .......... .......... .......... 27% 15.0M 2s
  8800K .......... .......... .......... .......... .......... 27% 7.50M 2s
  8850K .......... .......... .......... .......... .......... 28% 14.4M 2s
  8900K .......... .......... .......... .......... .......... 28% 27.9M 2s
  8950K .......... .......... .......... .......... .......... 28% 11.0M 2s
  9000K .......... .......... .......... .......... .......... 28% 8.86M 2s
  9050K .......... .......... .......... .......... .......... 28% 31.8M 2s
  9100K .......... .......... .......... .......... .......... 28% 11.2M 2s
  9150K .......... .......... .......... .......... .......... 29% 12.3M 2s
  9200K .......... .......... .......... .......... .......... 29% 9.27M 2s
  9250K .......... .......... .......... .......... .......... 29% 21.6M 2s
  9300K .......... .......... .......... .......... .......... 29% 14.5M 2s
  9350K .......... .......... .......... .......... .......... 29% 11.0M 2s
  9400K .......... .......... .......... .......... .......... 29% 17.4M 2s
  9450K .......... .......... .......... .......... .......... 30% 8.59M 2s
  9500K .......... .......... .......... .......... .......... 30% 17.4M 2s
  9550K .......... .......... .......... .......... .......... 30% 10.8M 2s
  9600K .......... .......... .......... .......... .......... 30% 11.2M 2s
  9650K .......... .......... .......... .......... .......... 30% 15.4M 2s
  9700K .......... .......... .......... .......... .......... 30% 12.7M 2s
  9750K .......... .......... .......... .......... .......... 30% 10.3M 2s
  9800K .......... .......... .......... .......... .......... 31% 12.2M 2s
  9850K .......... .......... .......... .......... .......... 31% 21.5M 2s
  9900K .......... .......... .......... .......... .......... 31% 13.7M 2s
  9950K .......... .......... .......... .......... .......... 31% 12.0M 2s
 10000K .......... .......... .......... .......... .......... 31% 13.7M 2s
 10050K .......... .......... .......... .......... .......... 31% 9.92M 2s
 10100K .......... .......... .......... .......... .......... 32% 12.4M 2s
 10150K .......... .......... .......... .......... .......... 32% 15.3M 2s
 10200K .......... .......... .......... .......... .......... 32% 10.6M 2s
 10250K .......... .......... .......... .......... .......... 32% 18.2M 2s
 10300K .......... .......... .......... .......... .......... 32% 9.70M 2s
 10350K .......... .......... .......... .......... .......... 32% 33.4M 2s
 10400K .......... .......... .......... .......... .......... 33% 8.80M 2s
 10450K .......... .......... .......... .......... .......... 33% 16.1M 2s
 10500K .......... .......... .......... .......... .......... 33% 14.5M 2s
 10550K .......... .......... .......... .......... .......... 33% 11.9M 2s
 10600K .......... .......... .......... .......... .......... 33% 9.38M 2s
 10650K .......... .......... .......... .......... .......... 33% 16.8M 2s
 10700K .......... .......... .......... .......... .......... 33% 17.5M 2s
 10750K .......... .......... .......... .......... .......... 34% 9.99M 2s
 10800K .......... .......... .......... .......... .......... 34% 7.59M 2s
 10850K .......... .......... .......... .......... .......... 34% 29.9M 2s
 10900K .......... .......... .......... .......... .......... 34% 12.8M 2s
 10950K .......... .......... .......... .......... .......... 34% 14.1M 2s
 11000K .......... .......... .......... .......... .......... 34% 11.1M 2s
 11050K .......... .......... .......... .......... .......... 35% 23.4M 2s
 11100K .......... .......... .......... .......... .......... 35% 2.56M 2s
 11150K .......... .......... .......... .......... .......... 35%  123M 2s
 11200K .......... .......... .......... .......... .......... 35%  139M 2s
 11250K .......... .......... .......... .......... .......... 35%  270M 2s
 11300K .......... .......... .......... .......... .......... 35%  260M 2s
 11350K .......... .......... .......... .......... .......... 36% 10.4M 2s
 11400K .......... .......... .......... .......... .......... 36% 14.1M 2s
 11450K .......... .......... .......... .......... .......... 36% 20.7M 2s
 11500K .......... .......... .......... .......... .......... 36% 12.0M 2s

Downloading atb.assembly.r0.2.batch.16.tar.xz from https://osf.io/download/66714394d835c439974ce096/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714394d835c439974ce096 [following]
--2026-09-06 18:51:42--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714394d835c439974ce096
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/a8a11428500d891d52902dabdf42851cd695fbe96e16952f1da3ccc2f575cd83?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.16.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.16.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713563&Signature=GpQWLeqlsMab9%2FPgY3i9KSXwmAVLJ%2BhsHIWWByvCENvi%2FOUL%2FXo91sgyI%2FqXRr4wDi6GptdlBDFnFBEf5zzTboL211EdoPDJw9i6pgLU%2BvAr0DXnOmLua1%2BFKKwPEbaTY6m%2FYvQAQuLTli%2B2cgUWRn7ltq4aOJgT9NZVstvda5giorJRxXEedlhg7BzQ4i50iaMWvrm%2FtZc2MK0C7i%2BZaLn8dhglS4JX4Jo5WVrL%2FoWA7iUiDOuU6YZEMMDmkoY20LBgOgmProS%2Fe6creD5RXlmNzByBACQRrnMOEFvj%2FXI7hEUlE2d86OmACL2nrs8Jsbt11iJodmZ%2FqTRUP4Ajvw%3D%3D [following]
--2026-09-06 18:51:43--  https://storage.googleapis.com/cos-osf-prod-files-de-1/a8a11428500d891d52902dabdf42851cd695fbe96e16952f1da3ccc2f575cd83?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.16.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.16.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713563&Signature=GpQWLeqlsMab9%2FPgY3i9KSXwmAVLJ%2BhsHIWWByvCENvi%2FOUL%2FXo91sgyI%2FqXRr4wDi6GptdlBDFnFBEf5zzTboL211EdoPDJw9i6pgLU%2BvAr0DXnOmLua1%2BFKKwPEbaTY6m%2FYvQAQuLTli%2B2cgUWRn7ltq4aOJgT9NZVstvda5giorJRxXEedlhg7BzQ4i50iaMWvrm%2FtZc2MK0C7i%2BZaLn8dhglS4JX4Jo5WVrL%2FoWA7iUiDOuU6YZEMMDmkoY20LBgOgmProS%2Fe6creD5RXlmNzByBACQRrnMOEFvj%2FXI7hEUlE2d86OmACL2nrs8Jsbt11iJodmZ%2FqTRUP4Ajvw%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 34085680 (33M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.16.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.33M 24s
    50K .......... .......... .......... .......... ..........  0% 2.82M 18s
   100K .......... .......... .......... .......... ..........  0% 4.92M 14s
   150K .......... .......... .......... .......... ..........  0% 4.46M 12s
   200K .......... .......... .......... .......... ..........  0% 8.93M 11s
   250K .......... .......... .......... .......... ..........  0% 7.57M 10s
   300K .......... .......... .......... .......... ..........  1% 9.69M 9s
   350K .......... .......... .......... .......... ..........  1% 14.2M 8s
   400K .......... .......... .......... .......... ..........  1% 12.9M 7s
   450K .......... .......... .......... .......... ..........  1% 11.6M 7s
   500K .......... .......... .......... .......... ..........  1% 11.0M 6s
   550K .......... .......... .......... .......... ..........  1% 7.61M 6s
   600K .......... .......... .......... .......... ..........  1% 13.1M 6s
   650K .......... .......... .......... .......... ..........  2% 47.6M 6s
   700K .......... .......... .......... .......... ..........  2% 9.45M 5s
   750K .......... .......... .......... .......... ..........  2% 14.1M 5s
   800K .......... .......... .......... .......... ..........  2% 12.3M 5s
   850K .......... .......... .......... .......... ..........  2% 15.2M 5s
   900K .......... .......... .......... .......... ..........  2% 14.3M 5s
   950K .......... .......... .......... .......... ..........  3% 11.6M 5s
  1000K .......... .......... .......... .......... ..........  3% 10.3M 5s
  1050K .......... .......... .......... .......... ..........  3% 18.0M 4s
  1100K .......... .......... .......... .......... ..........  3% 12.6M 4s
  1150K .......... .......... .......... .......... ..........  3% 8.71M 4s
  1200K .......... .......... .......... .......... ..........  3% 12.1M 4s
  1250K .......... .......... .......... .......... ..........  3% 10.0M 4s
  1300K .......... .......... .......... .......... ..........  4% 26.5M 4s
  1350K .......... .......... .......... .......... ..........  4% 8.54M 4s
  1400K .......... .......... .......... .......... ..........  4% 27.5M 4s
  1450K .......... .......... .......... .......... ..........  4% 18.8M 4s
  1500K .......... .......... .......... .......... ..........  4% 9.94M 4s
  1550K .......... .......... .......... .......... ..........  4% 13.4M 4s
  1600K .......... .......... .......... .......... ..........  4% 10.8M 4s
  1650K .......... .......... .......... .......... ..........  5% 12.7M 4s
  1700K .......... .......... .......... .......... ..........  5% 13.2M 4s
  1750K .......... .......... .......... .......... ..........  5% 17.2M 4s
  1800K .......... .......... .......... .......... ..........  5% 8.31M 4s
  1850K .......... .......... .......... .......... ..........  5%  136M 3s
  1900K .......... .......... .......... .......... ..........  5% 7.56M 3s
  1950K .......... .......... .......... .......... ..........  6% 8.78M 3s
  2000K .......... .......... .......... .......... ..........  6% 59.4M 3s
  2050K .......... .......... .......... .......... ..........  6% 14.6M 3s
  2100K .......... .......... .......... .......... ..........  6% 10.2M 3s
  2150K .......... .......... .......... .......... ..........  6% 11.9M 3s
  2200K .......... .......... .......... .......... ..........  6% 16.6M 3s
  2250K .......... .......... .......... .......... ..........  6% 11.6M 3s
  2300K .......... .......... .......... .......... ..........  7% 13.0M 3s
  2350K .......... .......... .......... .......... ..........  7% 8.83M 3s
  2400K .......... .......... .......... .......... ..........  7% 34.3M 3s
  2450K .......... .......... .......... .......... ..........  7% 9.77M 3s
  2500K .......... .......... .......... .......... ..........  7% 15.8M 3s
  2550K .......... .......... .......... .......... ..........  7% 13.0M 3s
  2600K .......... .......... .......... .......... ..........  7% 13.5M 3s
  2650K .......... .......... .......... .......... ..........  8% 13.4M 3s
  2700K .......... .......... .......... .......... ..........  8% 10.0M 3s
  2750K .......... .......... .......... .......... ..........  8% 12.8M 3s
  2800K .......... .......... .......... .......... ..........  8% 10.8M 3s
  2850K .......... .......... .......... .......... ..........  8% 22.4M 3s
  2900K .......... .......... .......... .......... ..........  8% 8.73M 3s
  2950K .......... .......... .......... .......... ..........  9% 14.5M 3s
  3000K .......... .......... .......... .......... ..........  9% 18.0M 3s
  3050K .......... .......... .......... .......... ..........  9% 11.1M 3s
  3100K .......... .......... .......... .......... ..........  9% 12.2M 3s
  3150K .......... .......... .......... .......... ..........  9% 11.6M 3s
  3200K .......... .......... .......... .......... ..........  9% 13.2M 3s
  3250K .......... .......... .......... .......... ..........  9% 15.5M 3s
  3300K .......... .......... .......... .......... .......... 10% 10.1M 3s
  3350K .......... .......... .......... .......... .......... 10% 15.7M 3s
  3400K .......... .......... .......... .......... .......... 10% 16.8M 3s
  3450K .......... .......... .......... .......... .......... 10% 13.0M 3s
  3500K .......... .......... .......... .......... .......... 10% 10.7M 3s
  3550K .......... .......... .......... .......... .......... 10% 8.23M 3s
  3600K .......... .......... .......... .......... .......... 10% 12.6M 3s
  3650K .......... .......... .......... .......... .......... 11% 33.1M 3s
  3700K .......... .......... .......... .......... .......... 11% 9.23M 3s
  3750K .......... .......... .......... .......... .......... 11% 17.5M 3s
  3800K .......... .......... .......... .......... .......... 11% 10.5M 3s
  3850K .......... .......... .......... .......... .......... 11% 25.1M 3s
  3900K .......... .......... .......... .......... .......... 11% 14.1M 3s
  3950K .......... .......... .......... .......... .......... 12% 10.7M 3s
  4000K .......... .......... .......... .......... .......... 12% 13.4M 3s
  4050K .......... .......... .......... .......... .......... 12% 11.9M 3s
  4100K .......... .......... .......... .......... .......... 12% 12.8M 3s
  4150K .......... .......... .......... .......... .......... 12% 9.86M 3s
  4200K .......... .......... .......... .......... .......... 12% 14.9M 3s
  4250K .......... .......... .......... .......... .......... 12% 16.7M 3s
  4300K .......... .......... .......... .......... .......... 13% 15.9M 3s
  4350K .......... .......... .......... .......... .......... 13% 7.84M 3s
  4400K .......... .......... .......... .......... .......... 13% 12.8M 3s
  4450K .......... .......... .......... .......... .......... 13% 15.6M 3s
  4500K .......... .......... .......... .......... .......... 13% 12.4M 3s
  4550K .......... .......... .......... .......... .......... 13% 13.7M 3s
  4600K .......... .......... .......... .......... .......... 13% 20.0M 3s
  4650K .......... .......... .......... .......... .......... 14% 10.1M 3s
  4700K .......... .......... .......... .......... .......... 14% 20.4M 3s
  4750K .......... .......... .......... .......... .......... 14% 7.67M 3s
  4800K .......... .......... .......... .......... .......... 14% 12.0M 3s
  4850K .......... .......... .......... .......... .......... 14% 14.1M 3s
  4900K .......... .......... .......... .......... .......... 14% 14.4M 3s
  4950K .......... .......... .......... .......... .......... 15% 15.3M 3s
  5000K .......... .......... .......... .......... .......... 15% 10.7M 3s
  5050K .......... .......... .......... .......... .......... 15% 31.1M 3s
  5100K .......... .......... .......... .......... .......... 15% 8.60M 3s
  5150K .......... .......... .......... .......... .......... 15% 13.9M 3s
  5200K .......... .......... .......... .......... .......... 15% 11.3M 2s
  5250K .......... .......... .......... .......... .......... 15% 16.0M 2s
  5300K .......... .......... .......... .......... .......... 16% 14.0M 2s
  5350K .......... .......... .......... .......... .......... 16% 14.2M 2s
  5400K .......... .......... .......... .......... .......... 16% 7.95M 2s
  5450K .......... .......... .......... .......... .......... 16% 16.7M 2s
  5500K .......... .......... .......... .......... .......... 16% 16.3M 2s
  5550K .......... .......... .......... .......... .......... 16% 9.50M 2s
  5600K .......... .......... .......... .......... .......... 16% 14.2M 2s
  5650K .......... .......... .......... .......... .......... 17% 11.7M 2s
  5700K .......... .......... .......... .......... .......... 17% 14.7M 2s
  5750K .......... .......... .......... .......... .......... 17% 18.2M 2s
  5800K .......... .......... .......... .......... .......... 17% 13.1M 2s
  5850K .......... .......... .......... .......... .......... 17% 9.82M 2s
  5900K .......... .......... .......... .......... .......... 17% 15.5M 2s
  5950K .......... .......... .......... .......... .......... 18% 9.28M 2s
  6000K .......... .......... .......... .......... .......... 18% 16.3M 2s
  6050K .......... .......... .......... .......... .......... 18% 10.8M 2s
  6100K .......... .......... .......... .......... .......... 18% 17.0M 2s
  6150K .......... .......... .......... .......... .......... 18% 11.6M 2s
  6200K .......... .......... .......... .......... .......... 18% 13.7M 2s
  6250K .......... .......... .......... .......... .......... 18% 18.8M 2s
  6300K .......... .......... .......... .......... .......... 19% 11.7M 2s
  6350K .......... .......... .......... .......... .......... 19% 7.76M 2s
  6400K .......... .......... .......... .......... .......... 19% 13.6M 2s
  6450K .......... .......... .......... .......... .......... 19% 21.7M 2s
  6500K .......... .......... .......... .......... .......... 19% 9.44M 2s
  6550K .......... .......... .......... .......... .......... 19% 10.5M 2s
  6600K .......... .......... .......... .......... .......... 19% 22.4M 2s
  6650K .......... .......... .......... .......... .......... 20% 11.4M 2s
  6700K .......... .......... .......... .......... .......... 20% 18.2M 2s
  6750K .......... .......... .......... .......... .......... 20% 9.23M 2s
  6800K .......... .......... .......... .......... .......... 20% 11.9M 2s
  6850K .......... .......... .......... .......... .......... 20% 12.3M 2s
  6900K .......... .......... .......... .......... .......... 20% 11.0M 2s
  6950K .......... .......... .......... .......... .......... 21% 30.9M 2s
  7000K .......... .......... .......... .......... .......... 21% 15.7M 2s
  7050K .......... .......... .......... .......... .......... 21% 7.89M 2s
  7100K .......... .......... .......... .......... .......... 21% 33.7M 2s
  7150K .......... .......... .......... .......... .......... 21% 8.74M 2s
  7200K .......... .......... .......... .......... .......... 21% 14.1M 2s
  7250K .......... .......... .......... .......... .......... 21% 6.95M 2s
  7300K .......... .......... .......... .......... .......... 22% 37.9M 2s
  7350K .......... .......... .......... .......... .......... 22% 28.8M 2s
  7400K .......... .......... .......... .......... .......... 22% 13.6M 2s
  7450K .......... .......... .......... .......... .......... 22% 11.6M 2s
  7500K .......... .......... .......... .......... .......... 22% 14.0M 2s
  7550K .......... .......... .......... .......... .......... 22% 7.88M 2s
  7600K .......... .......... .......... .......... .......... 22% 16.0M 2s
  7650K .......... .......... .......... .......... .......... 23% 12.9M 2s
  7700K .......... .......... .......... .......... .......... 23% 21.6M 2s
  7750K .......... .......... .......... .......... .......... 23% 9.01M 2s
  7800K .......... .......... .......... .......... .......... 23% 23.2M 2s
  7850K .......... .......... .......... .......... .......... 23% 9.89M 2s
  7900K .......... .......... .......... .......... .......... 23% 12.4M 2s
  7950K .......... .......... .......... .......... .......... 24% 10.1M 2s
  8000K .......... .......... .......... .......... .......... 24% 15.3M 2s
  8050K .......... .......... .......... .......... .......... 24% 9.13M 2s
  8100K .......... .......... .......... .......... .......... 24% 22.5M 2s
  8150K .......... .......... .......... .......... .......... 24% 13.6M 2s
  8200K .......... .......... .......... .......... .......... 24% 11.5M 2s
  8250K .......... .......... .......... .......... .......... 24% 10.8M 2s
  8300K .......... .......... .......... .......... .......... 25% 33.1M 2s
  8350K .......... .......... .......... .......... .......... 25% 10.2M 2s
  8400K .......... .......... .......... .......... .......... 25% 10.6M 2s
  8450K .......... .......... .......... .......... .......... 25% 19.8M 2s
  8500K .......... .......... .......... .......... .......... 25% 9.15M 2s
  8550K .......... .......... .......... .......... .......... 25% 12.4M 2s
  8600K .......... .......... .......... .......... .......... 25% 13.3M 2s
  8650K .......... .......... .......... .......... .......... 26% 10.4M 2s
  8700K .......... .......... .......... .......... .......... 26% 19.6M 2s
  8750K .......... .......... .......... .......... .......... 26% 9.62M 2s
  8800K .......... .......... .......... .......... .......... 26% 20.6M 2s
  8850K .......... .......... .......... .......... .......... 26% 10.9M 2s
  8900K .......... .......... .......... .......... .......... 26% 12.7M 2s
  8950K .......... .......... .......... .......... .......... 27% 8.80M 2s
  9000K .......... .......... .......... .......... .......... 27% 34.7M 2s
  9050K .......... .......... .......... .......... .......... 27% 20.3M 2s
  9100K .......... .......... .......... .......... .......... 27% 8.12M 2s
  9150K .......... .......... .......... .......... .......... 27% 13.1M 2s
  9200K .......... .......... .......... .......... .......... 27% 11.5M 2s
  9250K .......... .......... .......... .......... .......... 27% 15.3M 2s
  9300K .......... .......... .......... .......... .......... 28% 12.8M 2s
  9350K .......... .......... .......... .......... .......... 28% 17.0M 2s
  9400K .......... .......... .......... .......... .......... 28% 9.52M 2s
  9450K .......... .......... .......... .......... .......... 28% 31.8M 2s
  9500K .......... .......... .......... .......... .......... 28% 7.16M 2s
  9550K .......... .......... .......... .......... .......... 28% 10.6M 2s
  9600K .......... .......... .......... .......... .......... 28% 19.9M 2s
  9650K .......... .......... .......... .......... .......... 29% 17.9M 2s
  9700K .......... .......... .......... .......... .......... 29% 11.5M 2s
  9750K .......... .......... .......... .......... .......... 29% 14.4M 2s
  9800K .......... .......... .......... .......... .......... 29% 9.83M 2s
  9850K .......... .......... .......... .......... .......... 29% 18.3M 2s
  9900K .......... .......... .......... .......... .......... 29% 13.6M 2s
  9950K .......... .......... .......... .......... .......... 30% 7.66M 2s
 10000K .......... .......... .......... .......... .......... 30% 39.9M 2s
 10050K .......... .......... .......... .......... .......... 30% 11.5M 2s
 10100K .......... .......... .......... .......... .......... 30% 8.99M 2s
 10150K .......... .......... .......... .......... .......... 30% 14.6M 2s
 10200K .......... .......... .......... .......... .......... 30% 21.6M 2s
 10250K .......... .......... .......... .......... .......... 30% 8.34M 2s
 10300K .......... .......... .......... .......... .......... 31% 16.1M 2s
 10350K .......... .......... .......... .......... .......... 31% 17.4M 2s
 10400K .......... .......... .......... .......... .......... 31% 8.61M 2s
 10450K .......... .......... .......... .......... .......... 31% 26.3M 2s
 10500K .......... .......... .......... .......... .......... 31% 11.6M 2s
 10550K .......... .......... .......... .......... .......... 31% 13.2M 2s
 10600K .......... .......... .......... .......... .......... 31% 11.1M 2s
 10650K .......... .......... .......... .......... .......... 32% 14.2M 2s
 10700K .......... .......... .......... .......... .......... 32% 15.8M 2s
 10750K .......... .......... .......... .......... .......... 32% 9.40M 2s
 10800K .......... .......... .......... .......... .......... 32% 19.6M 2s
 10850K .......... .......... .......... .......... .......... 32% 11.5M 2s
 10900K .......... .......... .......... .......... .......... 32% 15.6M 2s
 10950K .......... .......... .......... .......... .......... 33% 7.98M 2s
 11000K .......... .......... .......... .......... .......... 33% 32.4M 2s
 11050K .......... .......... .......... .......... .......... 33% 11.3M 2s
 11100K .......... .......... .......... .......... .......... 33% 10.6M 2s
 11150K .......... .......... .......... .......... .......... 33% 10.2M 2s
 11200K .......... .......... .......... .......... .......... 33% 13.4M 2s
 11250K .......... .......... .......... .......... .......... 33% 12.2M 2s
 11300K .......... .......... .......... .......... .......... 34% 17.8M 2s
 11350K .......... .......... .......... .......... .......... 34% 11.5M 2s
 11400K .......... .......... .......... .......... .......... 34% 14.9M 2s
 11450K .......... .......... .......... .......... .......... 34% 14.7M 2s
 11500K .......... .......... .......... .......... .......... 34% 16.0M 2s

Downloading atb.assembly.r0.2.batch.30.tar.xz from https://osf.io/download/667143e865e1de5e74893e6b/

Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667143e865e1de5e74893e6b [following]
--2026-09-06 18:51:46--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667143e865e1de5e74893e6b
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/492da7ddfb50a6e019206db27abfa2e9764b5fc66a8abf5004670329231d5fa0?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.30.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.30.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713567&Signature=as7tDMNa5hukybDi3ql6i%2FyjhhDQ%2FB8YZ4auZ053kWS7wckZpRD8Y%2BKDpB4EhiHzvpH07fhGe6zyhrgEJ84nkx7zyiburnqrqceCD4JlT4i4E9UzrbEOM5DkmlPXuKnINfpL7G3zoeK6b246Z0XvmdWdXSg38icnWryCI4KvlR5tMyfQQDMmSAKP1dIwqXRTnCeC1F8nNjBhWqXSSHBnFiFXX%2BPTWAuWwHUbHxYO860uFxuD8erm7vAA3ddiGwa1UzYLYJhbHk5Us5xQoifMKiVm%2B9KQzO6r7Tfo6BcZEL6%2FXv%2BnRZN35cGHgsu7MBVOAHI7lMrpDpThKJzNWAfsUA%3D%3D [following]
--2026-09-06 18:51:47--  https://storage.googleapis.com/cos-osf-prod-files-de-1/492da7ddfb50a6e019206db27abfa2e9764b5fc66a8abf5004670329231d5fa0?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.30.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.30.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713567&Signature=as7tDMNa5hukybDi3ql6i%2FyjhhDQ%2FB8YZ4auZ053kWS7wckZpRD8Y%2BKDpB4EhiHzvpH07fhGe6zyhrgEJ84nkx7zyiburnqrqceCD4JlT4i4E9UzrbEOM5DkmlPXuKnINfpL7G3zoeK6b246Z0XvmdWdXSg38icnWryCI4KvlR5tMyfQQDMmSAKP1dIwqXRTnCeC1F8nNjBhWqXSSHBnFiFXX%2BPTWAuWwHUbHxYO860uFxuD8erm7vAA3ddiGwa1UzYLYJhbHk5Us5xQoifMKiVm%2B9KQzO6r7Tfo6BcZEL6%2FXv%2BnRZN35cGHgsu7MBVOAHI7lMrpDpThKJzNWAfsUA%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12790988 (12M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.30.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.21M 10s
    50K .......... .......... .......... .......... ..........  0% 2.79M 7s
   100K .......... .......... .......... .......... ..........  1% 3.95M 6s
   150K .......... .......... .......... .......... ..........  1% 4.40M 5s
   200K .......... .......... .......... .......... ..........  2% 6.24M 4s
   250K .......... .......... .......... .......... ..........  2% 14.2M 4s
   300K .......... .......... .......... .......... ..........  2% 6.94M 3s
   350K .......... .......... .......... .......... ..........  3% 11.8M 3s
   400K .......... .......... .......... .......... ..........  3% 22.4M 3s
   450K .......... .......... .......... .......... ..........  4% 7.02M 3s
   500K .......... .......... .......... .......... ..........  4% 20.0M 3s
   550K .......... .......... .......... .......... ..........  4% 11.3M 2s
   600K .......... .......... .......... .......... ..........  5% 14.6M 2s
   650K .......... .......... .......... .......... ..........  5% 12.2M 2s
   700K .......... .......... .......... .......... ..........  6% 10.0M 2s
   750K .......... .......... .......... .......... ..........  6% 12.2M 2s
   800K .......... .......... .......... .......... ..........  6% 14.3M 2s
   850K .......... .......... .......... .......... ..........  7% 19.3M 2s
   900K .......... .......... .......... .......... ..........  7% 10.6M 2s
   950K .......... .......... .......... .......... ..........  8% 13.3M 2s
  1000K .......... .......... .......... .......... ..........  8% 9.62M 2s
  1050K .......... .......... .......... .......... ..........  8% 17.5M 2s
  1100K .......... .......... .......... .......... ..........  9% 9.38M 2s
  1150K .......... .......... .......... .......... ..........  9% 14.6M 2s
  1200K .......... .......... .......... .......... .......... 10% 10.6M 2s
  1250K .......... .......... .......... .......... .......... 10% 22.5M 1s
  1300K .......... .......... .......... .......... .......... 10% 13.3M 1s
  1350K .......... .......... .......... .......... .......... 11% 15.0M 1s
  1400K .......... .......... .......... .......... .......... 11% 9.28M 1s
  1450K .......... .......... .......... .......... .......... 12% 18.2M 1s
  1500K .......... .......... .......... .......... .......... 12% 11.6M 1s
  1550K .......... .......... .......... .......... .......... 12% 11.2M 1s
  1600K .......... .......... .......... .......... .......... 13% 14.4M 1s
  1650K .......... .......... .......... .......... .......... 13% 9.66M 1s
  1700K .......... .......... .......... .......... .......... 14% 24.9M 1s
  1750K .......... .......... .......... .......... .......... 14% 13.5M 1s
  1800K .......... .......... .......... .......... .......... 14% 9.90M 1s
  1850K .......... .......... .......... .......... .......... 15% 13.0M 1s
  1900K .......... .......... .......... .......... .......... 15% 15.9M 1s
  1950K .......... .......... .......... .......... .......... 16% 11.0M 1s
  2000K .......... .......... .......... .......... .......... 16% 15.2M 1s
  2050K .......... .......... .......... .......... .......... 16% 12.1M 1s
  2100K .......... .......... .......... .......... .......... 17% 16.6M 1s
  2150K .......... .......... .......... .......... .......... 17% 10.2M 1s
  2200K .......... .......... .......... .......... .......... 18% 13.8M 1s
  2250K .......... .......... .......... .......... .......... 18% 13.5M 1s
  2300K .......... .......... .......... .......... .......... 18% 18.5M 1s
  2350K .......... .......... .......... .......... .......... 19% 7.28M 1s
  2400K .......... .......... .......... .......... .......... 19% 17.4M 1s
  2450K .......... .......... .......... .......... .......... 20% 14.3M 1s
  2500K .......... .......... .......... .......... .......... 20% 10.4M 1s
  2550K .......... .......... .......... .......... .......... 20% 13.3M 1s
  2600K .......... .......... .......... .......... .......... 21% 12.9M 1s
  2650K .......... .......... .......... .......... .......... 21% 14.7M 1s
  2700K .......... .......... .......... .......... .......... 22% 14.0M 1s
  2750K .......... .......... .......... .......... .......... 22% 10.3M 1s
  2800K .......... .......... .......... .......... .......... 22% 10.7M 1s
  2850K .......... .......... .......... .......... .......... 23% 23.3M 1s
  2900K .......... .......... .......... .......... .......... 23% 13.6M 1s
  2950K .......... .......... .......... .......... .......... 24% 9.38M 1s
  3000K .......... .......... .......... .......... .......... 24% 21.4M 1s
  3050K .......... .......... .......... .......... .......... 24% 11.1M 1s
  3100K .......... .......... .......... .......... .......... 25% 14.8M 1s
  3150K .......... .......... .......... .......... .......... 25% 11.9M 1s
  3200K .......... .......... .......... .......... .......... 26% 12.0M 1s
  3250K .......... .......... .......... .......... .......... 26% 10.0M 1s
  3300K .......... .......... .......... .......... .......... 26% 15.1M 1s
  3350K .......... .......... .......... .......... .......... 27% 11.9M 1s
  3400K .......... .......... .......... .......... .......... 27% 24.0M 1s
  3450K .......... .......... .......... .......... .......... 28% 13.1M 1s
  3500K .......... .......... .......... .......... .......... 28% 8.76M 1s
  3550K .......... .......... .......... .......... .......... 28% 12.6M 1s
  3600K .......... .......... .......... .......... .......... 29% 13.5M 1s
  3650K .......... .......... .......... .......... .......... 29% 12.1M 1s
  3700K .......... .......... .......... .......... .......... 30% 14.0M 1s
  3750K .......... .......... .......... .......... .......... 30% 12.8M 1s
  3800K .......... .......... .......... .......... .......... 30% 10.1M 1s
  3850K .......... .......... .......... .......... .......... 31% 26.5M 1s
  3900K .......... .......... .......... .......... .......... 31% 11.2M 1s
  3950K .......... .......... .......... .......... .......... 32% 12.6M 1s
  4000K .......... .......... .......... .......... .......... 32% 8.64M 1s
  4050K .......... .......... .......... .......... .......... 32% 22.6M 1s
  4100K .......... .......... .......... .......... .......... 33% 9.84M 1s
  4150K .......... .......... .......... .......... .......... 33% 15.8M 1s
  4200K .......... .......... .......... .......... .......... 34% 11.9M 1s
  4250K .......... .......... .......... .......... .......... 34% 12.4M 1s
  4300K .......... .......... .......... .......... .......... 34% 13.7M 1s
  4350K .......... .......... .......... .......... .......... 35% 16.6M 1s
  4400K .......... .......... .......... .......... .......... 35% 11.4M 1s
  4450K .......... .......... .......... .......... .......... 36% 11.4M 1s
  4500K .......... .......... .......... .......... .......... 36% 15.2M 1s
  4550K .......... .......... .......... .......... .......... 36% 13.6M 1s
  4600K .......... .......... .......... .......... .......... 37% 14.1M 1s
  4650K .......... .......... .......... .......... .......... 37% 9.35M 1s
  4700K .......... .......... .......... .......... .......... 38% 24.2M 1s
  4750K .......... .......... .......... .......... .......... 38% 7.33M 1s
  4800K .......... .......... .......... .......... .......... 38% 17.1M 1s
  4850K .......... .......... .......... .......... .......... 39% 17.3M 1s
  4900K .......... .......... .......... .......... .......... 39% 13.8M 1s
  4950K .......... .......... .......... .......... .......... 40% 13.0M 1s
  5000K .......... .......... .......... .......... .......... 40% 12.1M 1s
  5050K .......... .......... .......... .......... .......... 40% 10.5M 1s
  5100K .......... .......... .......... .......... .......... 41% 24.3M 1s
  5150K .......... .......... .......... .......... .......... 41% 8.31M 1s
  5200K .......... .......... .......... .......... .......... 42% 14.0M 1s
  5250K .......... .......... .......... .......... .......... 42% 13.6M 1s
  5300K .......... .......... .......... .......... .......... 42% 13.0M 1s
  5350K .......... .......... .......... .......... .......... 43% 15.6M 1s
  5400K .......... .......... .......... .......... .......... 43% 11.9M 1s
  5450K .......... .......... .......... .......... .......... 44% 14.5M 1s
  5500K .......... .......... .......... .......... .......... 44% 10.8M 1s
  5550K .......... .......... .......... .......... .......... 44% 9.74M 1s
  5600K .......... .......... .......... .......... .......... 45% 14.1M 1s
  5650K .......... .......... .......... .......... .......... 45% 10.9M 1s
  5700K .......... .......... .......... .......... .......... 46% 27.6M 1s
  5750K .......... .......... .......... .......... .......... 46% 9.72M 1s
  5800K .......... .......... .......... .......... .......... 46% 24.0M 1s
  5850K .......... .......... .......... .......... .......... 47% 8.94M 1s
  5900K .......... .......... .......... .......... .......... 47% 15.6M 1s
  5950K .......... .......... .......... .......... .......... 48% 12.3M 1s
  6000K .......... .......... .......... .......... .......... 48% 8.95M 1s
  6050K .......... .......... .......... .......... .......... 48% 12.6M 1s
  6100K .......... .......... .......... .......... .......... 49% 34.5M 1s
  6150K .......... .......... .......... .......... .......... 49% 9.45M 1s
  6200K .......... .......... .......... .......... .......... 50% 15.2M 1s
  6250K .......... .......... .......... .......... .......... 50% 14.2M 1s
  6300K .......... .......... .......... .......... .......... 50% 13.0M 1s
  6350K .......... .......... .......... .......... .......... 51% 10.5M 1s
  6400K .......... .......... .......... .......... .......... 51% 14.0M 1s
  6450K .......... .......... .......... .......... .......... 52% 14.1M 1s
  6500K .......... .......... .......... .......... .......... 52% 13.5M 1s
  6550K .......... .......... .......... .......... .......... 52% 14.6M 1s
  6600K .......... .......... .......... .......... .......... 53% 11.3M 1s
  6650K .......... .......... .......... .......... .......... 53% 9.44M 1s
  6700K .......... .......... .......... .......... .......... 54% 15.5M 1s
  6750K .......... .......... .......... .......... .......... 54% 9.85M 0s
  6800K .......... .......... .......... .......... .......... 54% 15.8M 0s
  6850K .......... .......... .......... .......... .......... 55% 11.5M 0s
  6900K .......... .......... .......... .......... .......... 55% 14.6M 0s
  6950K .......... .......... .......... .......... .......... 56% 13.5M 0s
  7000K .......... .......... .......... .......... .......... 56% 16.5M 0s
  7050K .......... .......... .......... .......... .......... 56% 10.4M 0s
  7100K .......... .......... .......... .......... .......... 57% 12.5M 0s
  7150K .......... .......... .......... .......... .......... 57% 10.8M 0s
  7200K .......... .......... .......... .......... .......... 58% 13.0M 0s
  7250K .......... .......... .......... .......... .......... 58% 11.3M 0s
  7300K .......... .......... .......... .......... .......... 58% 18.9M 0s
  7350K .......... .......... .......... .......... .......... 59% 13.9M 0s
  7400K .......... .......... .......... .......... .......... 59% 10.2M 0s
  7450K .......... .......... .......... .......... .......... 60% 13.1M 0s
  7500K .......... .......... .......... .......... .......... 60% 15.6M 0s
  7550K .......... .......... .......... .......... .......... 60% 10.8M 0s
  7600K .......... .......... .......... .......... .......... 61% 15.1M 0s
  7650K .......... .......... .......... .......... .......... 61% 11.5M 0s
  7700K .......... .......... .......... .......... .......... 62% 11.4M 0s
  7750K .......... .......... .......... .......... .......... 62% 13.2M 0s
  7800K .......... .......... .......... .......... .......... 62% 23.2M 0s
  7850K .......... .......... .......... .......... .......... 63% 10.5M 0s
  7900K .......... .......... .......... .......... .......... 63% 14.1M 0s
  7950K .......... .......... .......... .......... .......... 64% 9.36M 0s
  8000K .......... .......... .......... .......... .......... 64% 11.7M 0s
  8050K .......... .......... .......... .......... .......... 64% 11.1M 0s
  8100K .......... .......... .......... .......... .......... 65% 18.0M 0s
  8150K .......... .......... .......... .......... .......... 65% 22.0M 0s
  8200K .......... .......... .......... .......... .......... 66% 10.5M 0s
  8250K .......... .......... .......... .......... .......... 66% 12.4M 0s
  8300K .......... .......... .......... .......... .......... 66% 12.9M 0s
  8350K .......... .......... .......... .......... .......... 67% 15.1M 0s
  8400K .......... .......... .......... .......... .......... 67% 8.64M 0s
  8450K .......... .......... .......... .......... .......... 68% 12.9M 0s
  8500K .......... .......... .......... .......... .......... 68% 19.0M 0s
  8550K .......... .......... .......... .......... .......... 68% 14.4M 0s
  8600K .......... .......... .......... .......... .......... 69% 13.3M 0s
  8650K .......... .......... .......... .......... .......... 69% 12.2M 0s
  8700K .......... .......... .......... .......... .......... 70% 16.8M 0s
  8750K .......... .......... .......... .......... .......... 70% 9.15M 0s
  8800K .......... .......... .......... .......... .......... 70% 9.56M 0s
  8850K .......... .......... .......... .......... .......... 71% 13.2M 0s
  8900K .......... .......... .......... .......... .......... 71% 20.0M 0s
  8950K .......... .......... .......... .......... .......... 72% 14.0M 0s
  9000K .......... .......... .......... .......... .......... 72% 11.4M 0s
  9050K .......... .......... .......... .......... .......... 72% 12.2M 0s
  9100K .......... .......... .......... .......... .......... 73% 25.2M 0s
  9150K .......... .......... .......... .......... .......... 73% 9.84M 0s
  9200K .......... .......... .......... .......... .......... 74% 9.84M 0s
  9250K .......... .......... .......... .......... .......... 74% 11.4M 0s
  9300K .......... .......... .......... .......... .......... 74% 11.0M 0s
  9350K .......... .......... .......... .......... .......... 75% 15.3M 0s
  9400K .......... .......... .......... .......... .......... 75% 18.1M 0s
  9450K .......... .......... .......... .......... .......... 76% 16.8M 0s
  9500K .......... .......... .......... .......... .......... 76% 9.30M 0s
  9550K .......... .......... .......... .......... .......... 76% 11.0M 0s
  9600K .......... .......... .......... .......... .......... 77% 6.77M 0s
  9650K .......... .......... .......... .......... .......... 77%  503M 0s
  9700K .......... .......... .......... .......... .......... 78% 10.2M 0s
  9750K .......... .......... .......... .......... .......... 78% 15.4M 0s
  9800K .......... .......... .......... .......... .......... 78% 25.5M 0s
  9850K .......... .......... .......... .......... .......... 79% 11.7M 0s
  9900K .......... .......... .......... .......... .......... 79% 11.4M 0s
  9950K .......... .......... .......... .......... .......... 80% 9.59M 0s
 10000K .......... .......... .......... .......... .......... 80% 13.9M 0s
 10050K .......... .......... .......... .......... .......... 80% 18.9M 0s
 10100K .......... .......... .......... .......... .......... 81% 9.80M 0s
 10150K .......... .......... .......... .......... .......... 81% 26.8M 0s
 10200K .......... .......... .......... .......... .......... 82% 8.85M 0s
 10250K .......... .......... .......... .......... .......... 82% 14.2M 0s
 10300K .......... .......... .......... .......... .......... 82% 13.3M 0s
 10350K .......... .......... .......... .......... .......... 83% 12.8M 0s
 10400K .......... .......... .......... .......... .......... 83% 12.2M 0s
 10450K .......... .......... .......... .......... .......... 84% 14.7M 0s
 10500K .......... .......... .......... .......... .......... 84% 11.7M 0s
 10550K .......... .......... .......... .......... .......... 84% 10.9M 0s
 10600K .......... .......... .......... .......... .......... 85% 11.8M 0s
 10650K .......... .......... .......... .......... .......... 85% 24.6M 0s
 10700K .......... .......... .......... .......... .......... 86% 10.5M 0s
 10750K .......... .......... .......... .......... .......... 86% 14.8M 0s
 10800K .......... .......... .......... .......... .......... 86% 11.8M 0s
 10850K .......... .......... .......... .......... .......... 87% 11.3M 0s
 10900K .......... .......... .......... .......... .......... 87% 13.2M 0s
 10950K .......... .......... .......... .......... .......... 88% 8.70M 0s
 11000K .......... .......... .......... .......... .......... 88% 61.0M 0s
 11050K .......... .......... .......... .......... .......... 88% 14.0M 0s
 11100K .......... .......... .......... .......... .......... 89% 10.4M 0s
 11150K .......... .......... .......... .......... .......... 89% 8.75M 0s
 11200K .......... .......... .......... .......... .......... 90% 15.5M 0s
 11250K .......... .......... .......... .......... .......... 90% 9.95M 0s
 11300K .......... .......... .......... .......... .......... 90% 13.7M 0s
 11350K .......... .......... .......... .......... .......... 91% 13.6M 0s
 11400K .......... .......... .......... .......... .......... 91% 12.2M 0s
 11450K .......... .......... .......... .......... .......... 92% 34.3M 0s

Downloading atb.assembly.r0.2.batch.31.tar.xz from https://osf.io/download/6671452d65e1de5e74893fe1/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671452d65e1de5e74893fe1 [following]
--2026-09-06 18:51:48--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671452d65e1de5e74893fe1
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/9863bb2a60af03d852aa1c7738de18f8f16e722c797006ad91ca3c1b356102a6?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.31.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.31.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713569&Signature=vE%2BqI%2Fmgvy6RTtzBfQAuZure1aFOg5djQeXM%2BAQ5nBDWPw3p6J9EO1cihP50C%2ByjcfwlqrKY1wKJC1aDAy7mhwVQlXhV4YUzY5vsafuxX5gZ39FuzbugKofz8roC9OmfkoFNymmf%2BxcMHblvF4X9DJm6efggQ9kQRC9hK3CYq6vF4gh%2BQhKJOT6K8SbgekFb9iAuzsa9xuoCyYL%2BfQOfkD8PZo10PPYjCAsH8YHJNNoo4%2F%2B9mWJbTdeTbloM4NNwGIH1iwhawBL2Xb4fvkcuhWT%2B7yX8h9hcWPxcWbHHyKqZ2ymYmQMDOn2V3xO8V2loNKL8Kv6QGC8MIUcCIUrdww%3D%3D [following]
--2026-09-06 18:51:49--  https://storage.googleapis.com/cos-osf-prod-files-de-1/9863bb2a60af03d852aa1c7738de18f8f16e722c797006ad91ca3c1b356102a6?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.31.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.31.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713569&Signature=vE%2BqI%2Fmgvy6RTtzBfQAuZure1aFOg5djQeXM%2BAQ5nBDWPw3p6J9EO1cihP50C%2ByjcfwlqrKY1wKJC1aDAy7mhwVQlXhV4YUzY5vsafuxX5gZ39FuzbugKofz8roC9OmfkoFNymmf%2BxcMHblvF4X9DJm6efggQ9kQRC9hK3CYq6vF4gh%2BQhKJOT6K8SbgekFb9iAuzsa9xuoCyYL%2BfQOfkD8PZo10PPYjCAsH8YHJNNoo4%2F%2B9mWJbTdeTbloM4NNwGIH1iwhawBL2Xb4fvkcuhWT%2B7yX8h9hcWPxcWbHHyKqZ2ymYmQMDOn2V3xO8V2loNKL8Kv6QGC8MIUcCIUrdww%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30656612 (29M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.31.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.25M 23s
    50K .......... .......... .......... .......... ..........  0% 2.82M 17s
   100K .......... .......... .......... .......... ..........  0% 4.32M 13s
   150K .......... .......... .......... .......... ..........  0% 4.96M 12s
   200K .......... .......... .......... .......... ..........  0% 7.96M 10s
   250K .......... .......... .......... .......... ..........  1% 7.25M 9s
   300K .......... .......... .......... .......... ..........  1% 8.89M 8s
   350K .......... .......... .......... .......... ..........  1% 13.2M 7s
   400K .......... .......... .......... .......... ..........  1% 13.5M 7s
   450K .......... .......... .......... .......... ..........  1% 12.3M 6s
   500K .......... .......... .......... .......... ..........  1% 22.7M 6s
   550K .......... .......... .......... .......... ..........  2% 11.7M 6s
   600K .......... .......... .......... .......... ..........  2% 10.9M 5s
   650K .......... .......... .......... .......... ..........  2% 10.0M 5s
   700K .......... .......... .......... .......... ..........  2% 15.5M 5s
   750K .......... .......... .......... .......... ..........  2% 17.3M 5s
   800K .......... .......... .......... .......... ..........  2% 11.5M 5s
   850K .......... .......... .......... .......... ..........  3% 9.26M 4s
   900K .......... .......... .......... .......... ..........  3% 15.2M 4s
   950K .......... .......... .......... .......... ..........  3% 14.5M 4s
  1000K .......... .......... .......... .......... ..........  3% 10.4M 4s
  1050K .......... .......... .......... .......... ..........  3% 13.9M 4s
  1100K .......... .......... .......... .......... ..........  3% 13.5M 4s
  1150K .......... .......... .......... .......... ..........  4% 10.2M 4s
  1200K .......... .......... .......... .......... ..........  4% 12.9M 4s
  1250K .......... .......... .......... .......... ..........  4% 13.3M 4s
  1300K .......... .......... .......... .......... ..........  4% 13.5M 4s
  1350K .......... .......... .......... .......... ..........  4% 11.9M 4s
  1400K .......... .......... .......... .......... ..........  4% 14.9M 4s
  1450K .......... .......... .......... .......... ..........  5% 12.6M 3s
  1500K .......... .......... .......... .......... ..........  5% 13.2M 3s
  1550K .......... .......... .......... .......... ..........  5% 12.2M 3s
  1600K .......... .......... .......... .......... ..........  5% 11.5M 3s
  1650K .......... .......... .......... .......... ..........  5% 13.0M 3s
  1700K .......... .......... .......... .......... ..........  5% 12.6M 3s
  1750K .......... .......... .......... .......... ..........  6% 13.7M 3s
  1800K .......... .......... .......... .......... ..........  6% 11.8M 3s
  1850K .......... .......... .......... .......... ..........  6% 15.7M 3s
  1900K .......... .......... .......... .......... ..........  6% 13.2M 3s
  1950K .......... .......... .......... .......... ..........  6% 11.3M 3s
  2000K .......... .......... .......... .......... ..........  6% 12.9M 3s
  2050K .......... .......... .......... .......... ..........  7% 19.5M 3s
  2100K .......... .......... .......... .......... ..........  7% 12.3M 3s
  2150K .......... .......... .......... .......... ..........  7% 14.4M 3s
  2200K .......... .......... .......... .......... ..........  7% 11.2M 3s
  2250K .......... .......... .......... .......... ..........  7% 17.3M 3s
  2300K .......... .......... .......... .......... ..........  7% 10.8M 3s
  2350K .......... .......... .......... .......... ..........  8% 11.1M 3s
  2400K .......... .......... .......... .......... ..........  8% 9.46M 3s
  2450K .......... .......... .......... .......... ..........  8% 22.7M 3s
  2500K .......... .......... .......... .......... ..........  8% 13.4M 3s
  2550K .......... .......... .......... .......... ..........  8% 12.7M 3s
  2600K .......... .......... .......... .......... ..........  8% 9.36M 3s
  2650K .......... .......... .......... .......... ..........  9% 14.8M 3s
  2700K .......... .......... .......... .......... ..........  9% 14.9M 3s
  2750K .......... .......... .......... .......... ..........  9% 13.3M 3s
  2800K .......... .......... .......... .......... ..........  9% 11.3M 3s
  2850K .......... .......... .......... .......... ..........  9% 12.1M 3s
  2900K .......... .......... .......... .......... ..........  9% 18.6M 3s
  2950K .......... .......... .......... .......... .......... 10% 13.6M 3s
  3000K .......... .......... .......... .......... .......... 10% 9.62M 3s
  3050K .......... .......... .......... .......... .......... 10% 16.6M 3s
  3100K .......... .......... .......... .......... .......... 10% 10.0M 3s
  3150K .......... .......... .......... .......... .......... 10% 12.9M 3s
  3200K .......... .......... .......... .......... .......... 10% 14.6M 3s
  3250K .......... .......... .......... .......... .......... 11% 13.3M 3s
  3300K .......... .......... .......... .......... .......... 11% 10.6M 3s
  3350K .......... .......... .......... .......... .......... 11% 13.3M 3s
  3400K .......... .......... .......... .......... .......... 11% 14.5M 3s
  3450K .......... .......... .......... .......... .......... 11% 18.5M 3s
  3500K .......... .......... .......... .......... .......... 11% 12.2M 3s
  3550K .......... .......... .......... .......... .......... 12% 8.49M 3s
  3600K .......... .......... .......... .......... .......... 12% 14.1M 3s
  3650K .......... .......... .......... .......... .......... 12% 16.9M 2s
  3700K .......... .......... .......... .......... .......... 12% 9.21M 2s
  3750K .......... .......... .......... .......... .......... 12% 20.2M 2s
  3800K .......... .......... .......... .......... .......... 12% 15.0M 2s
  3850K .......... .......... .......... .......... .......... 13% 11.8M 2s
  3900K .......... .......... .......... .......... .......... 13% 11.0M 2s
  3950K .......... .......... .......... .......... .......... 13% 9.33M 2s
  4000K .......... .......... .......... .......... .......... 13% 18.4M 2s
  4050K .......... .......... .......... .......... .......... 13% 10.1M 2s
  4100K .......... .......... .......... .......... .......... 13% 24.0M 2s
  4150K .......... .......... .......... .......... .......... 14% 10.6M 2s
  4200K .......... .......... .......... .......... .......... 14% 11.7M 2s
  4250K .......... .......... .......... .......... .......... 14% 13.8M 2s
  4300K .......... .......... .......... .......... .......... 14% 14.8M 2s
  4350K .......... .......... .......... .......... .......... 14% 12.3M 2s
  4400K .......... .......... .......... .......... .......... 14% 11.0M 2s
  4450K .......... .......... .......... .......... .......... 15% 9.04M 2s
  4500K .......... .......... .......... .......... .......... 15% 33.9M 2s
  4550K .......... .......... .......... .......... .......... 15% 14.0M 2s
  4600K .......... .......... .......... .......... .......... 15% 10.7M 2s
  4650K .......... .......... .......... .......... .......... 15% 18.9M 2s
  4700K .......... .......... .......... .......... .......... 15% 10.1M 2s
  4750K .......... .......... .......... .......... .......... 16% 11.1M 2s
  4800K .......... .......... .......... .......... .......... 16% 11.4M 2s
  4850K .......... .......... .......... .......... .......... 16% 10.8M 2s
  4900K .......... .......... .......... .......... .......... 16% 22.3M 2s
  4950K .......... .......... .......... .......... .......... 16% 14.5M 2s
  5000K .......... .......... .......... .......... .......... 16% 8.37M 2s
  5050K .......... .......... .......... .......... .......... 17% 24.3M 2s
  5100K .......... .......... .......... .......... .......... 17% 13.9M 2s
  5150K .......... .......... .......... .......... .......... 17% 11.3M 2s
  5200K .......... .......... .......... .......... .......... 17% 10.1M 2s
  5250K .......... .......... .......... .......... .......... 17% 15.6M 2s
  5300K .......... .......... .......... .......... .......... 17% 14.0M 2s
  5350K .......... .......... .......... .......... .......... 18% 14.4M 2s
  5400K .......... .......... .......... .......... .......... 18% 13.9M 2s
  5450K .......... .......... .......... .......... .......... 18% 12.1M 2s
  5500K .......... .......... .......... .......... .......... 18% 13.0M 2s
  5550K .......... .......... .......... .......... .......... 18% 8.15M 2s
  5600K .......... .......... .......... .......... .......... 18% 14.5M 2s
  5650K .......... .......... .......... .......... .......... 19% 7.75M 2s
  5700K .......... .......... .......... .......... .......... 19%  149M 2s
  5750K .......... .......... .......... .......... .......... 19% 5.72M 2s
  5800K .......... .......... .......... .......... .......... 19%  634M 2s
  5850K .......... .......... .......... .......... .......... 19% 14.3M 2s
  5900K .......... .......... .......... .......... .......... 19% 21.2M 2s
  5950K .......... .......... .......... .......... .......... 20% 8.21M 2s
  6000K .......... .......... .......... .......... .......... 20% 15.5M 2s
  6050K .......... .......... .......... .......... .......... 20% 13.3M 2s
  6100K .......... .......... .......... .......... .......... 20% 11.2M 2s
  6150K .......... .......... .......... .......... .......... 20% 15.9M 2s
  6200K .......... .......... .......... .......... .......... 20% 10.7M 2s
  6250K .......... .......... .......... .......... .......... 21% 22.9M 2s
  6300K .......... .......... .......... .......... .......... 21% 7.51M 2s
  6350K .......... .......... .......... .......... .......... 21% 11.9M 2s
  6400K .......... .......... .......... .......... .......... 21% 31.7M 2s
  6450K .......... .......... .......... .......... .......... 21% 13.0M 2s
  6500K .......... .......... .......... .......... .......... 21% 9.66M 2s
  6550K .......... .......... .......... .......... .......... 22% 12.9M 2s
  6600K .......... .......... .......... .......... .......... 22% 14.9M 2s
  6650K .......... .......... .......... .......... .......... 22% 13.9M 2s
  6700K .......... .......... .......... .......... .......... 22% 10.1M 2s
  6750K .......... .......... .......... .......... .......... 22% 18.4M 2s
  6800K .......... .......... .......... .......... .......... 22% 11.7M 2s
  6850K .......... .......... .......... .......... .......... 23% 12.9M 2s
  6900K .......... .......... .......... .......... .......... 23% 14.9M 2s
  6950K .......... .......... .......... .......... .......... 23% 10.2M 2s
  7000K .......... .......... .......... .......... .......... 23% 12.0M 2s
  7050K .......... .......... .......... .......... .......... 23% 12.9M 2s
  7100K .......... .......... .......... .......... .......... 23% 14.6M 2s
  7150K .......... .......... .......... .......... .......... 24% 7.95M 2s
  7200K .......... .......... .......... .......... .......... 24% 49.5M 2s
  7250K .......... .......... .......... .......... .......... 24% 10.6M 2s
  7300K .......... .......... .......... .......... .......... 24% 15.0M 2s
  7350K .......... .......... .......... .......... .......... 24% 12.8M 2s
  7400K .......... .......... .......... .......... .......... 24% 12.9M 2s
  7450K .......... .......... .......... .......... .......... 25% 13.3M 2s
  7500K .......... .......... .......... .......... .......... 25% 16.3M 2s
  7550K .......... .......... .......... .......... .......... 25% 9.14M 2s
  7600K .......... .......... .......... .......... .......... 25% 15.3M 2s
  7650K .......... .......... .......... .......... .......... 25% 9.81M 2s
  7700K .......... .......... .......... .......... .......... 25% 20.8M 2s
  7750K .......... .......... .......... .......... .......... 26% 10.0M 2s
  7800K .......... .......... .......... .......... .......... 26% 19.0M 2s
  7850K .......... .......... .......... .......... .......... 26% 9.86M 2s
  7900K .......... .......... .......... .......... .......... 26% 12.2M 2s
  7950K .......... .......... .......... .......... .......... 26% 13.9M 2s
  8000K .......... .......... .......... .......... .......... 26% 15.2M 2s
  8050K .......... .......... .......... .......... .......... 27% 9.09M 2s
  8100K .......... .......... .......... .......... .......... 27% 15.1M 2s
  8150K .......... .......... .......... .......... .......... 27% 13.0M 2s
  8200K .......... .......... .......... .......... .......... 27% 23.3M 2s
  8250K .......... .......... .......... .......... .......... 27% 10.2M 2s
  8300K .......... .......... .......... .......... .......... 27% 17.5M 2s
  8350K .......... .......... .......... .......... .......... 28% 10.0M 2s
  8400K .......... .......... .......... .......... .......... 28% 13.1M 2s
  8450K .......... .......... .......... .......... .......... 28% 9.02M 2s
  8500K .......... .......... .......... .......... .......... 28% 15.3M 2s
  8550K .......... .......... .......... .......... .......... 28% 14.7M 2s
  8600K .......... .......... .......... .......... .......... 28% 12.2M 2s
  8650K .......... .......... .......... .......... .......... 29% 13.1M 2s
  8700K .......... .......... .......... .......... .......... 29% 11.3M 2s
  8750K .......... .......... .......... .......... .......... 29% 12.8M 2s
  8800K .......... .......... .......... .......... .......... 29% 12.7M 2s
  8850K .......... .......... .......... .......... .......... 29% 13.7M 2s
  8900K .......... .......... .......... .......... .......... 29% 13.0M 2s
  8950K .......... .......... .......... .......... .......... 30% 22.3M 2s
  9000K .......... .......... .......... .......... .......... 30% 8.47M 2s
  9050K .......... .......... .......... .......... .......... 30% 25.1M 2s
  9100K .......... .......... .......... .......... .......... 30% 11.8M 2s
  9150K .......... .......... .......... .......... .......... 30% 7.88M 2s
  9200K .......... .......... .......... .......... .......... 30% 13.8M 2s
  9250K .......... .......... .......... .......... .......... 31% 12.0M 2s
  9300K .......... .......... .......... .......... .......... 31% 29.7M 2s
  9350K .......... .......... .......... .......... .......... 31% 13.6M 2s
  9400K .......... .......... .......... .......... .......... 31% 12.4M 2s
  9450K .......... .......... .......... .......... .......... 31% 12.5M 2s
  9500K .......... .......... .......... .......... .......... 31% 10.3M 2s
  9550K .......... .......... .......... .......... .......... 32% 11.2M 2s
  9600K .......... .......... .......... .......... .......... 32% 10.4M 2s
  9650K .......... .......... .......... .......... .......... 32% 13.0M 2s
  9700K .......... .......... .......... .......... .......... 32% 16.5M 2s
  9750K .......... .......... .......... .......... .......... 32% 18.3M 2s
  9800K .......... .......... .......... .......... .......... 32% 12.6M 2s
  9850K .......... .......... .......... .......... .......... 33% 11.2M 2s
  9900K .......... .......... .......... .......... .......... 33% 11.8M 2s
  9950K .......... .......... .......... .......... .......... 33% 11.6M 2s
 10000K .......... .......... .......... .......... .......... 33% 13.2M 2s
 10050K .......... .......... .......... .......... .......... 33% 11.9M 2s
 10100K .......... .......... .......... .......... .......... 33% 10.9M 2s
 10150K .......... .......... .......... .......... .......... 34% 18.4M 2s
 10200K .......... .......... .......... .......... .......... 34% 10.3M 2s
 10250K .......... .......... .......... .......... .......... 34% 19.9M 2s
 10300K .......... .......... .......... .......... .......... 34% 12.2M 2s
 10350K .......... .......... .......... .......... .......... 34% 14.3M 2s
 10400K .......... .......... .......... .......... .......... 34% 12.5M 2s
 10450K .......... .......... .......... .......... .......... 35% 13.8M 2s
 10500K .......... .......... .......... .......... .......... 35% 13.2M 2s
 10550K .......... .......... .......... .......... .......... 35% 9.52M 2s
 10600K .......... .......... .......... .......... .......... 35% 17.0M 2s
 10650K .......... .......... .......... .......... .......... 35% 10.7M 2s
 10700K .......... .......... .......... .......... .......... 35% 13.5M 2s
 10750K .......... .......... .......... .......... .......... 36% 14.3M 2s
 10800K .......... .......... .......... .......... .......... 36% 9.14M 2s
 10850K .......... .......... .......... .......... .......... 36% 10.9M 2s
 10900K .......... .......... .......... .......... .......... 36% 23.7M 2s
 10950K .......... .......... .......... .......... .......... 36% 11.4M 2s
 11000K .......... .......... .......... .......... .......... 36% 14.5M 2s
 11050K .......... .......... .......... .......... .......... 37% 13.4M 2s
 11100K .......... .......... .......... .......... .......... 37% 10.9M 2s
 11150K .......... .......... .......... .......... .......... 37% 13.6M 2s
 11200K .......... .......... .......... .......... .......... 37% 11.7M 2s
 11250K .......... .......... .......... .......... .......... 37% 19.7M 2s
 11300K .......... .......... .......... .......... .......... 37% 9.41M 2s
 11350K .......... .......... .......... .......... .......... 38% 12.7M 2s
 11400K .......... .......... .......... .......... .......... 38% 18.7M 2s
 11450K .......... .......... .......... .......... .......... 38% 10.4M 2s
 11500K .......... .......... .......... .......... .......... 38% 13.2M 2s
 11550K .......... .......... .......... .......... .......... 38% 13.3M 2s

Downloading atb.assembly.r0.2.batch.32.tar.xz from https://osf.io/download/667145346b6c8e33f404cfdd/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667145346b6c8e33f404cfdd [following]
--2026-09-06 18:51:52--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667145346b6c8e33f404cfdd
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/e9639a807df27b614e198cd4d761d97dd5f7dc14d9b9cc921979421c7c3d353c?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.32.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.32.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713573&Signature=qQEfsZn9Zg89A88zmLqSZILQKqKIgZBUTYZkXDim5UASURjR%2FQxMmHFU7x6aZ%2FlcbGAUF02%2FUB1F2o7lGo3CD9GmFvBxkRqfLAermY6hH6ZFtkOpJn%2B9EmuGedxArGvZn3JGGRmDsMvbCgo0rAucpTJ1bzBZOwAMmrAqze038x5cZvsMDN21VGHJiyPVAeUtvOoDCKtvBAojVdChkQmDSV1f9ORXtKdYw6GG%2B3nHg92KxZYYA84ZpZPtAy55tkIuGEwQgLv7%2Fyj%2BpkCsd0vesTydl%2BQ3lsijx9r6ox7yA%2Flql03y4GZjzFSqnwfLd6jdMdE8KyJJQKVKTBu44MJhBg%3D%3D [following]
--2026-09-06 18:51:53--  https://storage.googleapis.com/cos-osf-prod-files-de-1/e9639a807df27b614e198cd4d761d97dd5f7dc14d9b9cc921979421c7c3d353c?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.32.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.32.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713573&Signature=qQEfsZn9Zg89A88zmLqSZILQKqKIgZBUTYZkXDim5UASURjR%2FQxMmHFU7x6aZ%2FlcbGAUF02%2FUB1F2o7lGo3CD9GmFvBxkRqfLAermY6hH6ZFtkOpJn%2B9EmuGedxArGvZn3JGGRmDsMvbCgo0rAucpTJ1bzBZOwAMmrAqze038x5cZvsMDN21VGHJiyPVAeUtvOoDCKtvBAojVdChkQmDSV1f9ORXtKdYw6GG%2B3nHg92KxZYYA84ZpZPtAy55tkIuGEwQgLv7%2Fyj%2BpkCsd0vesTydl%2BQ3lsijx9r6ox7yA%2Flql03y4GZjzFSqnwfLd6jdMdE8KyJJQKVKTBu44MJhBg%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38979376 (37M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.32.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.39M 27s
    50K .......... .......... .......... .......... ..........  0% 2.43M 21s
   100K .......... .......... .......... .......... ..........  0% 4.88M 16s
   150K .......... .......... .......... .......... ..........  0% 3.98M 15s
   200K .......... .......... .......... .......... ..........  0% 12.8M 12s
   250K .......... .......... .......... .......... ..........  0% 9.78M 11s
   300K .......... .......... .......... .......... ..........  0% 5.36M 10s
   350K .......... .......... .......... .......... ..........  1% 12.1M 9s
   400K .......... .......... .......... .......... ..........  1% 16.8M 9s
   450K .......... .......... .......... .......... ..........  1% 13.8M 8s
   500K .......... .......... .......... .......... ..........  1% 13.5M 7s
   550K .......... .......... .......... .......... ..........  1% 15.1M 7s
   600K .......... .......... .......... .......... ..........  1% 12.0M 7s
   650K .......... .......... .......... .......... ..........  1% 9.82M 7s
   700K .......... .......... .......... .......... ..........  1% 18.3M 6s
   750K .......... .......... .......... .......... ..........  2% 10.5M 6s
   800K .......... .......... .......... .......... ..........  2% 13.3M 6s
   850K .......... .......... .......... .......... ..........  2% 14.3M 6s
   900K .......... .......... .......... .......... ..........  2% 11.3M 5s
   950K .......... .......... .......... .......... ..........  2% 11.8M 5s
  1000K .......... .......... .......... .......... ..........  2% 9.52M 5s
  1050K .......... .......... .......... .......... ..........  2% 24.9M 5s
  1100K .......... .......... .......... .......... ..........  3% 16.0M 5s
  1150K .......... .......... .......... .......... ..........  3% 7.54M 5s
  1200K .......... .......... .......... .......... ..........  3% 11.2M 5s
  1250K .......... .......... .......... .......... ..........  3% 13.1M 5s
  1300K .......... .......... .......... .......... ..........  3% 24.0M 5s
  1350K .......... .......... .......... .......... ..........  3% 10.4M 5s
  1400K .......... .......... .......... .......... ..........  3% 10.6M 5s
  1450K .......... .......... .......... .......... ..........  3% 16.9M 4s
  1500K .......... .......... .......... .......... ..........  4% 17.8M 4s
  1550K .......... .......... .......... .......... ..........  4% 7.86M 4s
  1600K .......... .......... .......... .......... ..........  4% 22.6M 4s
  1650K .......... .......... .......... .......... ..........  4% 10.0M 4s
  1700K .......... .......... .......... .......... ..........  4% 25.2M 4s
  1750K .......... .......... .......... .......... ..........  4% 12.7M 4s
  1800K .......... .......... .......... .......... ..........  4% 17.5M 4s
  1850K .......... .......... .......... .......... ..........  4% 12.8M 4s
  1900K .......... .......... .......... .......... ..........  5% 9.84M 4s
  1950K .......... .......... .......... .......... ..........  5% 9.82M 4s
  2000K .......... .......... .......... .......... ..........  5% 21.9M 4s
  2050K .......... .......... .......... .......... ..........  5% 9.44M 4s
  2100K .......... .......... .......... .......... ..........  5% 14.3M 4s
  2150K .......... .......... .......... .......... ..........  5% 10.9M 4s
  2200K .......... .......... .......... .......... ..........  5% 18.1M 4s
  2250K .......... .......... .......... .......... ..........  6% 10.8M 4s
  2300K .......... .......... .......... .......... ..........  6% 16.3M 4s
  2350K .......... .......... .......... .......... ..........  6% 7.52M 4s
  2400K .......... .......... .......... .......... ..........  6% 19.8M 4s
  2450K .......... .......... .......... .......... ..........  6% 10.2M 4s
  2500K .......... .......... .......... .......... ..........  6% 29.9M 4s
  2550K .......... .......... .......... .......... ..........  6% 12.7M 4s
  2600K .......... .......... .......... .......... ..........  6% 8.58M 4s
  2650K .......... .......... .......... .......... ..........  7% 76.1M 4s
  2700K .......... .......... .......... .......... ..........  7% 9.58M 4s
  2750K .......... .......... .......... .......... ..........  7% 10.5M 4s
  2800K .......... .......... .......... .......... ..........  7% 14.2M 4s
  2850K .......... .......... .......... .......... ..........  7% 10.4M 4s
  2900K .......... .......... .......... .......... ..........  7% 10.9M 4s
  2950K .......... .......... .......... .......... ..........  7% 17.0M 3s
  3000K .......... .......... .......... .......... ..........  8% 12.7M 3s
  3050K .......... .......... .......... .......... ..........  8% 32.6M 3s
  3100K .......... .......... .......... .......... ..........  8% 7.87M 3s
  3150K .......... .......... .......... .......... ..........  8% 13.8M 3s
  3200K .......... .......... .......... .......... ..........  8% 13.9M 3s
  3250K .......... .......... .......... .......... ..........  8% 18.3M 3s
  3300K .......... .......... .......... .......... ..........  8% 11.6M 3s
  3350K .......... .......... .......... .......... ..........  8% 12.9M 3s
  3400K .......... .......... .......... .......... ..........  9% 15.1M 3s
  3450K .......... .......... .......... .......... ..........  9% 12.2M 3s
  3500K .......... .......... .......... .......... ..........  9% 9.40M 3s
  3550K .......... .......... .......... .......... ..........  9% 11.9M 3s
  3600K .......... .......... .......... .......... ..........  9% 14.4M 3s
  3650K .......... .......... .......... .......... ..........  9% 13.5M 3s
  3700K .......... .......... .......... .......... ..........  9% 11.9M 3s
  3750K .......... .......... .......... .......... ..........  9% 19.9M 3s
  3800K .......... .......... .......... .......... .......... 10% 8.64M 3s
  3850K .......... .......... .......... .......... .......... 10% 15.4M 3s
  3900K .......... .......... .......... .......... .......... 10% 13.3M 3s
  3950K .......... .......... .......... .......... .......... 10% 8.98M 3s
  4000K .......... .......... .......... .......... .......... 10% 32.3M 3s
  4050K .......... .......... .......... .......... .......... 10% 9.90M 3s
  4100K .......... .......... .......... .......... .......... 10% 18.5M 3s
  4150K .......... .......... .......... .......... .......... 11% 11.8M 3s
  4200K .......... .......... .......... .......... .......... 11% 9.94M 3s
  4250K .......... .......... .......... .......... .......... 11% 18.0M 3s
  4300K .......... .......... .......... .......... .......... 11% 10.2M 3s
  4350K .......... .......... .......... .......... .......... 11% 14.7M 3s
  4400K .......... .......... .......... .......... .......... 11% 10.2M 3s
  4450K .......... .......... .......... .......... .......... 11% 8.25M 3s
  4500K .......... .......... .......... .......... .......... 11%  165M 3s
  4550K .......... .......... .......... .......... .......... 12% 15.5M 3s
  4600K .......... .......... .......... .......... .......... 12% 9.07M 3s
  4650K .......... .......... .......... .......... .......... 12% 23.1M 3s
  4700K .......... .......... .......... .......... .......... 12% 10.9M 3s
  4750K .......... .......... .......... .......... .......... 12% 12.8M 3s
  4800K .......... .......... .......... .......... .......... 12% 9.23M 3s
  4850K .......... .......... .......... .......... .......... 12% 14.4M 3s
  4900K .......... .......... .......... .......... .......... 13% 13.7M 3s
  4950K .......... .......... .......... .......... .......... 13% 12.7M 3s
  5000K .......... .......... .......... .......... .......... 13% 12.7M 3s
  5050K .......... .......... .......... .......... .......... 13% 10.7M 3s
  5100K .......... .......... .......... .......... .......... 13% 18.8M 3s
  5150K .......... .......... .......... .......... .......... 13% 12.4M 3s
  5200K .......... .......... .......... .......... .......... 13% 10.4M 3s
  5250K .......... .......... .......... .......... .......... 13% 8.21M 3s
  5300K .......... .......... .......... .......... .......... 14% 20.0M 3s
  5350K .......... .......... .......... .......... .......... 14% 15.4M 3s
  5400K .......... .......... .......... .......... .......... 14% 17.0M 3s
  5450K .......... .......... .......... .......... .......... 14% 17.6M 3s
  5500K .......... .......... .......... .......... .......... 14% 9.16M 3s
  5550K .......... .......... .......... .......... .......... 14% 13.0M 3s
  5600K .......... .......... .......... .......... .......... 14% 14.8M 3s
  5650K .......... .......... .......... .......... .......... 14% 12.0M 3s
  5700K .......... .......... .......... .......... .......... 15% 11.5M 3s
  5750K .......... .......... .......... .......... .......... 15% 21.4M 3s
  5800K .......... .......... .......... .......... .......... 15% 8.35M 3s
  5850K .......... .......... .......... .......... .......... 15% 9.70M 3s
  5900K .......... .......... .......... .......... .......... 15%  157M 3s
  5950K .......... .......... .......... .......... .......... 15% 8.12M 3s
  6000K .......... .......... .......... .......... .......... 15% 14.4M 3s
  6050K .......... .......... .......... .......... .......... 16% 15.2M 3s
  6100K .......... .......... .......... .......... .......... 16% 9.23M 3s
  6150K .......... .......... .......... .......... .......... 16% 24.7M 3s
  6200K .......... .......... .......... .......... .......... 16% 8.36M 3s
  6250K .......... .......... .......... .......... .......... 16% 26.5M 3s
  6300K .......... .......... .......... .......... .......... 16% 11.0M 3s
  6350K .......... .......... .......... .......... .......... 16% 10.7M 3s
  6400K .......... .......... .......... .......... .......... 16% 15.5M 3s
  6450K .......... .......... .......... .......... .......... 17% 11.8M 3s
  6500K .......... .......... .......... .......... .......... 17% 14.1M 3s
  6550K .......... .......... .......... .......... .......... 17% 9.23M 3s
  6600K .......... .......... .......... .......... .......... 17% 15.7M 3s
  6650K .......... .......... .......... .......... .......... 17% 15.1M 3s
  6700K .......... .......... .......... .......... .......... 17% 16.8M 3s
  6750K .......... .......... .......... .......... .......... 17% 9.98M 3s
  6800K .......... .......... .......... .......... .......... 17% 12.4M 3s
  6850K .......... .......... .......... .......... .......... 18% 19.8M 3s
  6900K .......... .......... .......... .......... .......... 18% 12.5M 3s
  6950K .......... .......... .......... .......... .......... 18% 12.2M 3s
  7000K .......... .......... .......... .......... .......... 18% 10.1M 3s
  7050K .......... .......... .......... .......... .......... 18% 12.5M 3s
  7100K .......... .......... .......... .......... .......... 18% 19.8M 3s
  7150K .......... .......... .......... .......... .......... 18% 9.28M 3s
  7200K .......... .......... .......... .......... .......... 19% 13.3M 3s
  7250K .......... .......... .......... .......... .......... 19% 12.7M 3s
  7300K .......... .......... .......... .......... .......... 19% 10.6M 3s
  7350K .......... .......... .......... .......... .......... 19% 20.2M 3s
  7400K .......... .......... .......... .......... .......... 19% 15.9M 3s
  7450K .......... .......... .......... .......... .......... 19% 9.92M 3s
  7500K .......... .......... .......... .......... .......... 19% 14.9M 3s
  7550K .......... .......... .......... .......... .......... 19% 8.27M 3s
  7600K .......... .......... .......... .......... .......... 20% 37.0M 3s
  7650K .......... .......... .......... .......... .......... 20% 10.7M 3s
  7700K .......... .......... .......... .......... .......... 20% 15.7M 3s
  7750K .......... .......... .......... .......... .......... 20% 10.2M 3s
  7800K .......... .......... .......... .......... .......... 20% 8.80M 3s
  7850K .......... .......... .......... .......... .......... 20% 40.2M 3s
  7900K .......... .......... .......... .......... .......... 20% 14.2M 3s
  7950K .......... .......... .......... .......... .......... 21% 8.48M 3s
  8000K .......... .......... .......... .......... .......... 21% 13.3M 3s
  8050K .......... .......... .......... .......... .......... 21% 16.9M 3s
  8100K .......... .......... .......... .......... .......... 21% 9.85M 3s
  8150K .......... .......... .......... .......... .......... 21% 9.08M 3s
  8200K .......... .......... .......... .......... .......... 21% 15.0M 3s
  8250K .......... .......... .......... .......... .......... 21% 24.9M 3s
  8300K .......... .......... .......... .......... .......... 21% 13.1M 3s
  8350K .......... .......... .......... .......... .......... 22% 17.4M 3s
  8400K .......... .......... .......... .......... .......... 22% 8.25M 3s
  8450K .......... .......... .......... .......... .......... 22% 14.5M 2s
  8500K .......... .......... .......... .......... .......... 22% 15.3M 2s
  8550K .......... .......... .......... .......... .......... 22% 14.3M 2s
  8600K .......... .......... .......... .......... .......... 22% 8.81M 2s
  8650K .......... .......... .......... .......... .......... 22% 15.1M 2s
  8700K .......... .......... .......... .......... .......... 22% 14.0M 2s
  8750K .......... .......... .......... .......... .......... 23% 14.5M 2s
  8800K .......... .......... .......... .......... .......... 23% 10.3M 2s
  8850K .......... .......... .......... .......... .......... 23% 15.3M 2s
  8900K .......... .......... .......... .......... .......... 23% 14.6M 2s
  8950K .......... .......... .......... .......... .......... 23% 10.7M 2s
  9000K .......... .......... .......... .......... .......... 23% 14.9M 2s
  9050K .......... .......... .......... .......... .......... 23% 10.6M 2s
  9100K .......... .......... .......... .......... .......... 24% 20.7M 2s
  9150K .......... .......... .......... .......... .......... 24% 7.19M 2s
  9200K .......... .......... .......... .......... .......... 24% 25.1M 2s
  9250K .......... .......... .......... .......... .......... 24% 14.0M 2s
  9300K .......... .......... .......... .......... .......... 24% 9.47M 2s
  9350K .......... .......... .......... .......... .......... 24% 34.6M 2s
  9400K .......... .......... .......... .......... .......... 24% 11.2M 2s
  9450K .......... .......... .......... .......... .......... 24% 12.2M 2s
  9500K .......... .......... .......... .......... .......... 25% 8.87M 2s
  9550K .......... .......... .......... .......... .......... 25% 13.3M 2s
  9600K .......... .......... .......... .......... .......... 25% 12.4M 2s
  9650K .......... .......... .......... .......... .......... 25% 20.0M 2s
  9700K .......... .......... .......... .......... .......... 25% 9.70M 2s
  9750K .......... .......... .......... .......... .......... 25% 16.6M 2s
  9800K .......... .......... .......... .......... .......... 25% 12.7M 2s
  9850K .......... .......... .......... .......... .......... 26% 13.8M 2s
  9900K .......... .......... .......... .......... .......... 26% 15.4M 2s
  9950K .......... .......... .......... .......... .......... 26% 10.0M 2s
 10000K .......... .......... .......... .......... .......... 26% 10.8M 2s
 10050K .......... .......... .......... .......... .......... 26% 21.4M 2s
 10100K .......... .......... .......... .......... .......... 26% 13.6M 2s
 10150K .......... .......... .......... .......... .......... 26% 9.59M 2s
 10200K .......... .......... .......... .......... .......... 26% 11.0M 2s
 10250K .......... .......... .......... .......... .......... 27% 22.5M 2s
 10300K .......... .......... .......... .......... .......... 27% 7.97M 2s
 10350K .......... .......... .......... .......... .......... 27% 14.8M 2s
 10400K .......... .......... .......... .......... .......... 27% 14.0M 2s
 10450K .......... .......... .......... .......... .......... 27% 15.7M 2s
 10500K .......... .......... .......... .......... .......... 27% 13.0M 2s
 10550K .......... .......... .......... .......... .......... 27% 2.51M 2s
 10600K .......... .......... .......... .......... .......... 27% 98.0M 2s
 10650K .......... .......... .......... .......... .......... 28%  788M 2s
 10700K .......... .......... .......... .......... .......... 28%  136M 2s
 10750K .......... .......... .......... .......... .......... 28%  198M 2s
 10800K .......... .......... .......... .......... .......... 28% 23.8M 2s
 10850K .......... .......... .......... .......... .......... 28% 13.1M 2s
 10900K .......... .......... .......... .......... .......... 28% 7.17M 2s
 10950K .......... .......... .......... .......... .......... 28% 19.2M 2s
 11000K .......... .......... .......... .......... .......... 29% 33.7M 2s
 11050K .......... .......... .......... .......... .......... 29% 10.7M 2s
 11100K .......... .......... .......... .......... .......... 29% 17.2M 2s
 11150K .......... .......... .......... .......... .......... 29% 8.55M 2s
 11200K .......... .......... .......... .......... .......... 29% 12.6M 2s
 11250K .......... .......... .......... .......... .......... 29% 8.21M 2s
 11300K .......... .......... .......... .......... .......... 29%  104M 2s
 11350K .......... .......... .......... .......... .......... 29% 12.1M 2s
 11400K .......... .......... .......... .......... .......... 30% 11.9M 2s
 11450K .......... .......... .......... .......... .......... 30% 15.3M 2s
 11500K .......... .......... .......... .......... .......... 30% 15.3M 2s
 11550K .......... .......... .......... .......... .......... 30% 9.93M 2s

Downloading atb.assembly.r0.2.batch.33.tar.xz from https://osf.io/download/667145380f8c8017b73c913f/

connected.
HTTP request sent, awaiting response... 302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667145380f8c8017b73c913f [following]
--2026-09-06 18:51:56--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667145380f8c8017b73c913f
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/4d7b9d5e6f9c8db3932086c1497ec7e563746df19c217b5e9c0aebb590b9bd29?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.33.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.33.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713577&Signature=SwcfcHeIYlHoGW4L4AfpYSIFc8KwtB8p2mLxE6UxFkobKB4PdHTk21VF4nKAfUhMV8N6BzOcQcks5RSb%2FqYpqbp9Z6xJ6pJDPALnZXqHZBlPjQoQkHH1t7DgwkLqTSZ5tSHUAYGfPgFzNdcAW9vjdqtBpRrrq1xmUJVtWCfFlFTPj7w99tmAQ8TmnIWKHJZzaPgcZzknn4nt9BBaSvgnPI6FZGeSUGZaYJv%2FlyRlCveUgcKaSN23PHLQQYJ0miN1pBEEuemdyhqpYbzNAjw8bEgomtr9ZUrqHbO16plo%2FUNGSuicRKyCHQlI80HLA%2BjAfcmJ4emQjlEjzunRJh%2FqyA%3D%3D [following]
--2026-09-06 18:51:57--  https://storage.googleapis.com/cos-osf-prod-files-de-1/4d7b9d5e6f9c8db3932086c1497ec7e563746df19c217b5e9c0aebb590b9bd29?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.33.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.33.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713577&Signature=SwcfcHeIYlHoGW4L4AfpYSIFc8KwtB8p2mLxE6UxFkobKB4PdHTk21VF4nKAfUhMV8N6BzOcQcks5RSb%2FqYpqbp9Z6xJ6pJDPALnZXqHZBlPjQoQkHH1t7DgwkLqTSZ5tSHUAYGfPgFzNdcAW9vjdqtBpRrrq1xmUJVtWCfFlFTPj7w99tmAQ8TmnIWKHJZzaPgcZzknn4nt9BBaSvgnPI6FZGeSUGZaYJv%2FlyRlCveUgcKaSN23PHLQQYJ0miN1pBEEuemdyhqpYbzNAjw8bEgomtr9ZUrqHbO16plo%2FUNGSuicRKyCHQlI80HLA%2BjAfcmJ4emQjlEjzunRJh%2FqyA%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43732216 (42M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.33.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.29M 32s
    50K .......... .......... .......... .......... ..........  0% 2.36M 25s
   100K .......... .......... .......... .......... ..........  0% 3.66M 20s
   150K .......... .......... .......... .......... ..........  0% 4.56M 18s
   200K .......... .......... .......... .......... ..........  0% 10.9M 15s
   250K .......... .......... .......... .......... ..........  0% 10.3M 13s
   300K .......... .......... .......... .......... ..........  0% 4.77M 12s
   350K .......... .......... .......... .......... ..........  0% 5.56M 12s
   400K .......... .......... .......... .......... ..........  1% 14.6M 11s
   450K .......... .......... .......... .......... ..........  1% 9.42M 10s
   500K .......... .......... .......... .......... ..........  1% 14.1M 9s
   550K .......... .......... .......... .......... ..........  1% 15.5M 9s
   600K .......... .......... .......... .......... ..........  1% 12.2M 8s
   650K .......... .......... .......... .......... ..........  1% 14.7M 8s
   700K .......... .......... .......... .......... ..........  1% 15.0M 8s
   750K .......... .......... .......... .......... ..........  1% 12.8M 7s
   800K .......... .......... .......... .......... ..........  1% 10.4M 7s
   850K .......... .......... .......... .......... ..........  2% 11.5M 7s
   900K .......... .......... .......... .......... ..........  2% 20.1M 7s
   950K .......... .......... .......... .......... ..........  2% 12.5M 6s
  1000K .......... .......... .......... .......... ..........  2% 10.0M 6s
  1050K .......... .......... .......... .......... ..........  2% 12.7M 6s
  1100K .......... .......... .......... .......... ..........  2% 11.1M 6s
  1150K .......... .......... .......... .......... ..........  2% 11.1M 6s
  1200K .......... .......... .......... .......... ..........  2% 14.7M 6s
  1250K .......... .......... .......... .......... ..........  3% 9.00M 6s
  1300K .......... .......... .......... .......... ..........  3% 31.9M 6s
  1350K .......... .......... .......... .......... ..........  3% 17.9M 5s
  1400K .......... .......... .......... .......... ..........  3% 8.46M 5s
  1450K .......... .......... .......... .......... ..........  3% 27.0M 5s
  1500K .......... .......... .......... .......... ..........  3% 14.0M 5s
  1550K .......... .......... .......... .......... ..........  3% 2.77M 6s
  1600K .......... .......... .......... .......... ..........  3%  186M 5s
  1650K .......... .......... .......... .......... ..........  3%  292M 5s
  1700K .......... .......... .......... .......... ..........  4% 50.0M 5s
  1750K .......... .......... .......... .......... ..........  4% 32.2M 5s
  1800K .......... .......... .......... .......... ..........  4% 12.5M 5s
  1850K .......... .......... .......... .......... ..........  4% 12.6M 5s
  1900K .......... .......... .......... .......... ..........  4% 21.9M 5s
  1950K .......... .......... .......... .......... ..........  4% 7.60M 5s
  2000K .......... .......... .......... .......... ..........  4% 14.5M 5s
  2050K .......... .......... .......... .......... ..........  4% 15.6M 5s
  2100K .......... .......... .......... .......... ..........  5% 10.9M 5s
  2150K .......... .......... .......... .......... ..........  5% 18.0M 5s
  2200K .......... .......... .......... .......... ..........  5% 13.0M 5s
  2250K .......... .......... .......... .......... ..........  5% 19.2M 4s
  2300K .......... .......... .......... .......... ..........  5% 8.43M 4s
  2350K .......... .......... .......... .......... ..........  5% 11.8M 4s
  2400K .......... .......... .......... .......... ..........  5% 13.6M 4s
  2450K .......... .......... .......... .......... ..........  5% 13.8M 4s
  2500K .......... .......... .......... .......... ..........  5% 9.77M 4s
  2550K .......... .......... .......... .......... ..........  6% 19.6M 4s
  2600K .......... .......... .......... .......... ..........  6% 9.95M 4s
  2650K .......... .......... .......... .......... ..........  6% 13.9M 4s
  2700K .......... .......... .......... .......... ..........  6% 32.5M 4s
  2750K .......... .......... .......... .......... ..........  6% 9.50M 4s
  2800K .......... .......... .......... .......... ..........  6% 11.6M 4s
  2850K .......... .......... .......... .......... ..........  6% 12.8M 4s
  2900K .......... .......... .......... .......... ..........  6% 10.8M 4s
  2950K .......... .......... .......... .......... ..........  7% 12.9M 4s
  3000K .......... .......... .......... .......... ..........  7% 10.2M 4s
  3050K .......... .......... .......... .......... ..........  7% 22.6M 4s
  3100K .......... .......... .......... .......... ..........  7% 14.0M 4s
  3150K .......... .......... .......... .......... ..........  7% 11.1M 4s
  3200K .......... .......... .......... .......... ..........  7% 9.46M 4s
  3250K .......... .......... .......... .......... ..........  7% 18.6M 4s
  3300K .......... .......... .......... .......... ..........  7% 9.73M 4s
  3350K .......... .......... .......... .......... ..........  7% 33.8M 4s
  3400K .......... .......... .......... .......... ..........  8% 11.2M 4s
  3450K .......... .......... .......... .......... ..........  8% 18.5M 4s
  3500K .......... .......... .......... .......... ..........  8% 12.8M 4s
  3550K .......... .......... .......... .......... ..........  8% 9.72M 4s
  3600K .......... .......... .......... .......... ..........  8% 11.6M 4s
  3650K .......... .......... .......... .......... ..........  8% 16.3M 4s
  3700K .......... .......... .......... .......... ..........  8% 13.2M 4s
  3750K .......... .......... .......... .......... ..........  8% 10.3M 4s
  3800K .......... .......... .......... .......... ..........  9% 14.6M 4s
  3850K .......... .......... .......... .......... ..........  9% 12.4M 4s
  3900K .......... .......... .......... .......... ..........  9% 21.5M 4s
  3950K .......... .......... .......... .......... ..........  9% 6.32M 4s
  4000K .......... .......... .......... .......... ..........  9% 41.8M 4s
  4050K .......... .......... .......... .......... ..........  9% 12.8M 4s
  4100K .......... .......... .......... .......... ..........  9% 10.1M 4s
  4150K .......... .......... .......... .......... ..........  9% 15.9M 4s
  4200K .......... .......... .......... .......... ..........  9% 11.1M 4s
  4250K .......... .......... .......... .......... .......... 10% 9.85M 4s
  4300K .......... .......... .......... .......... .......... 10% 24.3M 4s
  4350K .......... .......... .......... .......... .......... 10% 8.65M 4s
  4400K .......... .......... .......... .......... .......... 10% 12.3M 4s
  4450K .......... .......... .......... .......... .......... 10% 18.3M 4s
  4500K .......... .......... .......... .......... .......... 10% 12.3M 4s
  4550K .......... .......... .......... .......... .......... 10% 22.2M 4s
  4600K .......... .......... .......... .......... .......... 10% 12.7M 4s
  4650K .......... .......... .......... .......... .......... 11% 8.38M 4s
  4700K .......... .......... .......... .......... .......... 11% 19.2M 4s
  4750K .......... .......... .......... .......... .......... 11% 9.31M 4s
  4800K .......... .......... .......... .......... .......... 11% 15.9M 4s
  4850K .......... .......... .......... .......... .......... 11% 12.0M 4s
  4900K .......... .......... .......... .......... .......... 11% 14.5M 3s
  4950K .......... .......... .......... .......... .......... 11% 13.8M 3s
  5000K .......... .......... .......... .......... .......... 11% 10.8M 3s
  5050K .......... .......... .......... .......... .......... 11% 17.6M 3s
  5100K .......... .......... .......... .......... .......... 12% 13.4M 3s
  5150K .......... .......... .......... .......... .......... 12% 12.1M 3s
  5200K .......... .......... .......... .......... .......... 12% 8.07M 3s
  5250K .......... .......... .......... .......... .......... 12% 28.3M 3s
  5300K .......... .......... .......... .......... .......... 12% 8.23M 3s
  5350K .......... .......... .......... .......... .......... 12% 12.7M 3s
  5400K .......... .......... .......... .......... .......... 12% 19.9M 3s
  5450K .......... .......... .......... .......... .......... 12% 14.8M 3s
  5500K .......... .......... .......... .......... .......... 12% 11.1M 3s
  5550K .......... .......... .......... .......... .......... 13% 8.60M 3s
  5600K .......... .......... .......... .......... .......... 13% 22.4M 3s
  5650K .......... .......... .......... .......... .......... 13% 10.6M 3s
  5700K .......... .......... .......... .......... .......... 13% 17.7M 3s
  5750K .......... .......... .......... .......... .......... 13% 10.7M 3s
  5800K .......... .......... .......... .......... .......... 13% 20.0M 3s
  5850K .......... .......... .......... .......... .......... 13% 8.74M 3s
  5900K .......... .......... .......... .......... .......... 13% 12.8M 3s
  5950K .......... .......... .......... .......... .......... 14% 11.7M 3s
  6000K .......... .......... .......... .......... .......... 14% 21.1M 3s
  6050K .......... .......... .......... .......... .......... 14% 16.2M 3s
  6100K .......... .......... .......... .......... .......... 14% 10.4M 3s
  6150K .......... .......... .......... .......... .......... 14% 11.7M 3s
  6200K .......... .......... .......... .......... .......... 14% 14.5M 3s
  6250K .......... .......... .......... .......... .......... 14% 13.8M 3s
  6300K .......... .......... .......... .......... .......... 14% 10.7M 3s
  6350K .......... .......... .......... .......... .......... 14% 18.0M 3s
  6400K .......... .......... .......... .......... .......... 15% 2.64M 3s
  6450K .......... .......... .......... .......... .......... 15% 74.1M 3s
  6500K .......... .......... .......... .......... .......... 15%  157M 3s
  6550K .......... .......... .......... .......... .......... 15%  147M 3s
  6600K .......... .......... .......... .......... .......... 15% 26.6M 3s
  6650K .......... .......... .......... .......... .......... 15% 32.5M 3s
  6700K .......... .......... .......... .......... .......... 15% 11.3M 3s
  6750K .......... .......... .......... .......... .......... 15% 8.93M 3s
  6800K .......... .......... .......... .......... .......... 16% 8.97M 3s
  6850K .......... .......... .......... .......... .......... 16% 30.6M 3s
  6900K .......... .......... .......... .......... .......... 16% 12.6M 3s
  6950K .......... .......... .......... .......... .......... 16% 25.4M 3s
  7000K .......... .......... .......... .......... .......... 16% 9.81M 3s
  7050K .......... .......... .......... .......... .......... 16% 8.37M 3s
  7100K .......... .......... .......... .......... .......... 16%  171M 3s
  7150K .......... .......... .......... .......... .......... 16% 9.40M 3s
  7200K .......... .......... .......... .......... .......... 16% 14.6M 3s
  7250K .......... .......... .......... .......... .......... 17% 11.9M 3s
  7300K .......... .......... .......... .......... .......... 17% 15.9M 3s
  7350K .......... .......... .......... .......... .......... 17% 11.7M 3s
  7400K .......... .......... .......... .......... .......... 17% 11.8M 3s
  7450K .......... .......... .......... .......... .......... 17% 15.3M 3s
  7500K .......... .......... .......... .......... .......... 17% 10.5M 3s
  7550K .......... .......... .......... .......... .......... 17% 11.6M 3s
  7600K .......... .......... .......... .......... .......... 17% 11.5M 3s
  7650K .......... .......... .......... .......... .......... 18% 25.9M 3s
  7700K .......... .......... .......... .......... .......... 18% 11.5M 3s
  7750K .......... .......... .......... .......... .......... 18% 12.3M 3s
  7800K .......... .......... .......... .......... .......... 18% 14.2M 3s
  7850K .......... .......... .......... .......... .......... 18% 13.1M 3s
  7900K .......... .......... .......... .......... .......... 18% 14.0M 3s
  7950K .......... .......... .......... .......... .......... 18% 9.12M 3s
  8000K .......... .......... .......... .......... .......... 18% 17.7M 3s
  8050K .......... .......... .......... .......... .......... 18% 13.2M 3s
  8100K .......... .......... .......... .......... .......... 19% 11.0M 3s
  8150K .......... .......... .......... .......... .......... 19% 12.0M 3s
  8200K .......... .......... .......... .......... .......... 19% 15.3M 3s
  8250K .......... .......... .......... .......... .......... 19% 14.8M 3s
  8300K .......... .......... .......... .......... .......... 19% 12.0M 3s
  8350K .......... .......... .......... .......... .......... 19% 7.15M 3s
  8400K .......... .......... .......... .......... .......... 19% 29.2M 3s
  8450K .......... .......... .......... .......... .......... 19% 8.13M 3s
  8500K .......... .......... .......... .......... .......... 20% 19.0M 3s
  8550K .......... .......... .......... .......... .......... 20% 13.3M 3s
  8600K .......... .......... .......... .......... .......... 20% 16.4M 3s
  8650K .......... .......... .......... .......... .......... 20% 12.2M 3s
  8700K .......... .......... .......... .......... .......... 20% 18.6M 3s
  8750K .......... .......... .......... .......... .......... 20% 7.77M 3s
  8800K .......... .......... .......... .......... .......... 20% 12.8M 3s
  8850K .......... .......... .......... .......... .......... 20% 17.0M 3s
  8900K .......... .......... .......... .......... .......... 20% 14.8M 3s
  8950K .......... .......... .......... .......... .......... 21% 12.6M 3s
  9000K .......... .......... .......... .......... .......... 21% 16.8M 3s
  9050K .......... .......... .......... .......... .......... 21% 14.4M 3s
  9100K .......... .......... .......... .......... .......... 21% 10.1M 3s
  9150K .......... .......... .......... .......... .......... 21% 13.0M 3s
  9200K .......... .......... .......... .......... .......... 21% 10.8M 3s
  9250K .......... .......... .......... .......... .......... 21% 11.8M 3s
  9300K .......... .......... .......... .......... .......... 21% 13.0M 3s
  9350K .......... .......... .......... .......... .......... 22% 16.5M 3s
  9400K .......... .......... .......... .......... .......... 22% 12.0M 3s
  9450K .......... .......... .......... .......... .......... 22% 11.3M 3s
  9500K .......... .......... .......... .......... .......... 22% 18.2M 3s
  9550K .......... .......... .......... .......... .......... 22% 7.68M 3s
  9600K .......... .......... .......... .......... .......... 22% 16.6M 3s
  9650K .......... .......... .......... .......... .......... 22% 15.9M 3s
  9700K .......... .......... .......... .......... .......... 22% 8.88M 3s
  9750K .......... .......... .......... .......... .......... 22% 28.5M 3s
  9800K .......... .......... .......... .......... .......... 23% 18.2M 3s
  9850K .......... .......... .......... .......... .......... 23% 9.59M 3s
  9900K .......... .......... .......... .......... .......... 23% 13.1M 3s
  9950K .......... .......... .......... .......... .......... 23% 11.0M 3s
 10000K .......... .......... .......... .......... .......... 23% 8.58M 3s
 10050K .......... .......... .......... .......... .......... 23% 26.5M 3s
 10100K .......... .......... .......... .......... .......... 23% 11.9M 3s
 10150K .......... .......... .......... .......... .......... 23% 16.3M 3s
 10200K .......... .......... .......... .......... .......... 24% 12.6M 3s
 10250K .......... .......... .......... .......... .......... 24% 10.9M 3s
 10300K .......... .......... .......... .......... .......... 24% 11.7M 3s
 10350K .......... .......... .......... .......... .......... 24% 13.3M 3s
 10400K .......... .......... .......... .......... .......... 24% 17.0M 3s
 10450K .......... .......... .......... .......... .......... 24% 10.5M 3s
 10500K .......... .......... .......... .......... .......... 24% 11.0M 3s
 10550K .......... .......... .......... .......... .......... 24% 16.9M 3s
 10600K .......... .......... .......... .......... .......... 24% 11.4M 3s
 10650K .......... .......... .......... .......... .......... 25% 12.5M 3s
 10700K .......... .......... .......... .......... .......... 25% 29.5M 3s
 10750K .......... .......... .......... .......... .......... 25% 8.80M 3s
 10800K .......... .......... .......... .......... .......... 25% 14.6M 3s
 10850K .......... .......... .......... .......... .......... 25% 9.79M 3s
 10900K .......... .......... .......... .......... .......... 25% 13.1M 3s
 10950K .......... .......... .......... .......... .......... 25% 15.4M 3s
 11000K .......... .......... .......... .......... .......... 25% 12.5M 3s
 11050K .......... .......... .......... .......... .......... 25% 11.3M 3s
 11100K .......... .......... .......... .......... .......... 26% 10.7M 3s
 11150K .......... .......... .......... .......... .......... 26% 20.6M 3s
 11200K .......... .......... .......... .......... .......... 26% 12.4M 3s
 11250K .......... .......... .......... .......... .......... 26% 11.6M 3s
 11300K .......... .......... .......... .......... .......... 26% 11.6M 3s
 11350K .......... .......... .......... .......... .......... 26% 33.0M 3s
 11400K .......... .......... .......... .......... .......... 26% 11.6M 3s
 11450K .......... .......... .......... .......... .......... 26% 11.0M 3s
 11500K .......... .......... .......... .......... .......... 27% 13.1M 3s

Downloading atb.assembly.r0.2.batch.34.tar.xz from https://osf.io/download/6671456b6b6c8e33f404d013/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671456b6b6c8e33f404d013 [following]
--2026-09-06 18:52:01--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671456b6b6c8e33f404d013
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/d53ba03b39caaddc9d01ac1f32cadfd67790ce1af45e3be4eada246a2a3fb155?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.34.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.34.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713583&Signature=QoGfm3AOm%2FYkcuTBx8Ngyp2Zjth1QZIMvr2QDx8ddOWqBhS2wKdioQPtWuiW0PG1Qg4pnW3uVbQWeO%2BrnDkXcGlGPqkIn2ZCp%2Bcegyl%2FKRvs1%2BZOmXB0%2BILzuPgjCErNKfKLkGQVKhNwTg9zi%2F8q9mdvNhNRQ1DhndXlxPxhHo6oqKIXdhXk9ZC8bZ7BGxHzr%2BgTJpq7TRVXvQU6bRKaqalVQ7yM48hFDnQt8qhXCsrjUQ0lEVYfa9cClvd%2FUSbCX5FibRFDAQCJOX0xI48wNMALzYuhDw5%2FEFOxlZ4fRYj39MbmyzZczQ02P5jdUzZ9e2m7jqluLZI%2Boexa4mhVZw%3D%3D [following]
--2026-09-06 18:52:03--  https://storage.googleapis.com/cos-osf-prod-files-de-1/d53ba03b39caaddc9d01ac1f32cadfd67790ce1af45e3be4eada246a2a3fb155?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.34.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.34.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713583&Signature=QoGfm3AOm%2FYkcuTBx8Ngyp2Zjth1QZIMvr2QDx8ddOWqBhS2wKdioQPtWuiW0PG1Qg4pnW3uVbQWeO%2BrnDkXcGlGPqkIn2ZCp%2Bcegyl%2FKRvs1%2BZOmXB0%2BILzuPgjCErNKfKLkGQVKhNwTg9zi%2F8q9mdvNhNRQ1DhndXlxPxhHo6oqKIXdhXk9ZC8bZ7BGxHzr%2BgTJpq7TRVXvQU6bRKaqalVQ7yM48hFDnQt8qhXCsrjUQ0lEVYfa9cClvd%2FUSbCX5FibRFDAQCJOX0xI48wNMALzYuhDw5%2FEFOxlZ4fRYj39MbmyzZczQ02P5jdUzZ9e2m7jqluLZI%2Boexa4mhVZw%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 133761772 (128M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.34.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.22M 1m44s
    50K .......... .......... .......... .......... ..........  0% 2.90M 74s
   100K .......... .......... .......... .......... ..........  0% 4.19M 59s
   150K .......... .......... .......... .......... ..........  0% 5.26M 51s
   200K .......... .......... .......... .......... ..........  0% 7.12M 44s
   250K .......... .......... .......... .......... ..........  0% 8.26M 39s
   300K .......... .......... .......... .......... ..........  0% 4.85M 37s
   350K .......... .......... .......... .......... ..........  0% 13.9M 34s
   400K .......... .......... .......... .......... ..........  0% 15.9M 31s
   450K .......... .......... .......... .......... ..........  0% 16.4M 29s
   500K .......... .......... .......... .......... ..........  0% 12.3M 27s
   550K .......... .......... .......... .......... ..........  0% 8.08M 26s
   600K .......... .......... .......... .......... ..........  0% 18.5M 25s
   650K .......... .......... .......... .......... ..........  0% 10.4M 24s
   700K .......... .......... .......... .......... ..........  0% 15.9M 23s
   750K .......... .......... .......... .......... ..........  0% 15.0M 22s
   800K .......... .......... .......... .......... ..........  0% 8.24M 21s
   850K .......... .......... .......... .......... ..........  0% 27.2M 20s
   900K .......... .......... .......... .......... ..........  0% 10.7M 20s
   950K .......... .......... .......... .......... ..........  0% 8.78M 20s
  1000K .......... .......... .......... .......... ..........  0% 12.8M 19s
  1050K .......... .......... .......... .......... ..........  0% 12.5M 19s
  1100K .......... .......... .......... .......... ..........  0%  128M 18s
  1150K .......... .......... .......... .......... ..........  0% 8.06M 18s
  1200K .......... .......... .......... .......... ..........  0% 11.0M 18s
  1250K .......... .......... .......... .......... ..........  0% 28.1M 17s
  1300K .......... .......... .......... .......... ..........  1% 8.97M 17s
  1350K .......... .......... .......... .......... ..........  1% 10.6M 17s
  1400K .......... .......... .......... .......... ..........  1% 35.3M 16s
  1450K .......... .......... .......... .......... ..........  1% 5.93M 16s
  1500K .......... .......... .......... .......... ..........  1% 97.1M 16s
  1550K .......... .......... .......... .......... ..........  1% 19.5M 16s
  1600K .......... .......... .......... .......... ..........  1% 12.3M 16s
  1650K .......... .......... .......... .......... ..........  1% 12.3M 15s
  1700K .......... .......... .......... .......... ..........  1% 10.4M 15s
  1750K .......... .......... .......... .......... ..........  1% 15.7M 15s
  1800K .......... .......... .......... .......... ..........  1% 10.1M 15s
  1850K .......... .......... .......... .......... ..........  1% 18.0M 15s
  1900K .......... .......... .......... .......... ..........  1% 16.3M 15s
  1950K .......... .......... .......... .......... ..........  1% 7.21M 15s
  2000K .......... .......... .......... .......... ..........  1% 42.9M 14s
  2050K .......... .......... .......... .......... ..........  1% 11.8M 14s
  2100K .......... .......... .......... .......... ..........  1% 13.0M 14s
  2150K .......... .......... .......... .......... ..........  1% 13.0M 14s
  2200K .......... .......... .......... .......... ..........  1% 10.4M 14s
  2250K .......... .......... .......... .......... ..........  1% 28.9M 14s
  2300K .......... .......... .......... .......... ..........  1% 13.0M 14s
  2350K .......... .......... .......... .......... ..........  1% 9.70M 14s
  2400K .......... .......... .......... .......... ..........  1% 10.3M 14s
  2450K .......... .......... .......... .......... ..........  1% 12.6M 14s
  2500K .......... .......... .......... .......... ..........  1% 18.8M 13s
  2550K .......... .......... .......... .......... ..........  1% 14.8M 13s
  2600K .......... .......... .......... .......... ..........  2% 9.88M 13s
  2650K .......... .......... .......... .......... ..........  2% 11.0M 13s
  2700K .......... .......... .......... .......... ..........  2% 13.7M 13s
  2750K .......... .......... .......... .......... ..........  2% 5.54M 13s
  2800K .......... .......... .......... .......... ..........  2% 96.3M 13s
  2850K .......... .......... .......... .......... ..........  2% 24.4M 13s
  2900K .......... .......... .......... .......... ..........  2% 13.8M 13s
  2950K .......... .......... .......... .......... ..........  2% 13.6M 13s
  3000K .......... .......... .......... .......... ..........  2% 11.5M 13s
  3050K .......... .......... .......... .......... ..........  2% 9.79M 13s
  3100K .......... .......... .......... .......... ..........  2% 10.4M 13s
  3150K .......... .......... .......... .......... ..........  2% 8.51M 13s
  3200K .......... .......... .......... .......... ..........  2% 10.7M 13s
  3250K .......... .......... .......... .......... ..........  2% 13.5M 13s
  3300K .......... .......... .......... .......... ..........  2% 17.3M 13s
  3350K .......... .......... .......... .......... ..........  2% 14.0M 13s
  3400K .......... .......... .......... .......... ..........  2% 13.5M 13s
  3450K .......... .......... .......... .......... ..........  2% 14.0M 12s
  3500K .......... .......... .......... .......... ..........  2% 16.4M 12s
  3550K .......... .......... .......... .......... ..........  2% 8.73M 12s
  3600K .......... .......... .......... .......... ..........  2% 12.9M 12s
  3650K .......... .......... .......... .......... ..........  2% 10.9M 12s
  3700K .......... .......... .......... .......... ..........  2% 11.6M 12s
  3750K .......... .......... .......... .......... ..........  2% 21.6M 12s
  3800K .......... .......... .......... .......... ..........  2% 10.7M 12s
  3850K .......... .......... .......... .......... ..........  2% 24.9M 12s
  3900K .......... .......... .......... .......... ..........  3% 11.3M 12s
  3950K .......... .......... .......... .......... ..........  3% 9.03M 12s
  4000K .......... .......... .......... .......... ..........  3% 21.1M 12s
  4050K .......... .......... .......... .......... ..........  3% 7.69M 12s
  4100K .......... .......... .......... .......... ..........  3% 21.8M 12s
  4150K .......... .......... .......... .......... ..........  3% 10.8M 12s
  4200K .......... .......... .......... .......... ..........  3% 22.8M 12s
  4250K .......... .......... .......... .......... ..........  3% 11.6M 12s
  4300K .......... .......... .......... .......... ..........  3% 15.3M 12s
  4350K .......... .......... .......... .......... ..........  3% 12.5M 12s
  4400K .......... .......... .......... .......... ..........  3% 7.67M 12s
  4450K .......... .......... .......... .......... ..........  3% 19.2M 12s
  4500K .......... .......... .......... .......... ..........  3% 11.2M 12s
  4550K .......... .......... .......... .......... ..........  3% 35.4M 12s
  4600K .......... .......... .......... .......... ..........  3% 6.97M 12s
  4650K .......... .......... .......... .......... ..........  3% 20.3M 12s
  4700K .......... .......... .......... .......... ..........  3% 17.6M 12s
  4750K .......... .......... .......... .......... ..........  3% 9.26M 12s
  4800K .......... .......... .......... .......... ..........  3% 14.1M 12s
  4850K .......... .......... .......... .......... ..........  3% 18.1M 12s
  4900K .......... .......... .......... .......... ..........  3% 12.2M 12s
  4950K .......... .......... .......... .......... ..........  3% 11.8M 11s
  5000K .......... .......... .......... .......... ..........  3% 15.4M 11s
  5050K .......... .......... .......... .......... ..........  3% 13.3M 11s
  5100K .......... .......... .......... .......... ..........  3% 11.9M 11s
  5150K .......... .......... .......... .......... ..........  3% 12.5M 11s
  5200K .......... .......... .......... .......... ..........  4% 11.2M 11s
  5250K .......... .......... .......... .......... ..........  4% 10.4M 11s
  5300K .......... .......... .......... .......... ..........  4% 17.4M 11s
  5350K .......... .......... .......... .......... ..........  4% 15.1M 11s
  5400K .......... .......... .......... .......... ..........  4% 10.9M 11s
  5450K .......... .......... .......... .......... ..........  4% 13.7M 11s
  5500K .......... .......... .......... .......... ..........  4% 12.6M 11s
  5550K .......... .......... .......... .......... ..........  4% 10.8M 11s
  5600K .......... .......... .......... .......... ..........  4% 15.0M 11s
  5650K .......... .......... .......... .......... ..........  4% 19.8M 11s
  5700K .......... .......... .......... .......... ..........  4% 9.81M 11s
  5750K .......... .......... .......... .......... ..........  4% 13.0M 11s
  5800K .......... .......... .......... .......... ..........  4% 13.6M 11s
  5850K .......... .......... .......... .......... ..........  4% 12.8M 11s
  5900K .......... .......... .......... .......... ..........  4% 12.1M 11s
  5950K .......... .......... .......... .......... ..........  4% 12.7M 11s
  6000K .......... .......... .......... .......... ..........  4% 9.68M 11s
  6050K .......... .......... .......... .......... ..........  4% 12.1M 11s
  6100K .......... .......... .......... .......... ..........  4% 20.3M 11s
  6150K .......... .......... .......... .......... ..........  4% 11.9M 11s
  6200K .......... .......... .......... .......... ..........  4% 21.3M 11s
  6250K .......... .......... .......... .......... ..........  4% 10.1M 11s
  6300K .......... .......... .......... .......... ..........  4% 15.8M 11s
  6350K .......... .......... .......... .......... ..........  4% 9.51M 11s
  6400K .......... .......... .......... .......... ..........  4% 17.7M 11s
  6450K .......... .......... .......... .......... ..........  4% 9.23M 11s
  6500K .......... .......... .......... .......... ..........  5% 11.7M 11s
  6550K .......... .......... .......... .......... ..........  5% 20.4M 11s
  6600K .......... .......... .......... .......... ..........  5% 11.7M 11s
  6650K .......... .......... .......... .......... ..........  5% 10.4M 11s
  6700K .......... .......... .......... .......... ..........  5% 23.8M 11s
  6750K .......... .......... .......... .......... ..........  5% 7.81M 11s
  6800K .......... .......... .......... .......... ..........  5% 9.13M 11s
  6850K .......... .......... .......... .......... ..........  5% 20.5M 11s
  6900K .......... .......... .......... .......... ..........  5% 23.6M 11s
  6950K .......... .......... .......... .......... ..........  5% 12.0M 11s
  7000K .......... .......... .......... .......... ..........  5% 10.6M 11s
  7050K .......... .......... .......... .......... ..........  5% 15.9M 11s
  7100K .......... .......... .......... .......... ..........  5% 15.0M 11s
  7150K .......... .......... .......... .......... ..........  5% 9.07M 11s
  7200K .......... .......... .......... .......... ..........  5% 12.6M 11s
  7250K .......... .......... .......... .......... ..........  5% 27.1M 11s
  7300K .......... .......... .......... .......... ..........  5% 11.2M 11s
  7350K .......... .......... .......... .......... ..........  5% 15.8M 11s
  7400K .......... .......... .......... .......... ..........  5% 12.2M 11s
  7450K .......... .......... .......... .......... ..........  5% 12.3M 11s
  7500K .......... .......... .......... .......... ..........  5% 10.1M 11s
  7550K .......... .......... .......... .......... ..........  5% 12.9M 11s
  7600K .......... .......... .......... .......... ..........  5% 16.2M 11s
  7650K .......... .......... .......... .......... ..........  5% 11.4M 11s
  7700K .......... .......... .......... .......... ..........  5% 12.7M 11s
  7750K .......... .......... .......... .......... ..........  5% 12.0M 11s
  7800K .......... .......... .......... .......... ..........  6% 12.0M 11s
  7850K .......... .......... .......... .......... ..........  6% 12.4M 11s
  7900K .......... .......... .......... .......... ..........  6% 15.8M 11s
  7950K .......... .......... .......... .......... ..........  6% 10.3M 11s
  8000K .......... .......... .......... .......... ..........  6% 14.7M 11s
  8050K .......... .......... .......... .......... ..........  6% 9.62M 11s
  8100K .......... .......... .......... .......... ..........  6% 22.0M 10s
  8150K .......... .......... .......... .......... ..........  6% 11.8M 10s
  8200K .......... .......... .......... .......... ..........  6% 19.0M 10s
  8250K .......... .......... .......... .......... ..........  6% 12.2M 10s
  8300K .......... .......... .......... .......... ..........  6% 10.8M 10s
  8350K .......... .......... .......... .......... ..........  6% 12.8M 10s
  8400K .......... .......... .......... .......... ..........  6% 12.5M 10s
  8450K .......... .......... .......... .......... ..........  6% 11.6M 10s
  8500K .......... .......... .......... .......... ..........  6% 12.4M 10s
  8550K .......... .......... .......... .......... ..........  6% 16.0M 10s
  8600K .......... .......... .......... .......... ..........  6% 8.71M 10s
  8650K .......... .......... .......... .......... ..........  6% 25.2M 10s
  8700K .......... .......... .......... .......... ..........  6% 13.0M 10s
  8750K .......... .......... .......... .......... ..........  6% 10.1M 10s
  8800K .......... .......... .......... .......... ..........  6% 15.2M 10s
  8850K .......... .......... .......... .......... ..........  6% 14.7M 10s
  8900K .......... .......... .......... .......... ..........  6% 11.2M 10s
  8950K .......... .......... .......... .......... ..........  6% 10.7M 10s
  9000K .......... .......... .......... .......... ..........  6% 21.8M 10s
  9050K .......... .......... .......... .......... ..........  6% 9.47M 10s
  9100K .......... .......... .......... .......... ..........  7% 28.0M 10s
  9150K .......... .......... .......... .......... ..........  7% 7.17M 10s
  9200K .......... .......... .......... .......... ..........  7% 18.8M 10s
  9250K .......... .......... .......... .......... ..........  7% 10.5M 10s
  9300K .......... .......... .......... .......... ..........  7% 12.8M 10s
  9350K .......... .......... .......... .......... ..........  7% 28.9M 10s
  9400K .......... .......... .......... .......... ..........  7% 11.1M 10s
  9450K .......... .......... .......... .......... ..........  7% 12.8M 10s
  9500K .......... .......... .......... .......... ..........  7% 9.63M 10s
  9550K .......... .......... .......... .......... ..........  7% 12.6M 10s
  9600K .......... .......... .......... .......... ..........  7% 11.7M 10s
  9650K .......... .......... .......... .......... ..........  7% 19.9M 10s
  9700K .......... .......... .......... .......... ..........  7% 14.1M 10s
  9750K .......... .......... .......... .......... ..........  7% 11.8M 10s
  9800K .......... .......... .......... .......... ..........  7% 12.0M 10s
  9850K .......... .......... .......... .......... ..........  7% 9.94M 10s
  9900K .......... .......... .......... .......... ..........  7% 42.7M 10s
  9950K .......... .......... .......... .......... ..........  7% 6.73M 10s
 10000K .......... .......... .......... .......... ..........  7% 18.7M 10s
 10050K .......... .......... .......... .......... ..........  7% 14.8M 10s
 10100K .......... .......... .......... .......... ..........  7% 15.0M 10s
 10150K .......... .......... .......... .......... ..........  7% 9.11M 10s
 10200K .......... .......... .......... .......... ..........  7% 27.5M 10s
 10250K .......... .......... .......... .......... ..........  7% 10.3M 10s
 10300K .......... .......... .......... .......... ..........  7% 15.6M 10s
 10350K .......... .......... .......... .......... ..........  7% 7.71M 10s
 10400K .......... .......... .......... .......... ..........  7% 22.5M 10s
 10450K .......... .......... .......... .......... ..........  8% 17.4M 10s
 10500K .......... .......... .......... .......... ..........  8% 11.0M 10s
 10550K .......... .......... .......... .......... ..........  8% 10.6M 10s
 10600K .......... .......... .......... .......... ..........  8% 18.3M 10s
 10650K .......... .......... .......... .......... ..........  8% 7.97M 10s
 10700K .......... .......... .......... .......... ..........  8% 25.2M 10s
 10750K .......... .......... .......... .......... ..........  8% 6.59M 10s
 10800K .......... .......... .......... .......... ..........  8% 93.5M 10s
 10850K .......... .......... .......... .......... ..........  8% 13.6M 10s
 10900K .......... .......... .......... .......... ..........  8% 13.3M 10s
 10950K .......... .......... .......... .......... ..........  8% 12.7M 10s
 11000K .......... .......... .......... .......... ..........  8% 12.1M 10s
 11050K .......... .......... .......... .......... ..........  8% 11.1M 10s
 11100K .......... .......... .......... .......... ..........  8% 14.3M 10s
 11150K .......... .......... .......... .......... ..........  8% 9.95M 10s
 11200K .......... .......... .......... .......... ..........  8% 11.4M 10s
 11250K .......... .......... .......... .......... ..........  8% 15.8M 10s
 11300K .......... .......... .......... .......... ..........  8% 19.2M 10s
 11350K .......... .......... .......... .......... ..........  8% 11.7M 10s

Downloading atb.assembly.r0.2.batch.35.tar.xz from https://osf.io/download/6671454fd835c4399d4ce3cc/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671454fd835c4399d4ce3cc [following]
--2026-09-06 18:52:13--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671454fd835c4399d4ce3cc
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/00568bb48f390b82588fa022c8b622a7a4ae4371220a9cbb849dec3ebbaeffbb?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.35.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.35.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713594&Signature=YKfZ8Mwb8wB2o9EPZtgDZ7orN8eAuuKGA2bJzTHEzBJlp752in2M29H%2FkYBK3zFtuCcrBod2PQKcXmc%2Bj9ga5xriZel1DeZbtWjcA9F3JmjDyE87lvrcIzo%2Bc%2Fw%2BB6hw0qDyJPJVZbuSzciVXXU1v6Sf%2BNmrxAXk53h5Pn3gVtG0etzBeOzCfAaLtD83QZcekL6rWiIEZuWCdVxdVti1c94%2BskJtLAuid%2FgtGLq93sUs7R%2BM%2F5pFDw7UcnQamkw6%2BvcQ%2BiUCQGwxtvBHhP6u2slx7zM7EE1Foa6HHKQ9CeBFf86D1DsCUMdyahGbxsZWICXPKoDAif1KbkL7e%2BM34A%3D%3D [following]
--2026-09-06 18:52:14--  https://storage.googleapis.com/cos-osf-prod-files-de-1/00568bb48f390b82588fa022c8b622a7a4ae4371220a9cbb849dec3ebbaeffbb?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.35.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.35.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713594&Signature=YKfZ8Mwb8wB2o9EPZtgDZ7orN8eAuuKGA2bJzTHEzBJlp752in2M29H%2FkYBK3zFtuCcrBod2PQKcXmc%2Bj9ga5xriZel1DeZbtWjcA9F3JmjDyE87lvrcIzo%2Bc%2Fw%2BB6hw0qDyJPJVZbuSzciVXXU1v6Sf%2BNmrxAXk53h5Pn3gVtG0etzBeOzCfAaLtD83QZcekL6rWiIEZuWCdVxdVti1c94%2BskJtLAuid%2FgtGLq93sUs7R%2BM%2F5pFDw7UcnQamkw6%2BvcQ%2BiUCQGwxtvBHhP6u2slx7zM7EE1Foa6HHKQ9CeBFf86D1DsCUMdyahGbxsZWICXPKoDAif1KbkL7e%2BM34A%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 70835180 (68M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.35.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.32M 51s
    50K .......... .......... .......... .......... ..........  0% 2.30M 40s
   100K .......... .......... .......... .......... ..........  0% 5.14M 31s
   150K .......... .......... .......... .......... ..........  0% 2.60M 30s
   200K .......... .......... .......... .......... ..........  0% 8.55M 25s
   250K .......... .......... .......... .......... ..........  0% 11.1M 22s
   300K .......... .......... .......... .......... ..........  0% 4.83M 21s
   350K .......... .......... .......... .......... ..........  0% 15.1M 19s
   400K .......... .......... .......... .......... ..........  0% 7.25M 18s
   450K .......... .......... .......... .......... ..........  0% 12.9M 17s
   500K .......... .......... .......... .......... ..........  0% 13.4M 15s
   550K .......... .......... .......... .......... ..........  0% 14.1M 15s
   600K .......... .......... .......... .......... ..........  0% 15.2M 14s
   650K .......... .......... .......... .......... ..........  1% 10.6M 13s
   700K .......... .......... .......... .......... ..........  1% 12.0M 13s
   750K .......... .......... .......... .......... ..........  1% 14.6M 12s
   800K .......... .......... .......... .......... ..........  1% 13.3M 12s
   850K .......... .......... .......... .......... ..........  1% 14.5M 11s
   900K .......... .......... .......... .......... ..........  1% 11.7M 11s
   950K .......... .......... .......... .......... ..........  1% 12.0M 11s
  1000K .......... .......... .......... .......... ..........  1% 9.85M 11s
  1050K .......... .......... .......... .......... ..........  1% 13.3M 10s
  1100K .......... .......... .......... .......... ..........  1% 16.3M 10s
  1150K .......... .......... .......... .......... ..........  1% 12.2M 10s
  1200K .......... .......... .......... .......... ..........  1% 11.0M 10s
  1250K .......... .......... .......... .......... ..........  1% 10.3M 10s
  1300K .......... .......... .......... .......... ..........  1% 22.0M 9s
  1350K .......... .......... .......... .......... ..........  2% 13.4M 9s
  1400K .......... .......... .......... .......... ..........  2% 11.1M 9s
  1450K .......... .......... .......... .......... ..........  2% 13.5M 9s
  1500K .......... .......... .......... .......... ..........  2% 10.7M 9s
  1550K .......... .......... .......... .......... ..........  2% 16.0M 9s
  1600K .......... .......... .......... .......... ..........  2% 10.1M 9s
  1650K .......... .......... .......... .......... ..........  2% 24.3M 8s
  1700K .......... .......... .......... .......... ..........  2% 12.9M 8s
  1750K .......... .......... .......... .......... ..........  2% 12.2M 8s
  1800K .......... .......... .......... .......... ..........  2% 13.4M 8s
  1850K .......... .......... .......... .......... ..........  2% 14.3M 8s
  1900K .......... .......... .......... .......... ..........  2% 11.7M 8s
  1950K .......... .......... .......... .......... ..........  2% 10.1M 8s
  2000K .......... .......... .......... .......... ..........  2% 12.9M 8s
  2050K .......... .......... .......... .......... ..........  3% 16.1M 8s
  2100K .......... .......... .......... .......... ..........  3% 12.0M 8s
  2150K .......... .......... .......... .......... ..........  3% 14.2M 8s
  2200K .......... .......... .......... .......... ..........  3% 14.7M 8s
  2250K .......... .......... .......... .......... ..........  3% 11.8M 7s
  2300K .......... .......... .......... .......... ..........  3% 13.4M 7s
  2350K .......... .......... .......... .......... ..........  3% 10.6M 7s
  2400K .......... .......... .......... .......... ..........  3% 14.4M 7s
  2450K .......... .......... .......... .......... ..........  3% 10.1M 7s
  2500K .......... .......... .......... .......... ..........  3% 17.4M 7s
  2550K .......... .......... .......... .......... ..........  3% 11.0M 7s
  2600K .......... .......... .......... .......... ..........  3% 15.1M 7s
  2650K .......... .......... .......... .......... ..........  3% 10.8M 7s
  2700K .......... .......... .......... .......... ..........  3% 14.9M 7s
  2750K .......... .......... .......... .......... ..........  4% 9.27M 7s
  2800K .......... .......... .......... .......... ..........  4% 13.7M 7s
  2850K .......... .......... .......... .......... ..........  4% 15.6M 7s
  2900K .......... .......... .......... .......... ..........  4% 12.8M 7s
  2950K .......... .......... .......... .......... ..........  4% 12.1M 7s
  3000K .......... .......... .......... .......... ..........  4% 9.91M 7s
  3050K .......... .......... .......... .......... ..........  4% 13.1M 7s
  3100K .......... .......... .......... .......... ..........  4% 13.3M 7s
  3150K .......... .......... .......... .......... ..........  4% 9.28M 7s
  3200K .......... .......... .......... .......... ..........  4% 13.0M 7s
  3250K .......... .......... .......... .......... ..........  4% 28.7M 7s
  3300K .......... .......... .......... .......... ..........  4% 8.71M 7s
  3350K .......... .......... .......... .......... ..........  4% 23.0M 7s
  3400K .......... .......... .......... .......... ..........  4% 13.0M 7s
  3450K .......... .......... .......... .......... ..........  5% 18.1M 7s
  3500K .......... .......... .......... .......... ..........  5% 9.62M 7s
  3550K .......... .......... .......... .......... ..........  5% 12.8M 7s
  3600K .......... .......... .......... .......... ..........  5% 15.0M 6s
  3650K .......... .......... .......... .......... ..........  5% 8.14M 6s
  3700K .......... .......... .......... .......... ..........  5% 21.7M 6s
  3750K .......... .......... .......... .......... ..........  5% 11.4M 6s
  3800K .......... .......... .......... .......... ..........  5% 11.3M 6s
  3850K .......... .......... .......... .......... ..........  5% 37.0M 6s
  3900K .......... .......... .......... .......... ..........  5% 9.20M 6s
  3950K .......... .......... .......... .......... ..........  5% 9.60M 6s
  4000K .......... .......... .......... .......... ..........  5% 11.8M 6s
  4050K .......... .......... .......... .......... ..........  5% 12.0M 6s
  4100K .......... .......... .......... .......... ..........  5% 28.1M 6s
  4150K .......... .......... .......... .......... ..........  6% 11.8M 6s
  4200K .......... .......... .......... .......... ..........  6% 20.0M 6s
  4250K .......... .......... .......... .......... ..........  6% 8.14M 6s
  4300K .......... .......... .......... .......... ..........  6% 25.9M 6s
  4350K .......... .......... .......... .......... ..........  6% 8.39M 6s
  4400K .......... .......... .......... .......... ..........  6% 12.6M 6s
  4450K .......... .......... .......... .......... ..........  6% 25.8M 6s
  4500K .......... .......... .......... .......... ..........  6% 9.18M 6s
  4550K .......... .......... .......... .......... ..........  6% 23.3M 6s
  4600K .......... .......... .......... .......... ..........  6% 10.1M 6s
  4650K .......... .......... .......... .......... ..........  6% 14.8M 6s
  4700K .......... .......... .......... .......... ..........  6% 12.7M 6s
  4750K .......... .......... .......... .......... ..........  6% 9.04M 6s
  4800K .......... .......... .......... .......... ..........  7% 14.8M 6s
  4850K .......... .......... .......... .......... ..........  7% 11.2M 6s
  4900K .......... .......... .......... .......... ..........  7% 19.6M 6s
  4950K .......... .......... .......... .......... ..........  7% 11.3M 6s
  5000K .......... .......... .......... .......... ..........  7% 12.2M 6s
  5050K .......... .......... .......... .......... ..........  7% 15.8M 6s
  5100K .......... .......... .......... .......... ..........  7% 15.1M 6s
  5150K .......... .......... .......... .......... ..........  7% 8.40M 6s
  5200K .......... .......... .......... .......... ..........  7% 20.3M 6s
  5250K .......... .......... .......... .......... ..........  7% 15.2M 6s
  5300K .......... .......... .......... .......... ..........  7% 10.4M 6s
  5350K .......... .......... .......... .......... ..........  7% 9.58M 6s
  5400K .......... .......... .......... .......... ..........  7% 12.8M 6s
  5450K .......... .......... .......... .......... ..........  7% 13.6M 6s
  5500K .......... .......... .......... .......... ..........  8% 16.9M 6s
  5550K .......... .......... .......... .......... ..........  8% 12.2M 6s
  5600K .......... .......... .......... .......... ..........  8% 15.5M 6s
  5650K .......... .......... .......... .......... ..........  8% 11.9M 6s
  5700K .......... .......... .......... .......... ..........  8% 13.9M 6s
  5750K .......... .......... .......... .......... ..........  8% 11.8M 6s
  5800K .......... .......... .......... .......... ..........  8% 15.4M 6s
  5850K .......... .......... .......... .......... ..........  8% 10.3M 6s
  5900K .......... .......... .......... .......... ..........  8% 13.7M 6s
  5950K .......... .......... .......... .......... ..........  8% 11.0M 6s
  6000K .......... .......... .......... .......... ..........  8% 17.0M 6s
  6050K .......... .......... .......... .......... ..........  8% 11.8M 6s
  6100K .......... .......... .......... .......... ..........  8% 16.5M 6s
  6150K .......... .......... .......... .......... ..........  8% 9.02M 6s
  6200K .......... .......... .......... .......... ..........  9% 16.0M 6s
  6250K .......... .......... .......... .......... ..........  9% 13.9M 6s
  6300K .......... .......... .......... .......... ..........  9% 12.2M 6s
  6350K .......... .......... .......... .......... ..........  9% 11.5M 6s
  6400K .......... .......... .......... .......... ..........  9% 9.97M 6s
  6450K .......... .......... .......... .......... ..........  9% 14.0M 6s
  6500K .......... .......... .......... .......... ..........  9% 12.0M 6s
  6550K .......... .......... .......... .......... ..........  9% 17.1M 6s
  6600K .......... .......... .......... .......... ..........  9% 13.1M 6s
  6650K .......... .......... .......... .......... ..........  9% 11.4M 6s
  6700K .......... .......... .......... .......... ..........  9% 15.4M 6s
  6750K .......... .......... .......... .......... ..........  9% 11.4M 6s
  6800K .......... .......... .......... .......... ..........  9% 12.0M 6s
  6850K .......... .......... .......... .......... ..........  9% 11.6M 6s
  6900K .......... .......... .......... .......... .......... 10% 21.9M 5s
  6950K .......... .......... .......... .......... .......... 10% 12.1M 5s
  7000K .......... .......... .......... .......... .......... 10% 9.19M 5s
  7050K .......... .......... .......... .......... .......... 10% 15.5M 5s
  7100K .......... .......... .......... .......... .......... 10% 19.8M 5s
  7150K .......... .......... .......... .......... .......... 10% 10.0M 5s
  7200K .......... .......... .......... .......... .......... 10% 9.70M 5s
  7250K .......... .......... .......... .......... .......... 10% 15.8M 5s
  7300K .......... .......... .......... .......... .......... 10% 12.5M 5s
  7350K .......... .......... .......... .......... .......... 10% 16.4M 5s
  7400K .......... .......... .......... .......... .......... 10% 13.8M 5s
  7450K .......... .......... .......... .......... .......... 10% 12.7M 5s
  7500K .......... .......... .......... .......... .......... 10% 16.9M 5s
  7550K .......... .......... .......... .......... .......... 10% 11.0M 5s
  7600K .......... .......... .......... .......... .......... 11% 11.6M 5s
  7650K .......... .......... .......... .......... .......... 11% 12.3M 5s
  7700K .......... .......... .......... .......... .......... 11% 9.08M 5s
  7750K .......... .......... .......... .......... .......... 11% 24.1M 5s
  7800K .......... .......... .......... .......... .......... 11% 11.1M 5s
  7850K .......... .......... .......... .......... .......... 11% 15.2M 5s
  7900K .......... .......... .......... .......... .......... 11% 14.7M 5s
  7950K .......... .......... .......... .......... .......... 11% 15.7M 5s
  8000K .......... .......... .......... .......... .......... 11% 8.25M 5s
  8050K .......... .......... .......... .......... .......... 11% 17.5M 5s
  8100K .......... .......... .......... .......... .......... 11% 10.6M 5s
  8150K .......... .......... .......... .......... .......... 11% 14.5M 5s
  8200K .......... .......... .......... .......... .......... 11% 16.3M 5s
  8250K .......... .......... .......... .......... .......... 11% 10.7M 5s
  8300K .......... .......... .......... .......... .......... 12% 14.1M 5s
  8350K .......... .......... .......... .......... .......... 12% 13.6M 5s
  8400K .......... .......... .......... .......... .......... 12% 12.2M 5s
  8450K .......... .......... .......... .......... .......... 12% 10.2M 5s
  8500K .......... .......... .......... .......... .......... 12% 13.8M 5s
  8550K .......... .......... .......... .......... .......... 12% 9.64M 5s
  8600K .......... .......... .......... .......... .......... 12% 13.6M 5s
  8650K .......... .......... .......... .......... .......... 12% 20.6M 5s
  8700K .......... .......... .......... .......... .......... 12% 12.9M 5s
  8750K .......... .......... .......... .......... .......... 12% 15.7M 5s
  8800K .......... .......... .......... .......... .......... 12% 8.82M 5s
  8850K .......... .......... .......... .......... .......... 12% 13.5M 5s
  8900K .......... .......... .......... .......... .......... 12% 16.1M 5s
  8950K .......... .......... .......... .......... .......... 13% 9.88M 5s
  9000K .......... .......... .......... .......... .......... 13% 16.0M 5s
  9050K .......... .......... .......... .......... .......... 13% 9.82M 5s
  9100K .......... .......... .......... .......... .......... 13% 19.8M 5s
  9150K .......... .......... .......... .......... .......... 13% 11.0M 5s
  9200K .......... .......... .......... .......... .......... 13% 10.9M 5s
  9250K .......... .......... .......... .......... .......... 13% 11.3M 5s
  9300K .......... .......... .......... .......... .......... 13% 18.6M 5s
  9350K .......... .......... .......... .......... .......... 13% 18.1M 5s
  9400K .......... .......... .......... .......... .......... 13% 8.64M 5s
  9450K .......... .......... .......... .......... .......... 13% 11.9M 5s
  9500K .......... .......... .......... .......... .......... 13% 23.7M 5s
  9550K .......... .......... .......... .......... .......... 13% 12.5M 5s
  9600K .......... .......... .......... .......... .......... 13% 9.02M 5s
  9650K .......... .......... .......... .......... .......... 14% 19.5M 5s
  9700K .......... .......... .......... .......... .......... 14% 13.9M 5s
  9750K .......... .......... .......... .......... .......... 14% 10.7M 5s
  9800K .......... .......... .......... .......... .......... 14% 12.5M 5s
  9850K .......... .......... .......... .......... .......... 14% 15.8M 5s
  9900K .......... .......... .......... .......... .......... 14% 11.4M 5s
  9950K .......... .......... .......... .......... .......... 14% 11.1M 5s
 10000K .......... .......... .......... .......... .......... 14% 11.0M 5s
 10050K .......... .......... .......... .......... .......... 14% 13.3M 5s
 10100K .......... .......... .......... .......... .......... 14% 12.0M 5s
 10150K .......... .......... .......... .......... .......... 14% 28.6M 5s
 10200K .......... .......... .......... .......... .......... 14% 9.69M 5s
 10250K .......... .......... .......... .......... .......... 14% 12.2M 5s
 10300K .......... .......... .......... .......... .......... 14% 11.8M 5s
 10350K .......... .......... .......... .......... .......... 15% 14.6M 5s
 10400K .......... .......... .......... .......... .......... 15% 11.0M 5s
 10450K .......... .......... .......... .......... .......... 15% 13.6M 5s
 10500K .......... .......... .......... .......... .......... 15% 13.2M 5s
 10550K .......... .......... .......... .......... .......... 15% 13.8M 5s
 10600K .......... .......... .......... .......... .......... 15% 15.3M 5s
 10650K .......... .......... .......... .......... .......... 15% 9.61M 5s
 10700K .......... .......... .......... .......... .......... 15% 17.3M 5s
 10750K .......... .......... .......... .......... .......... 15% 17.7M 5s
 10800K .......... .......... .......... .......... .......... 15% 6.82M 5s
 10850K .......... .......... .......... .......... .......... 15% 32.9M 5s
 10900K .......... .......... .......... .......... .......... 15% 11.8M 5s
 10950K .......... .......... .......... .......... .......... 15% 10.3M 5s
 11000K .......... .......... .......... .......... .......... 15% 14.9M 5s
 11050K .......... .......... .......... .......... .......... 16% 12.8M 5s
 11100K .......... .......... .......... .......... .......... 16% 15.7M 5s
 11150K .......... .......... .......... .......... .......... 16% 11.4M 5s
 11200K .......... .......... .......... .......... .......... 16% 12.5M 5s
 11250K .......... .......... .......... .......... .......... 16% 11.8M 5s
 11300K .......... .......... .......... .......... .......... 16% 19.2M 5s
 11350K .......... .......... .......... .......... .......... 16% 12.9M 5s
 11400K .......... .......... .......... .......... .......... 16% 13.8M 5s
 11450K .......... .......... .......... .......... .......... 16% 11.1M 5s
 11500K .......... .......... .......... .......... .......... 16% 14.7M 5s

Downloading atb.assembly.r0.2.batch.36.tar.xz from https://osf.io/download/667145536b6c8e33f004cf2f/

HTTP request sent, awaiting response... 302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667145536b6c8e33f004cf2f [following]
--2026-09-06 18:52:20--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667145536b6c8e33f004cf2f
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/cbd5450329587737ae9155e417b83753ced0267806020c6e63a15890f2c8aa30?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.36.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.36.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713601&Signature=tlFXuYiG7uJuN5UnlRIiR0VolFbU3Gon58oEFLEVr%2BY5tTuvEDpsotq6ShElff8OKPijnq78ZAFvvfthdRt%2F7cN%2F1czMwJnEgbVY6mFcVtmA%2FCFhq988vq2z2c2clbMDzLg2hbCJ3lo4HeJZlUzxd3cGgLjvY%2BLXwYSqyW9qshe5paBn47KRCHp0kuK4gtEVqdJqeYSzmw1HH307RT60dXPRG4VO4noPNz4vYLtZhnKZUcmHDCEnFQeKBOjRQ8LP3l6L9gtY1DkFwaJrSNDlJtqAQ52qqDc2Lwtfu4hXU5IF5H9x3FqY8uhUfoxgoseyKdfhMaDbcgA4uERWRvjsCw%3D%3D [following]
--2026-09-06 18:52:21--  https://storage.googleapis.com/cos-osf-prod-files-de-1/cbd5450329587737ae9155e417b83753ced0267806020c6e63a15890f2c8aa30?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.36.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.36.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713601&Signature=tlFXuYiG7uJuN5UnlRIiR0VolFbU3Gon58oEFLEVr%2BY5tTuvEDpsotq6ShElff8OKPijnq78ZAFvvfthdRt%2F7cN%2F1czMwJnEgbVY6mFcVtmA%2FCFhq988vq2z2c2clbMDzLg2hbCJ3lo4HeJZlUzxd3cGgLjvY%2BLXwYSqyW9qshe5paBn47KRCHp0kuK4gtEVqdJqeYSzmw1HH307RT60dXPRG4VO4noPNz4vYLtZhnKZUcmHDCEnFQeKBOjRQ8LP3l6L9gtY1DkFwaJrSNDlJtqAQ52qqDc2Lwtfu4hXU5IF5H9x3FqY8uhUfoxgoseyKdfhMaDbcgA4uERWRvjsCw%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43754028 (42M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.36.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.42M 29s
    50K .......... .......... .......... .......... ..........  0% 2.51M 23s
   100K .......... .......... .......... .......... ..........  0% 5.22M 18s
   150K .......... .......... .......... .......... ..........  0% 3.53M 16s
   200K .......... .......... .......... .......... ..........  0% 7.36M 14s
   250K .......... .......... .......... .......... ..........  0% 17.4M 12s
   300K .......... .......... .......... .......... ..........  0% 8.55M 11s
   350K .......... .......... .......... .......... ..........  0% 9.03M 10s
   400K .......... .......... .......... .......... ..........  1% 11.4M 10s
   450K .......... .......... .......... .......... ..........  1% 12.9M 9s
   500K .......... .......... .......... .......... ..........  1% 9.93M 8s
   550K .......... .......... .......... .......... ..........  1% 14.2M 8s
   600K .......... .......... .......... .......... ..........  1% 18.3M 8s
   650K .......... .......... .......... .......... ..........  1% 13.1M 7s
   700K .......... .......... .......... .......... ..........  1% 12.6M 7s
   750K .......... .......... .......... .......... ..........  1% 9.78M 7s
   800K .......... .......... .......... .......... ..........  1% 14.1M 7s
   850K .......... .......... .......... .......... ..........  2% 14.1M 6s
   900K .......... .......... .......... .......... ..........  2% 10.5M 6s
   950K .......... .......... .......... .......... ..........  2% 13.5M 6s
  1000K .......... .......... .......... .......... ..........  2% 10.6M 6s
  1050K .......... .......... .......... .......... ..........  2% 19.1M 6s
  1100K .......... .......... .......... .......... ..........  2% 16.2M 6s
  1150K .......... .......... .......... .......... ..........  2% 8.31M 6s
  1200K .......... .......... .......... .......... ..........  2% 14.4M 5s
  1250K .......... .......... .......... .......... ..........  3% 20.7M 5s
  1300K .......... .......... .......... .......... ..........  3% 9.67M 5s
  1350K .......... .......... .......... .......... ..........  3% 12.9M 5s
  1400K .......... .......... .......... .......... ..........  3% 11.6M 5s
  1450K .......... .......... .......... .......... ..........  3% 15.5M 5s
  1500K .......... .......... .......... .......... ..........  3% 14.5M 5s
  1550K .......... .......... .......... .......... ..........  3% 12.5M 5s
  1600K .......... .......... .......... .......... ..........  3% 9.16M 5s
  1650K .......... .......... .......... .......... ..........  3% 35.0M 5s
  1700K .......... .......... .......... .......... ..........  4% 13.0M 5s
  1750K .......... .......... .......... .......... ..........  4% 8.50M 5s
  1800K .......... .......... .......... .......... ..........  4% 13.9M 5s
  1850K .......... .......... .......... .......... ..........  4% 16.0M 5s
  1900K .......... .......... .......... .......... ..........  4% 11.8M 5s
  1950K .......... .......... .......... .......... ..........  4% 11.5M 4s
  2000K .......... .......... .......... .......... ..........  4% 14.0M 4s
  2050K .......... .......... .......... .......... ..........  4% 12.3M 4s
  2100K .......... .......... .......... .......... ..........  5% 19.3M 4s
  2150K .......... .......... .......... .......... ..........  5% 10.9M 4s
  2200K .......... .......... .......... .......... ..........  5% 12.5M 4s
  2250K .......... .......... .......... .......... ..........  5% 11.4M 4s
  2300K .......... .......... .......... .......... ..........  5% 12.8M 4s
  2350K .......... .......... .......... .......... ..........  5% 21.2M 4s
  2400K .......... .......... .......... .......... ..........  5% 11.4M 4s
  2450K .......... .......... .......... .......... ..........  5% 12.6M 4s
  2500K .......... .......... .......... .......... ..........  5% 11.8M 4s
  2550K .......... .......... .......... .......... ..........  6% 10.5M 4s
  2600K .......... .......... .......... .......... ..........  6% 13.2M 4s
  2650K .......... .......... .......... .......... ..........  6% 14.8M 4s
  2700K .......... .......... .......... .......... ..........  6% 9.52M 4s
  2750K .......... .......... .......... .......... ..........  6% 28.5M 4s
  2800K .......... .......... .......... .......... ..........  6% 12.6M 4s
  2850K .......... .......... .......... .......... ..........  6% 6.80M 4s
  2900K .......... .......... .......... .......... ..........  6% 17.2M 4s
  2950K .......... .......... .......... .......... ..........  7% 9.86M 4s
  3000K .......... .......... .......... .......... ..........  7% 27.8M 4s
  3050K .......... .......... .......... .......... ..........  7% 9.19M 4s
  3100K .......... .......... .......... .......... ..........  7% 18.1M 4s
  3150K .......... .......... .......... .......... ..........  7% 13.0M 4s
  3200K .......... .......... .......... .......... ..........  7% 10.4M 4s
  3250K .......... .......... .......... .......... ..........  7% 13.6M 4s
  3300K .......... .......... .......... .......... ..........  7% 17.1M 4s
  3350K .......... .......... .......... .......... ..........  7% 13.5M 4s
  3400K .......... .......... .......... .......... ..........  8% 11.9M 4s
  3450K .......... .......... .......... .......... ..........  8% 13.5M 4s
  3500K .......... .......... .......... .......... ..........  8% 9.19M 4s
  3550K .......... .......... .......... .......... ..........  8% 11.2M 4s
  3600K .......... .......... .......... .......... ..........  8% 38.6M 4s
  3650K .......... .......... .......... .......... ..........  8% 12.6M 4s
  3700K .......... .......... .......... .......... ..........  8% 7.73M 4s
  3750K .......... .......... .......... .......... ..........  8% 11.3M 4s
  3800K .......... .......... .......... .......... ..........  9% 14.7M 4s
  3850K .......... .......... .......... .......... ..........  9% 25.9M 4s
  3900K .......... .......... .......... .......... ..........  9% 12.0M 4s
  3950K .......... .......... .......... .......... ..........  9% 11.2M 4s
  4000K .......... .......... .......... .......... ..........  9% 22.3M 4s
  4050K .......... .......... .......... .......... ..........  9% 12.1M 4s
  4100K .......... .......... .......... .......... ..........  9% 8.06M 4s
  4150K .......... .......... .......... .......... ..........  9% 20.9M 4s
  4200K .......... .......... .......... .......... ..........  9% 12.8M 4s
  4250K .......... .......... .......... .......... .......... 10% 13.8M 4s
  4300K .......... .......... .......... .......... .......... 10% 9.91M 4s
  4350K .......... .......... .......... .......... .......... 10% 11.2M 4s
  4400K .......... .......... .......... .......... .......... 10% 22.2M 4s
  4450K .......... .......... .......... .......... .......... 10% 12.3M 3s
  4500K .......... .......... .......... .......... .......... 10% 10.7M 3s
  4550K .......... .......... .......... .......... .......... 10% 14.5M 3s
  4600K .......... .......... .......... .......... .......... 10% 19.9M 3s
  4650K .......... .......... .......... .......... .......... 10% 12.0M 3s
  4700K .......... .......... .......... .......... .......... 11% 8.60M 3s
  4750K .......... .......... .......... .......... .......... 11% 11.2M 3s
  4800K .......... .......... .......... .......... .......... 11% 18.5M 3s
  4850K .......... .......... .......... .......... .......... 11% 15.7M 3s
  4900K .......... .......... .......... .......... .......... 11% 9.48M 3s
  4950K .......... .......... .......... .......... .......... 11% 25.8M 3s
  5000K .......... .......... .......... .......... .......... 11% 10.7M 3s
  5050K .......... .......... .......... .......... .......... 11% 11.6M 3s
  5100K .......... .......... .......... .......... .......... 12% 12.2M 3s
  5150K .......... .......... .......... .......... .......... 12% 6.46M 3s
  5200K .......... .......... .......... .......... .......... 12% 39.0M 3s
  5250K .......... .......... .......... .......... .......... 12% 33.2M 3s
  5300K .......... .......... .......... .......... .......... 12% 10.4M 3s
  5350K .......... .......... .......... .......... .......... 12% 12.8M 3s
  5400K .......... .......... .......... .......... .......... 12% 12.7M 3s
  5450K .......... .......... .......... .......... .......... 12% 22.5M 3s
  5500K .......... .......... .......... .......... .......... 12% 8.97M 3s
  5550K .......... .......... .......... .......... .......... 13% 8.85M 3s
  5600K .......... .......... .......... .......... .......... 13% 17.5M 3s
  5650K .......... .......... .......... .......... .......... 13% 13.7M 3s
  5700K .......... .......... .......... .......... .......... 13% 12.2M 3s
  5750K .......... .......... .......... .......... .......... 13% 19.6M 3s
  5800K .......... .......... .......... .......... .......... 13% 9.14M 3s
  5850K .......... .......... .......... .......... .......... 13% 23.8M 3s
  5900K .......... .......... .......... .......... .......... 13% 9.67M 3s
  5950K .......... .......... .......... .......... .......... 14% 8.58M 3s
  6000K .......... .......... .......... .......... .......... 14% 15.9M 3s
  6050K .......... .......... .......... .......... .......... 14% 15.1M 3s
  6100K .......... .......... .......... .......... .......... 14% 11.7M 3s
  6150K .......... .......... .......... .......... .......... 14% 11.3M 3s
  6200K .......... .......... .......... .......... .......... 14% 18.6M 3s
  6250K .......... .......... .......... .......... .......... 14% 8.40M 3s
  6300K .......... .......... .......... .......... .......... 14% 18.6M 3s
  6350K .......... .......... .......... .......... .......... 14% 25.9M 3s
  6400K .......... .......... .......... .......... .......... 15% 10.4M 3s
  6450K .......... .......... .......... .......... .......... 15% 10.8M 3s
  6500K .......... .......... .......... .......... .......... 15% 12.7M 3s
  6550K .......... .......... .......... .......... .......... 15% 12.9M 3s
  6600K .......... .......... .......... .......... .......... 15% 17.4M 3s
  6650K .......... .......... .......... .......... .......... 15% 12.1M 3s
  6700K .......... .......... .......... .......... .......... 15% 10.8M 3s
  6750K .......... .......... .......... .......... .......... 15% 12.8M 3s
  6800K .......... .......... .......... .......... .......... 16% 23.6M 3s
  6850K .......... .......... .......... .......... .......... 16% 8.74M 3s
  6900K .......... .......... .......... .......... .......... 16% 12.3M 3s
  6950K .......... .......... .......... .......... .......... 16% 11.7M 3s
  7000K .......... .......... .......... .......... .......... 16% 14.9M 3s
  7050K .......... .......... .......... .......... .......... 16% 12.6M 3s
  7100K .......... .......... .......... .......... .......... 16% 14.5M 3s
  7150K .......... .......... .......... .......... .......... 16% 13.4M 3s
  7200K .......... .......... .......... .......... .......... 16% 13.4M 3s
  7250K .......... .......... .......... .......... .......... 17% 15.2M 3s
  7300K .......... .......... .......... .......... .......... 17% 11.2M 3s
  7350K .......... .......... .......... .......... .......... 17% 9.51M 3s
  7400K .......... .......... .......... .......... .......... 17% 14.8M 3s
  7450K .......... .......... .......... .......... .......... 17% 16.3M 3s
  7500K .......... .......... .......... .......... .......... 17% 15.0M 3s
  7550K .......... .......... .......... .......... .......... 17% 10.3M 3s
  7600K .......... .......... .......... .......... .......... 17% 10.8M 3s
  7650K .......... .......... .......... .......... .......... 18% 20.0M 3s
  7700K .......... .......... .......... .......... .......... 18% 8.60M 3s
  7750K .......... .......... .......... .......... .......... 18% 23.5M 3s
  7800K .......... .......... .......... .......... .......... 18% 10.4M 3s
  7850K .......... .......... .......... .......... .......... 18% 13.3M 3s
  7900K .......... .......... .......... .......... .......... 18% 14.5M 3s
  7950K .......... .......... .......... .......... .......... 18% 10.6M 3s
  8000K .......... .......... .......... .......... .......... 18% 17.3M 3s
  8050K .......... .......... .......... .......... .......... 18% 12.7M 3s
  8100K .......... .......... .......... .......... .......... 19% 11.6M 3s
  8150K .......... .......... .......... .......... .......... 19% 8.68M 3s
  8200K .......... .......... .......... .......... .......... 19% 24.6M 3s
  8250K .......... .......... .......... .......... .......... 19% 15.1M 3s
  8300K .......... .......... .......... .......... .......... 19% 11.6M 3s
  8350K .......... .......... .......... .......... .......... 19% 11.0M 3s
  8400K .......... .......... .......... .......... .......... 19% 14.8M 3s
  8450K .......... .......... .......... .......... .......... 19% 11.1M 3s
  8500K .......... .......... .......... .......... .......... 20% 16.2M 3s
  8550K .......... .......... .......... .......... .......... 20% 11.6M 3s
  8600K .......... .......... .......... .......... .......... 20% 12.2M 3s
  8650K .......... .......... .......... .......... .......... 20% 16.4M 3s
  8700K .......... .......... .......... .......... .......... 20% 14.0M 3s
  8750K .......... .......... .......... .......... .......... 20% 13.1M 3s
  8800K .......... .......... .......... .......... .......... 20% 10.9M 3s
  8850K .......... .......... .......... .......... .......... 20% 14.0M 3s
  8900K .......... .......... .......... .......... .......... 20% 8.94M 3s
  8950K .......... .......... .......... .......... .......... 21% 13.9M 3s
  9000K .......... .......... .......... .......... .......... 21% 10.8M 3s
  9050K .......... .......... .......... .......... .......... 21% 24.3M 3s
  9100K .......... .......... .......... .......... .......... 21% 11.0M 3s
  9150K .......... .......... .......... .......... .......... 21% 16.5M 3s
  9200K .......... .......... .......... .......... .......... 21% 9.48M 3s
  9250K .......... .......... .......... .......... .......... 21% 12.0M 3s
  9300K .......... .......... .......... .......... .......... 21% 14.0M 3s
  9350K .......... .......... .......... .......... .......... 21% 23.3M 3s
  9400K .......... .......... .......... .......... .......... 22% 8.35M 3s
  9450K .......... .......... .......... .......... .......... 22% 14.2M 3s
  9500K .......... .......... .......... .......... .......... 22% 12.9M 3s
  9550K .......... .......... .......... .......... .......... 22% 12.9M 3s
  9600K .......... .......... .......... .......... .......... 22% 12.7M 3s
  9650K .......... .......... .......... .......... .......... 22% 14.2M 3s
  9700K .......... .......... .......... .......... .......... 22% 11.9M 3s
  9750K .......... .......... .......... .......... .......... 22% 19.5M 3s
  9800K .......... .......... .......... .......... .......... 23% 9.52M 3s
  9850K .......... .......... .......... .......... .......... 23% 15.8M 3s
  9900K .......... .......... .......... .......... .......... 23% 14.0M 3s
  9950K .......... .......... .......... .......... .......... 23% 10.6M 3s
 10000K .......... .......... .......... .......... .......... 23% 9.72M 3s
 10050K .......... .......... .......... .......... .......... 23% 15.3M 3s
 10100K .......... .......... .......... .......... .......... 23% 24.2M 3s
 10150K .......... .......... .......... .......... .......... 23% 7.58M 3s
 10200K .......... .......... .......... .......... .......... 23% 17.4M 3s
 10250K .......... .......... .......... .......... .......... 24% 14.1M 3s
 10300K .......... .......... .......... .......... .......... 24% 8.33M 3s
 10350K .......... .......... .......... .......... .......... 24% 22.5M 3s
 10400K .......... .......... .......... .......... .......... 24% 14.2M 3s
 10450K .......... .......... .......... .......... .......... 24% 10.3M 3s
 10500K .......... .......... .......... .......... .......... 24% 15.1M 3s
 10550K .......... .......... .......... .......... .......... 24% 8.52M 3s
 10600K .......... .......... .......... .......... .......... 24% 12.7M 3s
 10650K .......... .......... .......... .......... .......... 25% 45.1M 3s
 10700K .......... .......... .......... .......... .......... 25% 9.90M 3s
 10750K .......... .......... .......... .......... .......... 25% 10.1M 3s
 10800K .......... .......... .......... .......... .......... 25% 9.75M 3s
 10850K .......... .......... .......... .......... .......... 25% 24.8M 3s
 10900K .......... .......... .......... .......... .......... 25% 15.0M 3s
 10950K .......... .......... .......... .......... .......... 25% 12.1M 3s
 11000K .......... .......... .......... .......... .......... 25% 17.7M 3s
 11050K .......... .......... .......... .......... .......... 25% 7.40M 3s
 11100K .......... .......... .......... .......... .......... 26% 21.3M 3s
 11150K .......... .......... .......... .......... .......... 26% 11.7M 3s
 11200K .......... .......... .......... .......... .......... 26% 16.7M 3s
 11250K .......... .......... .......... .......... .......... 26% 9.09M 3s
 11300K .......... .......... .......... .......... .......... 26% 23.5M 3s
 11350K .......... .......... .......... .......... .......... 26% 11.9M 3s
 11400K .......... .......... .......... .......... .......... 26% 11.2M 3s
 11450K .......... .......... .......... .......... .......... 26% 10.9M 3s
 11500K .......... .......... .......... .......... .......... 27% 17.1M 3s

Downloading atb.assembly.r0.2.batch.37.tar.xz from https://osf.io/download/6671455c0f8c8017b73c918b/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671455c0f8c8017b73c918b [following]
--2026-09-06 18:52:25--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671455c0f8c8017b73c918b
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/542e4518c8299609d8f2e0afdd8d99f3d13fb5975d8556f70986adc2dfd035eb?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.37.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.37.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713605&Signature=l8UZ7k1q8uji3aa37%2FGk7Dymk6qx9SZfKzwjo40E5wagHvFFM6D8z7Oj4eRowZdgYSrjGCse0owUDt5ha4IHhzpPI0vl1myOtasbMcnwm5m%2F4A%2B18m8NmpE56NCAVy3QcoDAHEJUers0U35N57bs8tmWh8eZa6pBJk8qwVQdRKMbjV1EwsxiHQeUlP68BLGblfnsNUKiMhHNnVn0m%2FJt46Pt6eUeWh7FXQeqpNnCbdB13HVISZjdsZh6Pzcl0hpH4IzTXIjUUA8iCO4WiAQYQYWhVm22Bb%2F4kNb74i5YaLGplGRzj3LPGue22aDp%2FAry3Gbq4wMpm4vGd0Z816RsNw%3D%3D [following]
--2026-09-06 18:52:25--  https://storage.googleapis.com/cos-osf-prod-files-de-1/542e4518c8299609d8f2e0afdd8d99f3d13fb5975d8556f70986adc2dfd035eb?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.37.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.37.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713605&Signature=l8UZ7k1q8uji3aa37%2FGk7Dymk6qx9SZfKzwjo40E5wagHvFFM6D8z7Oj4eRowZdgYSrjGCse0owUDt5ha4IHhzpPI0vl1myOtasbMcnwm5m%2F4A%2B18m8NmpE56NCAVy3QcoDAHEJUers0U35N57bs8tmWh8eZa6pBJk8qwVQdRKMbjV1EwsxiHQeUlP68BLGblfnsNUKiMhHNnVn0m%2FJt46Pt6eUeWh7FXQeqpNnCbdB13HVISZjdsZh6Pzcl0hpH4IzTXIjUUA8iCO4WiAQYQYWhVm22Bb%2F4kNb74i5YaLGplGRzj3LPGue22aDp%2FAry3Gbq4wMpm4vGd0Z816RsNw%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47986776 (46M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.37.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.41M 32s
    50K .......... .......... .......... .......... ..........  0% 2.03M 27s
   100K .......... .......... .......... .......... ..........  0% 6.71M 21s
   150K .......... .......... .......... .......... ..........  0% 3.75M 18s
   200K .......... .......... .......... .......... ..........  0% 7.13M 16s
   250K .......... .......... .......... .......... ..........  0% 8.81M 14s
   300K .......... .......... .......... .......... ..........  0% 11.3M 13s
   350K .......... .......... .......... .......... ..........  0% 8.85M 12s
   400K .......... .......... .......... .......... ..........  0% 10.1M 11s
   450K .......... .......... .......... .......... ..........  1% 12.9M 10s
   500K .......... .......... .......... .......... ..........  1% 11.4M 10s
   550K .......... .......... .......... .......... ..........  1% 7.68M 9s
   600K .......... .......... .......... .......... ..........  1% 21.0M 9s
   650K .......... .......... .......... .......... ..........  1% 14.6M 8s
   700K .......... .......... .......... .......... ..........  1% 13.9M 8s
   750K .......... .......... .......... .......... ..........  1% 15.4M 8s
   800K .......... .......... .......... .......... ..........  1% 12.0M 7s
   850K .......... .......... .......... .......... ..........  1% 9.11M 7s
   900K .......... .......... .......... .......... ..........  2% 15.7M 7s
   950K .......... .......... .......... .......... ..........  2% 11.4M 7s
  1000K .......... .......... .......... .......... ..........  2% 19.0M 7s
  1050K .......... .......... .......... .......... ..........  2% 9.17M 7s
  1100K .......... .......... .......... .......... ..........  2% 13.6M 6s
  1150K .......... .......... .......... .......... ..........  2% 9.54M 6s
  1200K .......... .......... .......... .......... ..........  2% 17.5M 6s
  1250K .......... .......... .......... .......... ..........  2% 9.90M 6s
  1300K .......... .......... .......... .......... ..........  2% 31.6M 6s
  1350K .......... .......... .......... .......... ..........  2% 10.6M 6s
  1400K .......... .......... .......... .......... ..........  3% 10.0M 6s
  1450K .......... .......... .......... .......... ..........  3% 30.4M 6s
  1500K .......... .......... .......... .......... ..........  3% 10.6M 6s
  1550K .......... .......... .......... .......... ..........  3% 11.2M 6s
  1600K .......... .......... .......... .......... ..........  3% 12.0M 5s
  1650K .......... .......... .......... .......... ..........  3% 12.9M 5s
  1700K .......... .......... .......... .......... ..........  3% 11.2M 5s
  1750K .......... .......... .......... .......... ..........  3% 18.8M 5s
  1800K .......... .......... .......... .......... ..........  3% 17.1M 5s
  1850K .......... .......... .......... .......... ..........  4% 9.85M 5s
  1900K .......... .......... .......... .......... ..........  4% 12.3M 5s
  1950K .......... .......... .......... .......... ..........  4% 10.3M 5s
  2000K .......... .......... .......... .......... ..........  4% 15.1M 5s
  2050K .......... .......... .......... .......... ..........  4% 11.9M 5s
  2100K .......... .......... .......... .......... ..........  4% 16.5M 5s
  2150K .......... .......... .......... .......... ..........  4% 12.4M 5s
  2200K .......... .......... .......... .......... ..........  4% 16.2M 5s
  2250K .......... .......... .......... .......... ..........  4% 12.6M 5s
  2300K .......... .......... .......... .......... ..........  5% 13.4M 5s
  2350K .......... .......... .......... .......... ..........  5% 8.24M 5s
  2400K .......... .......... .......... .......... ..........  5% 21.2M 5s
  2450K .......... .......... .......... .......... ..........  5% 10.2M 5s
  2500K .......... .......... .......... .......... ..........  5% 15.6M 5s
  2550K .......... .......... .......... .......... ..........  5% 17.9M 5s
  2600K .......... .......... .......... .......... ..........  5% 10.2M 5s
  2650K .......... .......... .......... .......... ..........  5% 12.6M 5s
  2700K .......... .......... .......... .......... ..........  5% 19.4M 5s
  2750K .......... .......... .......... .......... ..........  5% 8.17M 5s
  2800K .......... .......... .......... .......... ..........  6% 19.9M 4s
  2850K .......... .......... .......... .......... ..........  6% 10.1M 4s
  2900K .......... .......... .......... .......... ..........  6% 8.79M 4s
  2950K .......... .......... .......... .......... ..........  6% 11.3M 4s
  3000K .......... .......... .......... .......... ..........  6%  122M 4s
  3050K .......... .......... .......... .......... ..........  6% 11.7M 4s
  3100K .......... .......... .......... .......... ..........  6% 14.4M 4s
  3150K .......... .......... .......... .......... ..........  6% 9.42M 4s
  3200K .......... .......... .......... .......... ..........  6% 10.6M 4s
  3250K .......... .......... .......... .......... ..........  7% 17.0M 4s
  3300K .......... .......... .......... .......... ..........  7% 9.11M 4s
  3350K .......... .......... .......... .......... ..........  7% 12.0M 4s
  3400K .......... .......... .......... .......... ..........  7% 14.9M 4s
  3450K .......... .......... .......... .......... ..........  7% 17.2M 4s
  3500K .......... .......... .......... .......... ..........  7% 21.7M 4s
  3550K .......... .......... .......... .......... ..........  7% 8.70M 4s
  3600K .......... .......... .......... .......... ..........  7% 13.2M 4s
  3650K .......... .......... .......... .......... ..........  7% 12.9M 4s
  3700K .......... .......... .......... .......... ..........  8% 13.0M 4s
  3750K .......... .......... .......... .......... ..........  8% 18.3M 4s
  3800K .......... .......... .......... .......... ..........  8% 9.81M 4s
  3850K .......... .......... .......... .......... ..........  8% 14.5M 4s
  3900K .......... .......... .......... .......... ..........  8% 21.2M 4s
  3950K .......... .......... .......... .......... ..........  8% 7.27M 4s
  4000K .......... .......... .......... .......... ..........  8% 21.9M 4s
  4050K .......... .......... .......... .......... ..........  8% 7.40M 4s
  4100K .......... .......... .......... .......... ..........  8% 36.3M 4s
  4150K .......... .......... .......... .......... ..........  8% 13.1M 4s
  4200K .......... .......... .......... .......... ..........  9% 13.2M 4s
  4250K .......... .......... .......... .......... ..........  9% 9.32M 4s
  4300K .......... .......... .......... .......... ..........  9% 32.9M 4s
  4350K .......... .......... .......... .......... ..........  9% 8.24M 4s
  4400K .......... .......... .......... .......... ..........  9% 14.3M 4s
  4450K .......... .......... .......... .......... ..........  9% 12.4M 4s
  4500K .......... .......... .......... .......... ..........  9% 10.8M 4s
  4550K .......... .......... .......... .......... ..........  9% 19.0M 4s
  4600K .......... .......... .......... .......... ..........  9% 12.9M 4s
  4650K .......... .......... .......... .......... .......... 10% 11.6M 4s
  4700K .......... .......... .......... .......... .......... 10% 11.0M 4s
  4750K .......... .......... .......... .......... .......... 10% 12.8M 4s
  4800K .......... .......... .......... .......... .......... 10% 16.3M 4s
  4850K .......... .......... .......... .......... .......... 10% 11.0M 4s
  4900K .......... .......... .......... .......... .......... 10% 18.3M 4s
  4950K .......... .......... .......... .......... .......... 10% 13.3M 4s
  5000K .......... .......... .......... .......... .......... 10% 10.4M 4s
  5050K .......... .......... .......... .......... .......... 10% 12.0M 4s
  5100K .......... .......... .......... .......... .......... 10% 23.9M 4s
  5150K .......... .......... .......... .......... .......... 11% 8.30M 4s
  5200K .......... .......... .......... .......... .......... 11% 22.4M 4s
  5250K .......... .......... .......... .......... .......... 11% 7.70M 4s
  5300K .......... .......... .......... .......... .......... 11% 25.1M 4s
  5350K .......... .......... .......... .......... .......... 11% 10.8M 4s
  5400K .......... .......... .......... .......... .......... 11% 18.6M 4s
  5450K .......... .......... .......... .......... .......... 11% 11.3M 4s
  5500K .......... .......... .......... .......... .......... 11% 10.6M 4s
  5550K .......... .......... .......... .......... .......... 11% 12.8M 4s
  5600K .......... .......... .......... .......... .......... 12% 7.29M 4s
  5650K .......... .......... .......... .......... .......... 12% 73.3M 4s
  5700K .......... .......... .......... .......... .......... 12% 9.86M 4s
  5750K .......... .......... .......... .......... .......... 12% 27.8M 4s
  5800K .......... .......... .......... .......... .......... 12% 11.9M 4s
  5850K .......... .......... .......... .......... .......... 12% 15.1M 4s
  5900K .......... .......... .......... .......... .......... 12% 12.1M 4s
  5950K .......... .......... .......... .......... .......... 12% 7.36M 4s
  6000K .......... .......... .......... .......... .......... 12% 26.4M 4s
  6050K .......... .......... .......... .......... .......... 13% 8.81M 4s
  6100K .......... .......... .......... .......... .......... 13% 22.8M 4s
  6150K .......... .......... .......... .......... .......... 13% 12.1M 4s
  6200K .......... .......... .......... .......... .......... 13% 18.7M 4s
  6250K .......... .......... .......... .......... .......... 13% 13.9M 4s
  6300K .......... .......... .......... .......... .......... 13% 9.29M 4s
  6350K .......... .......... .......... .......... .......... 13% 11.6M 4s
  6400K .......... .......... .......... .......... .......... 13% 14.7M 4s
  6450K .......... .......... .......... .......... .......... 13% 12.0M 4s
  6500K .......... .......... .......... .......... .......... 13% 12.5M 4s
  6550K .......... .......... .......... .......... .......... 14% 17.8M 4s
  6600K .......... .......... .......... .......... .......... 14% 11.1M 4s
  6650K .......... .......... .......... .......... .......... 14% 13.0M 4s
  6700K .......... .......... .......... .......... .......... 14% 19.5M 3s
  6750K .......... .......... .......... .......... .......... 14% 2.80M 4s
  6800K .......... .......... .......... .......... .......... 14%  173M 4s
  6850K .......... .......... .......... .......... .......... 14%  284M 4s
  6900K .......... .......... .......... .......... .......... 14%  367M 3s
  6950K .......... .......... .......... .......... .......... 14% 20.4M 3s
  7000K .......... .......... .......... .......... .......... 15% 16.9M 3s
  7050K .......... .......... .......... .......... .......... 15% 5.69M 3s
  7100K .......... .......... .......... .......... .......... 15%  184M 3s
  7150K .......... .......... .......... .......... .......... 15% 11.8M 3s
  7200K .......... .......... .......... .......... .......... 15% 15.4M 3s
  7250K .......... .......... .......... .......... .......... 15% 12.6M 3s
  7300K .......... .......... .......... .......... .......... 15% 10.9M 3s
  7350K .......... .......... .......... .......... .......... 15% 18.3M 3s
  7400K .......... .......... .......... .......... .......... 15% 9.89M 3s
  7450K .......... .......... .......... .......... .......... 16% 17.6M 3s
  7500K .......... .......... .......... .......... .......... 16% 18.5M 3s
  7550K .......... .......... .......... .......... .......... 16% 8.42M 3s
  7600K .......... .......... .......... .......... .......... 16% 12.5M 3s
  7650K .......... .......... .......... .......... .......... 16% 8.35M 3s
  7700K .......... .......... .......... .......... .......... 16% 26.3M 3s
  7750K .......... .......... .......... .......... .......... 16% 15.8M 3s
  7800K .......... .......... .......... .......... .......... 16% 9.69M 3s
  7850K .......... .......... .......... .......... .......... 16% 23.1M 3s
  7900K .......... .......... .......... .......... .......... 16% 10.7M 3s
  7950K .......... .......... .......... .......... .......... 17% 11.1M 3s
  8000K .......... .......... .......... .......... .......... 17% 11.2M 3s
  8050K .......... .......... .......... .......... .......... 17% 12.5M 3s
  8100K .......... .......... .......... .......... .......... 17% 22.3M 3s
  8150K .......... .......... .......... .......... .......... 17% 9.57M 3s
  8200K .......... .......... .......... .......... .......... 17% 16.1M 3s
  8250K .......... .......... .......... .......... .......... 17% 10.2M 3s
  8300K .......... .......... .......... .......... .......... 17% 44.0M 3s
  8350K .......... .......... .......... .......... .......... 17% 7.67M 3s
  8400K .......... .......... .......... .......... .......... 18% 10.1M 3s
  8450K .......... .......... .......... .......... .......... 18% 24.3M 3s
  8500K .......... .......... .......... .......... .......... 18% 10.6M 3s
  8550K .......... .......... .......... .......... .......... 18% 21.9M 3s
  8600K .......... .......... .......... .......... .......... 18% 10.9M 3s
  8650K .......... .......... .......... .......... .......... 18% 7.22M 3s
  8700K .......... .......... .......... .......... .......... 18% 27.4M 3s
  8750K .......... .......... .......... .......... .......... 18% 11.9M 3s
  8800K .......... .......... .......... .......... .......... 18% 9.33M 3s
  8850K .......... .......... .......... .......... .......... 18% 60.1M 3s
  8900K .......... .......... .......... .......... .......... 19% 13.3M 3s
  8950K .......... .......... .......... .......... .......... 19% 9.79M 3s
  9000K .......... .......... .......... .......... .......... 19% 27.1M 3s
  9050K .......... .......... .......... .......... .......... 19% 8.89M 3s
  9100K .......... .......... .......... .......... .......... 19% 14.7M 3s
  9150K .......... .......... .......... .......... .......... 19% 8.87M 3s
  9200K .......... .......... .......... .......... .......... 19% 19.2M 3s
  9250K .......... .......... .......... .......... .......... 19% 13.2M 3s
  9300K .......... .......... .......... .......... .......... 19% 11.2M 3s
  9350K .......... .......... .......... .......... .......... 20% 13.0M 3s
  9400K .......... .......... .......... .......... .......... 20% 14.9M 3s
  9450K .......... .......... .......... .......... .......... 20% 11.8M 3s
  9500K .......... .......... .......... .......... .......... 20% 14.4M 3s
  9550K .......... .......... .......... .......... .......... 20% 9.15M 3s
  9600K .......... .......... .......... .......... .......... 20% 9.53M 3s
  9650K .......... .......... .......... .......... .......... 20% 61.5M 3s
  9700K .......... .......... .......... .......... .......... 20% 10.1M 3s
  9750K .......... .......... .......... .......... .......... 20% 13.0M 3s
  9800K .......... .......... .......... .......... .......... 21% 22.8M 3s
  9850K .......... .......... .......... .......... .......... 21% 11.9M 3s
  9900K .......... .......... .......... .......... .......... 21% 8.71M 3s
  9950K .......... .......... .......... .......... .......... 21% 9.75M 3s
 10000K .......... .......... .......... .......... .......... 21% 19.4M 3s
 10050K .......... .......... .......... .......... .......... 21% 9.66M 3s
 10100K .......... .......... .......... .......... .......... 21% 21.0M 3s
 10150K .......... .......... .......... .......... .......... 21% 15.2M 3s
 10200K .......... .......... .......... .......... .......... 21% 12.5M 3s
 10250K .......... .......... .......... .......... .......... 21% 16.2M 3s
 10300K .......... .......... .......... .......... .......... 22% 11.0M 3s
 10350K .......... .......... .......... .......... .......... 22% 12.3M 3s
 10400K .......... .......... .......... .......... .......... 22% 9.89M 3s
 10450K .......... .......... .......... .......... .......... 22% 18.5M 3s
 10500K .......... .......... .......... .......... .......... 22% 11.5M 3s
 10550K .......... .......... .......... .......... .......... 22% 11.7M 3s
 10600K .......... .......... .......... .......... .......... 22% 19.8M 3s
 10650K .......... .......... .......... .......... .......... 22% 9.71M 3s
 10700K .......... .......... .......... .......... .......... 22% 15.5M 3s
 10750K .......... .......... .......... .......... .......... 23% 11.6M 3s
 10800K .......... .......... .......... .......... .......... 23% 12.8M 3s
 10850K .......... .......... .......... .......... .......... 23% 17.3M 3s
 10900K .......... .......... .......... .......... .......... 23% 11.7M 3s
 10950K .......... .......... .......... .......... .......... 23% 10.3M 3s
 11000K .......... .......... .......... .......... .......... 23% 11.8M 3s
 11050K .......... .......... .......... .......... .......... 23% 13.2M 3s
 11100K .......... .......... .......... .......... .......... 23% 12.2M 3s
 11150K .......... .......... .......... .......... .......... 23% 11.5M 3s
 11200K .......... .......... .......... .......... .......... 24% 24.0M 3s
 11250K .......... .......... .......... .......... .......... 24% 12.8M 3s
 11300K .......... .......... .......... .......... .......... 24% 8.33M 3s
 11350K .......... .......... .......... .......... .......... 24% 19.5M 3s
 11400K .......... .......... .......... .......... .......... 24% 12.2M 3s
 11450K .......... .......... .......... .......... .......... 24% 13.3M 3s
 11500K .......... .......... .......... .......... .......... 24% 24.4M 3s
 11550K .......... .......... .......... .......... .......... 24% 6.61M 3s

Downloading atb.assembly.r0.2.batch.73.tar.xz from https://osf.io/download/66714d196b6c8e340104cd8a/

--2026-09-06 18:52:29--  https://osf.io/download/66714d196b6c8e340104cd8a/
Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d196b6c8e340104cd8a [following]
--2026-09-06 18:52:30--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d196b6c8e340104cd8a
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/d6b5d156654996750ffe961b48a978bf0b251798bfeddae474ed2338bc4c48f0?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.73.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.73.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713610&Signature=MVhdBKmYxoLW9uJXKh7Hf2re5SRXvEFvQ%2BrIJNn3cF%2FZ9JEGV8t%2Fpdz82Q3UxlB7Ipx1O9X1bDhkcb85uQxJ1cjjXMuvdLEy3RSF5iMBk70%2Fb7gOKlrQRkRmuIC4pJEb78eBykxy7Sdi2CImtp3Kanh9KQjCXRTkJL%2Bs219AyYjml1YQUnu4yQmZJQdH1wKQlYtXyQmrnOlxHOnl3BrVauUHwSe4jRCjAmhlYWl5CBHEb0aDfdR3V6eXFFW7WwIiykf0Mf40Jiky%2Bu82eAK7PYXAC%2B%2BVTld2vXYzFmxkvqWFnE3xN8JZRnnyPiWDAQD3%2BeLOcW0uFwK8hGBEGCmwGw%3D%3D [following]
--2026-09-06 18:52:30--  https://storage.googleapis.com/cos-osf-prod-files-de-1/d6b5d156654996750ffe961b48a978bf0b251798bfeddae474ed2338bc4c48f0?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.73.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.73.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713610&Signature=MVhdBKmYxoLW9uJXKh7Hf2re5SRXvEFvQ%2BrIJNn3cF%2FZ9JEGV8t%2Fpdz82Q3UxlB7Ipx1O9X1bDhkcb85uQxJ1cjjXMuvdLEy3RSF5iMBk70%2Fb7gOKlrQRkRmuIC4pJEb78eBykxy7Sdi2CImtp3Kanh9KQjCXRTkJL%2Bs219AyYjml1YQUnu4yQmZJQdH1wKQlYtXyQmrnOlxHOnl3BrVauUHwSe4jRCjAmhlYWl5CBHEb0aDfdR3V6eXFFW7WwIiykf0Mf40Jiky%2Bu82eAK7PYXAC%2B%2BVTld2vXYzFmxkvqWFnE3xN8JZRnnyPiWDAQD3%2BeLOcW0uFwK8hGBEGCmwGw%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6591356 (6.3M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.73.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.29M 5s
    50K .......... .......... .......... .......... ..........  1% 2.79M 4s
   100K .......... .......... .......... .......... ..........  2% 4.37M 3s
   150K .......... .......... .......... .......... ..........  3% 4.72M 2s
   200K .......... .......... .......... .......... ..........  3% 6.32M 2s
   250K .......... .......... .......... .......... ..........  4% 16.7M 2s
   300K .......... .......... .......... .......... ..........  5% 9.92M 2s
   350K .......... .......... .......... .......... ..........  6% 8.36M 1s
   400K .......... .......... .......... .......... ..........  6% 11.1M 1s
   450K .......... .......... .......... .......... ..........  7% 9.00M 1s
   500K .......... .......... .......... .......... ..........  8% 17.8M 1s
   550K .......... .......... .......... .......... ..........  9% 12.8M 1s
   600K .......... .......... .......... .......... .......... 10% 15.3M 1s
   650K .......... .......... .......... .......... .......... 10% 11.2M 1s
   700K .......... .......... .......... .......... .......... 11% 10.3M 1s
   750K .......... .......... .......... .......... .......... 12% 12.1M 1s
   800K .......... .......... .......... .......... .......... 13% 10.7M 1s
   850K .......... .......... .......... .......... .......... 13% 25.6M 1s
   900K .......... .......... .......... .......... .......... 14% 12.4M 1s
   950K .......... .......... .......... .......... .......... 15% 12.5M 1s
  1000K .......... .......... .......... .......... .......... 16% 13.3M 1s
  1050K .......... .......... .......... .......... .......... 17% 9.30M 1s
  1100K .......... .......... .......... .......... .......... 17% 16.3M 1s
  1150K .......... .......... .......... .......... .......... 18% 11.9M 1s
  1200K .......... .......... .......... .......... .......... 19% 13.5M 1s
  1250K .......... .......... .......... .......... .......... 20% 9.10M 1s
  1300K .......... .......... .......... .......... .......... 20% 26.7M 1s
  1350K .......... .......... .......... .......... .......... 21% 10.9M 1s
  1400K .......... .......... .......... .......... .......... 22% 14.6M 1s
  1450K .......... .......... .......... .......... .......... 23% 17.1M 1s
  1500K .......... .......... .......... .......... .......... 24% 11.1M 1s
  1550K .......... .......... .......... .......... .......... 24% 12.2M 1s
  1600K .......... .......... .......... .......... .......... 25% 10.7M 1s
  1650K .......... .......... .......... .......... .......... 26% 12.6M 1s
  1700K .......... .......... .......... .......... .......... 27% 23.3M 1s
  1750K .......... .......... .......... .......... .......... 27% 10.4M 1s
  1800K .......... .......... .......... .......... .......... 28% 14.2M 1s
  1850K .......... .......... .......... .......... .......... 29% 11.5M 1s
  1900K .......... .......... .......... .......... .......... 30% 14.6M 1s
  1950K .......... .......... .......... .......... .......... 31% 8.53M 0s
  2000K .......... .......... .......... .......... .......... 31% 22.0M 0s
  2050K .......... .......... .......... .......... .......... 32% 10.8M 0s
  2100K .......... .......... .......... .......... .......... 33% 7.34M 0s
  2150K .......... .......... .......... .......... .......... 34% 89.1M 0s
  2200K .......... .......... .......... .......... .......... 34% 14.7M 0s
  2250K .......... .......... .......... .......... .......... 35% 12.4M 0s
  2300K .......... .......... .......... .......... .......... 36% 8.61M 0s
  2350K .......... .......... .......... .......... .......... 37% 17.5M 0s
  2400K .......... .......... .......... .......... .......... 38% 9.72M 0s
  2450K .......... .......... .......... .......... .......... 38% 23.2M 0s
  2500K .......... .......... .......... .......... .......... 39% 7.15M 0s
  2550K .......... .......... .......... .......... .......... 40% 29.2M 0s
  2600K .......... .......... .......... .......... .......... 41% 18.4M 0s
  2650K .......... .......... .......... .......... .......... 41% 11.5M 0s
  2700K .......... .......... .......... .......... .......... 42% 14.3M 0s
  2750K .......... .......... .......... .......... .......... 43% 12.6M 0s
  2800K .......... .......... .......... .......... .......... 44% 13.8M 0s
  2850K .......... .......... .......... .......... .......... 45% 10.1M 0s
  2900K .......... .......... .......... .......... .......... 45% 14.4M 0s
  2950K .......... .......... .......... .......... .......... 46% 10.7M 0s
  3000K .......... .......... .......... .......... .......... 47% 12.9M 0s
  3050K .......... .......... .......... .......... .......... 48% 17.4M 0s
  3100K .......... .......... .......... .......... .......... 48% 11.3M 0s
  3150K .......... .......... .......... .......... .......... 49% 10.8M 0s
  3200K .......... .......... .......... .......... .......... 50% 17.7M 0s
  3250K .......... .......... .......... .......... .......... 51% 10.5M 0s
  3300K .......... .......... .......... .......... .......... 52% 10.9M 0s
  3350K .......... .......... .......... .......... .......... 52% 19.7M 0s
  3400K .......... .......... .......... .......... .......... 53% 12.2M 0s
  3450K .......... .......... .......... .......... .......... 54% 11.6M 0s
  3500K .......... .......... .......... .......... .......... 55% 14.7M 0s
  3550K .......... .......... .......... .......... .......... 55% 9.62M 0s
  3600K .......... .......... .......... .......... .......... 56% 12.4M 0s
  3650K .......... .......... .......... .......... .......... 57% 25.2M 0s
  3700K .......... .......... .......... .......... .......... 58% 9.03M 0s
  3750K .......... .......... .......... .......... .......... 59% 23.6M 0s
  3800K .......... .......... .......... .......... .......... 59% 14.0M 0s
  3850K .......... .......... .......... .......... .......... 60% 8.38M 0s
  3900K .......... .......... .......... .......... .......... 61% 12.9M 0s
  3950K .......... .......... .......... .......... .......... 62% 13.1M 0s
  4000K .......... .......... .......... .......... .......... 62% 9.26M 0s
  4050K .......... .......... .......... .......... .......... 63% 31.6M 0s
  4100K .......... .......... .......... .......... .......... 64% 9.54M 0s
  4150K .......... .......... .......... .......... .......... 65% 9.67M 0s
  4200K .......... .......... .......... .......... .......... 66% 30.3M 0s
  4250K .......... .......... .......... .......... .......... 66% 9.87M 0s
  4300K .......... .......... .......... .......... .......... 67% 16.8M 0s
  4350K .......... .......... .......... .......... .......... 68% 9.47M 0s
  4400K .......... .......... .......... .......... .......... 69% 20.4M 0s
  4450K .......... .......... .......... .......... .......... 69% 10.8M 0s
  4500K .......... .......... .......... .......... .......... 70% 10.3M 0s
  4550K .......... .......... .......... .......... .......... 71% 17.2M 0s
  4600K .......... .......... .......... .......... .......... 72% 12.8M 0s
  4650K .......... .......... .......... .......... .......... 73% 18.4M 0s
  4700K .......... .......... .......... .......... .......... 73% 11.8M 0s
  4750K .......... .......... .......... .......... .......... 74% 7.91M 0s
  4800K .......... .......... .......... .......... .......... 75% 37.9M 0s
  4850K .......... .......... .......... .......... .......... 76% 10.5M 0s
  4900K .......... .......... .......... .......... .......... 76% 12.4M 0s
  4950K .......... .......... .......... .......... .......... 77% 19.8M 0s
  5000K .......... .......... .......... .......... .......... 78% 15.9M 0s
  5050K .......... .......... .......... .......... .......... 79% 9.93M 0s
  5100K .......... .......... .......... .......... .......... 80% 12.8M 0s
  5150K .......... .......... .......... .......... .......... 80% 7.47M 0s
  5200K .......... .......... .......... .......... .......... 81% 27.5M 0s
  5250K .......... .......... .......... .......... .......... 82% 11.0M 0s
  5300K .......... .......... .......... .......... .......... 83% 12.1M 0s
  5350K .......... .......... .......... .......... .......... 83% 18.6M 0s
  5400K .......... .......... .......... .......... .......... 84% 13.0M 0s
  5450K .......... .......... .......... .......... .......... 85% 13.7M 0s
  5500K .......... .......... .......... .......... .......... 86% 11.5M 0s
  5550K .......... .......... .......... .......... .......... 86% 14.2M 0s
  5600K .......... .......... .......... .......... .......... 87% 8.49M 0s
  5650K .......... .......... .......... .......... .......... 88% 22.3M 0s
  5700K .......... .......... .......... .......... .......... 89% 9.79M 0s
  5750K .......... .......... .......... .......... .......... 90% 21.5M 0s
  5800K .......... .......... .......... .......... .......... 90% 13.9M 0s
  5850K .......... .......... .......... .......... .......... 91% 11.2M 0s
  5900K .......... .......... .......... .......... .......... 92% 24.3M 0s
  5950K .......... .......... .......... .......... .......... 93% 8.12M 0s
  6000K .......... .......... .......... .......... .......... 93% 12.8M 0s
  6050K .......... .......... .......... .......... .......... 94% 13.5M 0s
  6100K .......... .......... .......... .......... .......... 95% 9.00M 0s
  6150K .......... .......... .......... .......... .......... 96% 12.5M 0s
  6200K .......... .......... .......... .......... .......... 97% 17.9M 0s
  6250K .......... .......... .......... .......... .......... 97% 25.8M 0s
  6300K .......... .......... .......... .......... .......... 98% 11.4M 0s
  6350K .......... .......... .......... .......... .......... 99% 8.83M 0s
  6400K .......... .......... .......... ......               100% 48.9M=0.6s

2026-09-06 18:52:31 (11.2 MB/s) - 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.73.tar.xz' saved [6591356/6591356]

  4%|▍         | 17/436 [01:19<31:32,  4.52s/it]--2026-09-06 18:52:31--  https://osf.io/download/66714d1e65e1de5e79893fd1/
Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.

Downloading atb.assembly.r0.2.batch.74.tar.xz from https://osf.io/download/66714d1e65e1de5e79893fd1/

HTTP request sent, awaiting response... 302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d1e65e1de5e79893fd1 [following]
--2026-09-06 18:52:31--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d1e65e1de5e79893fd1
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/02bfa6a8e6932d7e86f1b4a78ca94b14be0dc7a21d838632850601730e033d6e?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.74.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.74.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713612&Signature=NWTXUOLYSvpPiqs35KNdrsvtBd7FxJTE47g0dQhxaPeDp708EBlflNmLKRqg7knLstIRKmT5mh3PuwUIulPZbzXrx56Vs%2F1RghkfVpVSPou3EqtKLi3Em4o3w3obTqHgEc%2BJcEdaGVnZW%2BzEaxxoVuCFGd5%2BIOlD1E%2BdybvkGAkI9cHY35QNB5J8yroNVJCYEMQy0DgcNeelI7Ykg7x9XfoRd7uCK6CZYiFFpe0tJJ04rvL%2BDErssDjPnrMyoPY5ntPih3sF%2Fh0QwOMHYb7ryru2jSwyvMuiuazLANYn0AIXxn32uE12B%2FkGXb94R0tx2S47Bs5vfRiQF5isbQHrsQ%3D%3D [following]
--2026-09-06 18:52:32--  https://storage.googleapis.com/cos-osf-prod-files-de-1/02bfa6a8e6932d7e86f1b4a78ca94b14be0dc7a21d838632850601730e033d6e?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.74.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.74.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713612&Signature=NWTXUOLYSvpPiqs35KNdrsvtBd7FxJTE47g0dQhxaPeDp708EBlflNmLKRqg7knLstIRKmT5mh3PuwUIulPZbzXrx56Vs%2F1RghkfVpVSPou3EqtKLi3Em4o3w3obTqHgEc%2BJcEdaGVnZW%2BzEaxxoVuCFGd5%2BIOlD1E%2BdybvkGAkI9cHY35QNB5J8yroNVJCYEMQy0DgcNeelI7Ykg7x9XfoRd7uCK6CZYiFFpe0tJJ04rvL%2BDErssDjPnrMyoPY5ntPih3sF%2Fh0QwOMHYb7ryru2jSwyvMuiuazLANYn0AIXxn32uE12B%2FkGXb94R0tx2S47Bs5vfRiQF5isbQHrsQ%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13802632 (13M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.74.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.28M 10s
    50K .......... .......... .......... .......... ..........  0% 2.48M 8s
   100K .......... .......... .......... .......... ..........  1% 2.58M 7s
   150K .......... .......... .......... .......... ..........  1% 7.67M 6s
   200K .......... .......... .......... .......... ..........  1% 7.89M 5s
   250K .......... .......... .......... .......... ..........  2% 5.58M 4s
   300K .......... .......... .......... .......... ..........  2% 9.93M 4s
   350K .......... .......... .......... .......... ..........  2% 9.52M 4s
   400K .......... .......... .......... .......... ..........  3% 18.2M 3s
   450K .......... .......... .......... .......... ..........  3% 10.1M 3s
   500K .......... .......... .......... .......... ..........  4% 14.6M 3s
   550K .......... .......... .......... .......... ..........  4% 11.0M 3s
   600K .......... .......... .......... .......... ..........  4% 13.3M 3s
   650K .......... .......... .......... .......... ..........  5% 18.2M 2s
   700K .......... .......... .......... .......... ..........  5% 10.8M 2s
   750K .......... .......... .......... .......... ..........  5% 10.6M 2s
   800K .......... .......... .......... .......... ..........  6% 13.9M 2s
   850K .......... .......... .......... .......... ..........  6% 11.8M 2s
   900K .......... .......... .......... .......... ..........  7% 12.6M 2s
   950K .......... .......... .......... .......... ..........  7% 14.7M 2s
  1000K .......... .......... .......... .......... ..........  7% 15.0M 2s
  1050K .......... .......... .......... .......... ..........  8% 11.8M 2s
  1100K .......... .......... .......... .......... ..........  8% 13.9M 2s
  1150K .......... .......... .......... .......... ..........  8% 9.15M 2s
  1200K .......... .......... .......... .......... ..........  9% 18.9M 2s
  1250K .......... .......... .......... .......... ..........  9% 11.6M 2s
  1300K .......... .......... .......... .......... .......... 10% 9.81M 2s
  1350K .......... .......... .......... .......... .......... 10% 38.4M 2s
  1400K .......... .......... .......... .......... .......... 10% 11.4M 2s
  1450K .......... .......... .......... .......... .......... 11% 13.2M 2s
  1500K .......... .......... .......... .......... .......... 11% 16.2M 1s
  1550K .......... .......... .......... .......... .......... 11% 7.93M 1s
  1600K .......... .......... .......... .......... .......... 12% 12.2M 1s
  1650K .......... .......... .......... .......... .......... 12% 12.4M 1s
  1700K .......... .......... .......... .......... .......... 12% 11.0M 1s
  1750K .......... .......... .......... .......... .......... 13% 13.3M 1s
  1800K .......... .......... .......... .......... .......... 13% 20.7M 1s
  1850K .......... .......... .......... .......... .......... 14% 11.9M 1s
  1900K .......... .......... .......... .......... .......... 14% 14.9M 1s
  1950K .......... .......... .......... .......... .......... 14% 15.0M 1s
  2000K .......... .......... .......... .......... .......... 15% 9.65M 1s
  2050K .......... .......... .......... .......... .......... 15% 13.2M 1s
  2100K .......... .......... .......... .......... .......... 15% 13.5M 1s
  2150K .......... .......... .......... .......... .......... 16% 17.5M 1s
  2200K .......... .......... .......... .......... .......... 16% 10.9M 1s
  2250K .......... .......... .......... .......... .......... 17% 15.9M 1s
  2300K .......... .......... .......... .......... .......... 17% 10.5M 1s
  2350K .......... .......... .......... .......... .......... 17% 9.27M 1s
  2400K .......... .......... .......... .......... .......... 18% 14.1M 1s
  2450K .......... .......... .......... .......... .......... 18% 15.2M 1s
  2500K .......... .......... .......... .......... .......... 18% 15.1M 1s
  2550K .......... .......... .......... .......... .......... 19% 14.5M 1s
  2600K .......... .......... .......... .......... .......... 19% 8.72M 1s
  2650K .......... .......... .......... .......... .......... 20% 12.1M 1s
  2700K .......... .......... .......... .......... .......... 20% 27.1M 1s
  2750K .......... .......... .......... .......... .......... 20% 8.14M 1s
  2800K .......... .......... .......... .......... .......... 21% 18.8M 1s
  2850K .......... .......... .......... .......... .......... 21% 15.7M 1s
  2900K .......... .......... .......... .......... .......... 21% 10.3M 1s
  2950K .......... .......... .......... .......... .......... 22% 14.6M 1s
  3000K .......... .......... .......... .......... .......... 22% 14.0M 1s
  3050K .......... .......... .......... .......... .......... 22% 9.12M 1s
  3100K .......... .......... .......... .......... .......... 23% 14.9M 1s
  3150K .......... .......... .......... .......... .......... 23% 13.0M 1s
  3200K .......... .......... .......... .......... .......... 24% 12.1M 1s
  3250K .......... .......... .......... .......... .......... 24% 13.0M 1s
  3300K .......... .......... .......... .......... .......... 24% 12.8M 1s
  3350K .......... .......... .......... .......... .......... 25% 15.8M 1s
  3400K .......... .......... .......... .......... .......... 25% 12.5M 1s
  3450K .......... .......... .......... .......... .......... 25% 18.1M 1s
  3500K .......... .......... .......... .......... .......... 26% 9.14M 1s
  3550K .......... .......... .......... .......... .......... 26% 11.8M 1s
  3600K .......... .......... .......... .......... .......... 27% 13.3M 1s
  3650K .......... .......... .......... .......... .......... 27% 11.8M 1s
  3700K .......... .......... .......... .......... .......... 27% 15.1M 1s
  3750K .......... .......... .......... .......... .......... 28% 12.3M 1s
  3800K .......... .......... .......... .......... .......... 28% 13.6M 1s
  3850K .......... .......... .......... .......... .......... 28% 13.7M 1s
  3900K .......... .......... .......... .......... .......... 29% 14.5M 1s
  3950K .......... .......... .......... .......... .......... 29% 7.25M 1s
  4000K .......... .......... .......... .......... .......... 30% 33.4M 1s
  4050K .......... .......... .......... .......... .......... 30% 12.5M 1s
  4100K .......... .......... .......... .......... .......... 30% 12.9M 1s
  4150K .......... .......... .......... .......... .......... 31% 12.7M 1s
  4200K .......... .......... .......... .......... .......... 31% 12.3M 1s
  4250K .......... .......... .......... .......... .......... 31% 11.8M 1s
  4300K .......... .......... .......... .......... .......... 32% 23.0M 1s
  4350K .......... .......... .......... .......... .......... 32% 10.3M 1s
  4400K .......... .......... .......... .......... .......... 33% 7.48M 1s
  4450K .......... .......... .......... .......... .......... 33% 37.2M 1s
  4500K .......... .......... .......... .......... .......... 33% 16.6M 1s
  4550K .......... .......... .......... .......... .......... 34% 8.73M 1s
  4600K .......... .......... .......... .......... .......... 34% 14.0M 1s
  4650K .......... .......... .......... .......... .......... 34% 20.3M 1s
  4700K .......... .......... .......... .......... .......... 35% 9.84M 1s
  4750K .......... .......... .......... .......... .......... 35% 10.2M 1s
  4800K .......... .......... .......... .......... .......... 35% 12.0M 1s
  4850K .......... .......... .......... .......... .......... 36% 16.7M 1s
  4900K .......... .......... .......... .......... .......... 36% 17.6M 1s
  4950K .......... .......... .......... .......... .......... 37% 8.74M 1s
  5000K .......... .......... .......... .......... .......... 37% 17.8M 1s
  5050K .......... .......... .......... .......... .......... 37% 12.9M 1s
  5100K .......... .......... .......... .......... .......... 38% 13.9M 1s
  5150K .......... .......... .......... .......... .......... 38% 9.36M 1s
  5200K .......... .......... .......... .......... .......... 38% 23.3M 1s
  5250K .......... .......... .......... .......... .......... 39% 9.02M 1s
  5300K .......... .......... .......... .......... .......... 39% 13.4M 1s
  5350K .......... .......... .......... .......... .......... 40% 13.6M 1s
  5400K .......... .......... .......... .......... .......... 40% 17.0M 1s
  5450K .......... .......... .......... .......... .......... 40% 15.7M 1s
  5500K .......... .......... .......... .......... .......... 41% 10.8M 1s
  5550K .......... .......... .......... .......... .......... 41% 8.41M 1s
  5600K .......... .......... .......... .......... .......... 41% 28.8M 1s
  5650K .......... .......... .......... .......... .......... 42% 8.36M 1s
  5700K .......... .......... .......... .......... .......... 42% 15.5M 1s
  5750K .......... .......... .......... .......... .......... 43% 16.7M 1s
  5800K .......... .......... .......... .......... .......... 43% 12.6M 1s
  5850K .......... .......... .......... .......... .......... 43% 14.3M 1s
  5900K .......... .......... .......... .......... .......... 44% 12.6M 1s
  5950K .......... .......... .......... .......... .......... 44% 7.69M 1s
  6000K .......... .......... .......... .......... .......... 44% 16.9M 1s
  6050K .......... .......... .......... .......... .......... 45% 13.1M 1s
  6100K .......... .......... .......... .......... .......... 45% 22.4M 1s
  6150K .......... .......... .......... .......... .......... 45% 12.6M 1s
  6200K .......... .......... .......... .......... .......... 46% 11.0M 1s
  6250K .......... .......... .......... .......... .......... 46% 12.6M 1s
  6300K .......... .......... .......... .......... .......... 47% 12.9M 1s
  6350K .......... .......... .......... .......... .......... 47% 11.8M 1s
  6400K .......... .......... .......... .......... .......... 47% 17.9M 1s
  6450K .......... .......... .......... .......... .......... 48% 10.2M 1s
  6500K .......... .......... .......... .......... .......... 48% 12.5M 1s
  6550K .......... .......... .......... .......... .......... 48% 12.3M 1s
  6600K .......... .......... .......... .......... .......... 49% 13.1M 1s
  6650K .......... .......... .......... .......... .......... 49% 14.7M 1s
  6700K .......... .......... .......... .......... .......... 50% 15.1M 1s
  6750K .......... .......... .......... .......... .......... 50% 9.64M 1s
  6800K .......... .......... .......... .......... .......... 50% 13.3M 1s
  6850K .......... .......... .......... .......... .......... 51% 12.3M 1s
  6900K .......... .......... .......... .......... .......... 51% 15.9M 1s
  6950K .......... .......... .......... .......... .......... 51% 11.4M 1s
  7000K .......... .......... .......... .......... .......... 52% 16.9M 1s
  7050K .......... .......... .......... .......... .......... 52% 12.7M 1s
  7100K .......... .......... .......... .......... .......... 53% 13.6M 1s
  7150K .......... .......... .......... .......... .......... 53% 10.5M 1s
  7200K .......... .......... .......... .......... .......... 53% 11.9M 1s
  7250K .......... .......... .......... .......... .......... 54% 11.7M 1s
  7300K .......... .......... .......... .......... .......... 54% 18.5M 1s
  7350K .......... .......... .......... .......... .......... 54% 14.4M 1s
  7400K .......... .......... .......... .......... .......... 55% 12.9M 1s
  7450K .......... .......... .......... .......... .......... 55% 10.9M 1s
  7500K .......... .......... .......... .......... .......... 56% 12.1M 1s
  7550K .......... .......... .......... .......... .......... 56% 10.8M 1s
  7600K .......... .......... .......... .......... .......... 56% 17.8M 1s
  7650K .......... .......... .......... .......... .......... 57% 11.1M 0s
  7700K .......... .......... .......... .......... .......... 57% 13.4M 0s
  7750K .......... .......... .......... .......... .......... 57% 12.5M 0s
  7800K .......... .......... .......... .......... .......... 58% 13.5M 0s
  7850K .......... .......... .......... .......... .......... 58% 13.1M 0s
  7900K .......... .......... .......... .......... .......... 58% 12.0M 0s
  7950K .......... .......... .......... .......... .......... 59% 14.0M 0s
  8000K .......... .......... .......... .......... .......... 59% 9.37M 0s
  8050K .......... .......... .......... .......... .......... 60% 24.3M 0s
  8100K .......... .......... .......... .......... .......... 60% 8.20M 0s
  8150K .......... .......... .......... .......... .......... 60% 37.4M 0s
  8200K .......... .......... .......... .......... .......... 61% 8.84M 0s
  8250K .......... .......... .......... .......... .......... 61% 12.7M 0s
  8300K .......... .......... .......... .......... .......... 61% 13.9M 0s
  8350K .......... .......... .......... .......... .......... 62% 11.3M 0s
  8400K .......... .......... .......... .......... .......... 62% 11.3M 0s
  8450K .......... .......... .......... .......... .......... 63% 11.3M 0s
  8500K .......... .......... .......... .......... .......... 63% 30.0M 0s
  8550K .......... .......... .......... .......... .......... 63% 11.8M 0s
  8600K .......... .......... .......... .......... .......... 64% 15.5M 0s
  8650K .......... .......... .......... .......... .......... 64% 9.79M 0s
  8700K .......... .......... .......... .......... .......... 64% 14.4M 0s
  8750K .......... .......... .......... .......... .......... 65% 9.36M 0s
  8800K .......... .......... .......... .......... .......... 65% 15.6M 0s
  8850K .......... .......... .......... .......... .......... 66% 16.2M 0s
  8900K .......... .......... .......... .......... .......... 66% 9.97M 0s
  8950K .......... .......... .......... .......... .......... 66% 12.0M 0s
  9000K .......... .......... .......... .......... .......... 67% 14.9M 0s
  9050K .......... .......... .......... .......... .......... 67% 10.6M 0s
  9100K .......... .......... .......... .......... .......... 67% 19.5M 0s
  9150K .......... .......... .......... .......... .......... 68% 9.01M 0s
  9200K .......... .......... .......... .......... .......... 68% 9.82M 0s
  9250K .......... .......... .......... .......... .......... 68% 36.3M 0s
  9300K .......... .......... .......... .......... .......... 69% 12.2M 0s
  9350K .......... .......... .......... .......... .......... 69% 13.5M 0s
  9400K .......... .......... .......... .......... .......... 70% 13.3M 0s
  9450K .......... .......... .......... .......... .......... 70% 13.3M 0s
  9500K .......... .......... .......... .......... .......... 70% 12.9M 0s
  9550K .......... .......... .......... .......... .......... 71% 12.1M 0s
  9600K .......... .......... .......... .......... .......... 71% 10.7M 0s
  9650K .......... .......... .......... .......... .......... 71% 8.41M 0s
  9700K .......... .......... .......... .......... .......... 72% 23.6M 0s
  9750K .......... .......... .......... .......... .......... 72% 17.7M 0s
  9800K .......... .......... .......... .......... .......... 73% 10.9M 0s
  9850K .......... .......... .......... .......... .......... 73% 14.5M 0s
  9900K .......... .......... .......... .......... .......... 73% 16.9M 0s
  9950K .......... .......... .......... .......... .......... 74% 9.36M 0s
 10000K .......... .......... .......... .......... .......... 74% 10.9M 0s
 10050K .......... .......... .......... .......... .......... 74% 10.4M 0s
 10100K .......... .......... .......... .......... .......... 75% 32.2M 0s
 10150K .......... .......... .......... .......... .......... 75% 10.7M 0s
 10200K .......... .......... .......... .......... .......... 76% 16.5M 0s
 10250K .......... .......... .......... .......... .......... 76% 14.3M 0s
 10300K .......... .......... .......... .......... .......... 76% 13.8M 0s
 10350K .......... .......... .......... .......... .......... 77% 12.2M 0s
 10400K .......... .......... .......... .......... .......... 77% 8.88M 0s
 10450K .......... .......... .......... .......... .......... 77% 19.5M 0s
 10500K .......... .......... .......... .......... .......... 78% 14.7M 0s
 10550K .......... .......... .......... .......... .......... 78% 12.2M 0s
 10600K .......... .......... .......... .......... .......... 79% 13.8M 0s
 10650K .......... .......... .......... .......... .......... 79% 12.2M 0s
 10700K .......... .......... .......... .......... .......... 79% 9.51M 0s
 10750K .......... .......... .......... .......... .......... 80% 10.4M 0s
 10800K .......... .......... .......... .......... .......... 80% 12.7M 0s
 10850K .......... .......... .......... .......... .......... 80% 14.5M 0s
 10900K .......... .......... .......... .......... .......... 81% 13.5M 0s
 10950K .......... .......... .......... .......... .......... 81% 22.5M 0s
 11000K .......... .......... .......... .......... .......... 81% 12.8M 0s
 11050K .......... .......... .......... .......... .......... 82% 10.9M 0s
 11100K .......... .......... .......... .......... .......... 82% 14.9M 0s
 11150K .......... .......... .......... .......... .......... 83% 8.30M 0s
 11200K .......... .......... .......... .......... .......... 83% 12.4M 0s
 11250K .......... .......... .......... .......... .......... 83% 21.5M 0s
 11300K .......... .......... .......... .......... .......... 84% 9.96M 0s
 11350K .......... .......... .......... .......... .......... 84% 13.7M 0s
 11400K .......... .......... .......... .......... .......... 84% 18.8M 0s
 11450K .......... .......... .......... .......... .......... 85% 9.60M 0s
 11500K .......... .......... .......... .......... .......... 85% 14.5M 0s

Downloading atb.assembly.r0.2.batch.76.tar.xz from https://osf.io/download/66714d4e65e1de5e7e893ed3/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d4e65e1de5e7e893ed3 [following]
--2026-09-06 18:52:34--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d4e65e1de5e7e893ed3
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/4b5a6d7044135873aa6c4782f2f3969c9f5511466df222c6a9f924686996c1fe?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.76.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.76.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713615&Signature=YIGJmzjFLsS96KldR94NoVddh0LQJBgd7v35SoklxXZEZxyF9Vhg1V0E8QZ%2Fw6kfFw2fD0v5CG1oCLKfWpau3HFrCKiLZ9JiYmXi5t1u7umI%2BPXqgH1LHNFnpe6gYT06VvtgK9T2dazTs4Zk86Sc%2FO6wByJ5hMkakHVc1wb5tO7DCmvdc8r2ygpyC1a78L0t6NEMX5O4saBqCVAc72aTDZJyK3p6by2zJrDUfVN4FMg3XVeH%2BJjkWV0uaX1YNVhJNmpgmHre13upJj%2BvZui8cbc5EBChxX7h0RwsA%2BW1kv0L8QuFoqW0eO55CmYAatFwbXx4HDwPEZoi40kmUrxOYA%3D%3D [following]
--2026-09-06 18:52:35--  https://storage.googleapis.com/cos-osf-prod-files-de-1/4b5a6d7044135873aa6c4782f2f3969c9f5511466df222c6a9f924686996c1fe?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.76.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.76.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713615&Signature=YIGJmzjFLsS96KldR94NoVddh0LQJBgd7v35SoklxXZEZxyF9Vhg1V0E8QZ%2Fw6kfFw2fD0v5CG1oCLKfWpau3HFrCKiLZ9JiYmXi5t1u7umI%2BPXqgH1LHNFnpe6gYT06VvtgK9T2dazTs4Zk86Sc%2FO6wByJ5hMkakHVc1wb5tO7DCmvdc8r2ygpyC1a78L0t6NEMX5O4saBqCVAc72aTDZJyK3p6by2zJrDUfVN4FMg3XVeH%2BJjkWV0uaX1YNVhJNmpgmHre13upJj%2BvZui8cbc5EBChxX7h0RwsA%2BW1kv0L8QuFoqW0eO55CmYAatFwbXx4HDwPEZoi40kmUrxOYA%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 103350936 (99M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.76.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.35M 73s
    50K .......... .......... .......... .......... ..........  0% 2.88M 54s
   100K .......... .......... .......... .......... ..........  0% 4.95M 42s
   150K .......... .......... .......... .......... ..........  0% 5.39M 36s
   200K .......... .......... .......... .......... ..........  0% 7.47M 32s
   250K .......... .......... .......... .......... ..........  0% 9.11M 28s
   300K .......... .......... .......... .......... ..........  0% 10.2M 25s
   350K .......... .......... .......... .......... ..........  0% 10.3M 23s
   400K .......... .......... .......... .......... ..........  0% 12.9M 22s
   450K .......... .......... .......... .......... ..........  0% 21.5M 20s
   500K .......... .......... .......... .......... ..........  0% 10.7M 19s
   550K .......... .......... .......... .......... ..........  0% 7.85M 18s
   600K .......... .......... .......... .......... ..........  0% 17.0M 17s
   650K .......... .......... .......... .......... ..........  0% 22.0M 17s
   700K .......... .......... .......... .......... ..........  0% 11.1M 16s
   750K .......... .......... .......... .......... ..........  0% 10.4M 16s
   800K .......... .......... .......... .......... ..........  0% 23.7M 15s
   850K .......... .......... .......... .......... ..........  0% 8.95M 15s
   900K .......... .......... .......... .......... ..........  0% 22.8M 14s
   950K .......... .......... .......... .......... ..........  0% 11.9M 14s
  1000K .......... .......... .......... .......... ..........  1% 10.4M 14s
  1050K .......... .......... .......... .......... ..........  1% 12.5M 13s
  1100K .......... .......... .......... .......... ..........  1% 18.0M 13s
  1150K .......... .......... .......... .......... ..........  1% 9.99M 13s
  1200K .......... .......... .......... .......... ..........  1% 10.7M 13s
  1250K .......... .......... .......... .......... ..........  1% 16.1M 12s
  1300K .......... .......... .......... .......... ..........  1% 12.0M 12s
  1350K .......... .......... .......... .......... ..........  1% 15.6M 12s
  1400K .......... .......... .......... .......... ..........  1% 11.6M 12s
  1450K .......... .......... .......... .......... ..........  1% 16.1M 12s
  1500K .......... .......... .......... .......... ..........  1% 10.9M 12s
  1550K .......... .......... .......... .......... ..........  1% 15.1M 11s
  1600K .......... .......... .......... .......... ..........  1% 11.6M 11s
  1650K .......... .......... .......... .......... ..........  1% 14.2M 11s
  1700K .......... .......... .......... .......... ..........  1% 13.6M 11s
  1750K .......... .......... .......... .......... ..........  1% 13.3M 11s
  1800K .......... .......... .......... .......... ..........  1% 12.7M 11s
  1850K .......... .......... .......... .......... ..........  1% 13.7M 11s
  1900K .......... .......... .......... .......... ..........  1% 11.4M 11s
  1950K .......... .......... .......... .......... ..........  1% 8.58M 11s
  2000K .......... .......... .......... .......... ..........  2% 26.7M 11s
  2050K .......... .......... .......... .......... ..........  2% 13.9M 10s
  2100K .......... .......... .......... .......... ..........  2% 12.4M 10s
  2150K .......... .......... .......... .......... ..........  2% 9.47M 10s
  2200K .......... .......... .......... .......... ..........  2% 13.2M 10s
  2250K .......... .......... .......... .......... ..........  2% 14.6M 10s
  2300K .......... .......... .......... .......... ..........  2% 14.0M 10s
  2350K .......... .......... .......... .......... ..........  2% 7.96M 10s
  2400K .......... .......... .......... .......... ..........  2% 30.1M 10s
  2450K .......... .......... .......... .......... ..........  2% 11.0M 10s
  2500K .......... .......... .......... .......... ..........  2% 11.3M 10s
  2550K .......... .......... .......... .......... ..........  2% 13.2M 10s
  2600K .......... .......... .......... .......... ..........  2% 17.1M 10s
  2650K .......... .......... .......... .......... ..........  2% 14.3M 10s
  2700K .......... .......... .......... .......... ..........  2% 9.01M 10s
  2750K .......... .......... .......... .......... ..........  2% 8.87M 10s
  2800K .......... .......... .......... .......... ..........  2% 20.6M 10s
  2850K .......... .......... .......... .......... ..........  2% 10.1M 10s
  2900K .......... .......... .......... .......... ..........  2% 67.1M 10s
  2950K .......... .......... .......... .......... ..........  2% 9.04M 10s
  3000K .......... .......... .......... .......... ..........  3% 21.9M 9s
  3050K .......... .......... .......... .......... ..........  3% 11.6M 9s
  3100K .......... .......... .......... .......... ..........  3% 9.60M 9s
  3150K .......... .......... .......... .......... ..........  3% 15.9M 9s
  3200K .......... .......... .......... .......... ..........  3% 14.1M 9s
  3250K .......... .......... .......... .......... ..........  3% 10.5M 9s
  3300K .......... .......... .......... .......... ..........  3% 15.6M 9s
  3350K .......... .......... .......... .......... ..........  3% 12.8M 9s
  3400K .......... .......... .......... .......... ..........  3% 12.3M 9s
  3450K .......... .......... .......... .......... ..........  3% 11.4M 9s
  3500K .......... .......... .......... .......... ..........  3% 18.5M 9s
  3550K .......... .......... .......... .......... ..........  3% 7.42M 9s
  3600K .......... .......... .......... .......... ..........  3% 17.5M 9s
  3650K .......... .......... .......... .......... ..........  3% 15.2M 9s
  3700K .......... .......... .......... .......... ..........  3% 16.8M 9s
  3750K .......... .......... .......... .......... ..........  3% 12.6M 9s
  3800K .......... .......... .......... .......... ..........  3% 13.9M 9s
  3850K .......... .......... .......... .......... ..........  3% 12.1M 9s
  3900K .......... .......... .......... .......... ..........  3% 13.9M 9s
  3950K .......... .......... .......... .......... ..........  3% 8.85M 9s
  4000K .......... .......... .......... .......... ..........  4% 10.7M 9s
  4050K .......... .......... .......... .......... ..........  4% 17.8M 9s
  4100K .......... .......... .......... .......... ..........  4% 18.6M 9s
  4150K .......... .......... .......... .......... ..........  4% 10.7M 9s
  4200K .......... .......... .......... .......... ..........  4% 12.9M 9s
  4250K .......... .......... .......... .......... ..........  4% 9.47M 9s
  4300K .......... .......... .......... .......... ..........  4% 18.6M 9s
  4350K .......... .......... .......... .......... ..........  4% 9.99M 9s
  4400K .......... .......... .......... .......... ..........  4% 16.1M 9s
  4450K .......... .......... .......... .......... ..........  4% 9.86M 9s
  4500K .......... .......... .......... .......... ..........  4% 14.4M 9s
  4550K .......... .......... .......... .......... ..........  4% 12.9M 9s
  4600K .......... .......... .......... .......... ..........  4% 27.0M 9s
  4650K .......... .......... .......... .......... ..........  4% 8.73M 9s
  4700K .......... .......... .......... .......... ..........  4% 14.8M 9s
  4750K .......... .......... .......... .......... ..........  4% 11.4M 9s
  4800K .......... .......... .......... .......... ..........  4% 9.42M 9s
  4850K .......... .......... .......... .......... ..........  4% 28.6M 9s
  4900K .......... .......... .......... .......... ..........  4% 14.7M 9s
  4950K .......... .......... .......... .......... ..........  4% 12.0M 9s
  5000K .......... .......... .......... .......... ..........  5% 13.3M 8s
  5050K .......... .......... .......... .......... ..........  5% 12.3M 8s
  5100K .......... .......... .......... .......... ..........  5% 9.44M 8s
  5150K .......... .......... .......... .......... ..........  5% 9.66M 9s
  5200K .......... .......... .......... .......... ..........  5% 28.3M 8s
  5250K .......... .......... .......... .......... ..........  5% 13.6M 8s
  5300K .......... .......... .......... .......... ..........  5% 13.1M 8s
  5350K .......... .......... .......... .......... ..........  5% 11.6M 8s
  5400K .......... .......... .......... .......... ..........  5% 14.2M 8s
  5450K .......... .......... .......... .......... ..........  5% 14.2M 8s
  5500K .......... .......... .......... .......... ..........  5% 9.20M 8s
  5550K .......... .......... .......... .......... ..........  5% 14.4M 8s
  5600K .......... .......... .......... .......... ..........  5% 15.1M 8s
  5650K .......... .......... .......... .......... ..........  5% 14.8M 8s
  5700K .......... .......... .......... .......... ..........  5% 10.9M 8s
  5750K .......... .......... .......... .......... ..........  5% 11.4M 8s
  5800K .......... .......... .......... .......... ..........  5% 13.7M 8s
  5850K .......... .......... .......... .......... ..........  5% 10.5M 8s
  5900K .......... .......... .......... .......... ..........  5% 11.1M 8s
  5950K .......... .......... .......... .......... ..........  5% 11.2M 8s
  6000K .......... .......... .......... .......... ..........  5% 23.5M 8s
  6050K .......... .......... .......... .......... ..........  6% 17.4M 8s
  6100K .......... .......... .......... .......... ..........  6% 10.5M 8s
  6150K .......... .......... .......... .......... ..........  6% 12.9M 8s
  6200K .......... .......... .......... .......... ..........  6% 10.2M 8s
  6250K .......... .......... .......... .......... ..........  6% 13.4M 8s
  6300K .......... .......... .......... .......... ..........  6% 22.8M 8s
  6350K .......... .......... .......... .......... ..........  6% 11.6M 8s
  6400K .......... .......... .......... .......... ..........  6% 9.86M 8s
  6450K .......... .......... .......... .......... ..........  6% 20.7M 8s
  6500K .......... .......... .......... .......... ..........  6% 9.09M 8s
  6550K .......... .......... .......... .......... ..........  6% 11.8M 8s
  6600K .......... .......... .......... .......... ..........  6% 17.0M 8s
  6650K .......... .......... .......... .......... ..........  6% 14.0M 8s
  6700K .......... .......... .......... .......... ..........  6% 13.2M 8s
  6750K .......... .......... .......... .......... ..........  6% 12.2M 8s
  6800K .......... .......... .......... .......... ..........  6% 10.6M 8s
  6850K .......... .......... .......... .......... ..........  6% 12.4M 8s
  6900K .......... .......... .......... .......... ..........  6% 12.5M 8s
  6950K .......... .......... .......... .......... ..........  6% 15.3M 8s
  7000K .......... .......... .......... .......... ..........  6% 11.8M 8s
  7050K .......... .......... .......... .......... ..........  7% 11.5M 8s
  7100K .......... .......... .......... .......... ..........  7% 25.6M 8s
  7150K .......... .......... .......... .......... ..........  7% 11.5M 8s
  7200K .......... .......... .......... .......... ..........  7% 8.64M 8s
  7250K .......... .......... .......... .......... ..........  7% 14.4M 8s
  7300K .......... .......... .......... .......... ..........  7% 12.5M 8s
  7350K .......... .......... .......... .......... ..........  7% 10.2M 8s
  7400K .......... .......... .......... .......... ..........  7% 17.5M 8s
  7450K .......... .......... .......... .......... ..........  7% 23.6M 8s
  7500K .......... .......... .......... .......... ..........  7% 8.20M 8s
  7550K .......... .......... .......... .......... ..........  7% 19.1M 8s
  7600K .......... .......... .......... .......... ..........  7% 13.8M 8s
  7650K .......... .......... .......... .......... ..........  7% 9.49M 8s
  7700K .......... .......... .......... .......... ..........  7% 16.6M 8s
  7750K .......... .......... .......... .......... ..........  7% 13.9M 8s
  7800K .......... .......... .......... .......... ..........  7% 14.4M 8s
  7850K .......... .......... .......... .......... ..........  7% 12.6M 8s
  7900K .......... .......... .......... .......... ..........  7% 16.5M 8s
  7950K .......... .......... .......... .......... ..........  7% 10.3M 8s
  8000K .......... .......... .......... .......... ..........  7% 11.8M 8s
  8050K .......... .......... .......... .......... ..........  8% 11.5M 8s
  8100K .......... .......... .......... .......... ..........  8% 13.2M 8s
  8150K .......... .......... .......... .......... ..........  8% 9.56M 8s
  8200K .......... .......... .......... .......... ..........  8% 17.7M 8s
  8250K .......... .......... .......... .......... ..........  8% 18.6M 8s
  8300K .......... .......... .......... .......... ..........  8% 12.7M 8s
  8350K .......... .......... .......... .......... ..........  8% 10.1M 8s
  8400K .......... .......... .......... .......... ..........  8% 9.76M 8s
  8450K .......... .......... .......... .......... ..........  8% 15.5M 8s
  8500K .......... .......... .......... .......... ..........  8% 10.6M 8s
  8550K .......... .......... .......... .......... ..........  8% 22.7M 8s
  8600K .......... .......... .......... .......... ..........  8% 11.5M 8s
  8650K .......... .......... .......... .......... ..........  8% 14.0M 8s
  8700K .......... .......... .......... .......... ..........  8% 11.2M 8s
  8750K .......... .......... .......... .......... ..........  8% 15.6M 8s
  8800K .......... .......... .......... .......... ..........  8% 11.2M 8s
  8850K .......... .......... .......... .......... ..........  8% 12.0M 8s
  8900K .......... .......... .......... .......... ..........  8% 16.6M 8s
  8950K .......... .......... .......... .......... ..........  8% 9.57M 8s
  9000K .......... .......... .......... .......... ..........  8% 25.1M 8s
  9050K .......... .......... .......... .......... ..........  9% 9.78M 8s
  9100K .......... .......... .......... .......... ..........  9% 12.1M 8s
  9150K .......... .......... .......... .......... ..........  9% 13.4M 8s
  9200K .......... .......... .......... .......... ..........  9% 13.1M 8s
  9250K .......... .......... .......... .......... ..........  9% 13.9M 8s
  9300K .......... .......... .......... .......... ..........  9% 8.97M 8s
  9350K .......... .......... .......... .......... ..........  9% 19.1M 8s
  9400K .......... .......... .......... .......... ..........  9% 13.8M 8s
  9450K .......... .......... .......... .......... ..........  9% 10.8M 8s
  9500K .......... .......... .......... .......... ..........  9% 14.1M 8s
  9550K .......... .......... .......... .......... ..........  9% 17.9M 8s
  9600K .......... .......... .......... .......... ..........  9% 10.6M 8s
  9650K .......... .......... .......... .......... ..........  9% 11.0M 8s
  9700K .......... .......... .......... .......... ..........  9% 11.0M 8s
  9750K .......... .......... .......... .......... ..........  9% 14.2M 8s
  9800K .......... .......... .......... .......... ..........  9% 10.3M 8s
  9850K .......... .......... .......... .......... ..........  9% 32.5M 8s
  9900K .......... .......... .......... .......... ..........  9% 14.1M 8s
  9950K .......... .......... .......... .......... ..........  9% 11.7M 8s
 10000K .......... .......... .......... .......... ..........  9% 8.35M 8s
 10050K .......... .......... .......... .......... .......... 10% 12.0M 8s
 10100K .......... .......... .......... .......... .......... 10% 10.5M 8s
 10150K .......... .......... .......... .......... .......... 10% 20.5M 7s
 10200K .......... .......... .......... .......... .......... 10% 18.7M 7s
 10250K .......... .......... .......... .......... .......... 10% 12.2M 7s
 10300K .......... .......... .......... .......... .......... 10% 19.8M 7s
 10350K .......... .......... .......... .......... .......... 10% 9.25M 7s
 10400K .......... .......... .......... .......... .......... 10% 10.6M 7s
 10450K .......... .......... .......... .......... .......... 10% 13.1M 7s
 10500K .......... .......... .......... .......... .......... 10% 15.7M 7s
 10550K .......... .......... .......... .......... .......... 10% 8.71M 7s
 10600K .......... .......... .......... .......... .......... 10% 31.0M 7s
 10650K .......... .......... .......... .......... .......... 10% 16.3M 7s
 10700K .......... .......... .......... .......... .......... 10% 10.5M 7s
 10750K .......... .......... .......... .......... .......... 10% 12.7M 7s
 10800K .......... .......... .......... .......... .......... 10% 13.1M 7s
 10850K .......... .......... .......... .......... .......... 10% 12.1M 7s
 10900K .......... .......... .......... .......... .......... 10% 15.0M 7s
 10950K .......... .......... .......... .......... .......... 10% 9.59M 7s
 11000K .......... .......... .......... .......... .......... 10% 19.9M 7s
 11050K .......... .......... .......... .......... .......... 10% 11.6M 7s
 11100K .......... .......... .......... .......... .......... 11% 11.6M 7s
 11150K .......... .......... .......... .......... .......... 11% 10.8M 7s
 11200K .......... .......... .......... .......... .......... 11% 12.6M 7s
 11250K .......... .......... .......... .......... .......... 11% 9.15M 7s
 11300K .......... .......... .......... .......... .......... 11% 23.8M 7s
 11350K .......... .......... .......... .......... .......... 11% 11.8M 7s
 11400K .......... .......... .......... .......... .......... 11% 10.5M 7s
 11450K .......... .......... .......... .......... .......... 11% 19.3M 7s
 11500K .......... .......... .......... .......... .......... 11% 10.8M 7s

Downloading atb.assembly.r0.2.batch.77.tar.xz from https://osf.io/download/66714d3777ff4c5f30e04531/

--2026-09-06 18:52:43--  https://osf.io/download/66714d3777ff4c5f30e04531/
Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d3777ff4c5f30e04531 [following]
--2026-09-06 18:52:43--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d3777ff4c5f30e04531
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/b2354e13ee55fa80b7319b89d6de49e9bcb725ff7eed3b3787818b128fbb8071?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.77.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.77.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713624&Signature=12NUeOYWRGUtdq9NuSbiKGDlCnsXOdQuKPKxZGmngeJ%2BZCznKE6U7dRQWkBjZv1LSHEKd7D1RLJudnLrVzFrT1vCo1kIKgDQjAh0hGL6DWCM0fKTm0E%2BdClYQuHxeRbybiuSxt8WqRJ0C5v4dSMHN1K6GijHdThN7fteWfqVQ%2FQCTcyk6jiqxD4SyjuKlperiGBEc7icLQBYtPSzikJ8eRj33DsYRcfiPbswL0aL397vTafforqb7FZVFVyVwdzMsmRbKEcioI9DqiLxWUSHpCS68UQkPlF6fozRIBRvXaDLTi1v%2FohwJRSY7dO%2B%2FPRGd2U3OJ5fpVZkv%2FoQxhv9kA%3D%3D [following]
--2026-09-06 18:52:44--  https://storage.googleapis.com/cos-osf-prod-files-de-1/b2354e13ee55fa80b7319b89d6de49e9bcb725ff7eed3b3787818b128fbb8071?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.77.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.77.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713624&Signature=12NUeOYWRGUtdq9NuSbiKGDlCnsXOdQuKPKxZGmngeJ%2BZCznKE6U7dRQWkBjZv1LSHEKd7D1RLJudnLrVzFrT1vCo1kIKgDQjAh0hGL6DWCM0fKTm0E%2BdClYQuHxeRbybiuSxt8WqRJ0C5v4dSMHN1K6GijHdThN7fteWfqVQ%2FQCTcyk6jiqxD4SyjuKlperiGBEc7icLQBYtPSzikJ8eRj33DsYRcfiPbswL0aL397vTafforqb7FZVFVyVwdzMsmRbKEcioI9DqiLxWUSHpCS68UQkPlF6fozRIBRvXaDLTi1v%2FohwJRSY7dO%2B%2FPRGd2U3OJ5fpVZkv%2FoQxhv9kA%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 37044136 (35M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.77.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.31M 27s
    50K .......... .......... .......... .......... ..........  0% 2.49M 20s
   100K .......... .......... .......... .......... ..........  0% 3.37M 17s
   150K .......... .......... .......... .......... ..........  0% 4.17M 15s
   200K .......... .......... .......... .......... ..........  0% 11.2M 13s
   250K .......... .......... .......... .......... ..........  0% 6.84M 11s
   300K .......... .......... .......... .......... ..........  0% 8.00M 10s
   350K .......... .......... .......... .......... ..........  1% 12.4M 9s
   400K .......... .......... .......... .......... ..........  1% 8.87M 9s
   450K .......... .......... .......... .......... ..........  1% 2.54M 9s
   500K .......... .......... .......... .......... ..........  1%  106M 8s
   550K .......... .......... .......... .......... ..........  1%  123M 8s
   600K .......... .......... .......... .......... ..........  1%  131M 7s
   650K .......... .......... .......... .......... ..........  1%  125M 7s
   700K .......... .......... .......... .......... ..........  2% 24.5M 6s
   750K .......... .......... .......... .......... ..........  2% 14.1M 6s
   800K .......... .......... .......... .......... ..........  2% 11.6M 6s
   850K .......... .......... .......... .......... ..........  2% 17.1M 6s
   900K .......... .......... .......... .......... ..........  2% 6.07M 6s
   950K .......... .......... .......... .......... ..........  2% 9.86M 5s
  1000K .......... .......... .......... .......... ..........  2% 11.3M 5s
  1050K .......... .......... .......... .......... ..........  3% 11.6M 5s
  1100K .......... .......... .......... .......... ..........  3% 19.3M 5s
  1150K .......... .......... .......... .......... ..........  3% 12.6M 5s
  1200K .......... .......... .......... .......... ..........  3% 16.2M 5s
  1250K .......... .......... .......... .......... ..........  3% 9.28M 5s
  1300K .......... .......... .......... .......... ..........  3% 14.0M 5s
  1350K .......... .......... .......... .......... ..........  3% 22.1M 5s
  1400K .......... .......... .......... .......... ..........  4% 8.08M 5s
  1450K .......... .......... .......... .......... ..........  4% 24.2M 4s
  1500K .......... .......... .......... .......... ..........  4% 7.08M 4s
  1550K .......... .......... .......... .......... ..........  4% 8.87M 4s
  1600K .......... .......... .......... .......... ..........  4% 16.2M 4s
  1650K .......... .......... .......... .......... ..........  4% 22.8M 4s
  1700K .......... .......... .......... .......... ..........  4% 25.7M 4s
  1750K .......... .......... .......... .......... ..........  4% 11.9M 4s
  1800K .......... .......... .......... .......... ..........  5% 13.1M 4s
  1850K .......... .......... .......... .......... ..........  5% 10.1M 4s
  1900K .......... .......... .......... .......... ..........  5% 14.4M 4s
  1950K .......... .......... .......... .......... ..........  5% 12.3M 4s
  2000K .......... .......... .......... .......... ..........  5% 13.7M 4s
  2050K .......... .......... .......... .......... ..........  5% 14.1M 4s
  2100K .......... .......... .......... .......... ..........  5% 9.00M 4s
  2150K .......... .......... .......... .......... ..........  6% 25.4M 4s
  2200K .......... .......... .......... .......... ..........  6% 13.8M 4s
  2250K .......... .......... .......... .......... ..........  6% 23.4M 4s
  2300K .......... .......... .......... .......... ..........  6% 7.98M 4s
  2350K .......... .......... .......... .......... ..........  6% 13.2M 4s
  2400K .......... .......... .......... .......... ..........  6% 11.6M 4s
  2450K .......... .......... .......... .......... ..........  6% 11.9M 4s
  2500K .......... .......... .......... .......... ..........  7% 14.9M 4s
  2550K .......... .......... .......... .......... ..........  7% 17.1M 4s
  2600K .......... .......... .......... .......... ..........  7% 9.38M 4s
  2650K .......... .......... .......... .......... ..........  7% 18.8M 4s
  2700K .......... .......... .......... .......... ..........  7% 9.83M 4s
  2750K .......... .......... .......... .......... ..........  7% 10.9M 4s
  2800K .......... .......... .......... .......... ..........  7% 13.3M 3s
  2850K .......... .......... .......... .......... ..........  8% 11.5M 3s
  2900K .......... .......... .......... .......... ..........  8% 14.3M 3s
  2950K .......... .......... .......... .......... ..........  8% 22.3M 3s
  3000K .......... .......... .......... .......... ..........  8% 12.8M 3s
  3050K .......... .......... .......... .......... ..........  8% 14.5M 3s
  3100K .......... .......... .......... .......... ..........  8% 9.01M 3s
  3150K .......... .......... .......... .......... ..........  8% 14.4M 3s
  3200K .......... .......... .......... .......... ..........  8% 11.4M 3s
  3250K .......... .......... .......... .......... ..........  9% 12.5M 3s
  3300K .......... .......... .......... .......... ..........  9% 20.0M 3s
  3350K .......... .......... .......... .......... ..........  9% 11.3M 3s
  3400K .......... .......... .......... .......... ..........  9% 13.6M 3s
  3450K .......... .......... .......... .......... ..........  9% 12.7M 3s
  3500K .......... .......... .......... .......... ..........  9% 9.73M 3s
  3550K .......... .......... .......... .......... ..........  9% 8.27M 3s
  3600K .......... .......... .......... .......... .......... 10% 41.9M 3s
  3650K .......... .......... .......... .......... .......... 10% 17.3M 3s
  3700K .......... .......... .......... .......... .......... 10% 8.07M 3s
  3750K .......... .......... .......... .......... .......... 10% 16.8M 3s
  3800K .......... .......... .......... .......... .......... 10% 12.7M 3s
  3850K .......... .......... .......... .......... .......... 10% 9.23M 3s
  3900K .......... .......... .......... .......... .......... 10% 30.6M 3s
  3950K .......... .......... .......... .......... .......... 11% 8.50M 3s
  4000K .......... .......... .......... .......... .......... 11% 39.7M 3s
  4050K .......... .......... .......... .......... .......... 11% 9.56M 3s
  4100K .......... .......... .......... .......... .......... 11% 10.5M 3s
  4150K .......... .......... .......... .......... .......... 11% 17.7M 3s
  4200K .......... .......... .......... .......... .......... 11% 11.4M 3s
  4250K .......... .......... .......... .......... .......... 11% 10.3M 3s
  4300K .......... .......... .......... .......... .......... 12% 17.4M 3s
  4350K .......... .......... .......... .......... .......... 12% 10.8M 3s
  4400K .......... .......... .......... .......... .......... 12% 12.2M 3s
  4450K .......... .......... .......... .......... .......... 12% 27.0M 3s
  4500K .......... .......... .......... .......... .......... 12% 9.76M 3s
  4550K .......... .......... .......... .......... .......... 12% 15.7M 3s
  4600K .......... .......... .......... .......... .......... 12% 13.6M 3s
  4650K .......... .......... .......... .......... .......... 12% 10.1M 3s
  4700K .......... .......... .......... .......... .......... 13% 10.9M 3s
  4750K .......... .......... .......... .......... .......... 13% 23.4M 3s
  4800K .......... .......... .......... .......... .......... 13% 10.1M 3s
  4850K .......... .......... .......... .......... .......... 13% 14.7M 3s
  4900K .......... .......... .......... .......... .......... 13% 12.4M 3s
  4950K .......... .......... .......... .......... .......... 13% 11.0M 3s
  5000K .......... .......... .......... .......... .......... 13% 11.5M 3s
  5050K .......... .......... .......... .......... .......... 14% 10.5M 3s
  5100K .......... .......... .......... .......... .......... 14% 23.3M 3s
  5150K .......... .......... .......... .......... .......... 14% 14.5M 3s
  5200K .......... .......... .......... .......... .......... 14% 13.4M 3s
  5250K .......... .......... .......... .......... .......... 14% 14.0M 3s
  5300K .......... .......... .......... .......... .......... 14% 10.4M 3s
  5350K .......... .......... .......... .......... .......... 14% 26.0M 3s
  5400K .......... .......... .......... .......... .......... 15% 7.00M 3s
  5450K .......... .......... .......... .......... .......... 15% 27.9M 3s
  5500K .......... .......... .......... .......... .......... 15% 9.96M 3s
  5550K .......... .......... .......... .......... .......... 15% 14.2M 3s
  5600K .......... .......... .......... .......... .......... 15% 14.7M 3s
  5650K .......... .......... .......... .......... .......... 15% 10.2M 3s
  5700K .......... .......... .......... .......... .......... 15% 30.8M 3s
  5750K .......... .......... .......... .......... .......... 16% 12.1M 3s
  5800K .......... .......... .......... .......... .......... 16% 9.93M 3s
  5850K .......... .......... .......... .......... .......... 16% 11.5M 3s
  5900K .......... .......... .......... .......... .......... 16% 10.9M 3s
  5950K .......... .......... .......... .......... .......... 16% 16.0M 3s
  6000K .......... .......... .......... .......... .......... 16% 11.5M 3s
  6050K .......... .......... .......... .......... .......... 16% 14.1M 3s
  6100K .......... .......... .......... .......... .......... 17% 12.4M 3s
  6150K .......... .......... .......... .......... .......... 17% 13.2M 3s
  6200K .......... .......... .......... .......... .......... 17% 10.6M 3s
  6250K .......... .......... .......... .......... .......... 17% 18.5M 3s
  6300K .......... .......... .......... .......... .......... 17% 11.7M 3s
  6350K .......... .......... .......... .......... .......... 17% 14.0M 3s
  6400K .......... .......... .......... .......... .......... 17% 7.79M 3s
  6450K .......... .......... .......... .......... .......... 17% 14.9M 3s
  6500K .......... .......... .......... .......... .......... 18% 36.5M 3s
  6550K .......... .......... .......... .......... .......... 18% 10.1M 3s
  6600K .......... .......... .......... .......... .......... 18% 12.3M 3s
  6650K .......... .......... .......... .......... .......... 18% 11.9M 3s
  6700K .......... .......... .......... .......... .......... 18% 13.6M 3s
  6750K .......... .......... .......... .......... .......... 18% 15.6M 3s
  6800K .......... .......... .......... .......... .......... 18% 11.4M 3s
  6850K .......... .......... .......... .......... .......... 19% 11.0M 3s
  6900K .......... .......... .......... .......... .......... 19% 12.2M 3s
  6950K .......... .......... .......... .......... .......... 19% 18.0M 3s
  7000K .......... .......... .......... .......... .......... 19% 14.3M 3s
  7050K .......... .......... .......... .......... .......... 19% 12.4M 3s
  7100K .......... .......... .......... .......... .......... 19% 14.5M 3s
  7150K .......... .......... .......... .......... .......... 19% 9.80M 3s
  7200K .......... .......... .......... .......... .......... 20% 10.3M 3s
  7250K .......... .......... .......... .......... .......... 20% 19.7M 3s
  7300K .......... .......... .......... .......... .......... 20% 9.41M 3s
  7350K .......... .......... .......... .......... .......... 20% 20.0M 3s
  7400K .......... .......... .......... .......... .......... 20% 12.8M 2s
  7450K .......... .......... .......... .......... .......... 20% 13.5M 2s
  7500K .......... .......... .......... .......... .......... 20% 10.9M 2s
  7550K .......... .......... .......... .......... .......... 21% 17.3M 2s
  7600K .......... .......... .......... .......... .......... 21% 11.8M 2s
  7650K .......... .......... .......... .......... .......... 21% 14.8M 2s
  7700K .......... .......... .......... .......... .......... 21% 10.1M 2s
  7750K .......... .......... .......... .......... .......... 21% 10.3M 2s
  7800K .......... .......... .......... .......... .......... 21% 12.2M 2s
  7850K .......... .......... .......... .......... .......... 21% 21.4M 2s
  7900K .......... .......... .......... .......... .......... 21% 15.5M 2s
  7950K .......... .......... .......... .......... .......... 22% 10.6M 2s
  8000K .......... .......... .......... .......... .......... 22% 8.87M 2s
  8050K .......... .......... .......... .......... .......... 22% 26.7M 2s
  8100K .......... .......... .......... .......... .......... 22% 9.29M 2s
  8150K .......... .......... .......... .......... .......... 22% 13.3M 2s
  8200K .......... .......... .......... .......... .......... 22% 18.5M 2s
  8250K .......... .......... .......... .......... .......... 22% 10.9M 2s
  8300K .......... .......... .......... .......... .......... 23% 10.9M 2s
  8350K .......... .......... .......... .......... .......... 23% 13.5M 2s
  8400K .......... .......... .......... .......... .......... 23% 21.2M 2s
  8450K .......... .......... .......... .......... .......... 23% 8.56M 2s
  8500K .......... .......... .......... .......... .......... 23% 20.0M 2s
  8550K .......... .......... .......... .......... .......... 23% 12.0M 2s
  8600K .......... .......... .......... .......... .......... 23% 11.6M 2s
  8650K .......... .......... .......... .......... .......... 24% 13.3M 2s
  8700K .......... .......... .......... .......... .......... 24% 9.54M 2s
  8750K .......... .......... .......... .......... .......... 24% 13.0M 2s
  8800K .......... .......... .......... .......... .......... 24% 10.1M 2s
  8850K .......... .......... .......... .......... .......... 24% 18.1M 2s
  8900K .......... .......... .......... .......... .......... 24% 23.2M 2s
  8950K .......... .......... .......... .......... .......... 24% 9.11M 2s
  9000K .......... .......... .......... .......... .......... 25% 30.1M 2s
  9050K .......... .......... .......... .......... .......... 25% 11.1M 2s
  9100K .......... .......... .......... .......... .......... 25% 11.4M 2s
  9150K .......... .......... .......... .......... .......... 25% 9.08M 2s
  9200K .......... .......... .......... .......... .......... 25% 11.0M 2s
  9250K .......... .......... .......... .......... .......... 25% 25.8M 2s
  9300K .......... .......... .......... .......... .......... 25% 9.53M 2s
  9350K .......... .......... .......... .......... .......... 25% 14.4M 2s
  9400K .......... .......... .......... .......... .......... 26% 12.4M 2s
  9450K .......... .......... .......... .......... .......... 26% 10.1M 2s
  9500K .......... .......... .......... .......... .......... 26% 18.0M 2s
  9550K .......... .......... .......... .......... .......... 26% 11.1M 2s
  9600K .......... .......... .......... .......... .......... 26% 14.1M 2s
  9650K .......... .......... .......... .......... .......... 26% 21.8M 2s
  9700K .......... .......... .......... .......... .......... 26% 8.84M 2s
  9750K .......... .......... .......... .......... .......... 27% 17.4M 2s
  9800K .......... .......... .......... .......... .......... 27% 11.6M 2s
  9850K .......... .......... .......... .......... .......... 27% 20.7M 2s
  9900K .......... .......... .......... .......... .......... 27% 8.40M 2s
  9950K .......... .......... .......... .......... .......... 27% 22.1M 2s
 10000K .......... .......... .......... .......... .......... 27% 10.7M 2s
 10050K .......... .......... .......... .......... .......... 27% 14.0M 2s
 10100K .......... .......... .......... .......... .......... 28% 9.14M 2s
 10150K .......... .......... .......... .......... .......... 28% 26.1M 2s
 10200K .......... .......... .......... .......... .......... 28% 9.44M 2s
 10250K .......... .......... .......... .......... .......... 28% 22.5M 2s
 10300K .......... .......... .......... .......... .......... 28% 8.20M 2s
 10350K .......... .......... .......... .......... .......... 28% 13.3M 2s
 10400K .......... .......... .......... .......... .......... 28% 14.3M 2s
 10450K .......... .......... .......... .......... .......... 29% 15.8M 2s
 10500K .......... .......... .......... .......... .......... 29% 13.6M 2s
 10550K .......... .......... .......... .......... .......... 29% 20.8M 2s
 10600K .......... .......... .......... .......... .......... 29% 6.57M 2s
 10650K .......... .......... .......... .......... .......... 29% 15.8M 2s
 10700K .......... .......... .......... .......... .......... 29% 14.9M 2s
 10750K .......... .......... .......... .......... .......... 29% 10.3M 2s
 10800K .......... .......... .......... .......... .......... 29% 16.7M 2s
 10850K .......... .......... .......... .......... .......... 30% 16.6M 2s
 10900K .......... .......... .......... .......... .......... 30% 9.57M 2s
 10950K .......... .......... .......... .......... .......... 30% 23.7M 2s
 11000K .......... .......... .......... .......... .......... 30% 9.85M 2s
 11050K .......... .......... .......... .......... .......... 30% 11.8M 2s
 11100K .......... .......... .......... .......... .......... 30% 13.4M 2s
 11150K .......... .......... .......... .......... .......... 30% 18.6M 2s
 11200K .......... .......... .......... .......... .......... 31% 6.35M 2s
 11250K .......... .......... .......... .......... .......... 31% 60.1M 2s
 11300K .......... .......... .......... .......... .......... 31% 11.0M 2s
 11350K .......... .......... .......... .......... .......... 31% 15.6M 2s
 11400K .......... .......... .......... .......... .......... 31% 25.9M 2s

Downloading atb.assembly.r0.2.batch.78.tar.xz from https://osf.io/download/66714d3377ff4c5f29e046eb/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d3377ff4c5f29e046eb [following]
--2026-09-06 18:52:47--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d3377ff4c5f29e046eb
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/d5b207aa7f9489cccd4a161c65ba4594892363a7bfbae263ef62302c8a51b824?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.78.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.78.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713628&Signature=t538ckL%2BAyXYPDAzCZcbCKxiHggAxGACYnb%2B0b6uVNyt10HZ9Q60iwKWyzOWbnES1BtA%2BciR135G4EKieB8DLhRrkLqw9aU6hg0rFJfGEoZgq%2FBj7f%2BWmMh%2BmmHHIkUjxO1RppTeblp5lqLlMaoiMtVAZh%2FvrwBygeO%2B9OYYKS1h0zICf9%2FpLDdBpFK8LK5QNrxUsKsPHj4L3MpdLRPw03IWfZ13q0LYQ8U4kQeNKDJKTNg9kHMVF%2FkkfFwkbIVf7SBYETYrAE%2FmWflXmuWbGNUg1nDnbErrV3HTgEP%2FnnCzv9pGX4eL2cGhUPRK5%2BKPnHU6iBgnxktIE6a1Eu5ckQ%3D%3D [following]
--2026-09-06 18:52:48--  https://storage.googleapis.com/cos-osf-prod-files-de-1/d5b207aa7f9489cccd4a161c65ba4594892363a7bfbae263ef62302c8a51b824?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.78.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.78.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713628&Signature=t538ckL%2BAyXYPDAzCZcbCKxiHggAxGACYnb%2B0b6uVNyt10HZ9Q60iwKWyzOWbnES1BtA%2BciR135G4EKieB8DLhRrkLqw9aU6hg0rFJfGEoZgq%2FBj7f%2BWmMh%2BmmHHIkUjxO1RppTeblp5lqLlMaoiMtVAZh%2FvrwBygeO%2B9OYYKS1h0zICf9%2FpLDdBpFK8LK5QNrxUsKsPHj4L3MpdLRPw03IWfZ13q0LYQ8U4kQeNKDJKTNg9kHMVF%2FkkfFwkbIVf7SBYETYrAE%2FmWflXmuWbGNUg1nDnbErrV3HTgEP%2FnnCzv9pGX4eL2cGhUPRK5%2BKPnHU6iBgnxktIE6a1Eu5ckQ%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21588068 (21M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.78.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.25M 16s
    50K .......... .......... .......... .......... ..........  0% 2.64M 12s
   100K .......... .......... .......... .......... ..........  0% 1.96M 12s
   150K .......... .......... .......... .......... ..........  0% 6.29M 9s
   200K .......... .......... .......... .......... ..........  1% 5.03M 8s
   250K .......... .......... .......... .......... ..........  1% 2.27M 8s
   300K .......... .......... .......... .......... ..........  1% 72.7M 7s
   350K .......... .......... .......... .......... ..........  1% 98.0M 6s
   400K .......... .......... .......... .......... ..........  2%  111M 6s
   450K .......... .......... .......... .......... ..........  2% 13.8M 5s
   500K .......... .......... .......... .......... ..........  2% 2.50M 5s
   550K .......... .......... .......... .......... ..........  2% 75.2M 5s
   600K .......... .......... .......... .......... ..........  3% 14.5M 5s
   650K .......... .......... .......... .......... ..........  3% 12.2M 4s
   700K .......... .......... .......... .......... ..........  3% 20.0M 4s
   750K .......... .......... .......... .......... ..........  3% 10.7M 4s
   800K .......... .......... .......... .......... ..........  4% 13.2M 4s
   850K .......... .......... .......... .......... ..........  4% 11.1M 4s
   900K .......... .......... .......... .......... ..........  4% 9.84M 4s
   950K .......... .......... .......... .......... ..........  4% 12.3M 4s
  1000K .......... .......... .......... .......... ..........  4% 11.2M 3s
  1050K .......... .......... .......... .......... ..........  5% 26.8M 3s
  1100K .......... .......... .......... .......... ..........  5% 17.2M 3s
  1150K .......... .......... .......... .......... ..........  5% 2.67M 3s
  1200K .......... .......... .......... .......... ..........  5%  229M 3s
  1250K .......... .......... .......... .......... ..........  6%  388M 3s
  1300K .......... .......... .......... .......... ..........  6%  321M 3s
  1350K .......... .......... .......... .......... ..........  6% 17.2M 3s
  1400K .......... .......... .......... .......... ..........  6% 20.0M 3s
  1450K .......... .......... .......... .......... ..........  7% 10.2M 3s
  1500K .......... .......... .......... .......... ..........  7% 12.9M 3s
  1550K .......... .......... .......... .......... ..........  7% 12.9M 3s
  1600K .......... .......... .......... .......... ..........  7% 13.7M 3s
  1650K .......... .......... .......... .......... ..........  8% 18.2M 3s
  1700K .......... .......... .......... .......... ..........  8% 9.77M 3s
  1750K .......... .......... .......... .......... ..........  8% 22.9M 3s
  1800K .......... .......... .......... .......... ..........  8% 9.08M 3s
  1850K .......... .......... .......... .......... ..........  9% 26.2M 2s
  1900K .......... .......... .......... .......... ..........  9% 11.3M 2s
  1950K .......... .......... .......... .......... ..........  9% 9.35M 2s
  2000K .......... .......... .......... .......... ..........  9% 23.2M 2s
  2050K .......... .......... .......... .......... ..........  9% 11.4M 2s
  2100K .......... .......... .......... .......... .......... 10% 11.5M 2s
  2150K .......... .......... .......... .......... .......... 10% 8.23M 2s
  2200K .......... .......... .......... .......... .......... 10% 19.3M 2s
  2250K .......... .......... .......... .......... .......... 10% 15.7M 2s
  2300K .......... .......... .......... .......... .......... 11% 13.2M 2s
  2350K .......... .......... .......... .......... .......... 11% 11.5M 2s
  2400K .......... .......... .......... .......... .......... 11% 14.0M 2s
  2450K .......... .......... .......... .......... .......... 11% 11.4M 2s
  2500K .......... .......... .......... .......... .......... 12% 12.8M 2s
  2550K .......... .......... .......... .......... .......... 12% 14.3M 2s
  2600K .......... .......... .......... .......... .......... 12% 23.4M 2s
  2650K .......... .......... .......... .......... .......... 12% 11.3M 2s
  2700K .......... .......... .......... .......... .......... 13% 10.3M 2s
  2750K .......... .......... .......... .......... .......... 13% 13.2M 2s
  2800K .......... .......... .......... .......... .......... 13% 12.1M 2s
  2850K .......... .......... .......... .......... .......... 13% 10.5M 2s
  2900K .......... .......... .......... .......... .......... 13% 13.3M 2s
  2950K .......... .......... .......... .......... .......... 14% 22.8M 2s
  3000K .......... .......... .......... .......... .......... 14% 12.5M 2s
  3050K .......... .......... .......... .......... .......... 14% 11.5M 2s
  3100K .......... .......... .......... .......... .......... 14% 12.5M 2s
  3150K .......... .......... .......... .......... .......... 15% 8.55M 2s
  3200K .......... .......... .......... .......... .......... 15% 10.1M 2s
  3250K .......... .......... .......... .......... .......... 15% 34.8M 2s
  3300K .......... .......... .......... .......... .......... 15% 18.6M 2s
  3350K .......... .......... .......... .......... .......... 16% 15.1M 2s
  3400K .......... .......... .......... .......... .......... 16% 8.38M 2s
  3450K .......... .......... .......... .......... .......... 16% 2.95M 2s
  3500K .......... .......... .......... .......... .......... 16%  138M 2s
  3550K .......... .......... .......... .......... .......... 17%  110M 2s
  3600K .......... .......... .......... .......... .......... 17%  163M 2s
  3650K .......... .......... .......... .......... .......... 17%  173M 2s
  3700K .......... .......... .......... .......... .......... 17% 15.4M 2s
  3750K .......... .......... .......... .......... .......... 18% 8.58M 2s
  3800K .......... .......... .......... .......... .......... 18% 12.7M 2s
  3850K .......... .......... .......... .......... .......... 18% 24.8M 2s
  3900K .......... .......... .......... .......... .......... 18% 16.1M 2s
  3950K .......... .......... .......... .......... .......... 18% 5.82M 2s
  4000K .......... .......... .......... .......... .......... 19% 20.9M 2s
  4050K .......... .......... .......... .......... .......... 19% 15.2M 2s
  4100K .......... .......... .......... .......... .......... 19% 17.8M 2s
  4150K .......... .......... .......... .......... .......... 19% 10.4M 2s
  4200K .......... .......... .......... .......... .......... 20% 13.7M 2s
  4250K .......... .......... .......... .......... .......... 20% 10.8M 2s
  4300K .......... .......... .......... .......... .......... 20% 14.9M 2s
  4350K .......... .......... .......... .......... .......... 20% 13.6M 2s
  4400K .......... .......... .......... .......... .......... 21% 12.0M 2s
  4450K .......... .......... .......... .......... .......... 21% 13.4M 2s
  4500K .......... .......... .......... .......... .......... 21% 11.8M 2s
  4550K .......... .......... .......... .......... .......... 21% 10.2M 2s
  4600K .......... .......... .......... .......... .......... 22% 15.3M 2s
  4650K .......... .......... .......... .......... .......... 22% 28.5M 2s
  4700K .......... .......... .......... .......... .......... 22% 10.1M 2s
  4750K .......... .......... .......... .......... .......... 22% 12.9M 2s
  4800K .......... .......... .......... .......... .......... 23% 10.9M 2s
  4850K .......... .......... .......... .......... .......... 23% 7.36M 2s
  4900K .......... .......... .......... .......... .......... 23% 21.6M 2s
  4950K .......... .......... .......... .......... .......... 23% 12.6M 2s
  5000K .......... .......... .......... .......... .......... 23% 13.3M 2s
  5050K .......... .......... .......... .......... .......... 24% 19.5M 2s
  5100K .......... .......... .......... .......... .......... 24% 8.36M 2s
  5150K .......... .......... .......... .......... .......... 24% 14.0M 2s
  5200K .......... .......... .......... .......... .......... 24% 9.57M 2s
  5250K .......... .......... .......... .......... .......... 25% 34.8M 2s
  5300K .......... .......... .......... .......... .......... 25% 12.1M 1s
  5350K .......... .......... .......... .......... .......... 25% 13.9M 1s
  5400K .......... .......... .......... .......... .......... 25% 18.2M 1s
  5450K .......... .......... .......... .......... .......... 26% 10.7M 1s
  5500K .......... .......... .......... .......... .......... 26% 12.2M 1s
  5550K .......... .......... .......... .......... .......... 26% 20.4M 1s
  5600K .......... .......... .......... .......... .......... 26% 8.01M 1s
  5650K .......... .......... .......... .......... .......... 27% 10.8M 1s
  5700K .......... .......... .......... .......... .......... 27% 13.5M 1s
  5750K .......... .......... .......... .......... .......... 27% 16.9M 1s
  5800K .......... .......... .......... .......... .......... 27% 13.3M 1s
  5850K .......... .......... .......... .......... .......... 27% 11.0M 1s
  5900K .......... .......... .......... .......... .......... 28% 16.4M 1s
  5950K .......... .......... .......... .......... .......... 28% 12.0M 1s
  6000K .......... .......... .......... .......... .......... 28% 13.8M 1s
  6050K .......... .......... .......... .......... .......... 28% 15.5M 1s
  6100K .......... .......... .......... .......... .......... 29% 11.8M 1s
  6150K .......... .......... .......... .......... .......... 29% 12.7M 1s
  6200K .......... .......... .......... .......... .......... 29% 10.9M 1s
  6250K .......... .......... .......... .......... .......... 29% 26.4M 1s
  6300K .......... .......... .......... .......... .......... 30% 9.78M 1s
  6350K .......... .......... .......... .......... .......... 30% 15.7M 1s
  6400K .......... .......... .......... .......... .......... 30% 10.6M 1s
  6450K .......... .......... .......... .......... .......... 30% 12.7M 1s
  6500K .......... .......... .......... .......... .......... 31% 11.9M 1s
  6550K .......... .......... .......... .......... .......... 31% 12.3M 1s
  6600K .......... .......... .......... .......... .......... 31% 19.9M 1s
  6650K .......... .......... .......... .......... .......... 31% 13.2M 1s
  6700K .......... .......... .......... .......... .......... 32% 9.13M 1s
  6750K .......... .......... .......... .......... .......... 32% 10.7M 1s
  6800K .......... .......... .......... .......... .......... 32% 19.1M 1s
  6850K .......... .......... .......... .......... .......... 32% 8.24M 1s
  6900K .......... .......... .......... .......... .......... 32% 22.8M 1s
  6950K .......... .......... .......... .......... .......... 33% 16.8M 1s
  7000K .......... .......... .......... .......... .......... 33% 8.93M 1s
  7050K .......... .......... .......... .......... .......... 33% 25.2M 1s
  7100K .......... .......... .......... .......... .......... 33% 9.55M 1s
  7150K .......... .......... .......... .......... .......... 34% 14.9M 1s
  7200K .......... .......... .......... .......... .......... 34% 11.5M 1s
  7250K .......... .......... .......... .......... .......... 34% 9.24M 1s
  7300K .......... .......... .......... .......... .......... 34% 24.4M 1s
  7350K .......... .......... .......... .......... .......... 35% 13.1M 1s
  7400K .......... .......... .......... .......... .......... 35% 11.0M 1s
  7450K .......... .......... .......... .......... .......... 35% 14.2M 1s
  7500K .......... .......... .......... .......... .......... 35% 11.5M 1s
  7550K .......... .......... .......... .......... .......... 36% 26.0M 1s
  7600K .......... .......... .......... .......... .......... 36% 7.73M 1s
  7650K .......... .......... .......... .......... .......... 36% 12.5M 1s
  7700K .......... .......... .......... .......... .......... 36% 15.1M 1s
  7750K .......... .......... .......... .......... .......... 36% 10.4M 1s
  7800K .......... .......... .......... .......... .......... 37% 9.66M 1s
  7850K .......... .......... .......... .......... .......... 37% 28.1M 1s
  7900K .......... .......... .......... .......... .......... 37% 22.9M 1s
  7950K .......... .......... .......... .......... .......... 37% 11.8M 1s
  8000K .......... .......... .......... .......... .......... 38% 11.5M 1s
  8050K .......... .......... .......... .......... .......... 38% 8.41M 1s
  8100K .......... .......... .......... .......... .......... 38% 15.6M 1s
  8150K .......... .......... .......... .......... .......... 38% 18.5M 1s
  8200K .......... .......... .......... .......... .......... 39% 9.30M 1s
  8250K .......... .......... .......... .......... .......... 39% 16.7M 1s
  8300K .......... .......... .......... .......... .......... 39% 14.9M 1s
  8350K .......... .......... .......... .......... .......... 39% 18.6M 1s
  8400K .......... .......... .......... .......... .......... 40% 10.1M 1s
  8450K .......... .......... .......... .......... .......... 40% 9.97M 1s
  8500K .......... .......... .......... .......... .......... 40% 13.5M 1s
  8550K .......... .......... .......... .......... .......... 40% 13.7M 1s
  8600K .......... .......... .......... .......... .......... 41% 14.1M 1s
  8650K .......... .......... .......... .......... .......... 41% 13.0M 1s
  8700K .......... .......... .......... .......... .......... 41% 10.7M 1s
  8750K .......... .......... .......... .......... .......... 41% 16.6M 1s
  8800K .......... .......... .......... .......... .......... 41% 11.7M 1s
  8850K .......... .......... .......... .......... .......... 42% 10.3M 1s
  8900K .......... .......... .......... .......... .......... 42% 25.6M 1s
  8950K .......... .......... .......... .......... .......... 42% 8.63M 1s
  9000K .......... .......... .......... .......... .......... 42% 15.3M 1s
  9050K .......... .......... .......... .......... .......... 43% 11.5M 1s
  9100K .......... .......... .......... .......... .......... 43% 17.6M 1s
  9150K .......... .......... .......... .......... .......... 43% 13.9M 1s
  9200K .......... .......... .......... .......... .......... 43% 9.21M 1s
  9250K .......... .......... .......... .......... .......... 44% 17.7M 1s
  9300K .......... .......... .......... .......... .......... 44% 7.03M 1s
  9350K .......... .......... .......... .......... .......... 44% 18.9M 1s
  9400K .......... .......... .......... .......... .......... 44% 8.32M 1s
  9450K .......... .......... .......... .......... .......... 45% 26.0M 1s
  9500K .......... .......... .......... .......... .......... 45% 19.8M 1s
  9550K .......... .......... .......... .......... .......... 45% 7.98M 1s
  9600K .......... .......... .......... .......... .......... 45% 22.2M 1s
  9650K .......... .......... .......... .......... .......... 46% 10.7M 1s
  9700K .......... .......... .......... .......... .......... 46% 12.7M 1s
  9750K .......... .......... .......... .......... .......... 46% 12.8M 1s
  9800K .......... .......... .......... .......... .......... 46% 13.0M 1s
  9850K .......... .......... .......... .......... .......... 46% 12.4M 1s
  9900K .......... .......... .......... .......... .......... 47% 21.9M 1s
  9950K .......... .......... .......... .......... .......... 47% 12.0M 1s
 10000K .......... .......... .......... .......... .......... 47% 12.2M 1s
 10050K .......... .......... .......... .......... .......... 47% 11.2M 1s
 10100K .......... .......... .......... .......... .......... 48% 11.6M 1s
 10150K .......... .......... .......... .......... .......... 48% 9.54M 1s
 10200K .......... .......... .......... .......... .......... 48% 26.4M 1s
 10250K .......... .......... .......... .......... .......... 48% 11.6M 1s
 10300K .......... .......... .......... .......... .......... 49% 13.6M 1s
 10350K .......... .......... .......... .......... .......... 49% 15.2M 1s
 10400K .......... .......... .......... .......... .......... 49% 13.2M 1s
 10450K .......... .......... .......... .......... .......... 49% 12.1M 1s
 10500K .......... .......... .......... .......... .......... 50% 12.0M 1s
 10550K .......... .......... .......... .......... .......... 50% 12.4M 1s
 10600K .......... .......... .......... .......... .......... 50% 16.1M 1s
 10650K .......... .......... .......... .......... .......... 50% 8.75M 1s
 10700K .......... .......... .......... .......... .......... 50% 18.0M 1s
 10750K .......... .......... .......... .......... .......... 51% 18.7M 1s
 10800K .......... .......... .......... .......... .......... 51% 9.39M 1s
 10850K .......... .......... .......... .......... .......... 51% 12.1M 1s
 10900K .......... .......... .......... .......... .......... 51% 14.5M 1s
 10950K .......... .......... .......... .......... .......... 52% 12.5M 1s
 11000K .......... .......... .......... .......... .......... 52% 15.9M 1s
 11050K .......... .......... .......... .......... .......... 52% 14.3M 1s
 11100K .......... .......... .......... .......... .......... 52% 12.2M 1s
 11150K .......... .......... .......... .......... .......... 53% 10.4M 1s
 11200K .......... .......... .......... .......... .......... 53% 14.9M 1s
 11250K .......... .......... .......... .......... .......... 53% 9.57M 1s
 11300K .......... .......... .......... .......... .......... 53% 10.9M 1s
 11350K .......... .......... .......... .......... .......... 54% 17.7M 1s
 11400K .......... .......... .......... .......... .......... 54% 24.9M 1s
 11450K .......... .......... .......... .......... .......... 54% 9.97M 1s
 11500K .......... .......... .......... .......... .......... 54% 12.9M 1s

Downloading atb.assembly.r0.2.batch.79.tar.xz from https://osf.io/download/66714d4a0f8c8017c33c92a6/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d4a0f8c8017c33c92a6 [following]
--2026-09-06 18:52:50--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d4a0f8c8017c33c92a6
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/3ca982671659f7c91c6af96e1549224cb75b1a85749b0227562eedee00b0e1e7?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.79.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.79.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713631&Signature=EpNfM%2FL6tQvG03F3eNYLK6Y5VljNAaPPyjQqINJl%2FGaQmGA1iOzDFFOwwDSMCZtXwjAJycQpQpLoGJe1IMZPXTuGDKuau54inBqw92ogiFXNjPfU6nhM5niSjGkzeaHIOZQdUgu%2BbpiRXP9xnyYkc7BEJk4uUKDla4b1%2FZLBu7ws%2B4cQW308acta3atTGfue%2BZ6UTuL5%2BRYwNZeRcIze2Sjj0b7n35OdDOxXYdJKsZY42hQT96n4o%2Bw5YCbYWNp0EDInsP5qE9IRzUOO9HrtIXfh%2BwAyt8fr7GqW8783ZQJPznKs%2Ba3KbS3h2GKu3dvzfuP0maMSCLoywL8qoAPyZg%3D%3D [following]
--2026-09-06 18:52:51--  https://storage.googleapis.com/cos-osf-prod-files-de-1/3ca982671659f7c91c6af96e1549224cb75b1a85749b0227562eedee00b0e1e7?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.79.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.79.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713631&Signature=EpNfM%2FL6tQvG03F3eNYLK6Y5VljNAaPPyjQqINJl%2FGaQmGA1iOzDFFOwwDSMCZtXwjAJycQpQpLoGJe1IMZPXTuGDKuau54inBqw92ogiFXNjPfU6nhM5niSjGkzeaHIOZQdUgu%2BbpiRXP9xnyYkc7BEJk4uUKDla4b1%2FZLBu7ws%2B4cQW308acta3atTGfue%2BZ6UTuL5%2BRYwNZeRcIze2Sjj0b7n35OdDOxXYdJKsZY42hQT96n4o%2Bw5YCbYWNp0EDInsP5qE9IRzUOO9HrtIXfh%2BwAyt8fr7GqW8783ZQJPznKs%2Ba3KbS3h2GKu3dvzfuP0maMSCLoywL8qoAPyZg%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 56413784 (54M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.79.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.31M 41s
    50K .......... .......... .......... .......... ..........  0% 2.52M 31s
   100K .......... .......... .......... .......... ..........  0% 5.40M 24s
   150K .......... .......... .......... .......... ..........  0% 4.50M 21s
   200K .......... .......... .......... .......... ..........  0% 7.59M 18s
   250K .......... .......... .......... .......... ..........  0% 7.79M 16s
   300K .......... .......... .......... .......... ..........  0% 18.9M 14s
   350K .......... .......... .......... .......... ..........  0% 10.2M 13s
   400K .......... .......... .......... .......... ..........  0% 5.95M 13s
   450K .......... .......... .......... .......... ..........  0% 12.5M 12s
   500K .......... .......... .......... .......... ..........  0% 21.8M 11s
   550K .......... .......... .......... .......... ..........  1% 9.48M 11s
   600K .......... .......... .......... .......... ..........  1% 11.6M 10s
   650K .......... .......... .......... .......... ..........  1% 30.4M 9s
   700K .......... .......... .......... .......... ..........  1% 10.1M 9s
   750K .......... .......... .......... .......... ..........  1% 12.5M 9s
   800K .......... .......... .......... .......... ..........  1% 17.2M 9s
   850K .......... .......... .......... .......... ..........  1% 10.6M 8s
   900K .......... .......... .......... .......... ..........  1% 9.56M 8s
   950K .......... .......... .......... .......... ..........  1% 11.7M 8s
  1000K .......... .......... .......... .......... ..........  1% 23.7M 8s
  1050K .......... .......... .......... .......... ..........  1% 11.3M 8s
  1100K .......... .......... .......... .......... ..........  2% 11.9M 7s
  1150K .......... .......... .......... .......... ..........  2% 9.20M 7s
  1200K .......... .......... .......... .......... ..........  2% 17.9M 7s
  1250K .......... .......... .......... .......... ..........  2% 16.4M 7s
  1300K .......... .......... .......... .......... ..........  2% 9.69M 7s
  1350K .......... .......... .......... .......... ..........  2% 19.4M 7s
  1400K .......... .......... .......... .......... ..........  2% 10.8M 7s
  1450K .......... .......... .......... .......... ..........  2% 16.6M 7s
  1500K .......... .......... .......... .......... ..........  2% 11.2M 7s
  1550K .......... .......... .......... .......... ..........  2% 10.8M 6s
  1600K .......... .......... .......... .......... ..........  2% 14.6M 6s
  1650K .......... .......... .......... .......... ..........  3% 13.7M 6s
  1700K .......... .......... .......... .......... ..........  3% 9.99M 6s
  1750K .......... .......... .......... .......... ..........  3% 18.9M 6s
  1800K .......... .......... .......... .......... ..........  3% 14.0M 6s
  1850K .......... .......... .......... .......... ..........  3% 15.0M 6s
  1900K .......... .......... .......... .......... ..........  3% 9.47M 6s
  1950K .......... .......... .......... .......... ..........  3% 16.1M 6s
  2000K .......... .......... .......... .......... ..........  3% 9.67M 6s
  2050K .......... .......... .......... .......... ..........  3% 18.6M 6s
  2100K .......... .......... .......... .......... ..........  3% 16.9M 6s
  2150K .......... .......... .......... .......... ..........  3% 13.3M 6s
  2200K .......... .......... .......... .......... ..........  4% 11.0M 6s
  2250K .......... .......... .......... .......... ..........  4% 13.9M 6s
  2300K .......... .......... .......... .......... ..........  4% 14.4M 6s
  2350K .......... .......... .......... .......... ..........  4% 9.60M 6s
  2400K .......... .......... .......... .......... ..........  4% 11.2M 6s
  2450K .......... .......... .......... .......... ..........  4% 12.2M 5s
  2500K .......... .......... .......... .......... ..........  4% 15.0M 5s
  2550K .......... .......... .......... .......... ..........  4% 15.9M 5s
  2600K .......... .......... .......... .......... ..........  4% 10.3M 5s
  2650K .......... .......... .......... .......... ..........  4% 12.7M 5s
  2700K .......... .......... .......... .......... ..........  4% 16.9M 5s
  2750K .......... .......... .......... .......... ..........  5% 10.5M 5s
  2800K .......... .......... .......... .......... ..........  5% 13.1M 5s
  2850K .......... .......... .......... .......... ..........  5% 11.6M 5s
  2900K .......... .......... .......... .......... ..........  5% 10.7M 5s
  2950K .......... .......... .......... .......... ..........  5% 11.3M 5s
  3000K .......... .......... .......... .......... ..........  5% 43.0M 5s
  3050K .......... .......... .......... .......... ..........  5% 9.65M 5s
  3100K .......... .......... .......... .......... ..........  5% 15.0M 5s
  3150K .......... .......... .......... .......... ..........  5% 10.2M 5s
  3200K .......... .......... .......... .......... ..........  5% 12.6M 5s
  3250K .......... .......... .......... .......... ..........  5% 12.1M 5s
  3300K .......... .......... .......... .......... ..........  6% 12.5M 5s
  3350K .......... .......... .......... .......... ..........  6% 21.7M 5s
  3400K .......... .......... .......... .......... ..........  6% 11.2M 5s
  3450K .......... .......... .......... .......... ..........  6% 11.5M 5s
  3500K .......... .......... .......... .......... ..........  6% 29.5M 5s
  3550K .......... .......... .......... .......... ..........  6% 7.34M 5s
  3600K .......... .......... .......... .......... ..........  6% 18.1M 5s
  3650K .......... .......... .......... .......... ..........  6% 12.0M 5s
  3700K .......... .......... .......... .......... ..........  6% 15.4M 5s
  3750K .......... .......... .......... .......... ..........  6% 12.4M 5s
  3800K .......... .......... .......... .......... ..........  6% 13.7M 5s
  3850K .......... .......... .......... .......... ..........  7% 11.2M 5s
  3900K .......... .......... .......... .......... ..........  7% 12.8M 5s
  3950K .......... .......... .......... .......... ..........  7% 12.3M 5s
  4000K .......... .......... .......... .......... ..........  7% 11.6M 5s
  4050K .......... .......... .......... .......... ..........  7% 9.78M 5s
  4100K .......... .......... .......... .......... ..........  7% 45.2M 5s
  4150K .......... .......... .......... .......... ..........  7% 10.8M 5s
  4200K .......... .......... .......... .......... ..........  7% 13.1M 5s
  4250K .......... .......... .......... .......... ..........  7% 12.2M 5s
  4300K .......... .......... .......... .......... ..........  7% 9.55M 5s
  4350K .......... .......... .......... .......... ..........  7% 14.0M 5s
  4400K .......... .......... .......... .......... ..........  8% 11.1M 5s
  4450K .......... .......... .......... .......... ..........  8% 13.9M 5s
  4500K .......... .......... .......... .......... ..........  8% 16.2M 5s
  4550K .......... .......... .......... .......... ..........  8% 14.4M 5s
  4600K .......... .......... .......... .......... ..........  8% 11.6M 5s
  4650K .......... .......... .......... .......... ..........  8% 16.1M 5s
  4700K .......... .......... .......... .......... ..........  8% 12.1M 5s
  4750K .......... .......... .......... .......... ..........  8% 7.97M 5s
  4800K .......... .......... .......... .......... ..........  8% 20.1M 5s
  4850K .......... .......... .......... .......... ..........  8% 11.7M 5s
  4900K .......... .......... .......... .......... ..........  8% 13.8M 5s
  4950K .......... .......... .......... .......... ..........  9% 17.6M 5s
  5000K .......... .......... .......... .......... ..........  9% 12.0M 5s
  5050K .......... .......... .......... .......... ..........  9% 11.5M 5s
  5100K .......... .......... .......... .......... ..........  9% 20.1M 4s
  5150K .......... .......... .......... .......... ..........  9% 8.24M 4s
  5200K .......... .......... .......... .......... ..........  9% 9.70M 4s
  5250K .......... .......... .......... .......... ..........  9% 30.3M 4s
  5300K .......... .......... .......... .......... ..........  9% 11.8M 4s
  5350K .......... .......... .......... .......... ..........  9% 9.62M 4s
  5400K .......... .......... .......... .......... ..........  9% 27.5M 4s
  5450K .......... .......... .......... .......... ..........  9% 11.7M 4s
  5500K .......... .......... .......... .......... .......... 10% 11.4M 4s
  5550K .......... .......... .......... .......... .......... 10% 9.34M 4s
  5600K .......... .......... .......... .......... .......... 10% 20.1M 4s
  5650K .......... .......... .......... .......... .......... 10% 11.4M 4s
  5700K .......... .......... .......... .......... .......... 10% 18.1M 4s
  5750K .......... .......... .......... .......... .......... 10% 7.81M 4s
  5800K .......... .......... .......... .......... .......... 10% 14.1M 4s
  5850K .......... .......... .......... .......... .......... 10% 28.1M 4s
  5900K .......... .......... .......... .......... .......... 10% 16.7M 4s
  5950K .......... .......... .......... .......... .......... 10% 8.32M 4s
  6000K .......... .......... .......... .......... .......... 10% 10.5M 4s
  6050K .......... .......... .......... .......... .......... 11% 20.2M 4s
  6100K .......... .......... .......... .......... .......... 11% 9.50M 4s
  6150K .......... .......... .......... .......... .......... 11% 20.0M 4s
  6200K .......... .......... .......... .......... .......... 11% 13.3M 4s
  6250K .......... .......... .......... .......... .......... 11% 13.2M 4s
  6300K .......... .......... .......... .......... .......... 11% 10.2M 4s
  6350K .......... .......... .......... .......... .......... 11% 22.8M 4s
  6400K .......... .......... .......... .......... .......... 11% 11.4M 4s
  6450K .......... .......... .......... .......... .......... 11% 10.1M 4s
  6500K .......... .......... .......... .......... .......... 11% 10.9M 4s
  6550K .......... .......... .......... .......... .......... 11% 28.6M 4s
  6600K .......... .......... .......... .......... .......... 12% 9.91M 4s
  6650K .......... .......... .......... .......... .......... 12% 14.8M 4s
  6700K .......... .......... .......... .......... .......... 12% 8.91M 4s
  6750K .......... .......... .......... .......... .......... 12% 12.4M 4s
  6800K .......... .......... .......... .......... .......... 12% 11.0M 4s
  6850K .......... .......... .......... .......... .......... 12% 16.4M 4s
  6900K .......... .......... .......... .......... .......... 12% 22.1M 4s
  6950K .......... .......... .......... .......... .......... 12% 13.6M 4s
  7000K .......... .......... .......... .......... .......... 12% 10.7M 4s
  7050K .......... .......... .......... .......... .......... 12% 14.0M 4s
  7100K .......... .......... .......... .......... .......... 12% 11.1M 4s
  7150K .......... .......... .......... .......... .......... 13% 10.5M 4s
  7200K .......... .......... .......... .......... .......... 13% 12.3M 4s
  7250K .......... .......... .......... .......... .......... 13% 24.3M 4s
  7300K .......... .......... .......... .......... .......... 13% 10.0M 4s
  7350K .......... .......... .......... .......... .......... 13% 16.4M 4s
  7400K .......... .......... .......... .......... .......... 13% 13.7M 4s
  7450K .......... .......... .......... .......... .......... 13% 14.4M 4s
  7500K .......... .......... .......... .......... .......... 13% 11.4M 4s
  7550K .......... .......... .......... .......... .......... 13% 8.03M 4s
  7600K .......... .......... .......... .......... .......... 13% 21.5M 4s
  7650K .......... .......... .......... .......... .......... 13% 11.0M 4s
  7700K .......... .......... .......... .......... .......... 14% 13.6M 4s
  7750K .......... .......... .......... .......... .......... 14% 19.3M 4s
  7800K .......... .......... .......... .......... .......... 14% 11.8M 4s
  7850K .......... .......... .......... .......... .......... 14% 12.7M 4s
  7900K .......... .......... .......... .......... .......... 14% 12.5M 4s
  7950K .......... .......... .......... .......... .......... 14% 8.20M 4s
  8000K .......... .......... .......... .......... .......... 14% 16.8M 4s
  8050K .......... .......... .......... .......... .......... 14% 15.6M 4s
  8100K .......... .......... .......... .......... .......... 14% 14.5M 4s
  8150K .......... .......... .......... .......... .......... 14% 10.4M 4s
  8200K .......... .......... .......... .......... .......... 14% 11.2M 4s
  8250K .......... .......... .......... .......... .......... 15% 36.9M 4s
  8300K .......... .......... .......... .......... .......... 15% 7.78M 4s
  8350K .......... .......... .......... .......... .......... 15% 34.2M 4s
  8400K .......... .......... .......... .......... .......... 15% 7.76M 4s
  8450K .......... .......... .......... .......... .......... 15% 14.4M 4s
  8500K .......... .......... .......... .......... .......... 15% 16.9M 4s
  8550K .......... .......... .......... .......... .......... 15% 9.91M 4s
  8600K .......... .......... .......... .......... .......... 15% 19.4M 4s
  8650K .......... .......... .......... .......... .......... 15% 9.30M 4s
  8700K .......... .......... .......... .......... .......... 15% 14.9M 4s
  8750K .......... .......... .......... .......... .......... 15% 10.6M 4s
  8800K .......... .......... .......... .......... .......... 16% 14.8M 4s
  8850K .......... .......... .......... .......... .......... 16% 12.5M 4s
  8900K .......... .......... .......... .......... .......... 16% 10.9M 4s
  8950K .......... .......... .......... .......... .......... 16% 12.4M 4s
  9000K .......... .......... .......... .......... .......... 16% 18.3M 4s
  9050K .......... .......... .......... .......... .......... 16% 20.6M 4s
  9100K .......... .......... .......... .......... .......... 16% 12.5M 4s
  9150K .......... .......... .......... .......... .......... 16% 9.94M 4s
  9200K .......... .......... .......... .......... .......... 16% 5.99M 4s
  9250K .......... .......... .......... .......... .......... 16%  136M 4s
  9300K .......... .......... .......... .......... .......... 16% 16.6M 4s
  9350K .......... .......... .......... .......... .......... 17% 11.7M 4s
  9400K .......... .......... .......... .......... .......... 17% 14.9M 4s
  9450K .......... .......... .......... .......... .......... 17% 9.60M 4s
  9500K .......... .......... .......... .......... .......... 17% 29.2M 4s
  9550K .......... .......... .......... .......... .......... 17% 7.45M 4s
  9600K .......... .......... .......... .......... .......... 17% 15.1M 4s
  9650K .......... .......... .......... .......... .......... 17% 10.5M 4s
  9700K .......... .......... .......... .......... .......... 17% 22.2M 4s
  9750K .......... .......... .......... .......... .......... 17% 11.0M 4s
  9800K .......... .......... .......... .......... .......... 17% 11.9M 4s
  9850K .......... .......... .......... .......... .......... 17% 22.2M 4s
  9900K .......... .......... .......... .......... .......... 18% 14.5M 4s
  9950K .......... .......... .......... .......... .......... 18% 8.85M 4s
 10000K .......... .......... .......... .......... .......... 18% 12.8M 4s
 10050K .......... .......... .......... .......... .......... 18% 18.8M 4s
 10100K .......... .......... .......... .......... .......... 18% 11.5M 4s
 10150K .......... .......... .......... .......... .......... 18% 12.4M 4s
 10200K .......... .......... .......... .......... .......... 18% 17.6M 4s
 10250K .......... .......... .......... .......... .......... 18% 9.02M 4s
 10300K .......... .......... .......... .......... .......... 18% 14.7M 4s
 10350K .......... .......... .......... .......... .......... 18% 13.0M 4s
 10400K .......... .......... .......... .......... .......... 18% 8.87M 4s
 10450K .......... .......... .......... .......... .......... 19% 28.4M 4s
 10500K .......... .......... .......... .......... .......... 19% 12.5M 4s
 10550K .......... .......... .......... .......... .......... 19% 14.0M 4s
 10600K .......... .......... .......... .......... .......... 19% 8.49M 4s
 10650K .......... .......... .......... .......... .......... 19% 22.9M 4s
 10700K .......... .......... .......... .......... .......... 19% 13.4M 4s
 10750K .......... .......... .......... .......... .......... 19% 7.78M 4s
 10800K .......... .......... .......... .......... .......... 19% 44.3M 4s
 10850K .......... .......... .......... .......... .......... 19% 8.24M 4s
 10900K .......... .......... .......... .......... .......... 19% 15.0M 4s
 10950K .......... .......... .......... .......... .......... 19% 14.0M 4s
 11000K .......... .......... .......... .......... .......... 20% 10.2M 4s
 11050K .......... .......... .......... .......... .......... 20% 13.8M 4s
 11100K .......... .......... .......... .......... .......... 20% 8.99M 4s
 11150K .......... .......... .......... .......... .......... 20% 18.3M 4s
 11200K .......... .......... .......... .......... .......... 20% 15.2M 4s
 11250K .......... .......... .......... .......... .......... 20% 9.20M 4s
 11300K .......... .......... .......... .......... .......... 20% 22.6M 4s
 11350K .......... .......... .......... .......... .......... 20% 13.5M 4s
 11400K .......... .......... .......... .......... .......... 20% 12.2M 4s
 11450K .......... .......... .......... .......... .......... 20% 23.5M 4s
 11500K .......... .......... .......... .......... .......... 20% 9.51M 4s

Downloading atb.assembly.r0.2.batch.80.tar.xz from https://osf.io/download/66714d4a0f8c8017b73c99d8/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d4a0f8c8017b73c99d8 [following]
--2026-09-06 18:52:56--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66714d4a0f8c8017b73c99d8
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/d03b90aff6437ea1fc288ebcd8a87d6db99b5bf26d7835761edd6cf98f2c3881?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.80.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.80.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713638&Signature=wppztm92ka5rka3ZNHlVd%2FtUht2BKZmuViOJy1FyX5jl%2BSssi2iA%2FYCwufZ9%2FXAl3ZPmCor72RcMy8f0rQiMil0Vhx%2FXSVjxAnvaegjMWzCQ4AELrnElCLG8UQ9BIqKEYsPmK6nJEdLXNoJh8NlTQRHsYGyUWcmoV5MD6wDG1%2F2qhnW4E%2FAiHLsiZLs%2BL7oWqWljLZflTvOfiVErxtUwV9IAYsRH87oxnDeayoTNnnVFhqTJSR8NXpGHwdxoTL0SQnDRTtPVoGJBkkaJ46K6T6cPbuWMFlfZidoTQ%2FpGC5jLOtS%2F6TsxkAtnk2vTs6UHX25P9Uzobtm2UI21uJVYLA%3D%3D [following]
--2026-09-06 18:52:58--  https://storage.googleapis.com/cos-osf-prod-files-de-1/d03b90aff6437ea1fc288ebcd8a87d6db99b5bf26d7835761edd6cf98f2c3881?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.80.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.80.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713638&Signature=wppztm92ka5rka3ZNHlVd%2FtUht2BKZmuViOJy1FyX5jl%2BSssi2iA%2FYCwufZ9%2FXAl3ZPmCor72RcMy8f0rQiMil0Vhx%2FXSVjxAnvaegjMWzCQ4AELrnElCLG8UQ9BIqKEYsPmK6nJEdLXNoJh8NlTQRHsYGyUWcmoV5MD6wDG1%2F2qhnW4E%2FAiHLsiZLs%2BL7oWqWljLZflTvOfiVErxtUwV9IAYsRH87oxnDeayoTNnnVFhqTJSR8NXpGHwdxoTL0SQnDRTtPVoGJBkkaJ46K6T6cPbuWMFlfZidoTQ%2FpGC5jLOtS%2F6TsxkAtnk2vTs6UHX25P9Uzobtm2UI21uJVYLA%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 53295292 (51M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.80.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.30M 39s
    50K .......... .......... .......... .......... ..........  0% 2.51M 30s
   100K .......... .......... .......... .......... ..........  0% 4.05M 24s
   150K .......... .......... .......... .......... ..........  0% 4.36M 21s
   200K .......... .......... .......... .......... ..........  0% 8.80M 18s
   250K .......... .......... .......... .......... ..........  0% 7.52M 16s
   300K .......... .......... .......... .......... ..........  0% 9.61M 14s
   350K .......... .......... .......... .......... ..........  0% 10.6M 13s
   400K .......... .......... .......... .......... ..........  0% 17.0M 12s
   450K .......... .......... .......... .......... ..........  0% 2.90M 13s
   500K .......... .......... .......... .......... ..........  1% 72.3M 11s
   550K .......... .......... .......... .......... ..........  1% 62.7M 11s
   600K .......... .......... .......... .......... ..........  1% 85.7M 10s
   650K .......... .......... .......... .......... ..........  1% 11.2M 9s
   700K .......... .......... .......... .......... ..........  1% 4.89M 9s
   750K .......... .......... .......... .......... ..........  1% 12.1M 9s
   800K .......... .......... .......... .......... ..........  1% 11.6M 9s
   850K .......... .......... .......... .......... ..........  1% 14.2M 9s
   900K .......... .......... .......... .......... ..........  1% 9.74M 8s
   950K .......... .......... .......... .......... ..........  1% 14.4M 8s
  1000K .......... .......... .......... .......... ..........  2% 16.7M 8s
  1050K .......... .......... .......... .......... ..........  2% 13.9M 8s
  1100K .......... .......... .......... .......... ..........  2% 11.5M 7s
  1150K .......... .......... .......... .......... ..........  2% 6.87M 7s
  1200K .......... .......... .......... .......... ..........  2% 20.4M 7s
  1250K .......... .......... .......... .......... ..........  2% 10.7M 7s
  1300K .......... .......... .......... .......... ..........  2% 14.9M 7s
  1350K .......... .......... .......... .......... ..........  2% 30.0M 7s
  1400K .......... .......... .......... .......... ..........  2% 12.0M 7s
  1450K .......... .......... .......... .......... ..........  2% 17.7M 7s
  1500K .......... .......... .......... .......... ..........  2% 6.04M 7s
  1550K .......... .......... .......... .......... ..........  3% 11.2M 7s
  1600K .......... .......... .......... .......... ..........  3%  115M 6s
  1650K .......... .......... .......... .......... ..........  3% 7.75M 6s
  1700K .......... .......... .......... .......... ..........  3% 28.1M 6s
  1750K .......... .......... .......... .......... ..........  3% 12.7M 6s
  1800K .......... .......... .......... .......... ..........  3% 14.5M 6s
  1850K .......... .......... .......... .......... ..........  3% 15.2M 6s
  1900K .......... .......... .......... .......... ..........  3% 10.7M 6s
  1950K .......... .......... .......... .......... ..........  3% 12.2M 6s
  2000K .......... .......... .......... .......... ..........  3% 10.0M 6s
  2050K .......... .......... .......... .......... ..........  4% 23.7M 6s
  2100K .......... .......... .......... .......... ..........  4% 13.2M 6s
  2150K .......... .......... .......... .......... ..........  4% 10.5M 6s
  2200K .......... .......... .......... .......... ..........  4% 26.5M 6s
  2250K .......... .......... .......... .......... ..........  4% 11.1M 6s
  2300K .......... .......... .......... .......... ..........  4% 10.6M 6s
  2350K .......... .......... .......... .......... ..........  4% 12.8M 5s
  2400K .......... .......... .......... .......... ..........  4% 13.6M 5s
  2450K .......... .......... .......... .......... ..........  4% 14.1M 5s
  2500K .......... .......... .......... .......... ..........  4% 10.5M 5s
  2550K .......... .......... .......... .......... ..........  4% 13.2M 5s
  2600K .......... .......... .......... .......... ..........  5% 13.1M 5s
  2650K .......... .......... .......... .......... ..........  5% 12.7M 5s
  2700K .......... .......... .......... .......... ..........  5% 29.3M 5s
  2750K .......... .......... .......... .......... ..........  5% 7.20M 5s
  2800K .......... .......... .......... .......... ..........  5% 14.0M 5s
  2850K .......... .......... .......... .......... ..........  5% 9.88M 5s
  2900K .......... .......... .......... .......... ..........  5% 65.0M 5s
  2950K .......... .......... .......... .......... ..........  5% 8.91M 5s
  3000K .......... .......... .......... .......... ..........  5% 9.09M 5s
  3050K .......... .......... .......... .......... ..........  5% 17.2M 5s
  3100K .......... .......... .......... .......... ..........  6% 9.79M 5s
  3150K .......... .......... .......... .......... ..........  6% 13.5M 5s
  3200K .......... .......... .......... .......... ..........  6% 15.0M 5s
  3250K .......... .......... .......... .......... ..........  6% 12.7M 5s
  3300K .......... .......... .......... .......... ..........  6% 13.5M 5s
  3350K .......... .......... .......... .......... ..........  6% 12.9M 5s
  3400K .......... .......... .......... .......... ..........  6% 8.83M 5s
  3450K .......... .......... .......... .......... ..........  6% 25.7M 5s
  3500K .......... .......... .......... .......... ..........  6% 11.8M 5s
  3550K .......... .......... .......... .......... ..........  6% 8.52M 5s
  3600K .......... .......... .......... .......... ..........  7% 22.7M 5s
  3650K .......... .......... .......... .......... ..........  7% 15.0M 5s
  3700K .......... .......... .......... .......... ..........  7% 14.5M 5s
  3750K .......... .......... .......... .......... ..........  7% 11.5M 5s
  3800K .......... .......... .......... .......... ..........  7% 11.2M 5s
  3850K .......... .......... .......... .......... ..........  7% 23.1M 5s
  3900K .......... .......... .......... .......... ..........  7% 11.0M 5s
  3950K .......... .......... .......... .......... ..........  7% 8.72M 5s
  4000K .......... .......... .......... .......... ..........  7% 16.2M 5s
  4050K .......... .......... .......... .......... ..........  7% 7.66M 5s
  4100K .......... .......... .......... .......... ..........  7%  151M 5s
  4150K .......... .......... .......... .......... ..........  8% 10.4M 5s
  4200K .......... .......... .......... .......... ..........  8% 12.1M 5s
  4250K .......... .......... .......... .......... ..........  8% 12.1M 5s
  4300K .......... .......... .......... .......... ..........  8% 24.7M 5s
  4350K .......... .......... .......... .......... ..........  8% 9.29M 5s
  4400K .......... .......... .......... .......... ..........  8% 11.6M 5s
  4450K .......... .......... .......... .......... ..........  8% 11.7M 5s
  4500K .......... .......... .......... .......... ..........  8% 16.0M 4s
  4550K .......... .......... .......... .......... ..........  8% 12.6M 4s
  4600K .......... .......... .......... .......... ..........  8% 13.3M 4s
  4650K .......... .......... .......... .......... ..........  9% 11.9M 4s
  4700K .......... .......... .......... .......... ..........  9% 22.2M 4s
  4750K .......... .......... .......... .......... ..........  9% 7.28M 4s
  4800K .......... .......... .......... .......... ..........  9% 21.1M 4s
  4850K .......... .......... .......... .......... ..........  9% 12.8M 4s
  4900K .......... .......... .......... .......... ..........  9% 14.7M 4s
  4950K .......... .......... .......... .......... ..........  9% 12.1M 4s
  5000K .......... .......... .......... .......... ..........  9% 19.7M 4s
  5050K .......... .......... .......... .......... ..........  9% 12.1M 4s
  5100K .......... .......... .......... .......... ..........  9% 8.33M 4s
  5150K .......... .......... .......... .......... ..........  9% 16.6M 4s
  5200K .......... .......... .......... .......... .......... 10% 9.07M 4s
  5250K .......... .......... .......... .......... .......... 10% 31.1M 4s
  5300K .......... .......... .......... .......... .......... 10% 9.77M 4s
  5350K .......... .......... .......... .......... .......... 10% 15.3M 4s
  5400K .......... .......... .......... .......... .......... 10% 13.8M 4s
  5450K .......... .......... .......... .......... .......... 10% 10.4M 4s
  5500K .......... .......... .......... .......... .......... 10% 18.7M 4s
  5550K .......... .......... .......... .......... .......... 10% 10.8M 4s
  5600K .......... .......... .......... .......... .......... 10% 11.5M 4s
  5650K .......... .......... .......... .......... .......... 10% 11.9M 4s
  5700K .......... .......... .......... .......... .......... 11% 18.7M 4s
  5750K .......... .......... .......... .......... .......... 11% 9.05M 4s
  5800K .......... .......... .......... .......... .......... 11% 14.1M 4s
  5850K .......... .......... .......... .......... .......... 11% 20.1M 4s
  5900K .......... .......... .......... .......... .......... 11% 8.00M 4s
  5950K .......... .......... .......... .......... .......... 11% 11.8M 4s
  6000K .......... .......... .......... .......... .......... 11% 14.3M 4s
  6050K .......... .......... .......... .......... .......... 11% 15.8M 4s
  6100K .......... .......... .......... .......... .......... 11% 18.2M 4s
  6150K .......... .......... .......... .......... .......... 11% 8.86M 4s
  6200K .......... .......... .......... .......... .......... 12% 31.0M 4s
  6250K .......... .......... .......... .......... .......... 12% 10.5M 4s
  6300K .......... .......... .......... .......... .......... 12% 10.8M 4s
  6350K .......... .......... .......... .......... .......... 12% 13.3M 4s
  6400K .......... .......... .......... .......... .......... 12% 14.1M 4s
  6450K .......... .......... .......... .......... .......... 12% 15.8M 4s
  6500K .......... .......... .......... .......... .......... 12% 10.7M 4s
  6550K .......... .......... .......... .......... .......... 12% 13.4M 4s
  6600K .......... .......... .......... .......... .......... 12% 14.1M 4s
  6650K .......... .......... .......... .......... .......... 12% 9.76M 4s
  6700K .......... .......... .......... .......... .......... 12% 15.9M 4s
  6750K .......... .......... .......... .......... .......... 13% 8.50M 4s
  6800K .......... .......... .......... .......... .......... 13% 12.3M 4s
  6850K .......... .......... .......... .......... .......... 13% 14.5M 4s
  6900K .......... .......... .......... .......... .......... 13% 15.0M 4s
  6950K .......... .......... .......... .......... .......... 13% 20.9M 4s
  7000K .......... .......... .......... .......... .......... 13% 11.5M 4s
  7050K .......... .......... .......... .......... .......... 13% 17.1M 4s
  7100K .......... .......... .......... .......... .......... 13% 6.13M 4s
  7150K .......... .......... .......... .......... .......... 13% 59.6M 4s
  7200K .......... .......... .......... .......... .......... 13% 11.4M 4s
  7250K .......... .......... .......... .......... .......... 14% 15.1M 4s
  7300K .......... .......... .......... .......... .......... 14% 11.7M 4s
  7350K .......... .......... .......... .......... .......... 14% 14.1M 4s
  7400K .......... .......... .......... .......... .......... 14% 11.7M 4s
  7450K .......... .......... .......... .......... .......... 14% 19.2M 4s
  7500K .......... .......... .......... .......... .......... 14% 12.8M 4s
  7550K .......... .......... .......... .......... .......... 14% 8.53M 4s
  7600K .......... .......... .......... .......... .......... 14% 12.9M 4s
  7650K .......... .......... .......... .......... .......... 14% 14.6M 4s
  7700K .......... .......... .......... .......... .......... 14% 15.0M 4s
  7750K .......... .......... .......... .......... .......... 14% 11.4M 4s
  7800K .......... .......... .......... .......... .......... 15% 11.5M 4s
  7850K .......... .......... .......... .......... .......... 15% 13.9M 4s
  7900K .......... .......... .......... .......... .......... 15% 17.4M 4s
  7950K .......... .......... .......... .......... .......... 15% 7.53M 4s
  8000K .......... .......... .......... .......... .......... 15% 15.9M 4s
  8050K .......... .......... .......... .......... .......... 15% 27.7M 4s
  8100K .......... .......... .......... .......... .......... 15% 14.0M 4s
  8150K .......... .......... .......... .......... .......... 15% 8.50M 4s
  8200K .......... .......... .......... .......... .......... 15% 7.11M 4s
  8250K .......... .......... .......... .......... .......... 15% 68.9M 4s
  8300K .......... .......... .......... .......... .......... 16% 32.9M 4s
  8350K .......... .......... .......... .......... .......... 16% 7.54M 4s
  8400K .......... .......... .......... .......... .......... 16% 14.4M 4s
  8450K .......... .......... .......... .......... .......... 16% 12.2M 4s
  8500K .......... .......... .......... .......... .......... 16% 16.4M 4s
  8550K .......... .......... .......... .......... .......... 16% 11.2M 4s
  8600K .......... .......... .......... .......... .......... 16% 11.4M 4s
  8650K .......... .......... .......... .......... .......... 16% 15.6M 4s
  8700K .......... .......... .......... .......... .......... 16% 19.4M 4s
  8750K .......... .......... .......... .......... .......... 16% 8.51M 4s
  8800K .......... .......... .......... .......... .......... 17% 17.4M 4s
  8850K .......... .......... .......... .......... .......... 17% 11.0M 4s
  8900K .......... .......... .......... .......... .......... 17% 17.7M 4s
  8950K .......... .......... .......... .......... .......... 17% 10.3M 4s
  9000K .......... .......... .......... .......... .......... 17% 20.8M 4s
  9050K .......... .......... .......... .......... .......... 17% 9.14M 4s
  9100K .......... .......... .......... .......... .......... 17% 20.3M 4s
  9150K .......... .......... .......... .......... .......... 17% 9.17M 4s
  9200K .......... .......... .......... .......... .......... 17% 13.7M 4s
  9250K .......... .......... .......... .......... .......... 17% 13.5M 4s
  9300K .......... .......... .......... .......... .......... 17% 10.1M 4s
  9350K .......... .......... .......... .......... .......... 18% 12.0M 4s
  9400K .......... .......... .......... .......... .......... 18% 16.9M 4s
  9450K .......... .......... .......... .......... .......... 18% 12.3M 4s
  9500K .......... .......... .......... .......... .......... 18% 14.8M 4s
  9550K .......... .......... .......... .......... .......... 18% 10.1M 4s
  9600K .......... .......... .......... .......... .......... 18% 12.2M 4s
  9650K .......... .......... .......... .......... .......... 18% 14.0M 4s
  9700K .......... .......... .......... .......... .......... 18% 15.5M 4s
  9750K .......... .......... .......... .......... .......... 18% 17.0M 4s
  9800K .......... .......... .......... .......... .......... 18% 13.5M 4s
  9850K .......... .......... .......... .......... .......... 19% 16.0M 4s
  9900K .......... .......... .......... .......... .......... 19% 8.36M 4s
  9950K .......... .......... .......... .......... .......... 19% 10.8M 4s
 10000K .......... .......... .......... .......... .......... 19% 18.8M 4s
 10050K .......... .......... .......... .......... .......... 19% 11.9M 4s
 10100K .......... .......... .......... .......... .......... 19% 9.74M 4s
 10150K .......... .......... .......... .......... .......... 19% 12.0M 4s
 10200K .......... .......... .......... .......... .......... 19% 21.5M 4s
 10250K .......... .......... .......... .......... .......... 19% 9.12M 4s
 10300K .......... .......... .......... .......... .......... 19% 24.1M 4s
 10350K .......... .......... .......... .......... .......... 19% 10.2M 4s
 10400K .......... .......... .......... .......... .......... 20% 19.4M 4s
 10450K .......... .......... .......... .......... .......... 20% 10.2M 4s
 10500K .......... .......... .......... .......... .......... 20% 11.8M 3s
 10550K .......... .......... .......... .......... .......... 20% 17.0M 3s
 10600K .......... .......... .......... .......... .......... 20% 16.5M 3s
 10650K .......... .......... .......... .......... .......... 20% 11.5M 3s
 10700K .......... .......... .......... .......... .......... 20% 9.37M 3s
 10750K .......... .......... .......... .......... .......... 20% 11.9M 3s
 10800K .......... .......... .......... .......... .......... 20% 13.7M 3s
 10850K .......... .......... .......... .......... .......... 20% 9.47M 3s
 10900K .......... .......... .......... .......... .......... 21% 28.2M 3s
 10950K .......... .......... .......... .......... .......... 21% 9.91M 3s
 11000K .......... .......... .......... .......... .......... 21% 13.7M 3s
 11050K .......... .......... .......... .......... .......... 21% 15.2M 3s
 11100K .......... .......... .......... .......... .......... 21% 17.3M 3s
 11150K .......... .......... .......... .......... .......... 21% 7.88M 3s
 11200K .......... .......... .......... .......... .......... 21% 12.0M 3s
 11250K .......... .......... .......... .......... .......... 21% 27.1M 3s
 11300K .......... .......... .......... .......... .......... 21% 8.97M 3s
 11350K .......... .......... .......... .......... .......... 21% 24.9M 3s
 11400K .......... .......... .......... .......... .......... 21% 13.2M 3s
 11450K .......... .......... .......... .......... .......... 22% 11.4M 3s
 11500K .......... .......... .......... .......... .......... 22% 14.1M 3s

Downloading atb.assembly.r0.2.batch.82.tar.xz from https://osf.io/download/6671525fd835c439b54cdd03/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671525fd835c439b54cdd03 [following]
--2026-09-06 18:53:02--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671525fd835c439b54cdd03
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/3467f2dd92bbc14fee1a30a45beab347e58f18c8131b5dc27c0e7d8ef985e8ba?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.82.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.82.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713643&Signature=tNf%2BKU7aTOyKQA0b630lB3HPshk7DPC0lJPFuagjMPjd67HLnVyM0Wj1sR8fxt2mEZf%2FH9DZhP%2BLzO4q239SUTtEc7t%2FuJMnNuYAc3Zj1A%2FWMrdaHrpqFARXAtWdKVIUwnG1f9Bf8OPX3pdd%2B0oPQJUGm3LMXkF4HrrRZ%2Bx4Oxp%2BpV3r9ZojDTPmTzzxpDWbSR3jKur9jvB9QwRTW9NuxV9LcdRJaOJCBcRS0fhl3m3rvQcepujnivRL4bm%2BphxUfDlShOT3%2FNJckPFwXMbPl%2F2Fn9KQmliPtpalx5Q9icL3B7Wk8gPFEx0%2BcTClaIHnAGkOh%2B7Q1J9EB1zvLWk%2F%2FA%3D%3D [following]
--2026-09-06 18:53:03--  https://storage.googleapis.com/cos-osf-prod-files-de-1/3467f2dd92bbc14fee1a30a45beab347e58f18c8131b5dc27c0e7d8ef985e8ba?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.82.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.82.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713643&Signature=tNf%2BKU7aTOyKQA0b630lB3HPshk7DPC0lJPFuagjMPjd67HLnVyM0Wj1sR8fxt2mEZf%2FH9DZhP%2BLzO4q239SUTtEc7t%2FuJMnNuYAc3Zj1A%2FWMrdaHrpqFARXAtWdKVIUwnG1f9Bf8OPX3pdd%2B0oPQJUGm3LMXkF4HrrRZ%2Bx4Oxp%2BpV3r9ZojDTPmTzzxpDWbSR3jKur9jvB9QwRTW9NuxV9LcdRJaOJCBcRS0fhl3m3rvQcepujnivRL4bm%2BphxUfDlShOT3%2FNJckPFwXMbPl%2F2Fn9KQmliPtpalx5Q9icL3B7Wk8gPFEx0%2BcTClaIHnAGkOh%2B7Q1J9EB1zvLWk%2F%2FA%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 70080508 (67M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.82.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.34M 50s
    50K .......... .......... .......... .......... ..........  0% 2.89M 36s
   100K .......... .......... .......... .......... ..........  0% 4.44M 29s
   150K .......... .......... .......... .......... ..........  0% 5.11M 25s
   200K .......... .......... .......... .......... ..........  0% 7.76M 22s
   250K .......... .......... .......... .......... ..........  0% 9.09M 19s
   300K .......... .......... .......... .......... ..........  0% 10.1M 18s
   350K .......... .......... .......... .......... ..........  0% 10.6M 16s
   400K .......... .......... .......... .......... ..........  0% 13.4M 15s
   450K .......... .......... .......... .......... ..........  0% 8.17M 14s
   500K .......... .......... .......... .......... ..........  0% 16.3M 13s
   550K .......... .......... .......... .......... ..........  0% 14.8M 13s
   600K .......... .......... .......... .......... ..........  0% 10.4M 12s
   650K .......... .......... .......... .......... ..........  1% 14.9M 12s
   700K .......... .......... .......... .......... ..........  1% 12.5M 11s
   750K .......... .......... .......... .......... ..........  1% 12.4M 11s
   800K .......... .......... .......... .......... ..........  1% 15.9M 10s
   850K .......... .......... .......... .......... ..........  1% 11.6M 10s
   900K .......... .......... .......... .......... ..........  1% 10.1M 10s
   950K .......... .......... .......... .......... ..........  1% 14.2M 10s
  1000K .......... .......... .......... .......... ..........  1% 13.5M 9s
  1050K .......... .......... .......... .......... ..........  1% 13.6M 9s
  1100K .......... .......... .......... .......... ..........  1% 18.7M 9s
  1150K .......... .......... .......... .......... ..........  1% 10.0M 9s
  1200K .......... .......... .......... .......... ..........  1% 10.5M 9s
  1250K .......... .......... .......... .......... ..........  1% 16.5M 9s
  1300K .......... .......... .......... .......... ..........  1% 11.5M 8s
  1350K .......... .......... .......... .......... ..........  2% 16.6M 8s
  1400K .......... .......... .......... .......... ..........  2% 9.41M 8s
  1450K .......... .......... .......... .......... ..........  2% 11.4M 8s
  1500K .......... .......... .......... .......... ..........  2% 25.5M 8s
  1550K .......... .......... .......... .......... ..........  2% 11.9M 8s
  1600K .......... .......... .......... .......... ..........  2% 9.03M 8s
  1650K .......... .......... .......... .......... ..........  2% 30.0M 8s
  1700K .......... .......... .......... .......... ..........  2% 10.1M 8s
  1750K .......... .......... .......... .......... ..........  2% 13.5M 8s
  1800K .......... .......... .......... .......... ..........  2% 9.60M 7s
  1850K .......... .......... .......... .......... ..........  2% 17.6M 7s
  1900K .......... .......... .......... .......... ..........  2% 17.4M 7s
  1950K .......... .......... .......... .......... ..........  2% 11.4M 7s
  2000K .......... .......... .......... .......... ..........  2% 10.5M 7s
  2050K .......... .......... .......... .......... ..........  3% 10.7M 7s
  2100K .......... .......... .......... .......... ..........  3% 17.1M 7s
  2150K .......... .......... .......... .......... ..........  3% 19.8M 7s
  2200K .......... .......... .......... .......... ..........  3% 15.3M 7s
  2250K .......... .......... .......... .......... ..........  3% 7.85M 7s
  2300K .......... .......... .......... .......... ..........  3% 16.3M 7s
  2350K .......... .......... .......... .......... ..........  3% 12.4M 7s
  2400K .......... .......... .......... .......... ..........  3% 13.9M 7s
  2450K .......... .......... .......... .......... ..........  3% 14.8M 7s
  2500K .......... .......... .......... .......... ..........  3% 13.8M 7s
  2550K .......... .......... .......... .......... ..........  3% 9.39M 7s
  2600K .......... .......... .......... .......... ..........  3% 31.4M 7s
  2650K .......... .......... .......... .......... ..........  3% 12.2M 7s
  2700K .......... .......... .......... .......... ..........  4% 11.2M 7s
  2750K .......... .......... .......... .......... ..........  4% 9.34M 7s
  2800K .......... .......... .......... .......... ..........  4% 12.4M 7s
  2850K .......... .......... .......... .......... ..........  4% 12.0M 6s
  2900K .......... .......... .......... .......... ..........  4% 14.5M 6s
  2950K .......... .......... .......... .......... ..........  4% 12.4M 6s
  3000K .......... .......... .......... .......... ..........  4% 9.36M 6s
  3050K .......... .......... .......... .......... ..........  4% 23.2M 6s
  3100K .......... .......... .......... .......... ..........  4% 14.2M 6s
  3150K .......... .......... .......... .......... ..........  4% 11.6M 6s
  3200K .......... .......... .......... .......... ..........  4% 13.0M 6s
  3250K .......... .......... .......... .......... ..........  4% 11.0M 6s
  3300K .......... .......... .......... .......... ..........  4% 12.6M 6s
  3350K .......... .......... .......... .......... ..........  4% 16.6M 6s
  3400K .......... .......... .......... .......... ..........  5% 11.6M 6s
  3450K .......... .......... .......... .......... ..........  5% 19.0M 6s
  3500K .......... .......... .......... .......... ..........  5% 12.4M 6s
  3550K .......... .......... .......... .......... ..........  5% 12.4M 6s
  3600K .......... .......... .......... .......... ..........  5% 7.56M 6s
  3650K .......... .......... .......... .......... ..........  5% 13.0M 6s
  3700K .......... .......... .......... .......... ..........  5% 37.3M 6s
  3750K .......... .......... .......... .......... ..........  5% 11.0M 6s
  3800K .......... .......... .......... .......... ..........  5% 14.7M 6s
  3850K .......... .......... .......... .......... ..........  5% 10.0M 6s
  3900K .......... .......... .......... .......... ..........  5% 24.9M 6s
  3950K .......... .......... .......... .......... ..........  5% 9.16M 6s
  4000K .......... .......... .......... .......... ..........  5% 11.0M 6s
  4050K .......... .......... .......... .......... ..........  5% 9.77M 6s
  4100K .......... .......... .......... .......... ..........  6% 23.5M 6s
  4150K .......... .......... .......... .......... ..........  6% 17.3M 6s
  4200K .......... .......... .......... .......... ..........  6% 9.86M 6s
  4250K .......... .......... .......... .......... ..........  6% 21.9M 6s
  4300K .......... .......... .......... .......... ..........  6% 12.0M 6s
  4350K .......... .......... .......... .......... ..........  6% 6.24M 6s
  4400K .......... .......... .......... .......... ..........  6%  193M 6s
  4450K .......... .......... .......... .......... ..........  6% 12.5M 6s
  4500K .......... .......... .......... .......... ..........  6% 11.6M 6s
  4550K .......... .......... .......... .......... ..........  6% 8.75M 6s
  4600K .......... .......... .......... .......... ..........  6% 24.0M 6s
  4650K .......... .......... .......... .......... ..........  6% 13.3M 6s
  4700K .......... .......... .......... .......... ..........  6% 14.3M 6s
  4750K .......... .......... .......... .......... ..........  7% 11.5M 6s
  4800K .......... .......... .......... .......... ..........  7% 14.1M 6s
  4850K .......... .......... .......... .......... ..........  7% 8.82M 6s
  4900K .......... .......... .......... .......... ..........  7% 11.4M 6s
  4950K .......... .......... .......... .......... ..........  7% 19.0M 6s
  5000K .......... .......... .......... .......... ..........  7% 10.8M 6s
  5050K .......... .......... .......... .......... ..........  7% 27.1M 6s
  5100K .......... .......... .......... .......... ..........  7% 11.2M 6s
  5150K .......... .......... .......... .......... ..........  7% 8.52M 6s
  5200K .......... .......... .......... .......... ..........  7% 13.2M 6s
  5250K .......... .......... .......... .......... ..........  7% 16.4M 6s
  5300K .......... .......... .......... .......... ..........  7% 12.0M 6s
  5350K .......... .......... .......... .......... ..........  7% 16.1M 6s
  5400K .......... .......... .......... .......... ..........  7% 13.4M 6s
  5450K .......... .......... .......... .......... ..........  8% 14.7M 6s
  5500K .......... .......... .......... .......... ..........  8% 11.3M 6s
  5550K .......... .......... .......... .......... ..........  8% 8.38M 6s
  5600K .......... .......... .......... .......... ..........  8% 19.8M 6s
  5650K .......... .......... .......... .......... ..........  8% 13.1M 6s
  5700K .......... .......... .......... .......... ..........  8% 11.1M 6s
  5750K .......... .......... .......... .......... ..........  8% 8.85M 6s
  5800K .......... .......... .......... .......... ..........  8% 61.0M 5s
  5850K .......... .......... .......... .......... ..........  8% 8.57M 5s
  5900K .......... .......... .......... .......... ..........  8% 19.2M 5s
  5950K .......... .......... .......... .......... ..........  8% 10.8M 5s
  6000K .......... .......... .......... .......... ..........  8% 11.0M 5s
  6050K .......... .......... .......... .......... ..........  8% 14.1M 5s
  6100K .......... .......... .......... .......... ..........  8% 11.3M 5s
  6150K .......... .......... .......... .......... ..........  9% 13.7M 5s
  6200K .......... .......... .......... .......... ..........  9% 21.2M 5s
  6250K .......... .......... .......... .......... ..........  9% 8.17M 5s
  6300K .......... .......... .......... .......... ..........  9% 59.4M 5s
  6350K .......... .......... .......... .......... ..........  9% 7.80M 5s
  6400K .......... .......... .......... .......... ..........  9% 11.3M 5s
  6450K .......... .......... .......... .......... ..........  9% 13.1M 5s
  6500K .......... .......... .......... .......... ..........  9% 23.8M 5s
  6550K .......... .......... .......... .......... ..........  9% 12.3M 5s
  6600K .......... .......... .......... .......... ..........  9% 11.2M 5s
  6650K .......... .......... .......... .......... ..........  9% 15.5M 5s
  6700K .......... .......... .......... .......... ..........  9% 12.0M 5s
  6750K .......... .......... .......... .......... ..........  9% 12.5M 5s
  6800K .......... .......... .......... .......... .......... 10% 9.18M 5s
  6850K .......... .......... .......... .......... .......... 10% 21.2M 5s
  6900K .......... .......... .......... .......... .......... 10% 17.7M 5s
  6950K .......... .......... .......... .......... .......... 10% 8.59M 5s
  7000K .......... .......... .......... .......... .......... 10% 10.8M 5s
  7050K .......... .......... .......... .......... .......... 10% 20.0M 5s
  7100K .......... .......... .......... .......... .......... 10% 13.2M 5s
  7150K .......... .......... .......... .......... .......... 10% 8.78M 5s
  7200K .......... .......... .......... .......... .......... 10% 13.8M 5s
  7250K .......... .......... .......... .......... .......... 10% 16.4M 5s
  7300K .......... .......... .......... .......... .......... 10% 14.8M 5s
  7350K .......... .......... .......... .......... .......... 10% 14.7M 5s
  7400K .......... .......... .......... .......... .......... 10% 12.3M 5s
  7450K .......... .......... .......... .......... .......... 10% 11.6M 5s
  7500K .......... .......... .......... .......... .......... 11% 18.1M 5s
  7550K .......... .......... .......... .......... .......... 11% 11.8M 5s
  7600K .......... .......... .......... .......... .......... 11% 9.94M 5s
  7650K .......... .......... .......... .......... .......... 11% 12.5M 5s
  7700K .......... .......... .......... .......... .......... 11% 15.8M 5s
  7750K .......... .......... .......... .......... .......... 11% 14.2M 5s
  7800K .......... .......... .......... .......... .......... 11% 11.1M 5s
  7850K .......... .......... .......... .......... .......... 11% 14.8M 5s
  7900K .......... .......... .......... .......... .......... 11% 12.8M 5s
  7950K .......... .......... .......... .......... .......... 11% 10.5M 5s
  8000K .......... .......... .......... .......... .......... 11% 9.15M 5s
  8050K .......... .......... .......... .......... .......... 11% 13.5M 5s
  8100K .......... .......... .......... .......... .......... 11% 14.7M 5s
  8150K .......... .......... .......... .......... .......... 11% 12.1M 5s
  8200K .......... .......... .......... .......... .......... 12% 14.6M 5s
  8250K .......... .......... .......... .......... .......... 12% 41.5M 5s
  8300K .......... .......... .......... .......... .......... 12% 11.6M 5s
  8350K .......... .......... .......... .......... .......... 12% 8.86M 5s
  8400K .......... .......... .......... .......... .......... 12% 11.5M 5s
  8450K .......... .......... .......... .......... .......... 12% 12.1M 5s
  8500K .......... .......... .......... .......... .......... 12% 20.9M 5s
  8550K .......... .......... .......... .......... .......... 12% 9.01M 5s
  8600K .......... .......... .......... .......... .......... 12% 19.8M 5s
  8650K .......... .......... .......... .......... .......... 12% 10.4M 5s
  8700K .......... .......... .......... .......... .......... 12% 26.7M 5s
  8750K .......... .......... .......... .......... .......... 12% 8.16M 5s
  8800K .......... .......... .......... .......... .......... 12% 11.7M 5s
  8850K .......... .......... .......... .......... .......... 13% 14.1M 5s
  8900K .......... .......... .......... .......... .......... 13% 17.8M 5s
  8950K .......... .......... .......... .......... .......... 13% 8.30M 5s
  9000K .......... .......... .......... .......... .......... 13% 24.7M 5s
  9050K .......... .......... .......... .......... .......... 13% 12.1M 5s
  9100K .......... .......... .......... .......... .......... 13% 12.4M 5s
  9150K .......... .......... .......... .......... .......... 13% 11.3M 5s
  9200K .......... .......... .......... .......... .......... 13% 10.6M 5s
  9250K .......... .......... .......... .......... .......... 13% 22.4M 5s
  9300K .......... .......... .......... .......... .......... 13% 14.4M 5s
  9350K .......... .......... .......... .......... .......... 13% 10.5M 5s
  9400K .......... .......... .......... .......... .......... 13% 13.9M 5s
  9450K .......... .......... .......... .......... .......... 13% 12.4M 5s
  9500K .......... .......... .......... .......... .......... 13% 24.2M 5s
  9550K .......... .......... .......... .......... .......... 14% 7.33M 5s
  9600K .......... .......... .......... .......... .......... 14% 13.4M 5s
  9650K .......... .......... .......... .......... .......... 14% 11.8M 5s
  9700K .......... .......... .......... .......... .......... 14% 19.2M 5s
  9750K .......... .......... .......... .......... .......... 14% 12.7M 5s
  9800K .......... .......... .......... .......... .......... 14% 13.2M 5s
  9850K .......... .......... .......... .......... .......... 14% 13.8M 5s
  9900K .......... .......... .......... .......... .......... 14% 11.0M 5s
  9950K .......... .......... .......... .......... .......... 14% 10.8M 5s
 10000K .......... .......... .......... .......... .......... 14% 12.9M 5s
 10050K .......... .......... .......... .......... .......... 14% 16.5M 5s
 10100K .......... .......... .......... .......... .......... 14% 13.4M 5s
 10150K .......... .......... .......... .......... .......... 14% 14.0M 5s
 10200K .......... .......... .......... .......... .......... 14% 12.1M 5s
 10250K .......... .......... .......... .......... .......... 15% 7.73M 5s
 10300K .......... .......... .......... .......... .......... 15% 81.0M 5s
 10350K .......... .......... .......... .......... .......... 15% 10.6M 5s
 10400K .......... .......... .......... .......... .......... 15% 8.34M 5s
 10450K .......... .......... .......... .......... .......... 15% 14.2M 5s
 10500K .......... .......... .......... .......... .......... 15% 13.3M 5s
 10550K .......... .......... .......... .......... .......... 15% 27.5M 5s
 10600K .......... .......... .......... .......... .......... 15% 13.1M 5s
 10650K .......... .......... .......... .......... .......... 15% 10.0M 5s
 10700K .......... .......... .......... .......... .......... 15% 17.8M 5s
 10750K .......... .......... .......... .......... .......... 15% 8.28M 5s
 10800K .......... .......... .......... .......... .......... 15% 26.1M 5s
 10850K .......... .......... .......... .......... .......... 15% 9.55M 5s
 10900K .......... .......... .......... .......... .......... 15% 11.1M 5s
 10950K .......... .......... .......... .......... .......... 16% 16.1M 5s
 11000K .......... .......... .......... .......... .......... 16% 21.8M 5s
 11050K .......... .......... .......... .......... .......... 16% 12.9M 5s
 11100K .......... .......... .......... .......... .......... 16% 9.36M 5s
 11150K .......... .......... .......... .......... .......... 16% 10.5M 5s
 11200K .......... .......... .......... .......... .......... 16% 11.9M 5s
 11250K .......... .......... .......... .......... .......... 16% 12.2M 5s
 11300K .......... .......... .......... .......... .......... 16% 22.0M 5s
 11350K .......... .......... .......... .......... .......... 16% 9.67M 5s
 11400K .......... .......... .......... .......... .......... 16% 19.8M 5s
 11450K .......... .......... .......... .......... .......... 16% 11.2M 5s
 11500K .......... .......... .......... .......... .......... 16% 21.9M 5s

Downloading atb.assembly.r0.2.batch.90.tar.xz from https://osf.io/download/6671526765e1de5e8b893ac2/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671526765e1de5e8b893ac2 [following]
--2026-09-06 18:53:09--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671526765e1de5e8b893ac2
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/95b3887384e6862be30898ab916f5846a942ffe1c8eb9b0f2313bd0baf211719?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.90.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.90.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713649&Signature=CKLLgPAtPAxwacwMEFcS0IulOHveNzmB8C2oqn7jg7gMK5imCk0UlrTu3244ijlqK7SSHzSwDiiKZqnh1wiIfn0eocCnK5C52Hige2sXgOvP%2FaBIYk%2FSuq3FeIaDjktH%2F2oP7gnjVbQhfugGZWic3rRkjJCmj7i0wHJ1Hp3z%2Bg3HXRSd8x2HVVEFfyhmzWLl%2FupbnfXCOdH34rNGuOpP7peIr8xP6q39%2FvpMAX%2BxueiEt2sGcuQCttYQa0wP1%2BQ9Qknpi19GwklNpkeZY1ogiFIKbjIQIFuRvn03TQXT3t1IuwpI4E6Kz07e8GIzGCo5Q7kqsIUAieiuitvKKt%2BdaQ%3D%3D [following]
--2026-09-06 18:53:09--  https://storage.googleapis.com/cos-osf-prod-files-de-1/95b3887384e6862be30898ab916f5846a942ffe1c8eb9b0f2313bd0baf211719?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.90.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.90.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713649&Signature=CKLLgPAtPAxwacwMEFcS0IulOHveNzmB8C2oqn7jg7gMK5imCk0UlrTu3244ijlqK7SSHzSwDiiKZqnh1wiIfn0eocCnK5C52Hige2sXgOvP%2FaBIYk%2FSuq3FeIaDjktH%2F2oP7gnjVbQhfugGZWic3rRkjJCmj7i0wHJ1Hp3z%2Bg3HXRSd8x2HVVEFfyhmzWLl%2FupbnfXCOdH34rNGuOpP7peIr8xP6q39%2FvpMAX%2BxueiEt2sGcuQCttYQa0wP1%2BQ9Qknpi19GwklNpkeZY1ogiFIKbjIQIFuRvn03TQXT3t1IuwpI4E6Kz07e8GIzGCo5Q7kqsIUAieiuitvKKt%2BdaQ%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25792256 (25M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.90.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.22M 20s
    50K .......... .......... .......... .......... ..........  0% 3.99M 13s
   100K .......... .......... .......... .......... ..........  0% 3.79M 11s
   150K .......... .......... .......... .......... ..........  0% 5.55M 9s
   200K .......... .......... .......... .......... ..........  0% 6.22M 8s
   250K .......... .......... .......... .......... ..........  1% 7.17M 7s
   300K .......... .......... .......... .......... ..........  1% 16.7M 6s
   350K .......... .......... .......... .......... ..........  1% 7.02M 6s
   400K .......... .......... .......... .......... ..........  1% 5.49M 6s
   450K .......... .......... .......... .......... ..........  1% 51.5M 5s
   500K .......... .......... .......... .......... ..........  2% 17.4M 5s
   550K .......... .......... .......... .......... ..........  2% 11.4M 5s
   600K .......... .......... .......... .......... ..........  2% 20.2M 4s
   650K .......... .......... .......... .......... ..........  2% 11.8M 4s
   700K .......... .......... .......... .......... ..........  2% 13.3M 4s
   750K .......... .......... .......... .......... ..........  3% 9.68M 4s
   800K .......... .......... .......... .......... ..........  3% 21.7M 4s
   850K .......... .......... .......... .......... ..........  3% 8.58M 4s
   900K .......... .......... .......... .......... ..........  3% 12.0M 4s
   950K .......... .......... .......... .......... ..........  3% 22.1M 4s
  1000K .......... .......... .......... .......... ..........  4% 9.28M 3s
  1050K .......... .......... .......... .......... ..........  4% 15.8M 3s
  1100K .......... .......... .......... .......... ..........  4% 20.5M 3s
  1150K .......... .......... .......... .......... ..........  4% 9.13M 3s
  1200K .......... .......... .......... .......... ..........  4% 13.2M 3s
  1250K .......... .......... .......... .......... ..........  5% 9.89M 3s
  1300K .......... .......... .......... .......... ..........  5% 13.8M 3s
  1350K .......... .......... .......... .......... ..........  5% 14.7M 3s
  1400K .......... .......... .......... .......... ..........  5% 15.8M 3s
  1450K .......... .......... .......... .......... ..........  5% 13.7M 3s
  1500K .......... .......... .......... .......... ..........  6% 10.1M 3s
  1550K .......... .......... .......... .......... ..........  6% 12.2M 3s
  1600K .......... .......... .......... .......... ..........  6% 13.6M 3s
  1650K .......... .......... .......... .......... ..........  6% 18.8M 3s
  1700K .......... .......... .......... .......... ..........  6% 12.2M 3s
  1750K .......... .......... .......... .......... ..........  7% 12.2M 3s
  1800K .......... .......... .......... .......... ..........  7% 11.4M 3s
  1850K .......... .......... .......... .......... ..........  7% 14.2M 3s
  1900K .......... .......... .......... .......... ..........  7% 21.0M 3s
  1950K .......... .......... .......... .......... ..........  7% 7.07M 3s
  2000K .......... .......... .......... .......... ..........  8% 16.8M 3s
  2050K .......... .......... .......... .......... ..........  8% 13.8M 3s
  2100K .......... .......... .......... .......... ..........  8% 14.2M 2s
  2150K .......... .......... .......... .......... ..........  8% 9.16M 2s
  2200K .......... .......... .......... .......... ..........  8% 12.3M 2s
  2250K .......... .......... .......... .......... ..........  9% 10.4M 2s
  2300K .......... .......... .......... .......... ..........  9% 75.1M 2s
  2350K .......... .......... .......... .......... ..........  9% 8.78M 2s
  2400K .......... .......... .......... .......... ..........  9% 17.3M 2s
  2450K .......... .......... .......... .......... ..........  9% 17.4M 2s
  2500K .......... .......... .......... .......... .......... 10% 10.6M 2s
  2550K .......... .......... .......... .......... .......... 10% 12.2M 2s
  2600K .......... .......... .......... .......... .......... 10% 11.7M 2s
  2650K .......... .......... .......... .......... .......... 10% 20.3M 2s
  2700K .......... .......... .......... .......... .......... 10% 14.5M 2s
  2750K .......... .......... .......... .......... .......... 11% 7.48M 2s
  2800K .......... .......... .......... .......... .......... 11% 13.8M 2s
  2850K .......... .......... .......... .......... .......... 11% 12.3M 2s
  2900K .......... .......... .......... .......... .......... 11% 12.6M 2s
  2950K .......... .......... .......... .......... .......... 11% 11.1M 2s
  3000K .......... .......... .......... .......... .......... 12% 16.4M 2s
  3050K .......... .......... .......... .......... .......... 12% 11.6M 2s
  3100K .......... .......... .......... .......... .......... 12% 21.0M 2s
  3150K .......... .......... .......... .......... .......... 12% 7.64M 2s
  3200K .......... .......... .......... .......... .......... 12% 18.1M 2s
  3250K .......... .......... .......... .......... .......... 13% 11.3M 2s
  3300K .......... .......... .......... .......... .......... 13% 15.1M 2s
  3350K .......... .......... .......... .......... .......... 13% 10.6M 2s
  3400K .......... .......... .......... .......... .......... 13% 40.4M 2s
  3450K .......... .......... .......... .......... .......... 13% 11.4M 2s
  3500K .......... .......... .......... .......... .......... 14% 14.4M 2s
  3550K .......... .......... .......... .......... .......... 14% 9.94M 2s
  3600K .......... .......... .......... .......... .......... 14% 11.1M 2s
  3650K .......... .......... .......... .......... .......... 14% 17.3M 2s
  3700K .......... .......... .......... .......... .......... 14% 12.7M 2s
  3750K .......... .......... .......... .......... .......... 15% 12.6M 2s
  3800K .......... .......... .......... .......... .......... 15% 12.0M 2s
  3850K .......... .......... .......... .......... .......... 15% 18.3M 2s
  3900K .......... .......... .......... .......... .......... 15% 11.6M 2s
  3950K .......... .......... .......... .......... .......... 15% 12.1M 2s
  4000K .......... .......... .......... .......... .......... 16% 10.4M 2s
  4050K .......... .......... .......... .......... .......... 16% 21.4M 2s
  4100K .......... .......... .......... .......... .......... 16% 12.0M 2s
  4150K .......... .......... .......... .......... .......... 16% 12.1M 2s
  4200K .......... .......... .......... .......... .......... 16% 11.9M 2s
  4250K .......... .......... .......... .......... .......... 17% 11.7M 2s
  4300K .......... .......... .......... .......... .......... 17% 14.2M 2s
  4350K .......... .......... .......... .......... .......... 17% 8.82M 2s
  4400K .......... .......... .......... .......... .......... 17% 16.0M 2s
  4450K .......... .......... .......... .......... .......... 17% 15.8M 2s
  4500K .......... .......... .......... .......... .......... 18% 10.8M 2s
  4550K .......... .......... .......... .......... .......... 18% 9.25M 2s
  4600K .......... .......... .......... .......... .......... 18% 27.2M 2s
  4650K .......... .......... .......... .......... .......... 18% 15.1M 2s
  4700K .......... .......... .......... .......... .......... 18% 11.4M 2s
  4750K .......... .......... .......... .......... .......... 19% 12.3M 2s
  4800K .......... .......... .......... .......... .......... 19% 11.2M 2s
  4850K .......... .......... .......... .......... .......... 19% 19.1M 2s
  4900K .......... .......... .......... .......... .......... 19% 8.23M 2s
  4950K .......... .......... .......... .......... .......... 19% 28.8M 2s
  5000K .......... .......... .......... .......... .......... 20% 11.6M 2s
  5050K .......... .......... .......... .......... .......... 20% 9.84M 2s
  5100K .......... .......... .......... .......... .......... 20% 15.8M 2s
  5150K .......... .......... .......... .......... .......... 20% 11.8M 2s
  5200K .......... .......... .......... .......... .......... 20% 14.8M 2s
  5250K .......... .......... .......... .......... .......... 21% 10.1M 2s
  5300K .......... .......... .......... .......... .......... 21% 21.7M 2s
  5350K .......... .......... .......... .......... .......... 21% 10.9M 2s
  5400K .......... .......... .......... .......... .......... 21% 15.4M 2s
  5450K .......... .......... .......... .......... .......... 21% 10.5M 2s
  5500K .......... .......... .......... .......... .......... 22% 11.4M 2s
  5550K .......... .......... .......... .......... .......... 22% 10.4M 2s
  5600K .......... .......... .......... .......... .......... 22% 13.3M 2s
  5650K .......... .......... .......... .......... .......... 22% 20.3M 2s
  5700K .......... .......... .......... .......... .......... 22% 9.17M 2s
  5750K .......... .......... .......... .......... .......... 23% 23.1M 2s
  5800K .......... .......... .......... .......... .......... 23% 14.0M 2s
  5850K .......... .......... .......... .......... .......... 23% 12.7M 2s
  5900K .......... .......... .......... .......... .......... 23% 13.6M 2s
  5950K .......... .......... .......... .......... .......... 23% 8.69M 2s
  6000K .......... .......... .......... .......... .......... 24% 15.9M 2s
  6050K .......... .......... .......... .......... .......... 24% 12.7M 2s
  6100K .......... .......... .......... .......... .......... 24% 12.5M 2s
  6150K .......... .......... .......... .......... .......... 24% 11.3M 2s
  6200K .......... .......... .......... .......... .......... 24% 13.8M 2s
  6250K .......... .......... .......... .......... .......... 25% 13.7M 2s
  6300K .......... .......... .......... .......... .......... 25% 11.7M 2s
  6350K .......... .......... .......... .......... .......... 25% 13.4M 2s
  6400K .......... .......... .......... .......... .......... 25% 11.4M 2s
  6450K .......... .......... .......... .......... .......... 25% 12.8M 2s
  6500K .......... .......... .......... .......... .......... 26% 28.9M 2s
  6550K .......... .......... .......... .......... .......... 26% 11.8M 2s
  6600K .......... .......... .......... .......... .......... 26% 11.1M 2s
  6650K .......... .......... .......... .......... .......... 26% 15.8M 2s
  6700K .......... .......... .......... .......... .......... 26% 10.9M 2s
  6750K .......... .......... .......... .......... .......... 26% 8.25M 2s
  6800K .......... .......... .......... .......... .......... 27% 14.6M 2s
  6850K .......... .......... .......... .......... .......... 27% 24.3M 2s
  6900K .......... .......... .......... .......... .......... 27% 13.5M 2s
  6950K .......... .......... .......... .......... .......... 27% 10.2M 2s
  7000K .......... .......... .......... .......... .......... 27% 13.6M 2s
  7050K .......... .......... .......... .......... .......... 28% 12.8M 2s
  7100K .......... .......... .......... .......... .......... 28% 15.8M 2s
  7150K .......... .......... .......... .......... .......... 28% 8.65M 2s
  7200K .......... .......... .......... .......... .......... 28% 10.4M 2s
  7250K .......... .......... .......... .......... .......... 28% 27.7M 2s
  7300K .......... .......... .......... .......... .......... 29% 15.8M 2s
  7350K .......... .......... .......... .......... .......... 29% 11.3M 2s
  7400K .......... .......... .......... .......... .......... 29% 14.1M 2s
  7450K .......... .......... .......... .......... .......... 29% 13.2M 2s
  7500K .......... .......... .......... .......... .......... 29% 13.0M 2s
  7550K .......... .......... .......... .......... .......... 30% 8.43M 2s
  7600K .......... .......... .......... .......... .......... 30% 12.4M 2s
  7650K .......... .......... .......... .......... .......... 30% 13.8M 1s
  7700K .......... .......... .......... .......... .......... 30% 19.4M 1s
  7750K .......... .......... .......... .......... .......... 30% 11.4M 1s
  7800K .......... .......... .......... .......... .......... 31% 12.5M 1s
  7850K .......... .......... .......... .......... .......... 31% 21.3M 1s
  7900K .......... .......... .......... .......... .......... 31% 9.83M 1s
  7950K .......... .......... .......... .......... .......... 31% 12.1M 1s
  8000K .......... .......... .......... .......... .......... 31% 8.79M 1s
  8050K .......... .......... .......... .......... .......... 32% 19.7M 1s
  8100K .......... .......... .......... .......... .......... 32% 12.7M 1s
  8150K .......... .......... .......... .......... .......... 32% 12.5M 1s
  8200K .......... .......... .......... .......... .......... 32% 21.0M 1s
  8250K .......... .......... .......... .......... .......... 32% 8.19M 1s
  8300K .......... .......... .......... .......... .......... 33% 24.7M 1s
  8350K .......... .......... .......... .......... .......... 33% 6.87M 1s
  8400K .......... .......... .......... .......... .......... 33% 28.9M 1s
  8450K .......... .......... .......... .......... .......... 33% 14.1M 1s
  8500K .......... .......... .......... .......... .......... 33% 11.5M 1s
  8550K .......... .......... .......... .......... .......... 34% 10.5M 1s
  8600K .......... .......... .......... .......... .......... 34% 12.9M 1s
  8650K .......... .......... .......... .......... .......... 34% 15.1M 1s
  8700K .......... .......... .......... .......... .......... 34% 22.5M 1s
  8750K .......... .......... .......... .......... .......... 34% 10.2M 1s
  8800K .......... .......... .......... .......... .......... 35% 7.56M 1s
  8850K .......... .......... .......... .......... .......... 35% 49.2M 1s
  8900K .......... .......... .......... .......... .......... 35% 11.1M 1s
  8950K .......... .......... .......... .......... .......... 35% 11.7M 1s
  9000K .......... .......... .......... .......... .......... 35% 21.5M 1s
  9050K .......... .......... .......... .......... .......... 36% 10.7M 1s
  9100K .......... .......... .......... .......... .......... 36% 12.0M 1s
  9150K .......... .......... .......... .......... .......... 36% 8.31M 1s
  9200K .......... .......... .......... .......... .......... 36% 29.7M 1s
  9250K .......... .......... .......... .......... .......... 36% 10.9M 1s
  9300K .......... .......... .......... .......... .......... 37% 22.6M 1s
  9350K .......... .......... .......... .......... .......... 37% 8.85M 1s
  9400K .......... .......... .......... .......... .......... 37% 13.0M 1s
  9450K .......... .......... .......... .......... .......... 37% 24.0M 1s
  9500K .......... .......... .......... .......... .......... 37% 13.6M 1s
  9550K .......... .......... .......... .......... .......... 38% 7.51M 1s
  9600K .......... .......... .......... .......... .......... 38% 11.2M 1s
  9650K .......... .......... .......... .......... .......... 38% 12.9M 1s
  9700K .......... .......... .......... .......... .......... 38% 14.0M 1s
  9750K .......... .......... .......... .......... .......... 38% 15.8M 1s
  9800K .......... .......... .......... .......... .......... 39% 19.8M 1s
  9850K .......... .......... .......... .......... .......... 39% 8.48M 1s
  9900K .......... .......... .......... .......... .......... 39% 18.1M 1s
  9950K .......... .......... .......... .......... .......... 39% 12.8M 1s
 10000K .......... .......... .......... .......... .......... 39% 12.9M 1s
 10050K .......... .......... .......... .......... .......... 40% 14.3M 1s
 10100K .......... .......... .......... .......... .......... 40% 13.4M 1s
 10150K .......... .......... .......... .......... .......... 40% 13.7M 1s
 10200K .......... .......... .......... .......... .......... 40% 9.77M 1s
 10250K .......... .......... .......... .......... .......... 40% 23.9M 1s
 10300K .......... .......... .......... .......... .......... 41% 9.87M 1s
 10350K .......... .......... .......... .......... .......... 41% 11.9M 1s
 10400K .......... .......... .......... .......... .......... 41% 11.9M 1s
 10450K .......... .......... .......... .......... .......... 41% 15.4M 1s
 10500K .......... .......... .......... .......... .......... 41% 11.4M 1s
 10550K .......... .......... .......... .......... .......... 42% 13.4M 1s
 10600K .......... .......... .......... .......... .......... 42% 14.4M 1s
 10650K .......... .......... .......... .......... .......... 42% 15.7M 1s
 10700K .......... .......... .......... .......... .......... 42% 10.6M 1s
 10750K .......... .......... .......... .......... .......... 42% 9.31M 1s
 10800K .......... .......... .......... .......... .......... 43% 17.5M 1s
 10850K .......... .......... .......... .......... .......... 43% 13.3M 1s
 10900K .......... .......... .......... .......... .......... 43% 11.9M 1s
 10950K .......... .......... .......... .......... .......... 43% 13.7M 1s
 11000K .......... .......... .......... .......... .......... 43% 13.6M 1s
 11050K .......... .......... .......... .......... .......... 44% 12.2M 1s
 11100K .......... .......... .......... .......... .......... 44% 12.5M 1s
 11150K .......... .......... .......... .......... .......... 44% 11.1M 1s
 11200K .......... .......... .......... .......... .......... 44% 13.5M 1s
 11250K .......... .......... .......... .......... .......... 44% 14.5M 1s
 11300K .......... .......... .......... .......... .......... 45% 12.0M 1s
 11350K .......... .......... .......... .......... .......... 45% 10.8M 1s
 11400K .......... .......... .......... .......... .......... 45% 13.5M 1s
 11450K .......... .......... .......... .......... .......... 45% 10.3M 1s
 11500K .......... .......... .......... .......... .......... 45% 26.7M 1s
 11550K .......... .......... .......... .......... .......... 46% 6.64M 1s

Downloading atb.assembly.r0.2.batch.92.tar.xz from https://osf.io/download/6671559e0f8c8017cf3c92ba/

Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671559e0f8c8017cf3c92ba [following]
--2026-09-06 18:53:12--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/6671559e0f8c8017cf3c92ba
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/af6dbd4f6ff031351558d7f6aab5d9623ed63d329f5e558b503a227e5032cbdc?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.92.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.92.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713653&Signature=AO5OfY%2B5B2EIQjgQiIIjfAe29zxP6KBZXQgHkzAozHEj5mQRqxldk38c1ipi0kJmVNMStHYNFt4ZbBd%2Fr4w7W9kG7zYKuc6hObS3HipIzPDrMUXy1rVJwKc0y26AMFlNrAQfe4s7lTpzn12lwUZnHUyovhIkKMDMFPahb7PiXdXkakBBHGfflx2LjHmQmS2YTdXse8OXZwrLnYMmIhf%2BjsJrgsJ1OMQDLVz%2FVAIcuILxplnTbADBg8c06NhcKY9fYFFd2nSALZ4sSIF7a3rqJlwhhJJpRH6H5SCRDhO%2B4HbmPQijHFtnkNo6pFx5MlSxhYy3kzQdd82KjJn4rhBHiQ%3D%3D [following]
--2026-09-06 18:53:13--  https://storage.googleapis.com/cos-osf-prod-files-de-1/af6dbd4f6ff031351558d7f6aab5d9623ed63d329f5e558b503a227e5032cbdc?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.92.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.92.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713653&Signature=AO5OfY%2B5B2EIQjgQiIIjfAe29zxP6KBZXQgHkzAozHEj5mQRqxldk38c1ipi0kJmVNMStHYNFt4ZbBd%2Fr4w7W9kG7zYKuc6hObS3HipIzPDrMUXy1rVJwKc0y26AMFlNrAQfe4s7lTpzn12lwUZnHUyovhIkKMDMFPahb7PiXdXkakBBHGfflx2LjHmQmS2YTdXse8OXZwrLnYMmIhf%2BjsJrgsJ1OMQDLVz%2FVAIcuILxplnTbADBg8c06NhcKY9fYFFd2nSALZ4sSIF7a3rqJlwhhJJpRH6H5SCRDhO%2B4HbmPQijHFtnkNo6pFx5MlSxhYy3kzQdd82KjJn4rhBHiQ%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.154.207, 192.178.183.207, 142.251.20.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.154.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 283695008 (271M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.92.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.29M 3m29s
    50K .......... .......... .......... .......... ..........  0% 2.69M 2m35s
   100K .......... .......... .......... .......... ..........  0% 3.86M 2m7s
   150K .......... .......... .......... .......... ..........  0% 6.25M 1m46s
   200K .......... .......... .......... .......... ..........  0% 6.44M 93s
   250K .......... .......... .......... .......... ..........  0% 10.4M 82s
   300K .......... .......... .......... .......... ..........  0% 8.47M 75s
   350K .......... .......... .......... .......... ..........  0% 12.9M 68s
   400K .......... .......... .......... .......... ..........  0% 8.99M 64s
   450K .......... .......... .......... .......... ..........  0% 12.9M 59s
   500K .......... .......... .......... .......... ..........  0% 8.75M 57s
   550K .......... .......... .......... .......... ..........  0% 14.8M 54s
   600K .......... .......... .......... .......... ..........  0% 14.9M 51s
   650K .......... .......... .......... .......... ..........  0% 15.8M 48s
   700K .......... .......... .......... .......... ..........  0% 9.36M 47s
   750K .......... .......... .......... .......... ..........  0% 18.6M 45s
   800K .......... .......... .......... .......... ..........  0% 11.3M 44s
   850K .......... .......... .......... .......... ..........  0% 11.3M 43s
   900K .......... .......... .......... .......... ..........  0% 11.5M 42s
   950K .......... .......... .......... .......... ..........  0% 8.74M 41s
  1000K .......... .......... .......... .......... ..........  0% 26.9M 40s
  1050K .......... .......... .......... .......... ..........  0% 13.5M 39s
  1100K .......... .......... .......... .......... ..........  0% 15.8M 38s
  1150K .......... .......... .......... .......... ..........  0% 9.26M 37s
  1200K .......... .......... .......... .......... ..........  0% 12.0M 37s
  1250K .......... .......... .......... .......... ..........  0% 12.0M 36s
  1300K .......... .......... .......... .......... ..........  0% 24.0M 35s
  1350K .......... .......... .......... .......... ..........  0% 11.5M 35s
  1400K .......... .......... .......... .......... ..........  0% 12.8M 34s
  1450K .......... .......... .......... .......... ..........  0% 15.9M 34s
  1500K .......... .......... .......... .......... ..........  0% 14.1M 33s
  1550K .......... .......... .......... .......... ..........  0% 8.95M 33s
  1600K .......... .......... .......... .......... ..........  0% 12.9M 33s
  1650K .......... .......... .......... .......... ..........  0% 20.3M 32s
  1700K .......... .......... .......... .......... ..........  0% 10.5M 32s
  1750K .......... .......... .......... .......... ..........  0% 11.3M 32s
  1800K .......... .......... .......... .......... ..........  0% 13.3M 31s
  1850K .......... .......... .......... .......... ..........  0% 21.5M 31s
  1900K .......... .......... .......... .......... ..........  0% 11.8M 31s
  1950K .......... .......... .......... .......... ..........  0% 9.43M 31s
  2000K .......... .......... .......... .......... ..........  0% 12.3M 30s
  2050K .......... .......... .......... .......... ..........  0% 15.1M 30s
  2100K .......... .......... .......... .......... ..........  0% 16.0M 30s
  2150K .......... .......... .......... .......... ..........  0% 9.33M 30s
  2200K .......... .......... .......... .......... ..........  0% 12.6M 30s
  2250K .......... .......... .......... .......... ..........  0% 30.5M 29s
  2300K .......... .......... .......... .......... ..........  0% 11.3M 29s
  2350K .......... .......... .......... .......... ..........  0% 10.6M 29s
  2400K .......... .......... .......... .......... ..........  0% 12.8M 29s
  2450K .......... .......... .......... .......... ..........  0% 15.4M 29s
  2500K .......... .......... .......... .......... ..........  0% 10.0M 29s
  2550K .......... .......... .......... .......... ..........  0% 12.4M 28s
  2600K .......... .......... .......... .......... ..........  0% 12.7M 28s
  2650K .......... .......... .......... .......... ..........  0% 14.7M 28s
  2700K .......... .......... .......... .......... ..........  0% 11.1M 28s
  2750K .......... .......... .......... .......... ..........  1% 11.9M 28s
  2800K .......... .......... .......... .......... ..........  1% 12.8M 28s
  2850K .......... .......... .......... .......... ..........  1% 14.1M 28s
  2900K .......... .......... .......... .......... ..........  1% 15.6M 27s
  2950K .......... .......... .......... .......... ..........  1% 12.7M 27s
  3000K .......... .......... .......... .......... ..........  1% 9.89M 27s
  3050K .......... .......... .......... .......... ..........  1% 14.3M 27s
  3100K .......... .......... .......... .......... ..........  1% 13.2M 27s
  3150K .......... .......... .......... .......... ..........  1% 12.5M 27s
  3200K .......... .......... .......... .......... ..........  1% 9.71M 27s
  3250K .......... .......... .......... .......... ..........  1% 27.9M 27s
  3300K .......... .......... .......... .......... ..........  1% 12.9M 27s
  3350K .......... .......... .......... .......... ..........  1% 15.0M 26s
  3400K .......... .......... .......... .......... ..........  1% 10.5M 26s
  3450K .......... .......... .......... .......... ..........  1% 13.4M 26s
  3500K .......... .......... .......... .......... ..........  1% 12.8M 26s
  3550K .......... .......... .......... .......... ..........  1% 11.3M 26s
  3600K .......... .......... .......... .......... ..........  1% 12.8M 26s
  3650K .......... .......... .......... .......... ..........  1% 13.0M 26s
  3700K .......... .......... .......... .......... ..........  1% 18.6M 26s
  3750K .......... .......... .......... .......... ..........  1% 9.47M 26s
  3800K .......... .......... .......... .......... ..........  1% 20.2M 26s
  3850K .......... .......... .......... .......... ..........  1% 12.1M 26s
  3900K .......... .......... .......... .......... ..........  1% 14.1M 26s
  3950K .......... .......... .......... .......... ..........  1% 6.94M 26s
  4000K .......... .......... .......... .......... ..........  1% 25.4M 26s
  4050K .......... .......... .......... .......... ..........  1% 12.3M 26s
  4100K .......... .......... .......... .......... ..........  1% 19.8M 25s
  4150K .......... .......... .......... .......... ..........  1% 9.13M 25s
  4200K .......... .......... .......... .......... ..........  1% 17.4M 25s
  4250K .......... .......... .......... .......... ..........  1% 14.2M 25s
  4300K .......... .......... .......... .......... ..........  1% 13.5M 25s
  4350K .......... .......... .......... .......... ..........  1% 7.81M 25s
  4400K .......... .......... .......... .......... ..........  1% 12.9M 25s
  4450K .......... .......... .......... .......... ..........  1% 15.4M 25s
  4500K .......... .......... .......... .......... ..........  1% 15.4M 25s
  4550K .......... .......... .......... .......... ..........  1% 15.2M 25s
  4600K .......... .......... .......... .......... ..........  1% 12.1M 25s
  4650K .......... .......... .......... .......... ..........  1% 16.2M 25s
  4700K .......... .......... .......... .......... ..........  1% 9.71M 25s
  4750K .......... .......... .......... .......... ..........  1% 10.1M 25s
  4800K .......... .......... .......... .......... ..........  1% 18.6M 25s
  4850K .......... .......... .......... .......... ..........  1% 9.17M 25s
  4900K .......... .......... .......... .......... ..........  1% 20.6M 25s
  4950K .......... .......... .......... .......... ..........  1% 14.8M 25s
  5000K .......... .......... .......... .......... ..........  1% 6.92M 25s
  5050K .......... .......... .......... .......... ..........  1% 40.1M 24s
  5100K .......... .......... .......... .......... ..........  1% 12.6M 24s
  5150K .......... .......... .......... .......... ..........  1% 8.58M 25s
  5200K .......... .......... .......... .......... ..........  1% 18.4M 24s
  5250K .......... .......... .......... .......... ..........  1% 13.1M 24s
  5300K .......... .......... .......... .......... ..........  1% 19.5M 24s
  5350K .......... .......... .......... .......... ..........  1% 11.9M 24s
  5400K .......... .......... .......... .......... ..........  1% 13.5M 24s
  5450K .......... .......... .......... .......... ..........  1% 13.7M 24s
  5500K .......... .......... .......... .......... ..........  2% 12.1M 24s
  5550K .......... .......... .......... .......... ..........  2% 9.24M 24s
  5600K .......... .......... .......... .......... ..........  2% 12.3M 24s
  5650K .......... .......... .......... .......... ..........  2% 12.1M 24s
  5700K .......... .......... .......... .......... ..........  2% 30.5M 24s
  5750K .......... .......... .......... .......... ..........  2% 11.6M 24s
  5800K .......... .......... .......... .......... ..........  2% 10.1M 24s
  5850K .......... .......... .......... .......... ..........  2% 15.6M 24s
  5900K .......... .......... .......... .......... ..........  2% 13.2M 24s
  5950K .......... .......... .......... .......... ..........  2% 9.44M 24s
  6000K .......... .......... .......... .......... ..........  2% 14.4M 24s
  6050K .......... .......... .......... .......... ..........  2% 16.2M 24s
  6100K .......... .......... .......... .......... ..........  2% 11.7M 24s
  6150K .......... .......... .......... .......... ..........  2% 13.1M 24s
  6200K .......... .......... .......... .......... ..........  2% 14.1M 24s
  6250K .......... .......... .......... .......... ..........  2% 10.5M 24s
  6300K .......... .......... .......... .......... ..........  2% 23.2M 24s
  6350K .......... .......... .......... .......... ..........  2% 6.75M 24s
  6400K .......... .......... .......... .......... ..........  2% 15.3M 24s
  6450K .......... .......... .......... .......... ..........  2% 16.0M 24s
  6500K .......... .......... .......... .......... ..........  2% 13.4M 24s
  6550K .......... .......... .......... .......... ..........  2% 12.8M 24s
  6600K .......... .......... .......... .......... ..........  2% 13.1M 24s
  6650K .......... .......... .......... .......... ..........  2% 11.7M 24s
  6700K .......... .......... .......... .......... ..........  2% 12.9M 23s
  6750K .......... .......... .......... .......... ..........  2% 8.62M 24s
  6800K .......... .......... .......... .......... ..........  2% 12.3M 24s
  6850K .......... .......... .......... .......... ..........  2% 23.0M 23s
  6900K .......... .......... .......... .......... ..........  2% 15.1M 23s
  6950K .......... .......... .......... .......... ..........  2% 12.1M 23s
  7000K .......... .......... .......... .......... ..........  2% 13.1M 23s
  7050K .......... .......... .......... .......... ..........  2% 25.2M 23s
  7100K .......... .......... .......... .......... ..........  2% 12.8M 23s
  7150K .......... .......... .......... .......... ..........  2% 8.37M 23s
  7200K .......... .......... .......... .......... ..........  2% 15.6M 23s
  7250K .......... .......... .......... .......... ..........  2% 13.6M 23s
  7300K .......... .......... .......... .......... ..........  2% 11.0M 23s
  7350K .......... .......... .......... .......... ..........  2% 13.7M 23s
  7400K .......... .......... .......... .......... ..........  2% 9.83M 23s
  7450K .......... .......... .......... .......... ..........  2% 33.7M 23s
  7500K .......... .......... .......... .......... ..........  2% 12.7M 23s
  7550K .......... .......... .......... .......... ..........  2% 7.74M 23s
  7600K .......... .......... .......... .......... ..........  2% 14.2M 23s
  7650K .......... .......... .......... .......... ..........  2% 12.1M 23s
  7700K .......... .......... .......... .......... ..........  2% 24.6M 23s
  7750K .......... .......... .......... .......... ..........  2% 9.85M 23s
  7800K .......... .......... .......... .......... ..........  2% 22.1M 23s
  7850K .......... .......... .......... .......... ..........  2% 10.6M 23s
  7900K .......... .......... .......... .......... ..........  2% 9.88M 23s
  7950K .......... .......... .......... .......... ..........  2% 12.2M 23s
  8000K .......... .......... .......... .......... ..........  2% 22.2M 23s
  8050K .......... .......... .......... .......... ..........  2% 12.7M 23s
  8100K .......... .......... .......... .......... ..........  2% 13.3M 23s
  8150K .......... .......... .......... .......... ..........  2% 6.80M 23s
  8200K .......... .......... .......... .......... ..........  2% 26.4M 23s
  8250K .......... .......... .......... .......... ..........  2% 20.9M 23s
  8300K .......... .......... .......... .......... ..........  3% 9.73M 23s
  8350K .......... .......... .......... .......... ..........  3% 11.8M 23s
  8400K .......... .......... .......... .......... ..........  3% 12.2M 23s
  8450K .......... .......... .......... .......... ..........  3% 9.73M 23s
  8500K .......... .......... .......... .......... ..........  3% 18.2M 23s
  8550K .......... .......... .......... .......... ..........  3% 15.0M 23s
  8600K .......... .......... .......... .......... ..........  3% 15.0M 23s
  8650K .......... .......... .......... .......... ..........  3% 13.4M 23s
  8700K .......... .......... .......... .......... ..........  3% 10.1M 23s
  8750K .......... .......... .......... .......... ..........  3% 27.3M 23s
  8800K .......... .......... .......... .......... ..........  3% 8.21M 23s
  8850K .......... .......... .......... .......... ..........  3% 14.1M 23s
  8900K .......... .......... .......... .......... ..........  3% 14.1M 23s
  8950K .......... .......... .......... .......... ..........  3% 13.4M 23s
  9000K .......... .......... .......... .......... ..........  3% 13.7M 23s
  9050K .......... .......... .......... .......... ..........  3% 7.45M 23s
  9100K .......... .......... .......... .......... ..........  3% 29.8M 23s
  9150K .......... .......... .......... .......... ..........  3% 16.5M 22s
  9200K .......... .......... .......... .......... ..........  3% 8.65M 23s
  9250K .......... .......... .......... .......... ..........  3% 20.7M 22s
  9300K .......... .......... .......... .......... ..........  3% 9.49M 22s
  9350K .......... .......... .......... .......... ..........  3% 10.8M 22s
  9400K .......... .......... .......... .......... ..........  3% 16.8M 22s
  9450K .......... .......... .......... .......... ..........  3% 11.4M 22s
  9500K .......... .......... .......... .......... ..........  3% 21.6M 22s
  9550K .......... .......... .......... .......... ..........  3% 11.4M 22s
  9600K .......... .......... .......... .......... ..........  3% 13.2M 22s
  9650K .......... .......... .......... .......... ..........  3% 10.3M 22s
  9700K .......... .......... .......... .......... ..........  3% 11.3M 22s
  9750K .......... .......... .......... .......... ..........  3% 25.8M 22s
  9800K .......... .......... .......... .......... ..........  3% 9.71M 22s
  9850K .......... .......... .......... .......... ..........  3% 12.8M 22s
  9900K .......... .......... .......... .......... ..........  3% 13.5M 22s
  9950K .......... .......... .......... .......... ..........  3% 15.5M 22s
 10000K .......... .......... .......... .......... ..........  3% 13.0M 22s
 10050K .......... .......... .......... .......... ..........  3% 12.1M 22s
 10100K .......... .......... .......... .......... ..........  3% 9.02M 22s
 10150K .......... .......... .......... .......... ..........  3% 12.8M 22s
 10200K .......... .......... .......... .......... ..........  3% 24.6M 22s
 10250K .......... .......... .......... .......... ..........  3% 13.2M 22s
 10300K .......... .......... .......... .......... ..........  3% 9.48M 22s
 10350K .......... .......... .......... .......... ..........  3% 27.9M 22s
 10400K .......... .......... .......... .......... ..........  3% 8.36M 22s
 10450K .......... .......... .......... .......... ..........  3% 11.9M 22s
 10500K .......... .......... .......... .......... ..........  3% 20.0M 22s
 10550K .......... .......... .......... .......... ..........  3% 12.5M 22s
 10600K .......... .......... .......... .......... ..........  3% 9.54M 22s
 10650K .......... .......... .......... .......... ..........  3% 11.8M 22s
 10700K .......... .......... .......... .......... ..........  3% 17.3M 22s
 10750K .......... .......... .......... .......... ..........  3% 13.3M 22s
 10800K .......... .......... .......... .......... ..........  3% 13.6M 22s
 10850K .......... .......... .......... .......... ..........  3% 11.1M 22s
 10900K .......... .......... .......... .......... ..........  3% 13.1M 22s
 10950K .......... .......... .......... .......... ..........  3% 11.8M 22s
 11000K .......... .......... .......... .......... ..........  3% 11.6M 22s
 11050K .......... .......... .......... .......... ..........  4% 16.3M 22s
 11100K .......... .......... .......... .......... ..........  4% 10.5M 22s
 11150K .......... .......... .......... .......... ..........  4% 28.9M 22s
 11200K .......... .......... .......... .......... ..........  4% 7.63M 22s
 11250K .......... .......... .......... .......... ..........  4% 22.2M 22s
 11300K .......... .......... .......... .......... ..........  4% 7.57M 22s

Downloading atb.assembly.r0.2.batch.94.tar.xz from https://osf.io/download/66715576d835c439ba4cdfdf/

302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66715576d835c439ba4cdfdf [following]
--2026-09-06 18:53:35--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/66715576d835c439ba4cdfdf
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-de-1/7df60f74404bc3ade5be0130addb6495342d6177961df8d55ed6392b7fd00cde?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.94.tar.xz%22%3B%20filename%2A%3DUTF-8%27%27atb.assembly.r0.2.batch.94.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713676&Signature=N7P8YaE4m12tSr0pun2zzW7kswmhb5ktTy154hSH2qijvRgrAOm1N69lU9WdFJpW8Jib55jigR8C71Q7fv5WGhVKUz9llj7MXOBeBK99jjyI9CWj%2F0wQ6yc98Iz9KkbNRUQWozfiGtSoQH1%2FllQK0ApAiwpjQnvAW7Ykr8um9Ehw9L3Xo5vul%2BqtdvMPlhOY8Jq2kg9B4McS%2FkkgZ7ZQK9f6euY9RbomPKASW6c3MVtRWBpHW27tx7egVuT%2F1Ja0RfGuEIoSEskhf%2FZ6IhHZhoBsgrez4Frq4UyEpxpFfMkAmAeIWcX%2B7KMU6f97JPMjeVyFowGMXk2%2BXcE%2BWEVuHg%3D%3D [following]
--2026-09-06 18:53:36--  https://storage.googleapis.com/cos-osf-prod-files-de-1/7df60f74404bc3ade5be0130addb6495342d6177961df8d55ed6392b7fd00cde?response-content-disposition=attachment%3B%20filename%3D%22atb.assembly.r0.2.batch.94.tar.xz%22%3B%20filename*%3DUTF-8''atb.assembly.r0.2.batch.94.tar.xz&GoogleAccessId=files-de-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1788713676&Signature=N7P8YaE4m12tSr0pun2zzW7kswmhb5ktTy154hSH2qijvRgrAOm1N69lU9WdFJpW8Jib55jigR8C71Q7fv5WGhVKUz9llj7MXOBeBK99jjyI9CWj%2F0wQ6yc98Iz9KkbNRUQWozfiGtSoQH1%2FllQK0ApAiwpjQnvAW7Ykr8um9Ehw9L3Xo5vul%2BqtdvMPlhOY8Jq2kg9B4McS%2FkkgZ7ZQK9f6euY9RbomPKASW6c3MVtRWBpHW27tx7egVuT%2F1Ja0RfGuEIoSEskhf%2FZ6IhHZhoBsgrez4Frq4UyEpxpFfMkAmAeIWcX%2B7KMU6f97JPMjeVyFowGMXk2%2BXcE%2BWEVuHg%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 192.178.183.207, 142.251.20.207, 142.251.13.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|192.178.183.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 232285708 (222M) [application/octet-stream]
Saving to: 'dataset/prev_studies/ATB/atb_batch/atb.assembly.r0.2.batch.94.tar.xz'

     0K .......... .......... .......... .......... ..........  0% 1.33M 2m46s
    50K .......... .......... .......... .......... ..........  0% 2.48M 2m8s
   100K .......... .......... .......... .......... ..........  0% 4.53M 1m41s
   150K .......... .......... .......... .......... ..........  0% 4.27M 89s
   200K .......... .......... .......... .......... ..........  0% 7.35M 77s
   250K .......... .......... .......... .......... ..........  0% 7.71M 69s
   300K .......... .......... .......... .......... ..........  0% 8.44M 63s
   350K .......... .......... .......... .......... ..........  0% 11.5M 57s
   400K .......... .......... .......... .......... ..........  0% 12.1M 53s
   450K .......... .......... .......... .......... ..........  0% 12.2M 50s
   500K .......... .......... .......... .......... ..........  0% 12.7M 47s
   550K .......... .......... .......... .......... ..........  0% 13.3M 44s
   600K .......... .......... .......... .......... ..........  0% 11.8M 42s
   650K .......... .......... .......... .......... ..........  0% 11.2M 41s
   700K .......... .......... .......... .......... ..........  0% 15.0M 39s
   750K .......... .......... .......... .......... ..........  0% 10.9M 38s
   800K .......... .......... .......... .......... ..........  0% 13.5M 36s
   850K .......... .......... .......... .......... ..........  0% 11.3M 35s
   900K .......... .......... .......... .......... ..........  0% 15.7M 34s
   950K .......... .......... .......... .......... ..........  0% 12.2M 34s
  1000K .......... .......... .......... .......... ..........  0% 13.7M 33s
  1050K .......... .......... .......... .......... ..........  0% 11.0M 32s
  1100K .......... .......... .......... .......... ..........  0% 25.8M 31s
  1150K .......... .......... .......... .......... ..........  0% 7.02M 31s
  1200K .......... .......... .......... .......... ..........  0% 13.2M 30s
  1250K .......... .......... .......... .......... ..........  0% 11.0M 30s
  1300K .......... .......... .......... .......... ..........  0% 23.6M 29s
  1350K .......... .......... .......... .......... ..........  0% 14.0M 29s
  1400K .......... .......... .......... .......... ..........  0% 12.8M 28s
  1450K .......... .......... .......... .......... ..........  0% 21.6M 28s
  1500K .......... .......... .......... .......... ..........  0% 11.9M 27s
  1550K .......... .......... .......... .......... ..........  0% 7.35M 28s
  1600K .......... .......... .......... .......... ..........  0% 15.0M 27s
  1650K .......... .......... .......... .......... ..........  0% 19.8M 27s
  1700K .......... .......... .......... .......... ..........  0% 12.0M 26s
  1750K .......... .......... .......... .......... ..........  0% 13.1M 26s
  1800K .......... .......... .......... .......... ..........  0% 14.8M 26s
  1850K .......... .......... .......... .......... ..........  0% 11.3M 26s
  1900K .......... .......... .......... .......... ..........  0% 14.1M 25s
  1950K .......... .......... .......... .......... ..........  0% 13.7M 25s
  2000K .......... .......... .......... .......... ..........  0% 8.43M 25s
  2050K .......... .......... .......... .......... ..........  0% 20.4M 25s
  2100K .......... .......... .......... .......... ..........  0% 11.4M 25s
  2150K .......... .......... .......... .......... ..........  0% 13.7M 24s
  2200K .......... .......... .......... .......... ..........  0% 10.0M 24s
  2250K .......... .......... .......... .......... ..........  1% 22.4M 24s
  2300K .......... .......... .......... .......... ..........  1% 16.2M 24s
  2350K .......... .......... .......... .......... ..........  1% 7.85M 24s
  2400K .......... .......... .......... .......... ..........  1% 37.3M 24s
  2450K .......... .......... .......... .......... ..........  1% 10.1M 24s
  2500K .......... .......... .......... .......... ..........  1% 9.84M 24s
  2550K .......... .......... .......... .......... ..........  1% 12.6M 23s
  2600K .......... .......... .......... .......... ..........  1% 11.0M 23s
  2650K .......... .......... .......... .......... ..........  1% 31.7M 23s
  2700K .......... .......... .......... .......... ..........  1% 18.0M 23s
  2750K .......... .......... .......... .......... ..........  1% 6.84M 23s
  2800K .......... .......... .......... .......... ..........  1% 25.5M 23s
  2850K .......... .......... .......... .......... ..........  1% 10.1M 23s
  2900K .......... .......... .......... .......... ..........  1% 15.8M 23s
  2950K .......... .......... .......... .......... ..........  1% 15.8M 22s
  3000K .......... .......... .......... .......... ..........  1% 9.94M 22s
  3050K .......... .......... .......... .......... ..........  1% 18.3M 22s
  3100K .......... .......... .......... .......... ..........  1% 12.4M 22s
  3150K .......... .......... .......... .......... ..........  1% 11.7M 22s
  3200K .......... .......... .......... .......... ..........  1% 10.3M 22s
  3250K .......... .......... .......... .......... ..........  1% 10.8M 22s
  3300K .......... .......... .......... .......... ..........  1% 31.9M 22s
  3350K .......... .......... .......... .......... ..........  1% 10.5M 22s
  3400K .......... .......... .......... .......... ..........  1% 11.4M 22s
  3450K .......... .......... .......... .......... ..........  1% 14.8M 22s
  3500K .......... .......... .......... .......... ..........  1% 12.9M 22s
  3550K .......... .......... .......... .......... ..........  1% 9.26M 22s
  3600K .......... .......... .......... .......... ..........  1% 12.3M 22s
  3650K .......... .......... .......... .......... ..........  1% 23.4M 21s
  3700K .......... .......... .......... .......... ..........  1% 12.3M 21s
  3750K .......... .......... .......... .......... ..........  1% 17.0M 21s
  3800K .......... .......... .......... .......... ..........  1% 8.26M 21s
  3850K .......... .......... .......... .......... ..........  1% 20.4M 21s
  3900K .......... .......... .......... .......... ..........  1% 8.13M 21s
  3950K .......... .......... .......... .......... ..........  1% 15.9M 21s
  4000K .......... .......... .......... .......... ..........  1% 11.3M 21s
  4050K .......... .......... .......... .......... ..........  1% 13.8M 21s
  4100K .......... .......... .......... .......... ..........  1% 17.4M 21s
  4150K .......... .......... .......... .......... ..........  1% 12.7M 21s
  4200K .......... .......... .......... .......... ..........  1% 14.7M 21s
  4250K .......... .......... .......... .......... ..........  1% 14.2M 21s
  4300K .......... .......... .......... .......... ..........  1% 12.3M 21s
  4350K .......... .......... .......... .......... ..........  1% 11.7M 21s
  4400K .......... .......... .......... .......... ..........  1% 12.4M 21s
  4450K .......... .......... .......... .......... ..........  1% 9.45M 21s
  4500K .......... .......... .......... .......... ..........  2% 14.3M 21s
  4550K .......... .......... .......... .......... ..........  2% 12.9M 20s
  4600K .......... .......... .......... .......... ..........  2% 9.47M 20s
  4650K .......... .......... .......... .......... ..........  2% 35.8M 20s
  4700K .......... .......... .......... .......... ..........  2% 10.4M 20s
  4750K .......... .......... .......... .......... ..........  2% 12.1M 20s
  4800K .......... .......... .......... .......... ..........  2% 9.01M 20s
  4850K .......... .......... .......... .......... ..........  2% 29.6M 20s
  4900K .......... .......... .......... .......... ..........  2% 10.9M 20s
  4950K .......... .......... .......... .......... ..........  2% 17.6M 20s
  5000K .......... .......... .......... .......... ..........  2% 12.0M 20s
  5050K .......... .......... .......... .......... ..........  2% 9.15M 20s
  5100K .......... .......... .......... .......... ..........  2% 23.8M 20s
  5150K .......... .......... .......... .......... ..........  2% 8.91M 20s
  5200K .......... .......... .......... .......... ..........  2% 15.5M 20s
  5250K .......... .......... .......... .......... ..........  2% 13.7M 20s
  5300K .......... .......... .......... .......... ..........  2% 13.4M 20s
  5350K .......... .......... .......... .......... ..........  2% 10.6M 20s
  5400K .......... .......... .......... .......... ..........  2% 21.6M 20s
  5450K .......... .......... .......... .......... ..........  2% 10.7M 20s
  5500K .......... .......... .......... .......... ..........  2% 10.8M 20s
  5550K .......... .......... .......... .......... ..........  2% 15.1M 20s
  5600K .......... .......... .......... .......... ..........  2% 10.1M 20s
  5650K .......... .......... .......... .......... ..........  2% 26.6M 20s
  5700K .......... .......... .......... .......... ..........  2% 10.8M 20s
  5750K .......... .......... .......... .......... ..........  2% 11.6M 20s
  5800K .......... .......... .......... .......... ..........  2% 16.2M 20s
  5850K .......... .......... .......... .......... ..........  2% 14.2M 20s
  5900K .......... .......... .......... .......... ..........  2% 10.2M 20s
  5950K .......... .......... .......... .......... ..........  2% 11.0M 20s
  6000K .......... .......... .......... .......... ..........  2% 10.5M 20s
  6050K .......... .......... .......... .......... ..........  2% 17.4M 19s
  6100K .......... .......... .......... .......... ..........  2% 13.9M 19s
  6150K .......... .......... .......... .......... ..........  2% 18.0M 19s
  6200K .......... .......... .......... .......... ..........  2% 11.5M 19s
  6250K .......... .......... .......... .......... ..........  2% 13.2M 19s
  6300K .......... .......... .......... .......... ..........  2% 8.16M 19s
  6350K .......... .......... .......... .......... ..........  2% 15.2M 19s
  6400K .......... .......... .......... .......... ..........  2% 21.3M 19s
  6450K .......... .......... .......... .......... ..........  2% 12.4M 19s
  6500K .......... .......... .......... .......... ..........  2% 9.83M 19s
  6550K .......... .......... .......... .......... ..........  2% 27.0M 19s
  6600K .......... .......... .......... .......... ..........  2% 11.8M 19s
  6650K .......... .......... .......... .......... ..........  2% 8.57M 19s
  6700K .......... .......... .......... .......... ..........  2% 37.2M 19s
  6750K .......... .......... .......... .......... ..........  2% 8.89M 19s
  6800K .......... .......... .......... .......... ..........  3% 14.5M 19s
  6850K .......... .......... .......... .......... ..........  3% 10.5M 19s
  6900K .......... .......... .......... .......... ..........  3% 15.2M 19s
  6950K .......... .......... .......... .......... ..........  3% 17.7M 19s
  7000K .......... .......... .......... .......... ..........  3% 9.35M 19s
  7050K .......... .......... .......... .......... ..........  3% 11.1M 19s
  7100K .......... .......... .......... .......... ..........  3% 13.5M 19s
  7150K .......... .......... .......... .......... ..........  3% 12.4M 19s
  7200K .......... .......... .......... .......... ..........  3% 12.0M 19s
  7250K .......... .......... .......... .......... ..........  3% 16.5M 19s
  7300K .......... .......... .......... .......... ..........  3% 9.13M 19s
  7350K .......... .......... .......... .......... ..........  3% 16.4M 19s
  7400K .......... .......... .......... .......... ..........  3% 13.2M 19s
  7450K .......... .......... .......... .......... ..........  3% 14.2M 19s
  7500K .......... .......... .......... .......... ..........  3% 14.2M 19s
  7550K .......... .......... .......... .......... ..........  3% 7.20M 19s
  7600K .......... .......... .......... .......... ..........  3% 38.6M 19s
  7650K .......... .......... .......... .......... ..........  3% 11.9M 19s
  7700K .......... .......... .......... .......... ..........  3% 15.4M 19s
  7750K .......... .......... .......... .......... ..........  3% 10.1M 19s
  7800K .......... .......... .......... .......... ..........  3% 21.4M 19s
  7850K .......... .......... .......... .......... ..........  3% 11.2M 19s
  7900K .......... .......... .......... .......... ..........  3% 20.9M 19s
  7950K .......... .......... .......... .......... ..........  3% 6.71M 19s
  8000K .......... .......... .......... .......... ..........  3% 10.2M 19s
  8050K .......... .......... .......... .......... ..........  3%  130M 19s
  8100K .......... .......... .......... .......... ..........  3% 9.65M 19s
  8150K .......... .......... .......... .......... ..........  3% 15.2M 19s
  8200K .......... .......... .......... .......... ..........  3% 16.8M 19s
  8250K .......... .......... .......... .......... ..........  3% 13.4M 19s
  8300K .......... .......... .......... .......... ..........  3% 11.0M 19s
  8350K .......... .......... .......... .......... ..........  3% 8.85M 19s
  8400K .......... .......... .......... .......... ..........  3% 13.1M 19s
  8450K .......... .......... .......... .......... ..........  3% 9.78M 19s
  8500K .......... .......... .......... .......... ..........  3% 83.2M 18s
  8550K .......... .......... .......... .......... ..........  3% 10.9M 18s
  8600K .......... .......... .......... .......... ..........  3% 12.9M 18s
  8650K .......... .......... .......... .......... ..........  3% 12.5M 18s
  8700K .......... .......... .......... .......... ..........  3% 11.3M 18s
  8750K .......... .......... .......... .......... ..........  3% 14.9M 18s
  8800K .......... .......... .......... .......... ..........  3% 11.0M 18s
  8850K .......... .......... .......... .......... ..........  3% 12.6M 18s
  8900K .......... .......... .......... .......... ..........  3% 11.1M 18s
  8950K .......... .......... .......... .......... ..........  3% 16.6M 18s
  9000K .......... .......... .......... .......... ..........  3% 17.2M 18s
  9050K .......... .......... .......... .......... ..........  4% 10.5M 18s
  9100K .......... .......... .......... .......... ..........  4% 16.1M 18s
  9150K .......... .......... .......... .......... ..........  4% 11.6M 18s
  9200K .......... .......... .......... .......... ..........  4% 9.37M 18s
  9250K .......... .......... .......... .......... ..........  4% 15.7M 18s
  9300K .......... .......... .......... .......... ..........  4% 12.9M 18s
  9350K .......... .......... .......... .......... ..........  4% 8.51M 18s
  9400K .......... .......... .......... .......... ..........  4% 32.4M 18s
  9450K .......... .......... .......... .......... ..........  4% 14.8M 18s
  9500K .......... .......... .......... .......... ..........  4% 9.56M 18s
  9550K .......... .......... .......... .......... ..........  4% 9.41M 18s
  9600K .......... .......... .......... .......... ..........  4% 22.0M 18s
  9650K .......... .......... .......... .......... ..........  4% 12.2M 18s
  9700K .......... .......... .......... .......... ..........  4% 12.9M 18s
  9750K .......... .......... .......... .......... ..........  4% 19.9M 18s
  9800K .......... .......... .......... .......... ..........  4% 9.01M 18s
  9850K .......... .......... .......... .......... ..........  4% 15.7M 18s
  9900K .......... .......... .......... .......... ..........  4% 14.8M 18s
  9950K .......... .......... .......... .......... ..........  4% 9.17M 18s
 10000K .......... .......... .......... .......... ..........  4% 13.4M 18s
 10050K .......... .......... .......... .......... ..........  4% 12.0M 18s
 10100K .......... .......... .......... .......... ..........  4% 14.0M 18s
 10150K .......... .......... .......... .......... ..........  4% 14.5M 18s
 10200K .......... .......... .......... .......... ..........  4% 10.4M 18s
 10250K .......... .......... .......... .......... ..........  4% 15.1M 18s
 10300K .......... .......... .......... .......... ..........  4% 14.7M 18s
 10350K .......... .......... .......... .......... ..........  4% 14.5M 18s
 10400K .......... .......... .......... .......... ..........  4% 9.05M 18s
 10450K .......... .......... .......... .......... ..........  4% 11.2M 18s
 10500K .......... .......... .......... .......... ..........  4% 13.5M 18s
 10550K .......... .......... .......... .......... ..........  4% 19.3M 18s
 10600K .......... .......... .......... .......... ..........  4% 12.6M 18s
 10650K .......... .......... .......... .......... ..........  4% 11.6M 18s
 10700K .......... .......... .......... .......... ..........  4% 11.5M 18s
 10750K .......... .......... .......... .......... ..........  4% 13.4M 18s
 10800K .......... .......... .......... .......... ..........  4% 12.7M 18s
 10850K .......... .......... .......... .......... ..........  4% 12.4M 18s
 10900K .......... .......... .......... .......... ..........  4% 13.9M 18s
 10950K .......... .......... .......... .......... ..........  4% 15.8M 18s
 11000K .......... .......... .......... .......... ..........  4% 12.8M 18s
 11050K .......... .......... .......... .......... ..........  4% 11.1M 18s
 11100K .......... .......... .......... .......... ..........  4% 12.6M 18s
 11150K .......... .......... .......... .......... ..........  4% 12.1M 18s
 11200K .......... .......... .......... .......... ..........  4% 20.1M 18s
 11250K .......... .......... .......... .......... ..........  4% 8.61M 18s
 11300K .......... .......... .......... .......... ..........  5% 13.5M 18s
 11350K .......... .......... .......... .......... ..........  5% 21.5M 18s
 11400K .......... .......... .......... .......... ..........  5% 11.0M 18s

Downloading atb.assembly.r0.2.batch.95.tar.xz from https://osf.io/download/667155b86b6c8e341c04cdf0/

connected.
HTTP request sent, awaiting response... 302 Found
Location: https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667155b86b6c8e341c04cdf0 [following]
--2026-09-06 18:54:52--  https://files.de-1.osf.io/v1/resources/h28c3/providers/osfstorage/667155b86b6c8e341c04cdf0
Resolving files.de-1.osf.io (files.de-1.osf.io)... 35.186.249.111
Connecting to files.de-1.osf.io (files.de-1.osf.io)|35.186.249.111|:443... connected.
  6%|▌         | 27/436 [03:48<57:40,  8.46s/it]

KeyboardInterrupt:

## Read ATB FASTA file (positive only)

In [10]:
atb_desc_file.head()#.contig.nunique() #4381 total positives 4252 unique contig ids

,Benbow_id,GI,NR_of_Genes,ATB_id,contig,containing_Genes,start,end,Strain,species_sylph,path,batch_folder
0,NC_000964.3,GI_1(extra_set),34,SAMEA114331916,SAMEA114331916.contig00002,30,366997,393518,Bacillus subtilis subsp. subtilis str. 168,Bacillus spizizenii,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.incr_release.202408.batch.35
1,NC_000964.3,GI_1(extra_set),34,SAMEA114331924,SAMEA114331924.contig00002,30,366997,393518,Bacillus subtilis subsp. subtilis str. 168,Bacillus spizizenii,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.incr_release.202408.batch.35
2,NC_000964.3,GI_1(extra_set),34,SAMN33940505,SAMN33940505.contig00017,29,60729,87090,Bacillus subtilis subsp. subtilis str. 168,Bacillus mojavensis,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.incr_release.202408.batch.35
3,NC_000964.3,GI_10(extra_set),10,SAMEA114331949,SAMEA114331949.contig00007,10,21091,30183,Bacillus subtilis subsp. subtilis str. 168,Bacillus spizizenii,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.incr_release.202408.batch.35
4,NC_000964.3,GI_10(extra_set),10,SAMN39909520,SAMN39909520.contig00001,10,486187,495279,Bacillus subtilis subsp. subtilis str. 168,Bacillus spizizenii,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.incr_release.202408.batch.35

In [32]:
atb_pos_df = atb_desc_file[['contig', 'start', 'end']].copy()
atb_pos_df['prediction_method'] = 'ATB'
atb_pos_df.rename(columns={'contig':'accession'}, inplace=True)
atb_pos_df.head()

                    accession   start     end prediction_method
0  SAMEA114331916.contig00002  366997  393518               ATB
1  SAMEA114331924.contig00002  366997  393518               ATB
2    SAMN33940505.contig00017   60729   87090               ATB
3  SAMEA114331949.contig00007   21091   30183               ATB
4    SAMN39909520.contig00001  486187  495279               ATB

In [33]:
atb_w_neg_sampling = negatives_sampling(atb_pos_df, genome_path=f"{FOLDER_TO_ATB}/atb_batch_extracted_new")

In [35]:
atb_w_neg_sampling.Accession.nunique()

4240

In [39]:
contig_to_species_dict = atb_desc_file.set_index('contig')['species_sylph'].to_dict()
atb_w_neg_sampling['species'] = atb_w_neg_sampling['Accession'].map(contig_to_species_dict)

In [50]:
atb_w_neg_sampling

,Accession,Start,End,prediction_method,Label,Sequence,Description,gc,species,taxa_dict
0,SAMEA114331916.contig00002,366997,393518,ATB,1,CGATATGATATAACGCTTTTTCTTCAGCGACCTGCAAGTGCTGCTG...,SAMEA114331916.contig00002:366997-393518 SAMEA...,0.445442,Bacillus spizizenii,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."
1,SAMEA114331924.contig00002,366997,393518,ATB,1,CGATATGATATAACGCTTTTTCTTCAGCGACCTGCAAGTGCTGCTG...,SAMEA114331924.contig00002:366997-393518 SAMEA...,0.445442,Bacillus spizizenii,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."
2,SAMN33940505.contig00017,60729,87090,ATB,1,CATTCAGCATGCTCTCCTTTCAAAGATAATAATGAAAGCTTTATAT...,SAMN33940505.contig00017:60729-87090 SAMN33940...,0.447728,Bacillus mojavensis,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."
3,SAMEA114331949.contig00007,21091,30183,ATB,1,TGAGCAATAATCAATCTCGTTATGAAAACCGTGATAAGCGCAGGAA...,SAMEA114331949.contig00007:21091-30183 SAMEA11...,0.442208,Bacillus spizizenii,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."
4,SAMN39909520.contig00001,486187,495279,ATB,1,TAGCTTTGCAGAGCTTCTTTTTGATCATCTATTTTTTTGTCAAAGA...,SAMN39909520.contig00001:486187-495279 SAMN399...,0.444408,Bacillus spizizenii,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."
...,...,...,...,...,...,...,...,...,...,...
4087,SAMN10228562.contig00003,231202,248280,random_neg_sample,0,AGCCAAAGACTGCCTGCCTTGTTCTGAATCGCATCAAAATGATAAT...,SAMN10228562.contig00003:231202-248280 SAMN102...,0.475965,Yersinia pestis,"{'phylum': 'Pseudomonadota', 'class': 'Gammapr..."
4088,SAMEA7290760.contig00017,90488,99993,random_neg_sample,0,GTAATATCGTCTAACTCGCGTAAAGTCACCATGCCCCCTTGGTAGG...,SAMEA7290760.contig00017:90488-99993 SAMEA7290...,0.555018,Pseudomonas aeruginosa,"{'phylum': 'Pseudomonadota', 'class': 'Gammapr..."
4089,SAMEA5795703.contig00034,13895,24124,random_neg_sample,0,GGGATACGGGACATCAAGCTGCTCTGCCACGTGAGCGGCGTCCATG...,SAMEA5795703.contig00034:13895-24124 SAMEA5795...,0.605865,Burkholderia sp905232215,Name not found
4090,SAMN04393521.contig00009,82702,92197,random_neg_sample,0,TTTCTGATCCCGCTTCGATACGTAGGATAATGCGACAAAACAAATA...,SAMN04393521.contig00009:82702-92197 SAMN04393...,0.575927,Brucella melitensis,"{'phylum': 'Pseudomonadota', 'class': 'Alphapr..."
4091,SAMN28626343.contig00009,64689,76506,random_neg_sample,0,TTTATCCAGCTGCGCCAGGGGGAGATCCAGACGCGGCCGATAAAAG...,SAMN28626343.contig00009:64689-76506 SAMN28626...,0.572940,Klebsiella pneumoniae,"{'phylum': 'Pseudomonadota', 'class': 'Gammapr..."

### Write to FASTA file

In [54]:
atb_w_neg_sampling['Description'] = atb_w_neg_sampling.parallel_apply(lambda x: f"{x['Accession']}:{x['Start']}-{x['End']} {x['species']}", axis=1)

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=2116), Label(value='0 / 2116'))), …

In [55]:
atb_w_neg_sampling.head()

,Accession,Start,End,prediction_method,Label,Sequence,Description,gc,species,taxa_dict
0,SAMEA114331916.contig00002,366997,393518,ATB,1,CGATATGATATAACGCTTTTTCTTCAGCGACCTGCAAGTGCTGCTG...,SAMEA114331916.contig00002:366997-393518 Bacil...,0.445442,Bacillus spizizenii,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."
1,SAMEA114331924.contig00002,366997,393518,ATB,1,CGATATGATATAACGCTTTTTCTTCAGCGACCTGCAAGTGCTGCTG...,SAMEA114331924.contig00002:366997-393518 Bacil...,0.445442,Bacillus spizizenii,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."
2,SAMN33940505.contig00017,60729,87090,ATB,1,CATTCAGCATGCTCTCCTTTCAAAGATAATAATGAAAGCTTTATAT...,SAMN33940505.contig00017:60729-87090 Bacillus ...,0.447728,Bacillus mojavensis,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."
3,SAMEA114331949.contig00007,21091,30183,ATB,1,TGAGCAATAATCAATCTCGTTATGAAAACCGTGATAAGCGCAGGAA...,SAMEA114331949.contig00007:21091-30183 Bacillu...,0.442208,Bacillus spizizenii,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."
4,SAMN39909520.contig00001,486187,495279,ATB,1,TAGCTTTGCAGAGCTTCTTTTTGATCATCTATTTTTTTGTCAAAGA...,SAMN39909520.contig00001:486187-495279 Bacillu...,0.444408,Bacillus spizizenii,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."

In [57]:
# write the test data to promge_test_neg_sampling.fasta
from utils.util import df_to_fasta_new

# write df to fasta file
param = {'write_file':True,'filename':f"{FOLDER_TEST}/ATB_neg_sampling.fasta"} #whether write sequences to a fasta file specified in filename

if not os.path.exists(param['filename']):
    fasta_data = atb_w_neg_sampling.progress_apply(lambda x: df_to_fasta_new(x,
                                                                dna_only=True, #dna_only determines whether or not to process sequences with IUPAC codes
                                                                query_db=False, #query sequence from database
                                                                **param), axis=1).to_list()
else:
    print(f"{param['filename']} already exists!")

100%|██████████| 8461/8461 [00:44<00:00, 190.97it/s]

In [117]:
ncbi.get_name_translator(['Bacillus'])

{'Bacillus': [1386, 55087]}

In [9]:
from ete3 import NCBITaxa

ncbi = NCBITaxa()

def species_to_lineage(species_name):
    try:
        # 1. Translate name to TaxID
        name_map = ncbi.get_name_translator([species_name])
        if not name_map:
            return "Name not found"
        taxid = name_map[species_name][0]
        
        # 2. Get the lineage (list of parent TaxIDs)
        lineage = ncbi.get_lineage(taxid)
        
        # 3. Get the rank for each ID in the lineage
        ranks = ncbi.get_rank(lineage)  # Returns {taxid: 'rank_name'}
        
        # 4. CORRECTED: Use get_taxid_translator to get names
        # Returns {taxid: 'name'}
        names = ncbi.get_taxid_translator(lineage)
        
        # 5. Build a clean dictionary of the desired ranks
        desired_ranks = ['phylum', 'class', 'order', 'family']
        taxonomy = {ranks[tid]: names[tid] for tid in lineage if ranks[tid] in desired_ranks}
        
        return taxonomy
    except Exception as e:
        return f"Error: {e}"

print(species_to_lineage("Bacillus"))

{'phylum': 'Bacillota', 'class': 'Bacilli', 'order': 'Bacillales', 'family': 'Bacillaceae'}

### Assign taxonomy to the samples

In [2]:
from Bio import Entrez
import taxoniq

Entrez.email = "your_email@example.com"

def get_taxid_from_sample(biosample_id):
    # Search for the BioSample
    handle = Entrez.esearch(db="biosample", term=biosample_id)
    record = Entrez.read(handle)
    ids = record["IdList"]
    
    if not ids:
        return None
    
    # Fetch the details
    handle = Entrez.esummary(db="biosample", id=ids[0])
    summary = Entrez.read(handle)

    taxid = int(summary["DocumentSummarySet"]["DocumentSummary"][0].get("Taxonomy"))
    
    # Extract TaxID (usually stored in 'TaxId' or within the SampleData XML)
    # BioSample summaries are often returned as XML strings in 'SampleData'
    return taxid

# map the taxid to the samples
def map_taxon_to_df(row):
    try:
        taxon = taxoniq.Taxon(row['taxid'])
        row['scientific_name'] = taxon.scientific_name

        for t in taxon.ranked_lineage:
            row[t.rank.name] = t.scientific_name 
    except Exception as e:
        row['scientific_name'] = None
    return row

def map_biosample_to_lineage(biosample_id):
    taxid = get_taxid_from_sample(sample_id)
    info = map_taxon_to_df({'taxid': taxid})

    return {biosample_id: info}


# Example use:
sample_id = "SAMEA7290760"
#taxid = get_taxid_from_sample(sample_id)
#info = map_taxon_to_df({'taxid': taxid})

map_biosample_to_lineage(sample_id)

/opt/anaconda3/envs/datacompos/lib/python3.10/site-packages/Bio/Entrez/Parser.py:1066: UserWarning: Failed to save esummary_biosample.dtd at /Users/WijayaA-Dev/.config/biopython/Bio/Entrez/DTDs/esummary_biosample.dtd
  warnings.warn(f"Failed to save {filename} at {path}")

{'SAMEA7290760': {'taxid': 287,
  'scientific_name': 'Pseudomonas aeruginosa',
  'species': 'Pseudomonas aeruginosa',
  'genus': 'Pseudomonas',
  'family': 'Pseudomonadaceae',
  'order': 'Pseudomonadales',
  'class': 'Gammaproteobacteria',
  'phylum': 'Pseudomonadota',
  'superkingdom': 'Bacteria'}}

In [124]:
contig_to_taxa_df = atb_w_neg_sampling[['Accession', 'species']].drop_duplicates().copy()
contig_to_taxa_df['genus'] = contig_to_taxa_df['species'].apply(lambda x: x.split(' ')[0] if '_' not in x else x.split('_')[0]) 
contig_to_taxa_df['biosample_id'] = contig_to_taxa_df['Accession'].apply(lambda x: x.split('.')[0])
contig_to_taxa_df['taxa_dict'] = contig_to_taxa_df['genus'].parallel_apply(species_to_lineage)

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=1060), Label(value='0 / 1060'))), …

In [125]:
contig_to_taxa_df.head()

,Accession,species,genus,biosample_id,taxa_dict
0,SAMEA114331916.contig00002,Bacillus spizizenii,Bacillus,SAMEA114331916,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."
1,SAMEA114331924.contig00002,Bacillus spizizenii,Bacillus,SAMEA114331924,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."
2,SAMN33940505.contig00017,Bacillus mojavensis,Bacillus,SAMN33940505,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."
3,SAMEA114331949.contig00007,Bacillus spizizenii,Bacillus,SAMEA114331949,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."
4,SAMN39909520.contig00001,Bacillus spizizenii,Bacillus,SAMN39909520,"{'phylum': 'Bacillota', 'class': 'Bacilli', 'o..."

In [126]:
# Unravel the 'details' column
df_unraveled = contig_to_taxa_df['taxa_dict'].apply(pd.Series)

# Join it back to the original dataframe and drop the old column
df = pd.concat([contig_to_taxa_df.drop('taxa_dict', axis=1), df_unraveled], axis=1)
df

,Accession,species,genus,biosample_id,phylum,class,order,family
0,SAMEA114331916.contig00002,Bacillus spizizenii,Bacillus,SAMEA114331916,Bacillota,Bacilli,Bacillales,Bacillaceae
1,SAMEA114331924.contig00002,Bacillus spizizenii,Bacillus,SAMEA114331924,Bacillota,Bacilli,Bacillales,Bacillaceae
2,SAMN33940505.contig00017,Bacillus mojavensis,Bacillus,SAMN33940505,Bacillota,Bacilli,Bacillales,Bacillaceae
3,SAMEA114331949.contig00007,Bacillus spizizenii,Bacillus,SAMEA114331949,Bacillota,Bacilli,Bacillales,Bacillaceae
4,SAMN39909520.contig00001,Bacillus spizizenii,Bacillus,SAMN39909520,Bacillota,Bacilli,Bacillales,Bacillaceae
...,...,...,...,...,...,...,...,...
4364,SAMN14206706.contig00027,Pseudomonas_E amygdali,Pseudomonas,SAMN14206706,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae
4365,SAMD00111861.contig00095,Pseudomonas_E avellanae,Pseudomonas,SAMD00111861,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae
4366,SAMN24624796.contig00036,Pseudomonas_E avellanae,Pseudomonas,SAMN24624796,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae
4367,SAMN37711865.contig00035,Pseudomonas_E avellanae,Pseudomonas,SAMN37711865,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae
4368,SAMN06197054.contig00081,Pseudomonas_E avellanae,Pseudomonas,SAMN06197054,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae

In [ ]:
#df.to_excel(f"{FOLDER_TEST}/ATB_neg_sampling_with_taxa.xlsx", index=False)

In [128]:
df.species.nunique()

327

In [129]:
atb_desc_file.species_sylph.nunique()

327

In [133]:
atb_desc_file.Strain.nunique()

109

In [134]:
atb_desc_file

,Benbow_id,GI,NR_of_Genes,ATB_id,contig,containing_Genes,start,end,Strain,species_sylph,path,batch_folder
0,NC_000964.3,GI_1(extra_set),34,SAMEA114331916,SAMEA114331916.contig00002,30,366997,393518,Bacillus subtilis subsp. subtilis str. 168,Bacillus spizizenii,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.incr_release.202408.batch.35
1,NC_000964.3,GI_1(extra_set),34,SAMEA114331924,SAMEA114331924.contig00002,30,366997,393518,Bacillus subtilis subsp. subtilis str. 168,Bacillus spizizenii,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.incr_release.202408.batch.35
2,NC_000964.3,GI_1(extra_set),34,SAMN33940505,SAMN33940505.contig00017,29,60729,87090,Bacillus subtilis subsp. subtilis str. 168,Bacillus mojavensis,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.incr_release.202408.batch.35
3,NC_000964.3,GI_10(extra_set),10,SAMEA114331949,SAMEA114331949.contig00007,10,21091,30183,Bacillus subtilis subsp. subtilis str. 168,Bacillus spizizenii,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.incr_release.202408.batch.35
4,NC_000964.3,GI_10(extra_set),10,SAMN39909520,SAMN39909520.contig00001,10,486187,495279,Bacillus subtilis subsp. subtilis str. 168,Bacillus spizizenii,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.incr_release.202408.batch.35
...,...,...,...,...,...,...,...,...,...,...,...,...
4376,NC_005773.3,GI_6,3,SAMN14206706,SAMN14206706.contig00027,3,56979,61475,Pseudomonas savastanoi pv. phaseolicola 1448A ...,Pseudomonas_E amygdali,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.r0.2.batch.131
4377,NC_005773.3,GI_9,7,SAMD00111861,SAMD00111861.contig00095,7,14588,22527,Pseudomonas savastanoi pv. phaseolicola 1448A ...,Pseudomonas_E avellanae,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.r0.2.batch.403
4378,NC_005773.3,GI_9,7,SAMN24624796,SAMN24624796.contig00036,7,39692,47598,Pseudomonas savastanoi pv. phaseolicola 1448A ...,Pseudomonas_E avellanae,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.r0.2.batch.403
4379,NC_005773.3,GI_9,7,SAMN37711865,SAMN37711865.contig00035,7,41274,49180,Pseudomonas savastanoi pv. phaseolicola 1448A ...,Pseudomonas_E avellanae,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.incr_release.202408.batch.51
4380,NC_005773.3,GI_9,7,SAMN06197054,SAMN06197054.contig00081,7,14821,22727,Pseudomonas savastanoi pv. phaseolicola 1448A ...,Pseudomonas_E avellanae,/scratch/projekte/MF1_Bioinformatics/2025-mobi...,atb.assembly.r0.2.batch.403

In [18]:
atb_neg_sampling_w_taxa = pd.read_excel(f"{FOLDER_TEST}/ATB_neg_sampling_with_taxa.xlsx")
atb_old = pd.read_csv("dataset/MF1_data/allTheBacteria/full_atb_matrix/ATB_pos_test.tsv", sep="\t")

In [17]:
atb_neg_sampling_w_taxa

,Accession,species,genus,biosample_id,phylum,class,order,family
0,SAMEA114331916.contig00002,Bacillus spizizenii,Bacillus,SAMEA114331916,Bacillota,Bacilli,Bacillales,Bacillaceae
1,SAMEA114331924.contig00002,Bacillus spizizenii,Bacillus,SAMEA114331924,Bacillota,Bacilli,Bacillales,Bacillaceae
2,SAMN33940505.contig00017,Bacillus mojavensis,Bacillus,SAMN33940505,Bacillota,Bacilli,Bacillales,Bacillaceae
3,SAMEA114331949.contig00007,Bacillus spizizenii,Bacillus,SAMEA114331949,Bacillota,Bacilli,Bacillales,Bacillaceae
4,SAMN39909520.contig00001,Bacillus spizizenii,Bacillus,SAMN39909520,Bacillota,Bacilli,Bacillales,Bacillaceae
...,...,...,...,...,...,...,...,...
4235,SAMN14206706.contig00027,Pseudomonas_E amygdali,Pseudomonas,SAMN14206706,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae
4236,SAMD00111861.contig00095,Pseudomonas_E avellanae,Pseudomonas,SAMD00111861,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae
4237,SAMN24624796.contig00036,Pseudomonas_E avellanae,Pseudomonas,SAMN24624796,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae
4238,SAMN37711865.contig00035,Pseudomonas_E avellanae,Pseudomonas,SAMN37711865,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae
4239,SAMN06197054.contig00081,Pseudomonas_E avellanae,Pseudomonas,SAMN06197054,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae

In [21]:
atb_neg_sampling_w_taxa.species.nunique()

327

In [16]:
atb_neg_sampling_w_taxa.family.nunique()

31

In [20]:
atb_neg_sampling_w_taxa.genus.nunique()

74

In [5]:
biosample_id = "SAMD00006172"
handle = Entrez.esearch(db="biosample", term=biosample_id)
record = Entrez.read(handle)
ids = record["IdList"]

In [10]:
handle = Entrez.esummary(db="biosample", id=ids[0], report="full")
summary = Entrez.read(handle)

docs = summary["DocumentSummarySet"]["DocumentSummary"]

In [11]:
docs

[DictElement({'Title': '94389', 'Accession': 'SAMD00006172', 'Date': '2016/03/07', 'PublicationDate': '2016/03/07', 'ModificationDate': '2022/03/31', 'Organization': 'name, lab, Your, Enter', 'Taxonomy': '1115511', 'Organism': 'Escherichia albertii NBRC 107761 = DSM 17582', 'SourceSample': 'BioSample:SAMD00006172', 'SampleData': '<BioSample access="public" publication_date="2016-03-07T00:00:00.000" last_update="2022-03-31T21:09:43.434" submission_date="2016-03-08T01:00:12.000" id="4537412" accession="SAMD00006172">   <Ids>     <Id db="BioSample" is_primary="1">SAMD00006172</Id>     <Id db="SRA">DRS014963</Id>   </Ids>   <Description>     <Title>94389</Title>     <Organism taxonomy_id="1115511" taxonomy_name="Escherichia albertii NBRC 107761 = DSM 17582">       <OrganismName>Escherichia albertii NBRC 107761 = DSM 17582</OrganismName>     </Organism>   </Description>   <Owner>     <Name>name, lab, Your, Enter</Name>   </Owner>   <Models>     <Model>Generic</Model>   </Models>   <Package display_name="Generic">Generic.1.0</Package>   <Attributes>     <Attribute attribute_name="sample_name" harmonized_name="sample_name" display_name="sample name">DRS014963</Attribute>     <Attribute attribute_name="sample comment">human-isolate</Attribute>   </Attributes>   <Status status="live" when="2016-03-08T01:00:12.273"/> </BioSample> ', 'Identifiers': 'BioSample: SAMD00006172; SRA: DRS014963', 'Infraspecies': '', 'Package': 'Generic', 'SortKey': '120220331'}, attributes={'uid': '4537412'})]